### ISSUE TITLE
Documentation.

### ISSUE THREAD

**Issue by Achaean** [Bash-it/bash-it#1003]
**Hi!** :-)

I really think that this project, needs better documentation.
The only well documented things, are installation and theming.

And maybe a proper help forum.
This tracker is OK, but not the friendliest option and is meant for issues and not for general help.

**Bye!**
A.

**Comment by nwinkler** [comment]
Thanks for the feedback!

For a help forum, we have a this in Gitter (it's also linked from the Bash-it README): https://gitter.im/Bash-it/bash-it - feel free to ask questions there.

With regards to documentation, what kind of documentation are you looking for? A more detailed description of the available plugins? If so, we could/should probably add that on the project's Wiki. Let me know what you're looking for, and we can certainly look into adding something.

Also, feel free to improve the existing documentation - pull requests are always welcome.

Thanks again for your valuable feedback!

**Comment by Achaean** [comment]
Ooops! I missed it.
Let me take a look at it and I'll be back.
Thanks!!! :-)
