### ISSUE TITLE
Possible System Environment Variables Pollution of git.completion.bash 

### ISSUE THREAD

**Issue by swatchion** [Bash-it/bash-it#1006]
Hi guys,

Found that git.completion.bash generate lists of variables as system wide variables like ENV, I think it's a good idea to keep the variables local within shell scripts since a variable is defined globally by default in shell's behaviour.

You may find it by type "echo $" and then press "TAB" to auto-completion, a list of variables named like $__git_*** will shows up.

It's not a big problem anyway, thanks for make this project, keep it up, will follow. :)

**Comment by nwinkler** [comment]
I'm not sure what to do about this. The code in the `git.completion.bash` file was contributed/copied from somewhere else. Unless you want to change that code, there's very little we can do.

I'm not too happy with having this completion included in Bash-it anyway - it's just a copy of the "official" Git completion code that gets installed when you install Bash completion (e.g. on Linux using your package manager, or on macOS using Homebrew). Having this duplicated here does not provide a lot of value, and leads to issues with stale code, unless someone updates the file in Bash-it on a regular basis.

Not sure what to do about this...

**Comment by swatchion** [comment]
thanks for a real fast response, it's just a small issue, hope the git
completion office repository will realize and run an update if possible.

thanks again for you great efforts in bash-it project, have a good day.

**Comment by nwinkler** [comment]
You're welcome, and thanks for reporting this!
