### ISSUE TITLE
ssh-agent management plugin

### ISSUE THREAD

**Issue by mvk** [Bash-it/bash-it#1016]
### Feature: sshagent management

Reference implementation of `ssh-agent` manager plugin. when you enable it, it keeps an agent alive across all your sessions.

- opinionated pid management using file in `~/.ssh`
- support for shared filesystem { the file contains hostname :) }
- I've been using it since 2015 :)

**Comment by nwinkler** [comment]
Closing this since the implementation is tracked in #1017.

Thanks for the contribution!

**Comment by jtarchie** [comment]
This does not work on Mac as it does not have the `/proc` available to see if something is running. That means I am always getting `There's a dead ssh-agent at the landing...` with new terminal window.

I don't see a `Darwin` specific implementation.

**Comment by mvk** [comment]
@jtarchie do you mind opening an issue, please ?

**Comment by jtarchie** [comment]
@mvk, done. #1137
