### ISSUE TITLE
How to use or run git commands with git_flow.completion.bash

### ISSUE THREAD

**Issue by ctr0306** [Bash-it/bash-it#1024]
Please help in understanding or using the git_flow.completion

Followed the below steps
1. git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
2. cd .bash_it
3. ./install.sh
4. cp bash-it/completion/available/git_flow.completion.bash ~/.git_flow.completion.sh
5. vi .bashrc and add source ~/.git-flow-completion.sh
6. source .bashrc
7.bash-it enable alias git
8. bash-it enable completion git
9.bash-it enable completion git_flow
10.bash-it enable completion git_flow_avh
11. created a directory with some files
12. Now how should i run or use git-flow-completion

Thanks

**Comment by nwinkler** [comment]
OK, let's take this one step at a time...

* Your steps 4 and 5 are not required, you don't need to copy and source the Bash-it files from your init script. Running `bash-it enable completion git_flow` should be enough.
* You should either enable the `git_flow` or the `git_flow_avh` completion - you don't need both.
* After running the `bash-it enable ...` commands, you need to either run `reload` or open a new terminal session to start using the completions. Running `reload` will source your shell init script (`~/.bashrc`) and will load all of the enabled Bash-it components.

Once you have done this, you can type `git flow <TAB><TAB>` and it should show you the available git flow commands like `feature`, `release`, etc.

Please let me know if this works.

**Comment by ctr0306** [comment]
sorry when i try to run git flow it gives the below error. should i need to install git flow on my desktop

○ → git flow
git: 'flow' is not a git command. See 'git --help'.

Did you mean one of these?
        reflog
        show

**Comment by nwinkler** [comment]
Yes, you will have to install git flow first, either through your package manager (Linux) or something like Homebrew (macOS).
