### ISSUE TITLE
sed: -e expression #2, char 36: unknown option to `s'

### ISSUE THREAD

**Issue by aggsol** [Bash-it/bash-it#1027]
I updated to the latest version. Every prompt or command yields the above error message

* GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
*  Ubuntu 16.04.3 

```
$ bashit show plugins
Plugin              Enabled?  Description
alias-completion      [x]     Automatic completion of aliases
base                  [x]     miscellaneous tools
xterm                 [x]     automatically set your xterm title with host and location info
```

**Comment by edubxb** [comment]
Can you provide more information about your environment? The full list of bash-it options enabled will help to find the issue.

**Comment by aggsol** [comment]
Sorry, de-installed it by now.
