### ISSUE TITLE
Bash-it shell launches vim?

### ISSUE THREAD

**Issue by boldandbusted** [Bash-it/bash-it#1030]
**Symptoms**:
After installing bash-it, I now:

-  Launch a new session in tmux,
-  find myself in vim, then
-  see this line when quitting vim:

`bash: complete: /usr/bin/vim: no completion specification `

Then I see the expected nice bash-it themed prompt.

FYI, I'm using bash-it installed via git.

Thanks!

**Comment by oz123** [comment]
I can confirm this behavior. Pretty annoying ...

**Comment by nwinkler** [comment]
Sorry, can't reproduce this... Any ideas what might be causing this? It seems to be related to completions in some way. Can you try disabling some of Bash-it features to see what's causing this?

**Comment by szymonpk** [comment]
In my case it is caused by `export EDITOR="/usr/bin/vim"` before `source "$BASH_IT"/bash_it.sh` in my `.bashrc`. I have moved it after bash_it.sh invocation. Works fine so far.

**Comment by nwinkler** [comment]
That is really weird - thanks for describing the behavior, maybe that helps some of the others who have this issue!

**Comment by szymonpk** [comment]
@nwinkler I have noticed one more thing. When I run `screen`, vim is started automatically. What is the best solution to set `EDITOR` with bash-it? I totally blame my `.bashrc` for this, but I am not sure how it should be changed.

**Comment by szymonpk** [comment]
OK my mistake, PEBKAC. `EDITOR` should be set as part of `.bash_profile`. `.bashrc`, by design should be used only for the non-interactive session. It still a puzzle why VIM is executed when exporting the mentioned variable. I have never seen this before with other tools.

**Comment by dracorp** [comment]
There is a "conflict" between two files:
* alias-completion.plugin.bash
* vim.aliases.bash

If at least one of both is disabled then everything is OK.

**Comment by szymonpk** [comment]
I did not had vim aliases enabled. Disabling alias-completion plugin helped. Thanks @dracorp for the workaround.

**Comment by nwinkler** [comment]
Closing this since #1165 was merged.
