### ISSUE TITLE
Bash-it and .screenrc

### ISSUE THREAD

**Issue by Toontje** [Bash-it/bash-it#1031]
Not really a bash-it issue, but more of a screen/bash-it integration question.
Whenever i launch screen i get a clean bash. No bash_profile is being sourced. What do i need to add to my .screenrc so whenever i launch a terminal in screen i get a full bash-it environment?

**Comment by nwinkler** [comment]
Which OS are you on? I just tried this on macOS, and I saw the same thing. I had to run `source ~/.bash_profile` from my screen session to make Bash-it work.

It's probably the old `~/.bashrc` vs. `~/.bash_profile` discussion. It's possible that it will work if you `source ~/.bash_profile` from your `~/.bashrc`.

**Comment by Toontje** [comment]
> It's probably the old ~/.bashrc vs. ~/.bash_profile discussion. It's possible that it will work if you source ~/.bash_profile from your ~/.bashrc.

Yeah, that's probably it. So how should this be set up? Should all the bash-it stuff go into .bashrc instead of .bash_profile? Should i source .bash_profile from .bashrc? How do i set this up so it works for interactive bash as well as bash in screen?

**Comment by nwinkler** [comment]
That could work, yes.

You could also leave everything as it was before and then simply `source ~/.bash_profile` from your `~/.bashrc`, e.g. at the end of the file. Really up to you.

**Comment by Toontje** [comment]
Thanks!!
