### ISSUE TITLE
Can't do silent installation if auto reload is set

### ISSUE THREAD

**Issue by joegnis** [Bash-it/bash-it#1037]
If I try installing when `BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE` is exported in `~/.bashrc`, `--silent` and `--no-modify-config` won't work. It will keep asking for input until all defaults are set.

```
$ export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1
$ ./install.sh --silent --no-modify-config
Installing bash-it

Enabling sane defaults
Installing bash-it
Would you like to keep your .bashrc and append bash-it templates at the end? [y/N] ^C
$ ./install.sh --silent --no-modify-config
Installing bash-it

Enabling sane defaults
bash-it is already enabled.
Installing bash-it
Would you like to keep your .bashrc and append bash-it templates at the end? [y/N]
```

This scenario happens when I'm migrating my config files to a new machine. Of course if I install `bash-it` before restoring my `.bashrc`, it would be fine. And the workaround is simple, make sure the variable is not exported to non-null value before the installation:

```
export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=
```

But I think it's better to open an issue for anyone who needs to install bash-it in an unattended way.

I am pretty new to Bash programming but I think I've managed to find the issue. During the installation, when enabling a "thing" (invoking the `_enable-thing` function). The [code](https://github.com/Bash-it/bash-it/blob/517d4b2ca486945aa1bec3b496f946d3b8493350/lib/helpers.bash#L387) seems not to be able to tell if this is a first-time installation or not, and it just reloads if the variable is set.

My environment:

- Linux version 4.4.0-92-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) )
- GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

**Comment by nwinkler** [comment]
Thanks for reporting this!
