### ISSUE TITLE
brew completion doesn't appear to work any longer

### ISSUE THREAD

**Issue by miketheman** [Bash-it/bash-it#1046]
https://github.com/Bash-it/bash-it/blob/5a92d26cabd195ba4186ec7f6d3e572ec1a6ffa8/completion/available/brew.completion.bash

```console
$ ls `brew --prefix`/etc/bash_completion
ls: /usr/local/etc/bash_completion: No such file or directory
$  ls `brew --prefix`/Library/Contributions/brew_bash_completion.sh
ls: /usr/local/Library/Contributions/brew_bash_completion.sh: No such file or directory
```

It appears to have moved to:

```console
$ ls `brew --prefix`/etc/bash_completion.d/brew
/usr/local/etc/bash_completion.d/brew
$ head `brew --prefix`/etc/bash_completion.d/brew
# Bash completion script for brew(1)

__brewcomp_words_include() {
  local i=1
  while [[ "$i" -lt "$COMP_CWORD" ]]
  do
    if [[ "${COMP_WORDS[i]}" = "$1" ]]
    then
      return 0
    fi
```

This directory contains other brew-installed completions as well.

What would be the best course of action to enact this change? Update the existing, or append this path to the end with another `if` statement?

**Comment by nwinkler** [comment]
Good question...

The first part (check for `/usr/local/etc/bash_completion` is overlapping with the more general `system.completion.bash` file, which tries to load all system completion files.

On my local system, I have the following files that make sense to get loaded in this case:

* `/usr/local/etc/bash_completion.d/brew` - this is pointing to a file from 2017, so fairly recent.
* `/usr/local/etc/bash_completion.d/brew_bash_completion.sh` - this is from 2015, so fairly old.

I suggest to change the first check to load `/usr/local/etc/bash_completion.d/brew` if that file exists. The first check is duplicated by the system completion file anyway...

(All instances of `/usr/local` should be using `brew --prefix`, of course)
