### ISSUE TITLE
PROMPT_COMMAND='history -a' breaks themes 

### ISSUE THREAD

**Issue by joeparis** [Bash-it/bash-it#1047]
I've run across a problem that is baffling me. When I have the line `PROMPT_COMMAND='history -a'` in my **~/.bash_it/custom/custom.bash** file no theme is applied to my prompt; neither my custom theme or any of the ones that ship with bash_it. If I comment out that line everything behaves as expected. In both cases the environment variable is set as are all the ones that follow it and neofetch runs as expected. I'm just left with the default bash prompt (`[joe@gandalf ~]$`) when I set that particular environment variable.

I'm running a fresh install of Manjaro with kernel 4.13.3-2-MANJARO, bash 4.4.12, and a version of bash_it I pulled down over the weekend. Following is my complete `~/.bash_it/custom/custom.bash` file for reference.

```
#!/usr/bin/env bash

hash vim 2>/dev/null && export EDITOR=vim

# Shorten long directory prompts
# https://sanctum.geek.nz/arabesque/prompt-directory-shortening/
export PROMPT_DIRTRIM=3

# Better Bash history
# https://sanctum.geek.nz/arabesque/bash-history-expansion/
# https://sanctum.geek.nz/arabesque/better-bash-history/
shopt -s cdspell
shopt -s cmdhist
shopt -s histappend
export PROMPT_COMMAND='history -a'
export HISTFILESIZE=1000000
export HISTSIZE=1000000
export HISTCONTROL=ignoreboth
export HISTIGNORE='ls:bg:fg:history*:exit'
export HISTTIMEFORMAT='%F %T '

# Display system info
neofetch
```

Any help would be appreciated.

**Comment by nwinkler** [comment]
The problem is that the `custom` files are loaded after the themes in Bash-it. So your selected theme defines the nice `PROMPT_COMMAND` variable for the theme, and then after that, you redefine the variable to just `history -a` in your custom file...

Out of curiosity: What do you want to achieve with setting the prompt command to `history -a`? Why does this need to be part of the prompt command? Why not simply run `history -a` in your custom prompt?

BTW: Many of the themes already include a call to `history -a` in their own code...

**Comment by joeparis** [comment]
I'll admit I am embarrassed. 

I traced the execution through the script files and knew that `custom` files came later and it still didn't occur to me what the issue really was. 

I have no compelling reason why `history -a` couldn't be part of my custom prompt, having read that just now I remember seeing it in the **~/.bash_it/themes/font/font.theme.bash** file I used as an example to write my custom theme. Truth be told I don't think I fully comprehended just what the `prompt_command()` function was actually doing. 

Thanks for your help, everything is working exactly as I want now.

**Comment by nwinkler** [comment]
Great to hear that - glad I was able to help!

**Comment by bval** [comment]
Ran across this when looking into how to make the bobby theme share history and wanted to add for future visitors that there's a shell function called `safe_append_prompt_command` in bash-it that you should take advantage of. If your theme doesn't do already do this, you can place this code in a custom file or in your bash_profile after you have loaded bash-it:

```
share_history() {
  history -a
  history -c
  history -r
}

safe_append_prompt_command share_history
```

**Comment by nwinkler** [comment]
Thanks for posting this!
