### ISSUE TITLE
error while updating

### ISSUE THREAD

**Issue by kirk86** [Bash-it/bash-it#1049]
Hi everyone I was wondering if someone could give me some hints on the following error:
```
bash-it update
Error updating Bash-it, please, check if your Bash-it installation folder (/Users/user/.bash_it) is clean.
```
What does it mean `check if installation folder is clean` shouldn't the update happen automatically?

**Comment by nwinkler** [comment]
It means that you might have local modifications in your `$BASH_IT` folder, preventing you from merging incoming changes.

Can you do the following and then check the output, or post it here?

```bash
# cd into the Bash-it folder
cd $BASH_IT

# Check the Git status
git status
```

**Comment by kirk86** [comment]
@nwinkler thanks.
Here's the output:
```
git status
On branch master
Your branch is behind 'origin/master' by 72 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   bash_it.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	themes/powerline-mandy-custom/

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by kirk86** [comment]
The weird thing is that last time I did a `bash-it update` and everything worked fine but since that time now it seems that something has been changed in `bash_it.sh`. Maybe the last update overwrote sth?

**Comment by nwinkler** [comment]
You can do a `git diff` to see what's changed and whether you had caused that... You can also run a `git reset --hard` if you want to remove all local changes, but be warned that that will remove all local changes, so make sure that it's not something you want to keep...

**Comment by nwinkler** [comment]
Thanks for closing this!
