### ISSUE TITLE
Unable to tab complete environment variables when using bash-it on Mac OS

### ISSUE THREAD

**Issue by brettonfinch-wf** [Bash-it/bash-it#1051]
Before installing bash-it I could do `cd $GOPATH/s` press tab and complete it to `cd $GOPATH/src` (or sometimes it could expand $GOPATH to the full path, but it would still expand). Once installing bash-it this behavior did not work.

This issue ended up not being a pure bash-it issue, but rather an issue with bash_completion. Installing and enabling bash_completion on the 'vanilla' bash in Mac OS will cause this issue as well. These are the steps I went though to fix the issue.

1. Install bash 4 using brew and follow these instructions http://clubmate.fi/upgrade-to-bash-4-in-mac-os-x/
2. Install bash_completion 2 (https://github.com/Homebrew/homebrew-core/blob/master/Formula/bash-completion%402.rb)
3. Enable `shopt -s direxpand` (https://askubuntu.com/questions/41891/bash-auto-complete-for-environment-variables) to fix variable expansion
4. Use bash-it and enable the 'system' completion (which will use bash_completion)
5. This should get everything working as expected

**Comment by CeleritasCelery** [comment]
What is really ironic is that I had this issue happen to me literally 20 minutes after you posted this. Thanks!

**Comment by nwinkler** [comment]
Thanks for the detailed steps!
