### ISSUE TITLE
custom.aliases.bash do not get completion until after a reload

### ISSUE THREAD

**Issue by brettonfinch-wf** [Bash-it/bash-it#1054]
If I have some aliases defined in `custom.aliases.bash`, completion on them does not work on load of my terminal until after I manually run `reload`.

`alias gco2='git checkout'` `gco2 mas` *tab* nothing happens (should complete to `gco2 master`)
`alias gco2='git checkout'` `reload` `gco2 mas` *tab* completes to `gco2 master`

Is there a way to have the `custom.aliases.bash` load after the alias completion plugin? Or a hack to get `reload` to occur on terminal start?

**Comment by brettonfinch-wf** [comment]
As a work around I can load bash-it twice in my .bash_profile to fix the issue, but that's obviously not very efficient
```
# Load Bash It
source "$BASH_IT"/bash_it.sh

# Load again to allow completion in custom aliases
source "$BASH_IT"/bash_it.sh
```

**Comment by nwinkler** [comment]
At the moment, you're out of luck with that one... As described in https://github.com/Bash-it/bash-it/blob/master/DEVELOPMENT.md, the custom files are loaded after everything else, that means they're also loaded after the alias-completion plugin.

Here are a couple of options for you:

* After loading Bash-it, you simply `source "$BASH_IT/plugins/available/alias-completion.plugin.bash"`, which will be loaded twice if you have it enabled, but that should fix the issue for you.
* A bit cleaner than the above: Move your custom aliases to a new alias file under `$BASH_IT/aliases/available` and use the standard enable/disable functionality. This will ensure that they are loaded before the `alias-completion` plugin.
* A bit more work: Change the Bash-it codebase (PR) to allow enabling/disabling custom files like other components. This would be clean (and I think other people have asked about this, too), but obviously a lot more work than the two options above.

Let me know if any of these work for you.

**Comment by brettonfinch-wf** [comment]
The middle option should work as an acceptable workaround for me, I only have a few custom aliases I would want completion for anyway. The enabling/disabling idea would be great as well, I'm not sure I'll find the time though I'm afraid.
Thanks for the quick response :)

**Comment by nwinkler** [comment]
OK, thanks! Closing this for now. Feel free to open another issue if you run into any problems.
