### ISSUE TITLE
virtualenv prompt + Iterm2 shell integration missing

### ISSUE THREAD

**Issue by MacFlurry** [Bash-it/bash-it#1055]
Hello,

just nocited that the virtualenv prompt an shell integration are missing:

Without BASH_IT
<img width="251" alt="screen shot 2017-10-08 at 10 29 29" src="https://user-images.githubusercontent.com/8139322/31315251-9da04ef6-ac14-11e7-9d2f-9bca5c7e7f23.png">

With BASH_IT
<img width="299" alt="screen shot 2017-10-08 at 10 37 45" src="https://user-images.githubusercontent.com/8139322/31315258-cf7b1500-ac14-11e7-8ec3-cec8bca23538.png">

thanks for your support,

MacFlurry

**Comment by nwinkler** [comment]
This depends on the theme that you're using. Some themes provide for `virtualenv`, while others do not.

Can you try switching to another theme that supports `virtualenv`, e.g. `cupcake` or `doubletime`?

**Comment by blvp** [comment]
you can look for answers here #962

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
