### ISSUE TITLE
Mercurial completions

### ISSUE THREAD

**Issue by sargunv** [Bash-it/bash-it#1064]
Is it possible to adapt the git completions to support Mercurial? I use Mercurial almost exclusively these days so that would be pretty useful.

**Comment by tswicegood** [comment]
It might be. A better way would be to use Mercurial's bash completion instead. I think [this script][1] does the trick. Wanna give it a try and open a PR adding it if it works?

[1]: https://www.mercurial-scm.org/repo/hg/file/tip/contrib/bash_completion

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
