### ISSUE TITLE
fzf interferes with xterm plugin

### ISSUE THREAD

**Issue by ser** [Bash-it/bash-it#1069]
Interesting thing with xterm plugin is that it interfes with fzf, crtl-r gives:

```
`__fzf_history__`bash: $'\E]0;bash-it': command not found
 me  08:20:41  ~  ^[]0;bash-it {~} (me@comp)^G^[]0;bash-it {~} (me@comp)^G^[]0;bash-it {~} (me@comp)^G^[]0;bash-it {~} (me@comp)^G^[]0;bash-it {~} (me@comp)^G
```

after issuing ```bash-it disable plugin xterm``` fzf is working again.

**Comment by nwinkler** [comment]
Thanks for reporting this!

**Comment by edubxb** [comment]
I have both plugins enabled with no issues, can you provide more info about your environment?

Thanks!

**Comment by ser** [comment]
hi @edubxb , what do you mean by the environment? ```env``` ?

**Comment by edubxb** [comment]
For environment, I refer to SO, Bash version, Bash-it version, fzf version, etc.

How you enabled fzf, with the Bash-it plugin, or using the fzf installer?

The whole content of your Bash config files and Bash-it enabled features can help to find whats is happening.

**Comment by ser** [comment]
@edubxb I'll close this ticket temporary and try to identify the issue by myself.
If it works for you, something must be definitely on my side. Thanks :)
