### ISSUE TITLE
Is there a way I can auto-complete from history?

### ISSUE THREAD

**Issue by priteshvora** [Bash-it/bash-it#1079]
Hi,
I am interested in an auto-complete plug-in which looks up the history and shows the recommendations in a grayed out fashion by toggling the top/down arrow button.

**Comment by priteshvora** [comment]
I am considering moving to Z-sh as I am not able to find it any of the plug-ins or completion methods of bash-it. Please help.

**Comment by edubxb** [comment]
Bash, and therefore, Bash-it, can't make colored output for things like this, but you can use complementary tools to achieve it, and other cool features... take a look of [fzf](https://github.com/junegunn/fzf).

Bash-it have a nice plugin that integrate it.

fzf, when installed, replaces the `Crtl-R` keybinding offering a more powerful history navigation...

I'm a fzf user (and fan) for some years, and is amazing!

**Comment by priteshvora** [comment]
Thanks edubxb for responding. I enabled the plugin but CTRL+R didn't show the history. I also reloaded the terminal, still no luck. Am I missing any step?

**Comment by edubxb** [comment]
Before enabling the plugin, you need to [install fzf](https://github.com/junegunn/fzf#installation), have you did it?

**Comment by priteshvora** [comment]
Ok, i am doing that. do we have to do similarly for other plugins also such as dirs?

**Comment by edubxb** [comment]
Some plugins require externals commands to work, others not, the dirs plugin isn't.

Refer to plugins command:

`bash-it show plugins`

and normally, the description can help to guess when a external command is needed.

**Comment by priteshvora** [comment]
I appreciate the help and step by step guidance. fzf is working fine now and I believe will help me with my daily work.

Also,
on the a different note how do I find descriptions of a given plugin supported on bash-it. I have tried googling and looked on bash-it plugin wiki but couldn't learn about different plugins and completion mechanisms it supports.

**Comment by nwinkler** [comment]
Awesome - thanks for the great instructions, @edubxb! I love `fzf`, fantastic tool!

@priteshvora You raise a good point - maybe we should add a description to the output of `bash-it show plugins` that explains which dependencies are needed.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
