### ISSUE TITLE
Discharging battery info in brainy theme

### ISSUE THREAD

**Issue by brossaip** [Bash-it/bash-it#1081]
Hi!

I love bash-it, my terminal experience has gone to a new dimension.

I am writing because I have made a modification in brainy theme. When it displayed the battery info, it didn't detect if it was discharging, I have replaced the code
`ac_adapter_connected && info+="+"`
by
`ac_adapter_connected && charging="+"
 ac_adapter_disconnected && charging="-"
 info+=$charging`

I hope it is useful.

Thanks!

**Comment by nwinkler** [comment]
Thanks for reporting this! Can you open a pull request for this, please?

Ideally, we'll add a unit test for this case, too. I'm about to merge #1080 into master, it contains a set of unit tests for (some of the) the battery functions, and it would be cool if we could write similar tests for the issue you described.

**Comment by brossaip** [comment]
Hi!

I have created the pull request.

Thanks.
