### ISSUE TITLE
documentation about git prompt

### ISSUE THREAD

**Issue by skgbanga** [Bash-it/bash-it#1083]
Hello,

This is less of an issue, but more of a request for addition documentation. 

I installed bash it yesterday, and also enabled git completions/plugin. I enabled 'simple' theme. My command prompt changed and I was wondering if I can find out what all the things in it mean?

In particular, in my git repo, the command prompt now displays a number {3} or sometimes {4} and I wanted to find out more about that. 

Thanks!

**Comment by skgbanga** [comment]
Also if there is a way to completely disable the prompt. I have my BASH_IT_THEME set to an empty string, but it still shows the branch and other info in the prompt. 

The reason for that is that having a prompt seems to be messing with Ctrl-r to search back the history.

**Comment by nwinkler** [comment]
Good questions!

* The numbers in the prompt show things like untracked/changed files, and stashed changes. The number in curly braces that you're seeing shows stashed changes. If you run `git stash list`, you should see a corresponding list of stashed changes.
* If you want to disable the Git information from the theme, you can do so by setting the `SCM_CHECK` variable to `false` in your Bash config file (either `~/.bashrc` or `~/.bash_profile`, depending on the OS): `export SCM_CHECK=false` - this is also described in the project's main README.md file, under the _Misc > Prompt Version Control Check`.
* When you say that the theme is messing with the history search function, what do you mean by that? Using `Ctrl+r` works fine for me, and I would like to understand what's broken in your case.

**Comment by skgbanga** [comment]
Hi @nwinkler, thanks for the quick reply!

Regarding `Ctrl+r`, this is what I am seeing. (on the theme 'simple' and not on the default 'bobby' theme) that when I search for something using `Ctrl+r` is overwrites on the git prompt, and when you click the right arrow button, you can't see the text.  I think you should be able to replicate this on 'simple' theme.

**Comment by nwinkler** [comment]
Can you please provide a screenshot of the above? Sorry, but I don't have time for trying to replicate this issue. (Ideally, you could also look into providing a fix for the issue.)

Have you tried using another theme that might not have this issue?

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
