### ISSUE TITLE
Prompted with "Please install argcomplete to use conda completion" after enabling conda completion

### ISSUE THREAD

**Issue by beastybryan** [Bash-it/bash-it#1086]
-Ubuntu 16.04LTS
-Have bash-it installed at `~/.bash_it`

I recently enabled the conda completion, and I was told to install `argcomplete` to use conda completion.
In my conda environment, I see that argcomplete is already installed.
What am I missing?

Thanks in advance!

**Comment by beastybryan** [comment]
[beastybryan_.bashrc.txt](https://github.com/Bash-it/bash-it/files/1452603/beastybryan_.bashrc.txt)

**Comment by nwinkler** [comment]
This is the code in question:

https://github.com/Bash-it/bash-it/blob/e9f6ab5a0f9cc5d7dde919d2e3aa08b71e6b17e5/completion/available/conda.completion.bash#L1-L4

As you can see, it checks for the `register-python-argcomplete` command. Is that what you have locally?

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
