### ISSUE TITLE
Bug? Why do some of the themes override the TERM variable?

### ISSUE THREAD

**Issue by maikelmeyers** [Bash-it/bash-it#1087]
I use urxvt and the recommendation is not to set the TERM variable manually. Instead the terminal emulator shall do this. In case of urxvt the line

`urxvt*termName: rxvt-unicode-256color`

in .Xresources is the correct way to setup the terminal type.

Now I wondered why my TERM was always overwritten with xterm-256color. I use the bash-it axin theme and the line

`elif [[ $TERM != dumb ]] && infocmp xterm-256color >/dev/null 2>&1; then export TERM=xterm-256color`

caused this. I don't understand why this line is necessary? infocmp always returns success if the terminfo for xterm-256color is available. But it is not correct to set TERM in this case.

**Comment by nwinkler** [comment]
Thanks for reporting this! If you want to fix this, please feel free to introduce a config variable that prevents the above code from running, e.g. `BASH_IT_THEME_SET_TERM`, and change it to `false` in your profile. Please feel free to provide a Pull Request for this.

**Comment by maikelmeyers** [comment]
Before I can do any changes, I need to understand the sense of this line. In the moment I am not convinced that this should be optional. Setting TERM shall never be done by bash-it at all.

**Comment by nwinkler** [comment]
Sorry, can't help you with that - I did not create the theme and don't know why this line is in the code...

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
