### ISSUE TITLE
bash: ruby: command not found, on load chruby

### ISSUE THREAD

**Issue by 007lva** [Bash-it/bash-it#1092]
I get `bash: ruby: command not found` running `source /usr/local/share/chruby/chruby.sh`. But it works well when I remove `source "$BASH_IT"/bash_it.sh` from .bashrc.

OS: Debian Buster
Plugins(none):
- alias-completion
- base

**Comment by nwinkler** [comment]
Can you please run the following with and without Bash-it, and then paste the output here?

* `which ruby`
* `echo $PATH`

**Comment by 007lva** [comment]
```sh
 2017-11-21 00:38:28 ⌚  x200 in ~
○ → echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

 2017-11-21 00:38:31 ⌚  x200 in ~
○ → which ruby

 2017-11-21 00:38:45 ⌚  x200 in ~
○ → 
```

**Comment by nwinkler** [comment]
Is that with Bash-it enabled? If so, could you please run the same without Bash-it?

BTW: On my Mac, the `ruby` executable can be found in `/usr/bin`, it's weird that it's not there in your case.

**Comment by 007lva** [comment]
BTW, I'm trying to use chruby with [ruby-install](https://github.com/postmodern/ruby-install), it installs Ruby in `~/.rubies` by default.

**Comment by 007lva** [comment]
Yep it is with bash-it enabled.

**Comment by nwinkler** [comment]
Have you tried adding that to your PATH then?

**Comment by 007lva** [comment]
Seems weird to do that, because without bash-it it works with no issues:

```sh
007lva@x200:~$ source /usr/local/share/chruby/chruby.sh
007lva@x200:~$ chruby
   ruby-2.4.2
007lva@x200:~$ chruby ruby-2.4.2
007lva@x200:~$ chruby
 * ruby-2.4.2
007lva@x200:~$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

```

also I can use chruby with ruby-install in another laptop that has oh-my-zsh

**Comment by nwinkler** [comment]
Isn't that exactly what the `chruby` plugin does?

https://github.com/Bash-it/bash-it/blob/76e4659126014b695ec2f01a14491bce7aa7e2a1/plugins/available/chruby.plugin.bash#L1-L4

What happens if you enabled Bash-it, and then do this:

```bash
bash-it enable plugin chruby

reload

ruby -v
```

**Comment by 007lva** [comment]
I get this

```sh
 2017-11-23 00:11:31 ⌚  x200 in ~
○ → bash-it enable plugin chruby
chruby enabled with priority 250.

 2017-11-23 00:11:41 ⌚  x200 in ~
○ → reload
bash: ruby: command not found

 2017-11-23 00:11:46 ⌚  (system) x200 in ~
○ → ruby -v
bash: ruby: command not found
bash: ruby: command not found


```

**Comment by nwinkler** [comment]
Can you print the contents of your `$PATH` variable before and after running `source /usr/local/share/chruby/chruby.sh`, without Bash-it enabled?

I don't understand why loading `chruby` without Bash-it works, but it does not when loading it through Bash-it...

**Comment by 007lva** [comment]
Sorry for the delay:

```sh
007lva@x200:~$ chruby
bash: chruby: command not found
007lva@x200:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
007lva@x200:~$ source /usr/local/share/chruby/chruby.sh
007lva@x200:~$ chruby
   ruby-2.4.2
007lva@x200:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

```

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
