### ISSUE TITLE
timemachine plugin + backup to synology

### ISSUE THREAD

**Issue by dillongreen** [Bash-it/bash-it#1094]
when doing a backup onto a synology NAS the timemachine plugin does not work

```bash
sa@mbp: ~/.bash_it/plugins/available  |master ↑2 ?:1 ✗| time-machine-destination

sa@mbp: ~/.bash_it/plugins/available  |master ↑2 ?:1 ✗| tmutil destinationinfo
====================================================
Name          : timemachine backups
Kind          : Network
URL           : afp://timemachine%20user@synology_rw27._afpovertcp._tcp.local./timemachine%20backups
ID            : 175F25C2-D329-4E5F-A949-5B265D109972
sa@mbp: ~/.bash_it/plugins/available  |master ↑2 ?:1 ✗|
```

**Comment by nwinkler** [comment]
I see... The `time-machine-destination` function currently only supports the `Mount Point` option, and Synology uses `URL` for the location...

If you could provide a Pull Request that takes both cases into account, I'd be more than happy to merge this.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
