### ISSUE TITLE
yarn ls doesn't exit anymore

### ISSUE THREAD

**Issue by dillongreen** [Bash-it/bash-it#1096]
among the bash-it aliases for yarn is `yals` which aliases `yarn ls` but then that doesn't exist anymore with current yarn: https://yarnpkg.com/en/docs/cli/

**Comment by LanikSJ** [comment]
Looks like we have `yarn list` https://yarnpkg.com/lang/en/docs/cli/list/

I can PR this for you if you like. 🙂

**Comment by nwinkler** [comment]
Good stuff - please create a PR and we'll get it merged!
