### ISSUE TITLE
My bash garbled with SecureCRT shells

### ISSUE THREAD

**Issue by Forpaw** [Bash-it/bash-it#1115]
I am using Ubuntu 16.04, Bash 4.3.48(1)-release, VMware Workstation 11.

Bash_it works well in the VMware shell, but **garbled in a SecureCRT 7.3 shell(random code)**.

It looks like this:
![image](https://user-images.githubusercontent.com/26356765/34073286-2d736c28-e2d1-11e7-8b62-477f8a221327.png)

I just ran the following commands:

```
git clone http://github.com/revans/bash-it.git ~/.bash_it
~/.bash_it/install.sh
```

Is there anyway to make it to show good in SecureCRT shells?

Btw, English is my second language and I am a new-beginner for Github and Bash-it, so I'm sorry for possible mistakes.:)

**Comment by nwinkler** [comment]
This seems to be a common issue with SecureCRT, please check here and see if one of these suggestions works for you:

* https://forums.vandyke.com/showthread.php?t=5666
* https://www.vandyke.com/support/tips/colorconfig.html

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
