### ISSUE TITLE
alias 'reload' conflicts with /sbin/reload

### ISSUE THREAD

**Issue by NGenetzky** [Bash-it/bash-it#1120]
Issue:
```
└─> which reload
reload is /sbin/reload
└─> alias reload
bash: alias: reload: not found
```
Context:
```
└─> uname -a
Linux ngenetzky-ultra 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
└─> bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
```
Possible solution:
Could detect if 'reload' is already a command and then use an alternative alias. I used 'reload!' in my old dotfiles (before I upgraded to bash-it :+1: ).
```
└─> which reload!
reload! is aliased to `. ~/.bashrc'
```

**Comment by nwinkler** [comment]
Good idea - please feel free to provide a PR for this!

**Comment by edubxb** [comment]
Probably, the best solution is using `reload` as a Bash-it command:

```bash-it reload```

What do you think @nwinkler?

**Comment by nwinkler** [comment]
Ah yes, that's a great idea! We could still alias it to just `reload` if the system does not have a native `reload` command...

**Comment by tswicegood** [comment]
I like the idea of having adding a `BASH_IT_RELOAD_LEGACY=1` that automatically adds the `reload` alias. It’s a good way of slowly deprecating it.

**Comment by dracorp** [comment]
I'm using custom/unalias.aliases.bash:
```
if alias q &>/dev/null; then
    unalias q
fi
```
Because:
```
$ ./q -help
MQSeries Q Program by Paul Clarke [ V6.0.0 Build:May  2 2012 ]
```
