### ISSUE TITLE
Alias completion odd behavior

### ISSUE THREAD

**Issue by seefood** [Bash-it/bash-it#1131]
trying to get completion for `ll`, aliased of course to `'ls -al'`.
```
# ll b<tab>
[lists all files and subdirectories starting with b as expected]
# ll bu<tab>
[expecting to get completion to "build", instead it rewrites to "ll u" and offeres files/dirs starting with u]
```
saw this behaviour at least on two Ubuntu machines, the `ll` alias completion looks only at the last letter of the last parameter.

(maybe happens in other aliases, that's the one I bumped into)

**Comment by nwinkler** [comment]
Interesting. I just tried this on my MacBook, and it works just fine...

**Comment by seefood** [comment]
Even weirder. I just tried to run it in asciinema but apparently it only happens in the top shell (SHLVL=1), not in subshells. digging deeper...

**Comment by adriaaula** [comment]
Hello there. 

I have experienced the same problems when connected in a cluster!

**Comment by cgjosephlee** [comment]
Same problem in CentOS! Completion do not work for alias implementing `ls`.

**Comment by NoahGorny** [comment]
hey @seefood, are you still experiencing it?

**Comment by seefood** [comment]
Hasn't happened in a while, can't remember if I fixed it somehow or it went away quietly. I'll try to recreate it tomorrow (1am now, nighty night)

**Comment by seefood** [comment]
can no longer replicate.
