### ISSUE TITLE
Prompt enters text in the wrong area when inside git repos

### ISSUE THREAD

**Issue by drawcard** [Bash-it/bash-it#1133]
This is likely related to #1125 but is worth tracking seperately.

For long directory paths, the prompt behaves (semi) properly and doesn't place the caret in the wrong area on the screen. For example, this is a wrapping PS1 in a long directory path:

![image](https://user-images.githubusercontent.com/1435638/35134972-eb39a8f4-fd29-11e7-8a47-2a707c1108e5.png)

However if within a git repo, the caret ends up embedded in the PS1:
![image](https://user-images.githubusercontent.com/1435638/35135034-5cf9ae80-fd2a-11e7-99a7-d331df146d61.png)

![image](https://user-images.githubusercontent.com/1435638/35135064-7f19df12-fd2a-11e7-954d-af80fa0af080.png)

**Comment by drawcard** [comment]
And even weirder, if you type in a long enough command the prompt will just wrap itself like so:

![image](https://user-images.githubusercontent.com/1435638/35135121-e929bc88-fd2a-11e7-9bd0-0ebef50bb2fb.png)

**Comment by Kevin-Mok** [comment]
I think I'm experiencing the same problem.
![cursor at wrong position](https://i.imgur.com/yCB6LRG.png)
This happens when I'm typing a line inside a git directory, and I jump to the beginning of the line. It seems to do this some of the time but not always.

**Comment by drawcard** [comment]
Yep that's pretty much what's happened with me.

For the time being I've disabled the just the bash-it shell prompt in ```~/.bash_profile```, and have set up https://github.com/magicmonty/bash-git-prompt to handle the git repo notices in the terminal, until a solution is found.

**Comment by Kevin-Mok** [comment]
For me, I just changed the bash-it theme to NWinkler where the command is entered a secondary line and the information is displayed on the previous line.

**Comment by nwinkler** [comment]
The "nwinkler" theme is the best, I know (har har har)!

To be honest, I haven't used it in a while. I use "powerline-multiline" and it works just fine for me. And it looks better than the "nwinkler" theme, too.

**Comment by drawcard** [comment]
> The "nwinkler" theme is the best, I know (har har har)!

😎

**Comment by hotzenklotz** [comment]
The same is happening for me. `clean` theme also breaks in `git` repos. Is there workaround other then changing the theme altogether?

**Comment by NoahGorny** [comment]
@drawcard does the issue still exist?

**Comment by drawcard** [comment]
@NoahGorny I am unable to re-test this so I can't confirm if it's gone away or not, perhaps another issue reporter here can assist. Thanks for following up!
