### ISSUE TITLE
ssh-agent plugin does not work on mac OSX

### ISSUE THREAD

**Issue by jtarchie** [Bash-it/bash-it#1137]
The ssh-agent plugin does not work on mac OSX. It complains `There's a dead ssh-agent at the landing...`. It looks like it is failing on `/proc` lookup, which is not supported on Mac OSX. Yay different flavors of Unix like OSes.

Reference #1016

**Comment by mvk** [comment]
@jtarchie thank you, I'm a bit busy, will look into this during next week.

**Comment by jtarchie** [comment]
@mvk, happy to make a PR, but I am not familiar with a good cross platform way to detect the agent running. My go to would be `ps`, but it seems wrong. 🤔

**Comment by Novite5** [comment]
I have also this problem on Arch. After enabling sshagent plugin, the ssh-agent process can't be shared between sessions.

**Comment by mvk** [comment]
@Novite5 hi, please specify version of Bash and the kernel you're running on Arch.

**Comment by Novite5** [comment]
@mvk my kernel version: 4.15.8-1-ARCH
bash version: 4.4.19(1)-release

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
