### ISSUE TITLE
Hostname in powerline themes

### ISSUE THREAD

**Issue by willprice** [Bash-it/bash-it#1145]
It seems the current powerline themes don't show the hostname, nor support toggling it to show. I see previously that the hostname was included, how come it got removed? Was this a conscious decision? I'd very much like to have the hostname in my prompt :)

**Comment by nwinkler** [comment]
If you're talking about the `powerline` theme - it does support showing the hostname.

You can set the `POWERLINE_PROMPT` variable to include the `hostname` entry like this in your Bash configuration, before you source the `bash_it.sh` file:

```bash
export POWERLINE_PROMPT="user_info scm python_venv ruby hostname cwd"
```

The documentation does not list the possible fields, that's a shortcoming and should be changed...

Here are the default settings for `powerline`:

https://github.com/Bash-it/bash-it/blob/7bd62af1518b0963cd9cf4d136ddbc7eb444ed50/themes/powerline/powerline.theme.bash#L49

If you're using the `powerline-multiline` theme, you can add the `hostname` entry to either the `POWERLINE_LEFT_PROMPT` or `POWERLINE_RIGHT_PROMPT` variable. The code contains the default values for these:

https://github.com/Bash-it/bash-it/blob/7bd62af1518b0963cd9cf4d136ddbc7eb444ed50/themes/powerline-multiline/powerline-multiline.theme.bash#L54-L55

Please let me know if this helps...

**Comment by willprice** [comment]
Hi @nwinkler,

Thanks the quick and comprehensive response! Yes this helps enormously, I'd be happy to add the information you've provided into the documentation if that'd be helpful? I did try digging through the source code to find out whether this was an option, it seems I was just looking in the wrong place :)

It seems there *might* be a formatting issue with using `hostname` in either `powerline` or `powerline-multiline`, although it might be my setup. I'm using Konsole with Iosevka Term (although I can reproduce with gnome-terminal and other powerline patched fonts)

![powerline-hostname-issue](https://user-images.githubusercontent.com/966205/36301232-03cf22d0-12fc-11e8-95af-70efbec5fe04.png)
![powerline-multiline-hostname-issue](https://user-images.githubusercontent.com/966205/36301233-03eb26f6-12fc-11e8-86cc-2d66428628b6.png)

I'll file a bug report if you think this isn't a problem with my setup.

**Comment by nwinkler** [comment]
Hi, sure, PRs are always welcome, and improving the documentation would be great. There's a separate README.md in the themes' directories, please feel free to provide changes there.

With the display issue with the hostname, are you referring to the wrong colour of the caret?

**Comment by willprice** [comment]
Correct, I believe the colours are inverted, i.e. the background should be the foreground and vice versa. 

Will put a PR later today with doc changes after work.

Cheers

**Comment by jalmansor** [comment]
When I enable hostname it flashes :-(

**Comment by jalmansor** [comment]
@willprice is this something you're still planning on working on?

**Comment by willprice** [comment]
@jalmansor I did the doc changes, but I don't think I've got a good enough understanding of the code to delve into this, I had a prod around and it doesn't look that simple without knowing the codebase.

**Comment by sub77** [comment]
https://github.com/Bash-it/bash-it/pull/1170/commits/0b8cc190056234b4472beaa0a1938a6be0602076
https://github.com/Bash-it/bash-it/pull/1169/commits/f8d5ffe84c906f059b6d7ff42d79628e64fbb6c2

**Comment by jalmansor** [comment]
@sub77 seems like you submitted the same PR twice. I've tested the fix and confirm it works in powerline and powerline-multiline. not sure about the other powerline themes.

**Comment by nwinkler** [comment]
Merged #1169 - should be fixed now! Thanks for the help - closing this for now.

**Comment by jalmansor** [comment]
@nwinkler the PR from @sub77 only fixed `powerline-multiline`. The same addition needs to be made to the other powerline themes. I'll try to submit a PR for this later.

**Comment by kirk86** [comment]
@nwinkler On the same topic of showing hostname in powerline but I would like to show up like user@hostname. How we should we go about doing that, I tried `user_info$@ hostname` but not luck. Any ideas?

**Comment by nwinkler** [comment]
@kirk86 I responded in the other issue that you opened (#1416)...
