### ISSUE TITLE
Running tmux from bash-it

### ISSUE THREAD

**Issue by Toontje** [Bash-it/bash-it#1151]
Is it a good idea to automatically run tmux when i launch my terminal and if so, how do i configure that in bash-it?

**Comment by nwinkler** [comment]
Probably not something for Bash-it itself. You might want to do that as the last step in your `~/.bashrc` file...

**Comment by Toontje** [comment]
I added it to my Terminal launch command. All good. Love tmux!

**Comment by nwinkler** [comment]
Thanks for confirming!
