### ISSUE TITLE
COMP_WORDBREAKS should not be changed by completion plugins

### ISSUE THREAD

**Issue by cedef** [Bash-it/bash-it#1152]
Hi,

First, thank you very much for this awesome project ! I've discovered that recently and it's just an awesome idea !

I'm facing an issue regarding completion and I'm not comfortable enough with bash-completion problems.

I'm using: Debian 9 (Stretch), with bash version `4.4.12(1)-release (x86_64-pc-linux-gnu)` and the following bash-it plugins/completions (see attachments [bash-it show plugins](https://github.com/Bash-it/bash-it/files/1767656/bash-it-plugins.txt) and [bash-it show completions](https://github.com/Bash-it/bash-it/files/1767825/bash-it-completion.txt))

I'm also a happy user of taskwarrior and its builtin completion (see [bash-completion-task.txt](https://github.com/Bash-it/bash-it/files/1767663/bash-completion-task.txt) which comes with the Debian package).

When I'm using the `project:` taskwarrior completion _while_ bash-it loaded I'm facing the following behaviour:
![taskwarrior-completion-wrong-behaviour](https://user-images.githubusercontent.com/1536135/36796256-6de08f94-1ca5-11e8-9ff2-65cfeccf4709.gif)

Here is the expected behaviour (when *not* using bash-it):
![taskwarrior-completion-expected-behaviour](https://user-images.githubusercontent.com/1536135/36796287-80851c50-1ca5-11e8-9ad4-5fe0154db0ee.gif)

I've enabled some debugging inside the `_task()` completion function and I can see differences:
"wrong" behaviour:
```
❯ task project:Bash<Tab>
cur='project:Bash'
prev='task'
prev2=''
       BashIt
```

"expected" behaviour:
```
cedef@arval:~/tmp/bash-it-issue$ task project:Bash
cur='Bash'
prev=':'
prev2='project'
It
```

To me, it looks like there is an issue regarding what the word separator should be, within `_task()` function, but I cannot figure where the difference comes from.

To reproduce the problem, the easiest way would be to install taskwarrior (as a Debian 9 package).

Please let me know if you need further informations, I'd be happy to help fixing this issue.

Regards,

**Comment by nwinkler** [comment]
Ouch, that looks like a tough one! I'm not using Taskwarrior - can't really help with this.

What I'm not sure about is what's impacting the completion to go wrong...

One thing you could do is trying to see whether something else is trying to handle the completion for the `task` command:

```bash
complete -p | grep task
```

Run this with and without Bash-it and then we can check whether there's something going on...

**Comment by cedef** [comment]
I've already tried to compare the results without success: there are identical.
```
$ complete -p | grep task
complete -o nospace -F _task task
```

My hint would be something around completion separator (compopt or something similar) because it acts as if `:` were part of the word, instead of being a separator between 2 differents categories of word to complete (see animated gifs for details)

Thank you for you help @nwinkler, I'm still looking to fix this so any idea are welcome :)

**Comment by cedef** [comment]
OK, I found it \o/

Here is the issue (found in multiple available completion plugins (I'll talk about the `ssh` completion plugin for my example):

```
# File ~/.bash_it/completion/available/ssh.completion.bash
#!/usr/bin/env bash
# Bash completion support for ssh.

export COMP_WORDBREAKS=${COMP_WORDBREAKS/\:/}
...
```

By exporting re-assigning a value to `COMP_WORDBREAKS` (and removing the `:` from it) the global variable `COMP_WORDBREAKS` is changed.
IMO, the variable change _SHOULD_ be placed within the `_ssh()` completion function, or

**Comment by nwinkler** [comment]
Great find - it looks like this is polluting the environment.

Overwriting this variable is indeed not recommended. This SO question has a couple of options for working around this: https://stackoverflow.com/questions/10528695/how-to-reset-comp-wordbreaks-without-affecting-other-completion-script

And there's also this: https://github.com/npm/npm/issues/4530

**Comment by cedef** [comment]
How naive I was, thinking we could just use `local` !!  I love when I learn new Bashism :D
Should be fine to update those bash-it completion scripts so they don't update COMP_WORDBREAKS anymore.

I'll submit a PR when I've got some time to spend on it.

Thank for your help @nwinkler

**Comment by nwinkler** [comment]
Thanks for taking this up, @cedef - appreciate the help!

**Comment by cornfeedhobo** [comment]
Excited to see the associated PR. I've had a few issues with completion and have been meaning to dig into it, but it looks like you tracked it down! Does this mean we need to go on a spree of looking at all completion plugins?

**Comment by cedef** [comment]
@cornfeedhobo : yes, probably... I've noticed that some completions files comes directly from upstream (i.e. git) and therefore we'll probably need to ask them what they think about leaving COMP_WORDBREAKS alone :)

I've missed time for starting this work... It's still somewhere in my todolist :S

**Comment by NoahGorny** [comment]
hey @cedef - do you still have time to work on this?

**Comment by cedef** [comment]
Hello,

Unfortunately no... sorry about that :(

**Comment by NoahGorny** [comment]
It's completely fine, thank you for your time and effort :smile:
