### ISSUE TITLE
Failed to create symbolic link

### ISSUE THREAD

**Issue by aashutoshrathi** [Bash-it/bash-it#1161]
On Linux Mint 18 Machine it throws the following:
![image](https://user-images.githubusercontent.com/21199234/37385962-641b7e74-277c-11e8-9f88-69a40681f26c.png)

**Comment by nwinkler** [comment]
Did you install Bash-it using something like `sudo` by accident? Can you please check the permissions of both the `~/.bash-it` folder, and also the `enabled` folder shown in the screenshot?

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
