### ISSUE TITLE
"bad_array_subscript" on vim completions

### ISSUE THREAD

**Issue by thejohnbackes** [Bash-it/bash-it#1167]
Completions with vim are failing with "bash: _xspecs: bad array subscript" issue. I have the most recent version of bash-it.

Here is an example: type "vim foo" then tab:

2018-04-03 15:00:57 ⌚  jbackes-ld2 in ~/dotfiles/bash_config/bash-it/aliases/available
± |master ✓| → vim foobash: _xspecs: bad array subscript

```
± |master ✓| → bash-it show plugins
Plugin              Enabled?  Description
alias-completion      [x]     Automatic completion of aliases
autojump              [ ]     Autojump configuration, see https://github.com/wting/autojump for more details
aws                   [ ]     AWS helper functions
base                  [x]     miscellaneous tools
```

bash version:
```
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by thejohnbackes** [comment]
I can't recreate this on opening a new terminal window. Closing.

**Comment by seefood** [comment]
happens to me with latest master (039cfa7), when completing vi, but not when completing for vim. I'll try to compare and sync them.
