### ISSUE TITLE
terminal title not changing

### ISSUE THREAD

**Issue by kurktchiev** [Bash-it/bash-it#1178]
For some reason no matter what I do or enable my terminal title never changes from "bash"

Even running echo -ne "\033k"$(hostname -s)"\033\\" manually does not set it :/

I have tried enabling xterm plugin and disabling it. It WILL switch the title to the running process name, but thats about it. Any ideas/thoughts?

**Comment by yboikov** [comment]
try to add: ```source /etc/bashrc```
just before ```source "$BASH_IT"/bash_it.sh``` in $HOME/.bashrc

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
