### ISSUE TITLE
Conflicting fd function in fzf plugin

### ISSUE THREAD

**Issue by arunvelsriram** [Bash-it/bash-it#1183]
`fd` function in `fzf.plugin.bash` conflicts with [`fd`](https://github.com/sharkdp/fd) utility.

If you can suggest an alternate name I can make the necessary change.

**Comment by nwinkler** [comment]
Thanks for the note - I had completely forgotten about this. I had made the same change in my fork of Bash-it, and have merged the change in #1186.

The `fd` function has now been renamed to `fcd` to avoid this conflict.
