### ISSUE TITLE
[Feature Idea] Bash-it Update Check and Diffs

### ISSUE THREAD

**Issue by iammanbeard** [Bash-it/bash-it#1188]
I've been thinking about the Bash-it update feature and had a couple ideas I wanted to bounce off you all before I start diving down that road. 

First, the `update` option should have the ability to check for an update and display some information (maybe the commits and their links?) before actually committing to updating

Second, which is partially dependent on the first, is adding the ability to see that status easily, either MOTD-esque (like when you open a new terminal) or an icon in your prompt (like SCM status). 

Comments? Thoughts? Questions? Concerns? I'm actually pretty new to customizing `bash`, but I thought this might be a useful first project.

**Comment by nwinkler** [comment]
Yes, this sounds like a good set of features to work on. A couple of thoughts:
* Definitely split this into two separate pull requests.
* Whatever functionality you're adding, make it optional, with the current behavior as the default. We don't want to break the existing functionality.
* Please add/update unit tests for any changes.
* For your second idea (Bash-it update status): Try to avoid overhead, e.g. checking for the status in every prompt. It should ideally only be done once when opening a new shell. If you want to go with an indicator in the prompt, you'd probably have to add it to one of the themes.

Makes sense?

**Comment by NoahGorny** [comment]
This was pretty implemented :smile:
