### ISSUE TITLE
Broken line issue

### ISSUE THREAD

**Issue by jbuisine** [Bash-it/bash-it#1190]
Hi !

I would like to tell you that I encountered issues with use of **bash-it**. 

First, when I write a command which not fits into the displayed width of terminal. As you can see on picture below, characters are erased at the beginning of the line by the end of new command.

![issue1](https://user-images.githubusercontent.com/11876986/39472663-127dd162-4d4b-11e8-87ca-86eaeba11873.png)

Second one, when I want to use history with the upper arrow key, it seems to erase previous displayed lines on terminal and make it unreadable.

![issue2](https://user-images.githubusercontent.com/11876986/39472665-16f3f9ce-4d4b-11e8-9b8b-3ebaee475f3e.png)

I didn't find someone which has same issues. If I made a mistake do not hesitate to give the link !

Thanks in advance,

Jérôme.

**Comment by nwinkler** [comment]
Isn't this similar to #1133?

**Comment by jbuisine** [comment]
Thanks for your answer!

Indeed, it seems to be the same issue. I use 'powerline-multiline' theme and it works better. I have just a little issue when I have a very long path such as example below :

![issue3](https://user-images.githubusercontent.com/11876986/39486260-c91f0604-4d7b-11e8-8b5a-bb6748972e65.png)

Perhaps this issue already exists.

**Comment by utrescu** [comment]
I had the same problem and I fixed it enabling 'checkwinsize' because it was disabled:

    $ shopt checkwinsize
    checkwinsize   	off

After activating it the problem disappears:

    $ shopt -s checkwinsize

So I put the command in .bashrc

**Comment by fxaviersala** [comment]
The same problem once again happened to me in a new installation of Fedora. And now `checkwinsize` did not solve the problem

The solution I have found has been to surround the variable `scm_prompt_info` with `\[` ... `\]`. 

For example, in the `clean` theme I had to change the line:

    PS1="${no_color}\u${reset_color}:${blue}\W/${reset_color} $(scm_prompt_info)${normal}$ "

for this one:

    PS1="${no_color}\u${reset_color}:${blue}\W/${reset_color} \[$(scm_prompt_info)\]${normal}$ "

**Comment by utrescu** [comment]
The same problem once again happened to me in a new installation of Fedora. And now `checkwinsize` did not solve the problem

The solution I have found has been to surround the variable `scm_prompt_info` with `\[` ... `\]`. 

For example, in the `clean` theme I had to change the line:

    PS1="${no_color}\u${reset_color}:${blue}\W/${reset_color} $(scm_prompt_info)${normal}$ "

for this one:

    PS1="${no_color}\u${reset_color}:${blue}\W/${reset_color} \[$(scm_prompt_info)\]${normal}$ "

**Comment by NoahGorny** [comment]
hey @jbuisine
Does the issue still exists?

**Comment by jbuisine** [comment]
Hey @NoahGorny !

It seems to be fixed now !
