### ISSUE TITLE
Enabling plugins doesn't seem to work

### ISSUE THREAD

**Issue by kirk86** [Bash-it/bash-it#1197]
Hi everyone and thanks for this work! I was wondering if you could decipher something for me. Do we need to install plugins separately/manually ourselves prior to enabling them? It seems to me that just enabling a plugin doesn't do anything. For instance I've enabled autojump but when I try to follow the examples `j Downloads` nothing happens. I thought that by enabling plugins they automatically get installed as well?

**Comment by nwinkler** [comment]
No, they don't get installed. If you want to use autojump, you'll have to install it manually, e.g. through your OS's package manager or similar.

The `bash-it enable` functionality simply enables the Bash-it plugin, which helps with loading autojump, but it does not install autojump (or other dependencies).

**Comment by kirk86** [comment]
@nwinkler ok, thanks that makes sense and verifies my assumption. Cheers!
