### ISSUE TITLE
Extra space at end of PS1

### ISSUE THREAD

**Issue by yang** [Bash-it/bash-it#1208]
On macOS 10.13, using iTerm.  Seems to not matter which theme I'm using, there's an extra empty space at the end of `PS1`:

![screen shot 2018-07-03 at 2 56 56 pm](https://user-images.githubusercontent.com/7129/42246450-6f6c849c-7ed1-11e8-8e10-092e6ee6e3af.png)
![screen shot 2018-07-03 at 2 57 04 pm](https://user-images.githubusercontent.com/7129/42246451-6f89b350-7ed1-11e8-9b4f-3674e1c26fcc.png)

Doesn't happen when I don't use bash-it themes:

![screen shot 2018-07-03 at 2 57 12 pm](https://user-images.githubusercontent.com/7129/42246461-77f8c882-7ed1-11e8-9f2e-ddc51ee2f46f.png)

**Comment by nwinkler** [comment]
Please feel free to provide a Pull Request to fix this...

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
