### ISSUE TITLE
XDOTOOL failing 

### ISSUE THREAD

**Issue by samlambert96** [Bash-it/bash-it#1220]
Hi guys,

After working fine for months on end, my raspberry pi's are now throwing up error messages when I'm trying to run a script. I have attached the following errors, or what I think to be the errors anyway.

My scrips simple opened a desired URL, and entered the username and password and clicked login.

If someone could explain what the error messages mean, or can suggest another way to do this kind of script, I would be more than grateful.

![ubuntuimg](https://user-images.githubusercontent.com/41616389/43129483-6c7d3892-8f2c-11e8-926d-7990723ab9f8.PNG)

Any help is welcome.
Thanks, Sam

**Comment by nwinkler** [comment]
Just to confirm: Are you using the Bash-it framework (as in this GitHub repo) on this machine?

At first glance, I don't see how your question might be connected to Bash-it...

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
