### ISSUE TITLE
error in line 5

### ISSUE THREAD

**Issue by harsh-anand1999** [Bash-it/bash-it#1229]

**Comment by nwinkler** [comment]
Any more details than that?

**Comment by harsh-anand1999** [comment]
I am using 18.04 Ubuntu mate desktop environment, during compilation it
shows an error in line 5

**Comment by nwinkler** [comment]
Sorry, but we'll need more details. What compilation are you talking about? Can you please post a screenshot or a log of what you're trying to do that leads up to the error? And how is this related to Bash-it?

**Comment by DranoelMit** [comment]
@harsh-anand1999 use  `./install.sh` not `sh ./install.sh`
That fixed the issue for me

![image](https://user-images.githubusercontent.com/24358521/50312647-07ccea80-0477-11e9-994e-ccff5e2916b3.png)
