### ISSUE TITLE
Weird Performance issue

### ISSUE THREAD

**Issue by lightyaer** [Bash-it/bash-it#1233]
I had installed bash it, just to check it out, but didnt like that it took a huge amount of time to start in vscode or externally, 
PS> i have a high end laptop XPS 15 2018, 

Anyways.. so I uninstalled it.. still my bash is running slow as usual.. 
i uninstalled and installed gitscm alot of times.. but no improvement.. 

On the other hand.. my office pc is years old with 8gb ram and an i5 of 3rd gen.. which run bash.exe is vscode in less than a second.. Although I had the same performance before installing bash it on my laptop.

So things I have done is.. copy the bashrc file from work pc to laptop.. still no difference.. 

Made a new user on my laptop and checked if the bash.exe in vscode runs any better, still no difference..

Kindly suggest how I  do completely remove bash it..

I'm on windows pro x64

**Comment by nwinkler** [comment]
The only thing you have to do is to remove the lines loading Bash-it from your `~/.bashrc` and/or `~/.bash_profile` files. Depending on the OS, it might be in either of these.

There's also an `uninstall.sh` script in the Bash-it distribution that does the exact same thing.

After that, you should be back to normal.

**Comment by nwinkler** [comment]
There really shouldn't be anything that launches Bash-it. Please feel free to post your `~/.bashrc` and `~/.bash_profile` files here.

**Comment by ttnguyen89** [comment]
I have the same performance problem. I'm currently using a Xeon 16G Ram machine.
I removed the ~/.bashrc and everything comes back to original. However, when I reinstalled bash_it, it got slow again.

**Comment by nwinkler** [comment]
After installing Bash-it and opening a new shell, please post the output of the following commands:
* `bash-it show aliases`
* `bash-it show completions`
* `bash-it show plugins`

**Comment by NoahGorny** [comment]
dup of #517
