### ISSUE TITLE
[Question] How to show python virtual environment in command prompt after activating?

### ISSUE THREAD

**Issue by sulhome** [Bash-it/bash-it#1235]
When activating a python virtual environment (`source <env folder>/bin/activate`), the command prompt doesn't show the virtual environment name. I have enabled the python plugin but that didn't make any difference.

Is this supported in bash it or I need to create some custom scripts to enable it.

I am running on ubuntu 16.04

**Comment by sulhome** [comment]
I am using the `minimal` theme

**Comment by nwinkler** [comment]
Well, as the name indicates, the "minimal" team is fairly minimal. It does not include a lot of information:

https://github.com/Bash-it/bash-it/blob/ceee5cb2c165eba2f1c72f1c15039561e616fbb7/themes/minimal/minimal.theme.bash#L9

You might want to try using another theme that includes more information.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
