### ISSUE TITLE
How to change theme for current session only

### ISSUE THREAD

**Issue by jrop** [Bash-it/bash-it#1240]
I think this is expected behavior, but I would like to change the Bash-It theme on a one-off basis sometimes (e.g., I am loading env to work in production and I want the prompt to look different).

Things I have tried:

**Attempt 1**:
```sh
export BASH_IT_THEME=bobby
bashit reload
```

**Attempt 2**:
```sh
BASH_IT_THEME=bobby bashit reload
```

**Attempt 3**:

Update profile:
```diff
- export BASH_IT_THEME='minimal'
+ [[ -z $BASH_IT_THEME ]] && export BASH_IT_THEME='minimal'
```

Then tried both (1) and (2) to no avail.

Do you have a recommendation for accomplishing what I am trying to do?  Thanks for such a great tool!

**Comment by nwinkler** [comment]
Well, the `bash-it reload` command simply reloads your profile, so whatever you have in there gets loaded/set.

I don't have a better suggestion for this at the moment, sorry...

**Comment by jrop** [comment]
@nwinkler No worries, I kind of guessed as much.  All the same, I'm loving bash-it, it's awesom

**Comment by nwinkler** [comment]
Thanks for the praise, glad that you like it!

Having said that, I'm sure that with some variable/default fiddling in your Bash profile, you can achieve what you want, e.g. by checking for something like _theme override_ variable after the initial setting of `BASH_IT_THEME`. If that override variable is set, simply set the `BASH_IT_THEME` variable again. That should work...

**Comment by NoahGorny** [comment]
`bash it restart` is the preferred solution now :smile:
