### ISSUE TITLE
Tab completion error

### ISSUE THREAD

**Issue by msis** [Bash-it/bash-it#1245]
I just checked out the latest commit : 4a64dcbc6f15b9b2cd3883a96f81bc94a5a0fe24 I am having issues with the completion: for instance if I hit tab after `vim.tiny` I get the following error:

```shell
vim.tiny bash: vim.tiny: syntax error: invalid arithmetic operator (error token is ".tiny")
```

Note that when hitting tab just after `vim.tin`, it will complete to `vim.tiny `. The issue only happens after the space is added. 

N.B. : I didn't have this issue before installing bash-it.

-----
System details:
```shell
$ bash-it version
Current git SHA: 4a64dcb on 2018-10-18T15:43:37+02:00
https://github.com/Bash-it/bash-it/commit/4a64dcb
Compare to latest: https://github.com/Bash-it/bash-it/compare/4a64dcb...master

$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by caguettaz** [comment]
@msis, do you use Debian and its bash-completion package?

I had the same issue with it.

I solved it in this commit: https://github.com/caguettaz/bash-it/commit/c0389d0ff14bb0d4502b7fd5f3a564d773328695

It's dirty though, and only works with bash 4.2 and up, hence the lack of PR.

---------------------

Here's a quick explanation of the fix:

bash-completion uses an associative array named `_xspecs`, which it needs to be declared to work properly.

It's declared using `declare -A`, which is [local when executed within a function](https://stackoverflow.com/questions/10806357/associative-arrays-are-local-by-default).

This would be fine when sourcing the file straight away, but bash-it sources files from within the function `_load_bash_it_files`, making `declare -A` variables invisible in the global scope, hence the issue.

My quick and dirty fix temporarily makes every 'declare' global using an alias, which is less than ideal.

A cleaner fix would probably be to do away with `function _load_bash_it_files` and load files inline. That's not great either though.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
