### ISSUE TITLE
Commands suggested by apropos are not working

### ISSUE THREAD

**Issue by P34rL** [Bash-it/bash-it#1263]
I was trying to look for encryption commands with apropos:

**apropos encrypt**

A lot of them don't work, for example:  gpgsm, setkey, passwd2des etc.
When I type them I just get:

 _bash: *command_name*: command not found_

Any idea on how to fix this?
Thanks in advance!

**Comment by nwinkler** [comment]
I'm sorry, how is this related to Bash-it? This looks like a generic Bash question...

**Comment by P34rL** [comment]
Oh sorry, in that case could you please point me to the repository in which I should post this issue? I signed up yesterday, I don't really know my way around here.

**Comment by nwinkler** [comment]
No problem! You might want to try posting questions like this on https://unix.stackexchange.com.
