### ISSUE TITLE
Hosts plugin

### ISSUE THREAD

**Issue by philipjohn** [Bash-it/bash-it#1264]
As someone who regularly needs to edit my `/etc/hosts` files, a plugin to make that easier might be good. I could envisage something like this:

Add a hosts entry:

```
$ hosts add 127.0.0.1 example.com
Added 127.0.0.1 example.com to hosts file
```

List hosts entries:

```
$ hosts list
127.0.0.1 example.com
```

Remove a hosts entry:

```
$ hosts remove example.com
Removed 127.0.0.1 example.com from hosts file
```

Dropping the idea because there are probably people better than me at this stuff to work on it :) I might still give it a go, though...

**Comment by nwinkler** [comment]
Sounds good - please feel free to provide a PR for this.

**Comment by tbhaxor** [comment]
As far as i know every time you try to add host entry, you'll need `sudo`

**Comment by jusdepatate** [comment]
I'll try to add this with a PR

**Comment by tbhaxor** [comment]
@nwinkler 
I got some stuff

![image](https://user-images.githubusercontent.com/28386721/59132187-19a53a00-8992-11e9-9648-50bca6236a71.png)
Is it fine, like you have a lot of issue with #1321

**Comment by georgettica** [comment]
also here @nwinkler, seems code was done but not merged for reasons..
should this be resurfaced?

**Comment by davidpfarrell** [comment]
Greetings - Although the two PR's mentioned here are ok starts, I have issues with the concept as a whole:

A useful hosts management tool shouldn't be locked away inside a bash-it plugin. It should exist as its own project that can be used by everyone and improved by the entire community.

The hosts file format is more nuanced than these PRs suggest, i.e allowing multiple domains on the same line.

Trying to manage the need for root access makes a plugin more complicated.

There exists at least two popular standalone tools to manage hosts files:
* [Hosts](https://github.com/xwmx/hosts) - Implemented in ~1,700 lines of Bash - Installable via Brew, has Completion support
* [Hostess](https://github.com/cbednarski/hostess) - Implemented in Go

I recommend we close the issue/PR's in favor of standalone tools.

**Comment by nwinkler** [comment]
Completely agree - don't really want to add the complexity if there are other tools that already do the job...
