### ISSUE TITLE
Arch DE login loop after installing Bash-it

### ISSUE THREAD

**Issue by yaceben** [Bash-it/bash-it#1266]
#### Issue
Stuck in boot loop after installing bash-it

#### Steps to reproduce issue
install arch linux with cinnamon desktop

**install bash-it**
-- from the installation instructions
1. Check out a clone of this repo to a location of your choice, such as git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
2. Run ~/.bash_it/install.sh (it automatically backs up your ~/.bash_profile or ~/.bashrc, depending on your OS)

**activate it**
source .bashrc

it works without errors... until
reboot
you're now stuck in a login loop in DE
switch to terminal (CTRL+ALT+F2)
login
terminal properly applies themes etc. no error message

#### Expected Result
Being able to normally login

#### Temporary Solution
reactivate old working .bashrc file

#### System information
NAME="Antergos Linux"
VERSION="18.11-ISO-Rolling"
ID="antergos"
ID_LIKE="arch"
PRETTY_NAME="Antergos Linux"
CPE_NAME="cpe:/o:antergosproject:antergos:18.11"
ANSI_COLOR="1;34;40"
HOME_URL="https://antergos.com/"
SUPPORT_URL="https://forum.antergos.com/"
BUG_REPORT_URL="https://github.com/antergos"
Kernel=4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux

**Comment by nwinkler** [comment]
Can you please describe the above steps in more detail, especially the "install bash-it" and "activate it" steps?

Also, once you have activated Bash-it, what happens when you open a new Terminal/shell without rebooting? Are there any messages displayed?

And, which user are you installing Bash-it for/with? The `root` user?

**Comment by yaceben** [comment]
> Can you please describe the above steps in more detail, especially the "install bash-it" and "activate it" steps?
> 
> Also, once you have activated Bash-it, what happens when you open a new Terminal/shell without rebooting? Are there any messages displayed?
> 
> And, which user are you installing Bash-it for/with? The `root` user?

Thanks for the quick reply @nwinkler, I edited my original post with more info.
I installed it for the local user (me), it works until I reboot or logout. My /var/log/gdm/ is empty so I'm not sure where to start looking...
I had the same problem with a previous bashrc that included some debian-based variables but that's about the only clues I have for now.

Cheers

**Comment by yaceben** [comment]
@nwinkler The following are enabled:
- general            
- bash-it 
- system   
- alias-completion  
- base
if you could suggest a possible way to provide more detailed logs I'd be more than happy to provide them.

**Comment by nwinkler** [comment]
Try to disable the alias-completion plugin, this does a lot of things behind the scenes that might potentially cause trouble...

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
