### ISSUE TITLE
Conflict with iTerm2's shell integration script

### ISSUE THREAD

**Issue by gnachman** [Bash-it/bash-it#1278]
I received a report that bash-it conflicts with iTerm2's shell integration scripts:

https://gitlab.com/gnachman/iterm2/issues/6045

It seems the xterm plugin in particular has a problem. When I investigated, I saw that bash-it uses an old version of the preexec library that does not guard against duplicate installs. There is a much newer fork of the twisted matrix code you're using that fixes a lot of bugs. It is here: https://github.com/rcaloras/bash-preexec

**Comment by nwinkler** [comment]
Thanks for reporting this - would be great to get a PR for this!

**Comment by LanikSJ** [comment]
I took a stab at this one.  More like stabbing in a dark really but maybe we can test this with iTerm and see if things get better?

@gnachman any chance we can get the person reporting the issue to test my branch?

**Comment by gnachman** [comment]
@LanikSJ Comment in https://gitlab.com/gnachman/iterm2/issues/6045 and give them the info they need. It's a bit of an older issue but it's worth a try.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
