### ISSUE TITLE
error message when terminal start and enable/disable

### ISSUE THREAD

**Issue by Novite5** [Bash-it/bash-it#1286]
displays error message when terminal starts and enable/disable aliases plugins or completions

`
bash: local: kann nur innerhalb einer Funktion benutzt werden.
bash: [: -lt: Einstelliger (unärer) Operator erwartet.
`

OS: Archlinux
locale: German

**Comment by Novite5** [comment]
GNU bash, Version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
[.bashrc](https://pastebin.com/i7sjk6Sa)
Completion enabled: bash-it defaults dirs export gem git go makefile npm nvm pip3 pip pipenv projects rvm ssh system tmux virtualbox
Plugins enabled: base battery direnv explain fasd fzf git  go history node nvm percol proxy pyenv ruby ssh virtualenv

**Comment by nwinkler** [comment]
Thanks for the additional info. Can you please try to disable all completions and plugins, and then open a new Terminal to see if the error is gone? If it's gone, you can start enabling things one by one again, running `bash-it reload` after each change. Hopefully we can narrow it down by doing this.

I know that's a lot to ask, and I'm sorry about having to do this - but this seems to be the easiest way to figure out what might be causing this.

**Comment by Novite5** [comment]
Thank you for your reply. 
I've just all these tried. Finally, I find it's caused by the percol plugin.

**Comment by nwinkler** [comment]
Thanks - that really helped. The `local` keyword in the `percol` plugin was causing this issue - I've fixed this in #1287.

Thanks again for reporting this and helping with solving the issue - much appreciated!

**Comment by Novite5** [comment]
Thank you very much for your work! It has saved me very much time.
