### ISSUE TITLE
 `/usr/bin/which: no xx in($PATH)`

### ISSUE THREAD

**Issue by ComplicatedPhenomenon** [Bash-it/bash-it#1290]
I install `bash-it` through `~/.bash_it/install.sh --interactive`. Since I don't exactly the meaning of setting up something about alias and plugins, I very likely made some bad choices. Then every time I launch the terminal, information like below show up at first.

![screenshot from 2018-12-23 16-22-46](https://user-images.githubusercontent.com/24690806/50381974-0b5aae80-06cf-11e9-8acc-3c12d70386da.png)

How to correct the configuration then it won't display this information anymore.

**Comment by nwinkler** [comment]
Please run the following:

```
bash-it disable alias all
bash-it disable completion all
bash-it disable plugin all
```

Then start a new shell and just enable the ones you want/need - don't enable everything.

**Comment by ComplicatedPhenomenon** [comment]
Problem solved then, thanks.

**Comment by nwinkler** [comment]
Thanks for confirming - appreciate the feedback!
