### ISSUE TITLE
error running install.sh

### ISSUE THREAD

**Issue by lenovolobo933** [Bash-it/bash-it#1291]
hi i experienced the following error when running the install script:

Installing bash-it
Would you like to keep your .bashrc and append bash-it templates at the end? [y/N] y
./install.sh: line 132: /home/lenovo/.bashrc: Permission denied
Bash-it template has been added to your .bashrc

Enabling reasonable defaults
bash-it is already enabled.
system is already enabled.
base is already enabled.
alias-completion is already enabled.
general is already enabled.

Installation finished successfully! Enjoy bash-it!
To start using it, open a new tab or 'source /home/lenovo/.bashrc'.

To show the available aliases/completions/plugins, type one of the following:
  bash-it show aliases
  bash-it show completions
  bash-it show plugins

To avoid issues and to keep your shell lean, please enable only features you really want to use.
Enabling everything can lead to issues.

also when trying to run bash-it, it returns command not found

**Comment by nwinkler** [comment]
The error seems to be here:

```
./install.sh: line 132: /home/lenovo/.bashrc: Permission denied
```

Can you please ensure that your own user has write permissions for that file? Once you have fixed that, please run the installer again.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
