### ISSUE TITLE
[FEATURE] = Add bash completions for vue js

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1292]
Vue js is a front end framework, plz do add its bash completions

**Download Vue Cli**
```
npm i -g @vue/cli
```

**Comment by tswicegood** [comment]
Thanks for the request @tbhaxor. I’d love to review a PR for adding this if you wanna take a stab.

**Comment by tbhaxor** [comment]
I am new to bashit
Will you plz guide me in understadjng ur coding sta dards ?

**Comment by nwinkler** [comment]
Thanks - looking forward to your contributions!

A good starting point are these:
* Take a look at the other completion scripts in the `completion/available` folder to see how they work, e.g. this one: https://github.com/Bash-it/bash-it/blob/master/completion/available/brew.completion.bash
* Also take a look at the `CONTRIBUTING.md` file: 
https://github.com/Bash-it/bash-it/blob/master/CONTRIBUTING.md

**Comment by tbhaxor** [comment]
@nwinkler i wont be able to PR for this issue
Somebody else can open PR

**Comment by tbhaxor** [comment]
@nwinkler  please review the PR

**Comment by nwinkler** [comment]
Great - thanks!
