### ISSUE TITLE
missing commands: compgen and _command_exists

### ISSUE THREAD

**Issue by nkorde** [Bash-it/bash-it#1298]
On my mac I get this error

BZ-C02W42D4HTD8% source /Users/neeraj.korde/.bash_profile
/Users/neeraj.korde/.bash_it/bash_it.sh:source:36: no such file or directory: /Users/neeraj.korde/.bash_it/lib/*.bash
/Users/neeraj.korde/.bash_it/scripts/reloader.bash:11: command not found: compgen
/Users/neeraj.korde/.bash_it/themes/base.theme.bash:438: command not found: _command_exists
/Users/neeraj.korde/.bash_it/themes/base.theme.bash:448: command not found: _command_exists
safe_append_prompt_command:3: = not found

Where can I get these missing commands from ?

**Comment by dualbus** [comment]
On Mon, Dec 31, 2018 at 2:29 PM Neeraj K <notifications@github.com> wrote:

> On my mac I get this error
>
> BZ-C02W42D4HTD8% source /Users/neeraj.korde/.bash_profile
> /Users/neeraj.korde/.bash_it/bash_it.sh:source:36: no such file or
> directory: /Users/neeraj.korde/.bash_it/lib/*.bash
> /Users/neeraj.korde/.bash_it/scripts/reloader.bash:11: command not found:
> compgen
> /Users/neeraj.korde/.bash_it/themes/base.theme.bash:438: command not
> found: _command_exists
> /Users/neeraj.korde/.bash_it/themes/base.theme.bash:448: command not
> found: _command_exists
> safe_append_prompt_command:3: = not found
>
What version of Bash are you using? The `%' in the prompt and the fact that
it complains about `compgen' (a Bash builtin) makes me think you're not
using Bash, perhaps Zsh?

**Comment by MuYunyun** [comment]
@dualbus You mean it only be used in Bash? How about using in Zsh?

**Comment by nwinkler** [comment]
Well, the framework is named "Bash-it" - it's not guaranteed to work with Zsh.
