### ISSUE TITLE
Add a cli argument to change theme

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1307]
bashit should change theme from cli
```
bashit switch <theme-name>
```

Also this could run `bashit reload` afterwards

**Comment by nwinkler** [comment]
Please feel free to provide a PR for this if you want to see this functionality in Bash-it.

**Comment by tbhaxor** [comment]
@nwinkler will you please guide me where do i add my code for registering new cli arguments for bashit ?

**Comment by nwinkler** [comment]
All of the CLI options are handled in `helpers.bash`: https://github.com/Bash-it/bash-it/blob/master/lib/helpers.bash

A couple more questions: Do you see a real use case for this additional new command? How frequently do you change your prompt theme? Changing the theme manually is not that difficult (edit profile, then `bash-it reload`) - does this really require a specific command?

**Comment by tbhaxor** [comment]
@nwinkler  Sorry sir :disappointed:

**Comment by nwinkler** [comment]
No need to be sorry at all. If there's a real need for a certain command, then let's add it - but let's figure out first whether it's really needed.
