### ISSUE TITLE
BUG: bad array subscript

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1308]
Whenever i write `vbr` and press tab i get the error
```
terabyte at h3ll in ~/Downloads
$ vbrc bash: _xspecs: bad array subscript

```

**Comment by nwinkler** [comment]
I just tried this locally and it works fine for me...

**Comment by tbhaxor** [comment]
OS : Arch Linux 4.20
Bashit Version
```
Current git SHA: 9f61cd3 on 2019-01-09T09:10:30+01:00
https://github.com/Bash-it/bash-it/commit/9f61cd3
Compare to latest: https://github.com/Bash-it/bash-it/compare/9f61cd3...master
```
Bash Version : 4.4.23(1)-release

**Comment by tbhaxor** [comment]
I am closing this because of no response from your side

**Comment by nwinkler** [comment]
I'm sorry about the lack of response, but I'm not sure what to do about this issue. Like I've said above, I tried this locally, and it works just fine for me, no error...

**Comment by arghasen** [comment]
I see the same bug on my installation. Do you use negative array indexes?
