### ISSUE TITLE
Make bash_it and extraterm play nicely together

### ISSUE THREAD

**Issue by spkane** [Bash-it/bash-it#1319]
I use the bash_it (https://github.com/Bash-it/bash-it
) framework for managing bash plugins/themes and it doesn't quite play nice with the setup script for ExtraTerm (https://github.com/sedwards2009/extraterm), mostly because they both define some of the same post/pre functions.

I've been playing with it a little bit, but am still having issues getting them to play 100% nicely together. That being said, I don't think it would be too hard, just might require some small changes to both.

If I figure out a basic working example, I'll post it here, but I'd love some other eyes on it, if anyone feels inspired.

**Comment by spkane** [comment]
https://github.com/sedwards2009/extraterm/issues/161

**Comment by nwinkler** [comment]
Good stuff - I was not aware of ExtraTerm - looks nice! There's another PR that deals with some of the pre/post scripts here (#1304), maybe take a look there?

**Comment by spkane** [comment]
Great. I will take a look at that PR!

Just to make sure these reports point to each other. This issue is likely very similar to this bug: https://github.com/Bash-it/bash-it/issues/1278
