### ISSUE TITLE
Bash-it slowdown when search domains turned on

### ISSUE THREAD

**Issue by madIlama** [Bash-it/bash-it#1330]
# Issue

When "search domain" activated in network manager , bash with bash-it config will experience slowdown

# Expected Behavior

Bash run normal

# Current Behavior

Bash prompt slowing down, similiar to #572 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Join any network which already turn on localdomain in their local dns
2. Use "search domain" feature in local machine (which bash-it installed) network configuration
3. Use bash-it

## Other Detail

* Linux 4.20.0-1-MANJARO SMP PREEMPT Mon Dec 24 08:20:48 UTC 2018 x86_64 GNU/Linux
* Current git SHA: f02dab4 on 2019-02-05T08:58:23+01:00

**Comment by betawi** [comment]
bash_profile

```
# ~/.bash_profile
#
export SCM_CHECK=false
export BASH_IT_THEME='redline'
[[ -f ~/.bashrc ]] && . ~/.bashrc
```

**Comment by nwinkler** [comment]
Thanks for reporting this! Can you please provide the following:
* Which Bash-it aliases, completions, and plugins do you have enabled?
* When/where are you seeing the slowdown? When opening a new terminal, or when hitting the Enter key in a terminal, i.e. is the slowdown impacting the terminal start, or every command execution?
* Are you inside of an SCM repo (e.g. Git) when you see the slowdown?

**Comment by betawi** [comment]
1. Aliases,Completions & Plugins
    Alias
```
ag                    [x]     the silver searcher (ag) aliases
clipboard             [x]     pbcopy and pbpaste shortcuts to linux
fuck                  [x]     
general               [x]     general aliases
git                   [x]     common git abbreviations
```
    Completion
```
bash-it               [x]     
defaults              [x]     
export                [x]     
git                   [x] 
```
    Plug-ins
```
alias-completion      [x]     Automatic completion of aliases
base                  [x]     miscellaneous tools
battery               [x]     display info about your battery charge level
browser               [x]     render commandline output in your browser
explain               [x]     mankier.com explain function to explain other commands
extract               [x]     one command to extract them all...
git                   [x]     git helper functions
history               [x]     history manipulation
less-pretty-cat       [x]     pygmentize instead of cat to terminal if possible
```
2. Prompt, Hitting enter or Ctrl+[key]
command execution is normal

3. No

**Comment by betawi** [comment]
ahh i think it might come with my current theme `redline`
funny enough, if you set search domain (in network manager) to existing domain but without your ip/host recorded , `redline` theme will display it domain instead

example, setting search domain : reddit.com

![image](https://user-images.githubusercontent.com/1744593/52938771-18291500-3395-11e9-9b7a-e9825a55dbfb.png)

**Comment by betawi** [comment]
further inspection seems suggest that my problem probably caused because i lost connection to my external private dns because vpn broke out, which lead timeout to hostname resolution

**Comment by nwinkler** [comment]
Yes, the `redline` theme shows the `hostname` by default, which could explain the slowdown if you're having network issues. If you happen to replicate this issue, you can try running `hostname -s` (which is what the theme is doing under the hood), and you should see the same slowness there.

(Good thinking about the theme, BTW - I did not have that in my list of questions.)
