### ISSUE TITLE
Consider renaming coloured less and cat

### ISSUE THREAD

**Issue by markusdd** [Bash-it/bash-it#1331]
I love the feature to highlight cat and less outputs with pygments, e.g. to quickly vie scripts or code on the command line with hightlighting.

Although in my envrionment, I noticed that especially for cat, it is dangerous to actually alias the 'coloured cat' to cat. Some scripts, and also I myself on the command line, commonly use cat in conjunction with piping or stream redirection. If you do that with this bash-it plugin, you will actually pipe the content plus all the pygments insertions, which is generally not what you want.

I personally modified my environment to create the aliases ccat and cless (coloured cat, coloured less) instead, so the original cat and less are not touched and function as they should normally.

**Comment by nwinkler** [comment]
Good point - do you want to create a PR for that?

(FWIW, personally, I use https://github.com/sharkdp/bat - it's awesome)

**Comment by markusdd** [comment]
There you go:
https://github.com/Bash-it/bash-it/pull/1332

**Comment by nwinkler** [comment]
Thanks!
