### ISSUE TITLE
[FEATURE] : Add github new issues and new pull request templates

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1335]
Why don't we add GitHub templates for new issue and new pull request.
It will be more convenient in submitting bug report / feature request or new pull request

**Comment by nwinkler** [comment]
That's a good idea, yes. Do you have a suggestion for what these should look like? I'm more than happy to review if you provide an initial draft.

**Comment by tbhaxor** [comment]
@nwinkler shall i proceed ?
