### ISSUE TITLE
scm_prompt_info is returning nothing on certain linux distros

### ISSUE THREAD

**Issue by chairmanjones** [Bash-it/bash-it#1338]
When run, scm_prompt_info is returning nothing on Arch, Gentoo and for some reason one CentOS7 VM but not others. This results in no git branch info in the prompt for themes that use scm_prompt_info.

Only bash-it and system completions are enabled, and alias-completion and base plugins.

Where do I go from here to further debug?

**Comment by nwinkler** [comment]
Here are a couple of things to look at:
- Which theme are you using in Bash-it?
- Depending on the theme, you can look at the code that is run by `scm_prompt_info` and then run the commands individually, e.g. `git status`.
- There are environment variables in Bash-it that disable the SCM info in the prompt.
- I assume that you have verified that the `git` executable is installed and on the PATH, right?
- Lastly, please make sure that you're actually running a Bash shell. Some distros replace the `bash` executable with a different shell, e.g. `dash`.

**Comment by chairmanjones** [comment]
Codeword, pure, and I tried a couple others.
scm_prompt_info returns nothing, you simply get a new line. git status is normal and correct
SCM isn't disabled, it's explicitly enabled in .bashrc
Git:
`jjones@monkey-king:~/git-projects/Scripts [±] $ which git && `which git` --version
/usr/bin/git
git version 2.21.0`
Bash:
`jjones@monkey-king:~/git-projects/Scripts [±] $ which bash && `which bash` --version
/usr/bin/bash
GNU bash, version 5.0.2(1)-release (x86_64-pc-linux-gnu)`

Is it possible I'm missing a prereq library or something?

**Comment by nwinkler** [comment]
Thanks for checking! That's really weird - not sure what's happening here. You could try to run the shell with `set -x` to see what's going on, but that is going to generate a lot of output.

You could actually try to add the `set -x` and `set +x` code inside of the SCM function in the prompt to see what's happening there.

The other thing I could think of is that it's potentially not detecting that it's inside of a Git repo and never call the scm_prompt_info function.

Just to be sure, can you try the `powerline-multiline` theme? That's the one I use and it works fine...

**Comment by chairmanjones** [comment]
Powerline variants work fine; I'll take a look into the debug later.
To note, these are all VMs on a common user directory mounted via NFS, could that be a culprit?

**Comment by chairmanjones** [comment]
I managed to fix this by running `git config --global --add bash-it.hide-status 0`, not sure if it's a repeatable thing but I had not previously set hide status for any repos.

**Comment by nwinkler** [comment]
That's weird, why would that flag be set to 1 in a default configuration - something's wrong here...

Thanks for debugging this, and for posting an update!
