### ISSUE TITLE
Allow users to toggle exit code display

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1342]
Allow user to choose whether to display exit code

**Comment by tbhaxor** [comment]
@nwinkler may i proceed ?

**Comment by nwinkler** [comment]
Sorry, what does this mean? Are you referring to themes in this context?

**Comment by tbhaxor** [comment]
Some themes shows exit code of the command and some not. 
I want to add a feature to bashit that could allow user to manually set / unset whether to show exit code in prompt or not

This might be helpful from development point of view

**Comment by tbhaxor** [comment]
> Sorry, what does this mean? Are you referring to themes in this context?

@nwinkler  Yes i am refering this feature in context with themes only

**Comment by nwinkler** [comment]
Can you please elaborate on what would be the benefit of being able to turn the exit code on/off?

As an example, I really like the exit code to be shown - why would I want to turn this off?

**Comment by tbhaxor** [comment]
Originally in the `sexy` theme
```
terabyte at h3ll in ~
$
```

I want user to choose whether to show an exit code of command or not
```
terabyte at h3ll in ~ exited with 0
$ jdklshfdjs
bash: jdklshfdjs: command not found
terabyte at h3ll in ~ exited with 127
$
```

**Comment by tbhaxor** [comment]
> Can you please elaborate on what would be the benefit of being able to turn the exit code on/off?
> 
> As an example, I really like the exit code to be shown - why would I want to turn this off?

@nwinkler  its not only for you some non programmer users / tech geeks might not want this functionality. They just want a beautiful minimal theme :confused:

**Comment by nwinkler** [comment]
Well, that's true, I guess. Just wanted to understand what the motivation for this request was...

**Comment by tbhaxor** [comment]
> Well, that's true, I guess. Just wanted to understand what the motivation for this request was...

well i found bash-it quite stable framework and easy to use and i want it to me more customizable for end user, no matter which background he/she from

**Comment by nwinkler** [comment]
Yes, but keep in mind that every bit of new functionality/configurability comes at a cost - increased maintenance efforts, more complexity in the code, etc.

We'll have to find a balance between adding new functionality and keeping Bash-it simple and lightweight. That's why I want to see some justification for new features, to see whether the use case is really there. I don't want to add configurability just for its own sake - it's just going to make things more complex without any real value, if nobody is using the new configuration options.

**Comment by tbhaxor** [comment]
@nwinkler  i can understand your concern.

Why don't you release a beta version of bashit ? Or pin this issue, if users and contributors are interested, then we can work on it ?

**Comment by nwinkler** [comment]
Sorry, I don't understand what you mean with "beta version" - what good would this do?

**Comment by tbhaxor** [comment]
Adding a new branch, not merging it to master until users / other developers are not satisfied and releasing it as a beta test version and collecting feedback

if feedback is positive then merge it with master branch otherwise delete the branch :smile:

**Comment by tbhaxor** [comment]
Perhaps it should be closed now
