### ISSUE TITLE
reloader.bash extremely slow

### ISSUE THREAD

**Issue by ashleyblackmore** [Bash-it/bash-it#1348]
Hello,

Commenting out `source "${BASH_IT}/scripts/reloader.bash"` from bash_it.sh takes me from a 10-second terminal load time to negligible load time. Further tracing shows that it is line 14 in reloader.bash that causes the crazy load time:

```
  8 if [ "$1" != "skip" ] && [ -d "./enabled" ]; then
  7   _bash_it_config_type=""
  6   if [[ "${1}" =~ ^(alias|completion|plugin)$ ]]; then
  5     _bash_it_config_type=$1
  4   fi
  3   for _bash_it_config_file in $(sort <(compgen -G "./enabled/*${_bash_it_config_type}.bash")); do
  2     if [ -e "${_bash_it_config_file}" ]; then
  1       # shellcheck source=/dev/null
14        source $_bash_it_config_file
  1     else
  2       echo "Unable to read ${_bash_it_config_file}" > /dev/stderr
  3     fi
  4   done
  5 fi
```

Any idea how I can fix this? I see there is a "skip" arg that is checked, and presumably also some way of loading _bash_it_config_file that would bring down the load time?

Thanks!

Ashley Blackmore

**Comment by ashleyblackmore** [comment]
It looks like something takes a very long time loading from the enabled dir.

**Comment by ashleyblackmore** [comment]
Okay I've traced it to what looks like brew completion loading command:
```
 $ time . "$BREW_PREFIX"/etc/bash_completion

real    0m9.980s
user    0m0.210s
sys     0m0.127s
```

**Comment by nwinkler** [comment]
This loads the Bash completion packages that are installed on your system through Homebrew (in your case). More info on this can be found here: https://debian-administration.org/article/316/An_introduction_to_bash_completion_part_1

Disabling this will speed up things, but it will also disable all of the system completions found in `$BREW_PREFIX/etc/bash_completion.d`.

**Comment by ashleyblackmore** [comment]
If anyone else comes across this issue, I solved it with help from this superuser question: https://superuser.com/questions/311056/why-is-bash-completion-being-loaded-so-slow-on-os-x

**Comment by nwinkler** [comment]
Thanks for documenting this here - that's useful. People should be aware thought that there's a potential drawback, the `type` command that you commented out was there for a reason. If you can live with this (acceptable) drawback, that's fine. Just wanted to make sure that people understand that making this change might have other side effects.

**Comment by ashleyblackmore** [comment]
Actually there's no commenting out in the solution I chose. Was simply a matter of upgrading bash-completion: https://superuser.com/a/1393343

**Comment by nwinkler** [comment]
Yes, please outline the exact steps taken to fix this issue - would be good for others to see what exactly you did.

**Comment by nwinkler** [comment]
@ashleyblackmore Just to clarify, one more question: Which version of Bash are you running? The `bash-completion@2` package is only supported on Bash v4.1+. If you're running this on macOS, I assume that you have upgraded your Bash install from the stock v3.2 that comes with macOS, right?

**Comment by ashleyblackmore** [comment]
Bash 5.0.7. Yes, I upgraded. This was my fix:
```
brew uninstall bash-completion
brew install bash-completion@2
```
