### ISSUE TITLE
Bashit metal theme emoji not as expected

### ISSUE THREAD

**Issue by gsunil1201** [Bash-it/bash-it#1351]
Hi, 
I am using mobaxterm/putty to ssh to my machine and the bashit Metal theme doesnt match to the preview in the page. Tried installing a bunch of fonts and its still the same. Can someone please help

![image](https://user-images.githubusercontent.com/49007488/55119170-10544300-50ae-11e9-89cf-d429106981f5.png)

**Comment by yashwanth2804** [comment]
I am using ubuntu, but getting like how you got only

**Comment by nwinkler** [comment]
@jrab66 Which font did you use for the _metal_ theme when you added the theme?

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
