### ISSUE TITLE
Powerline theme is lost on changing directory to a git repository.

### ISSUE THREAD

**Issue by dostiharise** [Bash-it/bash-it#1355]
I have enabled the `powerline` plugin and pointed my `BASH_IT_THEME` to `powerline-multiline`, and it seems to work fine. 

However, as soon as I change directory to a git repo, the `powerline` theme is lost, and seems to default to `bobby` theme style prompt.

Strangely when I `cd` back to my home directory, the `powerline` prompt that I expect to display in a git repo is displayed just as I exist the repo directory. 

How can I fix this behaviour?

Refer to the screen-grab below:

![Screenshot 2019-04-04 at 2 54 52 PM](https://user-images.githubusercontent.com/734968/55544875-a3622e00-56e9-11e9-9e3a-446852973754.png)

**Comment by dostiharise** [comment]
Alright, my bad! 

I had also previously installed `bash-git-prompt` (https://github.com/magicmonty/bash-git-prompt) using homebrew.

Running `brew uninstall bash-git-prompt` and dropping the config from `~/.bash_profile` did the trick. 

Thanks!

**Comment by dostiharise** [comment]
Work just fine now. Closed the ticket.

Thanks for the awesome work!

**Comment by nwinkler** [comment]
Thanks for confirming - and also for closing the ticket once the issue was resolved!
