### ISSUE TITLE
Setting system-wide java version on mac

### ISSUE THREAD

**Issue by trmaphi** [Bash-it/bash-it#1359]
From an answer from [stackoverflow](https://stackoverflow.com/a/44169445/6730571), I wrote a script to change system-wide java version. Is [this script](https://gist.github.com/trmaphi/3bc5b5a397a9491a61787143b098da85) suitable in this repo?

**Comment by nwinkler** [comment]
Certainly, if you want to _donate_ this script - this would make a great plugin, in addition to things like `jenv` or similar.

One thing I would like to see is maybe splitting this script into two functions:
* One to display the available versions, including their enabled/disabled state.
* One to change the current selection.

Optionally, it might make sense to have the second function work with a parameter, letting you select the version to be enabled through said parameter. This could be used from scripts or if someone does not want to use the interactive selection method.

Thoughts?

**Comment by trmaphi** [comment]
So, I should put it inside `osx.plugin.bash` or `java.plugin.bash`?

**Comment by nwinkler** [comment]
It might actually make sense to create a new plugin for this, e.g. `macOS-java`.

**Comment by trmaphi** [comment]
Why don't put it in `osx.plugin.bash`, two functions are quite short.

**Comment by nwinkler** [comment]
Yes, let's do this.
