### ISSUE TITLE
Error upon changing directories

### ISSUE THREAD

**Issue by tdiprima** [Bash-it/bash-it#1360]
I'm using bash-it on RHEL 7.6.  I'm getting the following error when changing directories:
```
-bash: 1m]✓: command not found
```
The 1m looks like a colorizing thing... as if maybe there's a line break somewhere where there shouldn't be and bash thinks the color identifier is a command.  At least that's what it looks like to me, I could be wrong.
Anybody else have any idea?

**Comment by nwinkler** [comment]
Which _theme_ are you using with Bash-it? Can you try switching to a different theme?

Also try to disable plugins as much as possible to avoid any interference there.

In the worst case, try to run your shell with `set -x`, which will generate a lot of output, though. You might want to enclose the theme code in `set -x/+x` to just print debug output for that part - this should give you a hint about what's wrong.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
