### ISSUE TITLE
New feature: Show runtime of last command

### ISSUE THREAD

**Issue by martinus** [Bash-it/bash-it#1363]
Before I've discovered bash-it, I've made my own bash prompt which shows the runtime of the last command. I find this feature extremely useful, and would find it helpful if bash-it had it as well. 

Here is a working example:

```bash
function prompt_timer_start {
    PROMPT_TIMER=${PROMPT_TIMER:-`date +%s.%3N`}
    echo -ne "\033]0;${@}\007"
}

function prompt_timer_stop {
    local NOW=`date +%s.%3N`

    local ELAPSED=$(bc <<< "$NOW - $PROMPT_TIMER")
    unset PROMPT_TIMER

    local T=${ELAPSED%.*} 
    local AFTER_COMMA=${ELAPSED##*.}
    local D=$((T/60/60/24))
    local H=$((T/60/60%24))
    local M=$((T/60%60))
    local S=$((T%60))

    local TIMER_SHOW=
    [[ $D > 0 ]] && TIMER_SHOW=${TIMER_SHOW}$(printf '%dd ' $D)
    [[ $H > 0 ]] && TIMER_SHOW=${TIMER_SHOW}$(printf '%dh ' $H)
    [[ $M > 0 ]] && TIMER_SHOW=${TIMER_SHOW}$(printf '%dm ' $M)
    TIMER_SHOW=${TIMER_SHOW}$(printf "%d.${AFTER_COMMA}s" $S)  
    PS1="${TIMER_SHOW} $ "
}
 
trap 'prompt_timer_start "$BASH_COMMAND (`date +%H:%M:%S`)"' DEBUG
PROMPT_COMMAND=prompt_timer_stop
```

See https://martin.ankerl.com/2016/11/04/linux-bash-prompt/ for full example.

**Comment by nwinkler** [comment]
Thanks for suggesting this - looks like a great new feature. Here are a couple of thoughts:

* If we add this, it should be optional. We need to be able to disable the feature to avoid breaking existing themes, and also to avoid adding overhead to the prompts.
* Some themes (like the _Powerline_ ones) support adding features via configuration. This would be a natural fit for this new functionality - you could enable the new feature if needed, otherwise it doesn't show, and does not introduce any CPU overhead.

Which Bash-it theme are you currently using? This might help with figuring out, where/how to add this new feature.

**Comment by martinus** [comment]
I'm currently using the `zork` theme

**Comment by nwinkler** [comment]
OK - thanks for the info. The `zork` theme does not look to be configurable. Here are a couple of options:
* Add the new function to the `base.theme.bash` script - this will expose it to all themes.
* If you want to stick with `zork`, you can add the new function in there, but I would recommend to make it optional via an environment variable.
* Or create a copy of the `zork` script where you add the new function.
* Or add it to a configurable theme, e.g. one of the `powerline` ones, and add the new output to your default configuration.

Let me know if this makes sense.

**Comment by martinus** [comment]
I don't mind switching the theme, I think I might make my own one based on zork or some other one. 

But I don't know much about bash programming unfortunately, so I'm not sure how to best integrate the functionality function into bash_it. Adding the function to base theme and making it available to all themes sounds good, the only thing I'm not sure about is if the `trap ...` command might cause a problem. There is something about "Disable trap DEBUG" in bash_it.sh and preexec.bash

**Comment by NoahGorny** [comment]
see #1683  for a nice implementation- it will get merged soon probably
