### ISSUE TITLE
modern-t theme prompt todo.sh count incorrect

### ISSUE THREAD

**Issue by russelltadams** [Bash-it/bash-it#1374]
In the modern-t theme prompt the method to show the number of "todo.sh" tasks, we get an incorrect count by default and always remain +2 more than we should be.  this bit here:

(t | wc -l | sed -e's/ *//')

When there is no tasks will result in a [2] being displayed because its just counting lines returned and todo list always returns at least two lines even when there is no tasks. If you add one task, it returns 3, and so on.  We need to ignore the first 2 lines.  I did this hack, and it works for me. I am not sure what the use of sed was for, maybe in the past todo.sh had different list behaviour?

My fix: 
$(t | wc -l | awk '{print ($1-2)}' | sed -e's/ *//')

This so far seems to always result in the right number, simple doing a subtraction of two... maybe there is more elegant way to do this here, but awk was the only way I could think of. 

Here is where the lines exist. 

https://github.com/Bash-it/bash-it/blob/039cfa7e0f73eddcf334bbdb371e787b333a32cf/themes/modern-t/modern-t.theme.bash#L44-L47

Happy to try a PR if my fix is legit enough, otherwise, issue raised, always getting two more tasks than we should for todo.sh list in prompt. I am using Fedora 29, todo.sh is latest installed from github.

**Comment by nwinkler** [comment]
Yes, please provide a PR for this. Thanks!

**Comment by russelltadams** [comment]
arg, OK, this bug is only in affect if you using the todo plugin, I see that the "general" alias files has a legit alias that works to put things in and count the lines in a file ".t".   When the plugin is installed "todo.sh" takes over this function with its own alias, and now the result needs to be filtered.  So, this is not really a bug to be fixed, rather a miss use by me.  Not sure the best way to fix this.

**Comment by NoahGorny** [comment]
@russelltadams do you want to provide a PR for this? we would be delighted :smile:

**Comment by russelltadams** [comment]
Let me take another look and see if there is a real fix. Seems to be a conflict between a general todo.sh alias you can enable, and a todo.sh plugin. If both enable the bug exists if just using one of the other, no bug. I'll test to see if it's still valid and have another look for a more global fix.

**Comment by russelltadams** [comment]
OK, this issue is related to a bigger issue I think.    https://github.com/Bash-it/bash-it/issues/1693

Sorry for the long explanation...

The modern-t theme is intended to be used with "t", not "todo.sh", and due to some lack of clarity, and documentation, it becomes very unclear what the intended use case is for the todo.sh plugin and whether or not modern-t is supposed to be used with "t" or "todo.sh".  For example:

bash-it sets: `export TODO="t"`  and we also have a nice little set of _common_ aliases used for todo.sh, which includes `alias tls='$TODO ls'` The "todo.sh plugin" defines a redundant alias `alias t='todo.sh'` and also takes the leap to set a default action (why? for some other theme? Docs?).  I for one am missing the value of this plugin and would argue that it is not needed, it seems its only purpose is to shorten "tls" to "t"? Ironically this causes todo.sh to act like "t", as "t" by default presents the list of tasks when you issue "t" without any arguments, whereas todo.sh requires an argument.  The plugin is providing no value I can see and breaks the modern-t theme. Was it created to support another theme or is this just a vanity alias? 

I think I can close this issue in favor of the one linked above... but I have a question:
 * Where should theme documentation go?
 * Where should plugin documentation go?

**Comment by russelltadams** [comment]
I made this: https://github.com/Bash-it/bash-it/pull/1742
