### ISSUE TITLE
Error while changing theme

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1382]
![image](https://user-images.githubusercontent.com/28386721/58652091-69e82080-8330-11e9-9ae2-a7a27b91c68d.png)

This error came when i tried changing my theme from `powerline-multiline` to `sexy`

**Comment by tbhaxor** [comment]
@nwinkler  plz help me in this

**Comment by nwinkler** [comment]
When changing themes, I usually open a new Terminal window/tab - I've seen issues like this before, and they typically don't happen in a new tab.

Can you verify whether the issue is fixed when you open a new Terminal window or tab?

**Comment by tbhaxor** [comment]
No it happens only in same window

**Comment by nwinkler** [comment]
So do you see the error when you open a new terminal window? Sorry, I don't understand your response.

**Comment by tbhaxor** [comment]
> When changing themes, I usually open a new Terminal window/tab - I've seen issues like this before, and they typically don't happen in a new tab.
> 
> Can you verify whether the issue is fixed when you open a new Terminal window or tab?

Solved
