### ISSUE TITLE
Issue with setting the powerline theme in osX

### ISSUE THREAD

**Issue by bythckr** [Bash-it/bash-it#1396]
I am using bash-it via Terminal.app 2.9.5 on osX MacOS 10.14.5. I am a newbie, so my issue might be due to my lack of some fundamental stuff that was not specified in the documenation. Or maybe some steps are missing in the documentations.

In my terminal, I am seeing square box with a '?' inside it. Which I i have learnt is due to missing font/unicode and my solution is to install powerline font. But I haven't found instruction on how to install powerline font in Mac. One option I saw was to install macvim & vundle then install powerline via vundle. While another was to download "patched powerline font" (did not get a link to it) and install via Font Book.

So, some clarity from some mac users will be helpful. Also is bash-it meant to run in terminal.app or do I need iterm2? I am under the assumption that iterm2 is meant for zsh & oh-my-zsh. Since bash-it is like oh-my-zsh, do I need iterm2 also?

**Comment by nwinkler** [comment]
The link to the patched Powerline fonts is in the README file of the Powerline theme: https://github.com/Bash-it/bash-it/tree/master/themes/powerline

It links to this repo: https://github.com/powerline/fonts

Download one of the fonts from this repo and then select it in Finder and run "Install Font".

I'm using the macOS Terminal.app as well, with the "Source Code Pro" font from the above repo.

If you have Homebrew, you can also install it using `brew cask`: `brew cask install font-source-code-pro-for-powerline`

Let me know if this works...

**Comment by bythckr** [comment]
> If you have Homebrew, you can also install it using `brew cask`: `brew cask install font-source-code-pro-for-powerline`

I ran:
`brew cask install font-source-code-pro-for-powerline`
I got an error:
`Error: Cask 'font-source-code-pro-for-powerline' is unavailable: No Cask with this name exists.`

That odd since I even found the [source page](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-source-code-pro-for-powerline.rb) and even copied `font-source-code-pro-for-powerline` from line 1 to be safe. Not sure what is causing the error.

**Comment by nwinkler** [comment]
Can you try to run a `brew tap caskroom/fonts` first?

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!

**Comment by Niceplace** [comment]
For documentation purposes, the `caskroom/fonts` seems to have moved to ` homebrew/cask-fonts`

In other words:

This no good: `brew tap caskroom/fonts`
This good: `brew tap homebrew/cask-fonts`
