### ISSUE TITLE
autocomplete: the golang (go) autocomplete feature doesn't work

### ISSUE THREAD

**Issue by idanko** [Bash-it/bash-it#1401]
Hi,
After setting `bash-it enable completion go` system reports `go enabled with priority 350`. 
And trying it out the system reports `$ go _bash: _get_cword: command not found_`.
Looks like a broken autocomplete function for golang. Re-login doesn't help.

To make sure that the go binary is inside the $PATH before `source "$BASH_IT"/bash_it.sh` I added the golang path to the global scope but didn't help.

**Comment by nwinkler** [comment]
Sorry, I don't use Go, won't be able to help much with this.

@MunifTanjim It looks like you added the Go completion way back. Any ideas?

**Comment by MunifTanjim** [comment]
https://github.com/Bash-it/bash-it/blob/ca2e3edb978e8fbb808d1cfca241736bbe6626da/completion/available/go.completion.bash#L4

I just copied it from the mentioned repository. That's probably outdated.

Maybe a more up-to-date source will help:

- https://github.com/kura/go-bash-completion/blob/master/etc/bash_completion.d/go

**Comment by idanko** [comment]
> https://github.com/Bash-it/bash-it/blob/ca2e3edb978e8fbb808d1cfca241736bbe6626da/completion/available/go.completion.bash#L4
> 
> I just copied it from the mentioned repository.
> 
> Maybe it's related to this issue [Homebrew/legacy-homebrew#22535](https://github.com/Homebrew/legacy-homebrew/issues/22535)
> 
> Or maybe the script is outdated and a more up-to-date source will help:
> 
> * https://github.com/kura/go-bash-completion/blob/master/etc/bash_completion.d/go
> 
> I can't confirm the exact issue. I'm currently not using Go or Bash-it...

I've checked and this isn't Mac or Linux related issue. It's reproducible on both.
@MunifTanjim @nwinkler If you need some logs or other information feel free to ask, thank you.

**Comment by MunifTanjim** [comment]
I can confirm that there's something wrong with your system. This script works fine for me. Maybe you got an older `bash` or `bash-completion` package?

**Comment by idanko** [comment]
@MunifTanjim yes, I found the `bash-completion` package wasn't installed on my system. Seems Debian 10 doesn't provide it out of the box.
