### ISSUE TITLE
Sanitization of using sudo

### ISSUE THREAD

**Issue by Kreyren** [Bash-it/bash-it#1409]
# PASSING! - Reasoning
Passing for the issue atm since i'm not familiar with workflow of repository.

EDIT: "passing" in terms of leaving the MR for X amount of time not forcing to pass QA.

---

I've made a wrapper for sudo that triggers only if user is not root -> sudo won't be used on root.

This should be further sanitized with checking for sudo executable flag or alternatively using `su -c "command"` 

Referencing `checkroot()` from https://github.com/RXT067/Scripts/blob/kreyren/chrooter
```bash
checkroot () { # Check if executed as root, if not tries to use sudo
	if ! ((EUID)); then
		return
	elif [[ -x "$(command -v sudo)" ]] && [ -n "$KREYREN_CHECKROOT" ]; then
			info "Failed to aquire root permission, trying reinvoking with 'sudo' prefix"
			exec sudo "$0" "$@"
			exit 1
	elif [[ ! -x "$(command -v sudo)" ]] && [ -n "$KREYREN_CHECKROOT" ]; then
		info "Failed to aquire root permission, trying reinvoking as root user."
		exec su -c "$0 $*"
		exit 1
	else
		die 0 "Unable to elevate root access."
	fi
}
```

###  Affected Merge Requests
https://github.com/Bash-it/bash-it/pull/1407
https://github.com/Bash-it/bash-it/pull/1406
https://github.com/Bash-it/bash-it/pull/1405

**Comment by gaelicWizard** [comment]
I don't think this is useful. `sudo` works without prompt when running as root. It's just a noop. It already performs the goal of this function. Wrapping it seems simply unnecessary. $0.02.

**Comment by NoahGorny** [comment]
I got to agree with @gaelicWizard on this one. closing
