### ISSUE TITLE
Remove 'gs' from git aliases

### ISSUE THREAD

**Issue by dleavitt** [Bash-it/bash-it#141]
Currently `git status` is aliased to `gs`. However, `gs` is the Ghostscript binary, which may be common enough that's it's worth removing the the alias.

https://github.com/revans/bash-it/blob/master/aliases/available/git.aliases.bash#L10

**Comment by knorth55** [comment]
I came up with this problem when I run a script which uses ghostscript inside.
`gs` is not an alias for `ghostscript`, and `git status` have two aliases `gs` and `gst` now.
I recommend to use `gst` instead of `gs` and remove `gs` alias.

**Comment by oestrada1001** [comment]
I encountered this issue inside a docker container. `gst` works perfectly for me. Thank you.

**Comment by blv-madhavacarrillo** [comment]
@oestrada1001 exactly 1 year later I encounter the same issue and going to use gst too.

**Comment by cornfeedhobo** [comment]
Yet another reason why we should not be supporting this crazy list of git aliases. You all should really explore git's internal alias support.
