### ISSUE TITLE
sed command in proxy plugin is not correct.

### ISSUE THREAD

**Issue by Sraw** [Bash-it/bash-it#1411]
It will throw an error: `sed: can't read : No such file or directory`

The command is: `sed -e's/#	ProxyCommand/	ProxyCommand/' -i ""  ~/.ssh/config`. I believe the problem is that `-i ""`. It looks like it is trying to read an empty file name?

**Comment by nwinkler** [comment]
Ah, that problem again... The command as it is (with the `-i ""`) works fine for BSD `sed`, e.g. on macOS. The GNU `sed` used on Linux distributions does not require the empty double quotes to make inline changes.

I have a fix for that in another project (basically tries to detect the OS and then uses the correct syntax) - need to copy that in...

**Comment by Sraw** [comment]
Cool, thanks for your efforts :) And I will leave this issue open until you close it with a PR.

**Comment by nwinkler** [comment]
And... done.

Please give the updated version a try - it should now work with both GNU and BSD sed...

**Comment by Sraw** [comment]
It works great :) But here I have another issue... probably.

The issue is that the keywords in the ssh config are [case insensitive](https://linux.die.net/man/5/ssh_config). Which means I should be able to use `proxycommand` or `Proxycommand` or `proxyCommand` or...

But all sed commands here use case sensitive mode. Do you think this should be considered as a bug?

**Comment by nwinkler** [comment]
Good question - I never thought about that when I created the proxy plugin. If you say this should work regardless of case, then let's change the way sed is used in the plugin. Please feel free to provide a PR for fixing this...

**Comment by Sraw** [comment]
I will try to fix it but it doesn't look like an easy issue as the BSD doesn't support case insensitive match.
