### ISSUE TITLE
powerline theme is a little bit lag.

### ISSUE THREAD

**Issue by Sraw** [Bash-it/bash-it#1412]
I'm not sure if this is normal or not. Basically, the powerline theme has around 200~500ms lag to prompt. It is somehow understandable as it requires more actions. But I'm wondering if it is solvable?

I'm using the latest bashit on Linux Mint 19

**Comment by nwinkler** [comment]
That really depends on how you're using it. It does a lot of guesswork/parsing to detect things like Git, SVN, Python environment - all of these come at a cost.

There have been several tickets that addressed individual items to speed up things, but it still does a lot, that's right.

You can try to disable some of the items of the theme to see if that helps - see the README.md file in the Powerline theme folder.

Or switch to another theme to see if it is any faster...

**Comment by Sraw** [comment]
Thanks for your reply. Changing to even `simple` theme also causes like 50ms lag. Guess it is normal.
