### ISSUE TITLE
VScode Metal theme show unexpected last sumbol when push arrow up

### ISSUE THREAD

**Issue by ishpartko** [Bash-it/bash-it#1415]
1) ![изображение](https://user-images.githubusercontent.com/27618114/62554795-7336c180-b87a-11e9-8ed9-3233898e5e44.png)
run any command
2) push *arrow up* button
3) get first sumbol from previous command(only cosmetic bug)  
 ![изображение](https://user-images.githubusercontent.com/27618114/62554768-6619d280-b87a-11e9-8a8b-1619171a0a47.png)

Something similar as this ( https://unix.stackexchange.com/questions/28827/why-is-my-bash-prompt-getting-bugged-when-i-browse-the-history ), but I can't solve it with my mind all day :(

I'm new ubuntu user. What should I do to fix it?

**Comment by ishpartko** [comment]
And in regular bash that dont happend. Only in VScode Terminal

**Comment by ishpartko** [comment]
And it's working good with other themes, only Metal has this bug :disappointed:

**Comment by AmberWilliams** [comment]
This isn't fixable for VScode?

**Comment by ishpartko** [comment]
@AmberWilliams I just switched to windows :smiley: There's no bash :tada: haha

**Comment by nwinkler** [comment]
Windows now also has a built-in Linux subsystem with a full Bash shell (WSL): https://docs.microsoft.com/en-us/windows/wsl/install-win10
