### ISSUE TITLE
aws plugin does not deal with cred files with less than 3 entries

### ISSUE THREAD

**Issue by girifirm** [Bash-it/bash-it#1418]
So the  command `awskeys export myawsprofile` will fail if the credentials file has less than 3 fields.

Example:

`[default]
aws_access_key_id = xxx
aws_secret_access_key = xxx

[dplay]
aws_access_key_id = xxx
aws_secret_access_key = xxx

[myecs]
aws_access_key_id = xxx
aws_secret_access_key = xxx`

the problem line of code is :
https://github.com/Bash-it/bash-it/blob/629ab9fce66f66316e7f6c596e06d7ad987b36d9/plugins/available/aws.plugin.bash#L43

`tail -n +${ln} "${AWS_SHARED_CREDENTIALS_FILE}" | egrep -m 3 "aws_access_key_id|aws_secret_access_key|aws_session_token"`

changing `-m 3` to `-m 2` fixes it, but a more dynamic solution is probably required

**Comment by meatware** [comment]
Anyways, i had a go at rewriting the function so that it can deal with a variable number of environment variables:

`function __awskeys_get {
    
    local ln=$(grep -n "\[ *$1 *\]" "${AWS_SHARED_CREDENTIALS_FILE}" | cut -d ":" -f 1)
    if [[ -n "${ln}" ]]; then
        local profile_line_idxs=$(grep -n "\[*\]" "${AWS_SHARED_CREDENTIALS_FILE}" | tr ":" " " | awk '{print $1}' | tr '\n' ' ')
        local  last_line=$(wc -l "${AWS_SHARED_CREDENTIALS_FILE}" | awk '{print $1}')

        local  all_idxs="${profile_line_idxs}${last_line}"  
        local  term_ln=$(echo "$all_idxs" | tr ' ' '\n' | grep -w -A 1 "$ln" | tail -1)
        
        local  match_strings="aws_access_key_id|aws_secret_access_key|aws_session_token|aws_default_region|aws_default_output|aws_profile|aws_role_session_name|aws_ca_bundle"
        sed -n "${ln},${term_ln}p" "${AWS_SHARED_CREDENTIALS_FILE}" | egrep  "${match_strings}"
    fi
}`

Here is a test infile:

`[default]
aws_secret_access_key = hlihlij
aws_access_key_id = tets

[test2]
aws_secret_access_key = vcfvvrvrv
aws_access_key_id = vvrtwsvtwr
aws_ca_bundle = calocation
aws_default_region = us-west-1

[test3]
aws_secret_access_key = xjopjok
aws_access_key_id = ohmyGawd!!`

**Comment by nwinkler** [comment]
Can you provide a PR for this?

**Comment by meatware** [comment]
sure, will do

**Comment by cornfeedhobo** [comment]
@nwinkler I think this can be closed then.

Pro tip, if you add `Closes #<issue number>` in your merging comment, it will auto close these. More here https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by nwinkler** [comment]
Thanks for the heads up, @cornfeedhobo! I knew about the `closes/fixes` comments, but I usually forget adding them when merging - the "merge" button is so tempting...
