### ISSUE TITLE
White theme

### ISSUE THREAD

**Issue by pedro2555** [Bash-it/bash-it#1425]
My head is exploding. How do I get one of the light themes?

**Comment by nwinkler** [comment]
This is down to your terminal program, e.g. "iTerm2" on macOS, or "Gnome Terminal" on Linux. These typically have color schemes/themes as well, defining the background colors used in the terminal window. Try playing around with them...

**Comment by pedro2555** [comment]
Yes. Its the dreadful windows thing. Thanks.
