### ISSUE TITLE
alias-completion.plugin.bash causes eval error (unexpected EOF while looking for matching `'')

### ISSUE THREAD

**Issue by mick-d** [Bash-it/bash-it#1437]
When using bash-it i get the same error every time i open a new terminal and source my `.bashrc`:
```
bash: eval: line 209: unexpected EOF while looking for matching `''
bash: eval: line 210: syntax error: unexpected end of file
```
After investigations, this error comes from `bash_it.sh` when it calls `source "${BASH_IT}/scripts/reloader.bash"` when that later script calls line 23 and 24 of `alias-completion.plugin.bash`:
```
eval "local completions=($(complete -p | sed -Ene "/$compl_regex/s//'\3'/p"))"
(( ${#completions[@]} == 0 )) && return 0
```

So commenting out these two lines solves the issue. However i have no idea why this is happening and what side effects are created by commenting these two lines.

**Comment by NoahGorny** [comment]
@mick-d do you still have this issue?
