### ISSUE TITLE
mensagem de aviso sobre a bateria

### ISSUE THREAD

**Issue by marcelloinfoweb** [Bash-it/bash-it#1440]
Estou recebendo esta mensagem de aviso sobre o plugin da bateria:
bash: 10#battery_percentage: valor muito grande para esta base de numeração (token de erro é "10#battery_percentage")

Mas quando ativo o plugin aparece mais uma quebra de linha. Estou usando o tema "multiline" do powerline.

**Comment by davidpfarrell** [comment]
Using Google's Portuguese to English translator:

> I am receiving this warning message about the battery plugin:
> bash: 10 # battery_percentage: Very large value for this numbering base (error token is 
> "10 # battery_percentage")
> 
> But when active the plugin appears one more line break. I am using the powerline "multiline" theme.
>

**Comment by marcelloinfoweb** [comment]
Encontrei o problema nessa linha "POWERLINE_PADDING=${POWERLINE_PADDING:=2}" do tema powerline-multiline.

Tive que mudar pra "3", mas ficou muito afastado da borda, e não aceita "2.5".

**Comment by nwinkler** [comment]
Sorry, but can we please do this in English language? I'm not going to use Google Translate for support questions...

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
