### ISSUE TITLE
Is there fuzzy directory path tab completion (a feature from oh-my-zsh)

### ISSUE THREAD

**Issue by rekendahl** [Bash-it/bash-it#1441]
Hello

Is there a way to enable "fuzzy" directory completion? Oh-My-Zsh tab completion does this (but I'm not sure what enables it).

For example of you stand in a directory and have the following directories:

```
/example/[misc project_ro project_a project_b]
```

Then the following command in oh-my-zsh completes like this:

```
-> cd /example/ro<tab> 
```

Fills out

```
-> cd /example/project_ro
```

Can you do this in Bash-It?

**Comment by nwinkler** [comment]
Not that I'm aware, no. The absolutely wonderful `fzf` (https://github.com/junegunn/fzf) supports something like that, though. We have a plugin for `fzf` in Bash-it as well, check it out!

(Sorry about the delay, work and life got in the way the last couple of weeks...)

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
