### ISSUE TITLE
'draft' function name clash

### ISSUE THREAD

**Issue by akaliazin** [Bash-it/bash-it#1453]
'draft' function is defined in the `lib/composure.bash`

Unfortunately the name of this function is clashing with the draft binary [Draft](https://draft.sh) actively developed for the K8S domain.
Simply renaming 'draft' function here to say 'draft_fun' would do.

**Comment by nwinkler** [comment]
Good point. Since our `composure.bash` is simply a copy from here: https://github.com/erichs/composure, it might make sense to open an issue there and then update our version once the upstream change has been accepted.

**Comment by akaliazin** [comment]
thanks for the prompt. Have raised the issue at the composure repo. It does not seem to be actively developed. Or maybe it has reached the Zen stage already?

**Comment by nwinkler** [comment]
Thanks! Maybe feel free to create a PR here in this repo to change the composure `draft` function to something like `__draft`?

**Comment by ernstki** [comment]
@akaliazin I think Composure is just feature complete. Finished, you might say.

Making a change to the name of this function on the Composure end, as proposed in erichs/composure#26 is not a great solution. It's a user-facing command which probably accounts for most of the typical usage of Composure.

For me, I run `draft` sometimes dozens of times per day, and it's very nearly the _only_ Composure command I actually run interactively.

**Comment by nwinkler** [comment]
Thanks for the details, @ernstki!

@akaliazin I'm going to close this since I don't think that we should change the name of the _Composure_ `draft` function. For your case, I suggest that you add a custom script to your Bash-it installation that either renames the Composure `draft` function, or defines a `draft` alias that points to the `draft` script that you prefer.
