### ISSUE TITLE
brew.completion.bash is not correct for the current version of brew.

### ISSUE THREAD

**Issue by hongyi-zhao** [Bash-it/bash-it#1458]
Hi,

I noticed that the brew has do some changes on the files' location.    For the bash/zsh/fish completion help scripts, they are located at the following location:

`$(brew --prefix)/completions`

So should use the following form brew.completion.bash

```
if which brew >/dev/null 2>&1; then
  BREW_PREFIX=$(brew --prefix)

  if [ -f "$BREW_PREFIX"/completions/bash/brew ]; then
    . "$BREW_PREFIX"/completions/bash/brew
  fi
fi
```

**Comment by hongyi-zhao** [comment]
The brew's official document is also not changed for this:

https://docs.brew.sh/Shell-Completion

**Comment by nwinkler** [comment]
Sorry, can't replicate this. My local installation of Homebrew is in `/usr/local` (`brew --prefix`), and I don't have a directory `/usr/local/completions`.

Are you sure you have a standard installation of Homebrew?

(On the other hand, it's possible that Homebrew was changed - my installation of Homebrew is a couple of years old, regularly updated, though. It's possible that they changed the location in the meantime...)

**Comment by hongyi-zhao** [comment]
I use the latest git version of homebrew and all of my descriptions are based on it.

**Comment by hongyi-zhao** [comment]
You are using a very old version of homebrew.   It seems that in  the past year, homebrew has chaged a lot and combined several relative projects into it.

In my opinion, the bash-it should track with and conform to the lasted versions of the corresponding tools for the completion functions.

**Comment by nwinkler** [comment]
If you're using the latest Git version of Homebrew, you might not be using the same settings as the installed version - I think that the brew installer repackages some files/folders to a different location.

The brew `install` script specifically mentions `"#{HOMEBREW_PREFIX}/etc/bash_completion.d/brew"` as the installation location for the brew completion script:

https://github.com/Homebrew/install/blob/9452528bc4513bf41b76e2afe939e2b7f90e6020/install#L211

**Comment by hongyi-zhao** [comment]
Yes, I use the the following method depicted here:

https://docs.brew.sh/Homebrew-on-Linux

```
Alternative Installation

Extract or git clone Homebrew wherever you want. Use /home/linuxbrew/.linuxbrew if possible (to enable the use of binary packages).

git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
mkdir ~/.linuxbrew/bin
ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
eval $(~/.linuxbrew/bin/brew shellenv)
```

**Comment by nwinkler** [comment]
OK, understood. The `git clone` installation that you're doing seems to use a different directory layout than the official `install` script.

To support both, we could include the `if` check for the `completions` directory (from your first post) as an additional check in the `brew.completion.bash` file, after the current check. That way, we could support both the installation through the `install` script and through `git clone`.

Please feel free to provide a PR for this. Thanks for the great analysis!

**Comment by hongyi-zhao** [comment]
I also have written a brew.completion.bash for my case, but I use the following directory:
`
~/.brew ` instead of `~/.linuxbrew`.

If others prefer this name, I'll do it.

**Comment by nwinkler** [comment]
Why would that matter? Wouldn't you use `brew --prefix` for that?

**Comment by hongyi-zhao** [comment]
I just mean that I use this path name for my own flavor, and if use this name, must first add the corresponding PATH into .bashrc/.profile etc.

Another notes, due to it's a installation method based on git clone and it's the same for all OSes, so it should use a general local path name.  This is just why I named it as ~/.brew instead of ~/.linuxbrew.

**Comment by hongyi-zhao** [comment]
See my commit here:

https://github.com/hongyi-zhao/bash-it/commit/7c73b22e75ac7cceffaec9bc88b6c20d5b5436b6

**Comment by hongyi-zhao** [comment]
Another discussion, the original brew.completion.bash use separate if ... fi blocks for souring the completion script. 

But, I think it should use the following flow control bock:

if ... ; then

elif ...; then
...
fi

 Considering that the corresponding completion script need only one run for sourcing it.

**Comment by hongyi-zhao** [comment]
See my commit here for the above idea:
https://github.com/hongyi-zhao/bash-it/commit/6f2376daa23930387e95891777776344f5ba481c

If agree with it, could you please merge it into master?

**Comment by nwinkler** [comment]
If you want this to be merged into Bash-it, you need to create a _Pull Request_ first.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

I can't merge changes from your fork, please read through the above documentation...

**Comment by hongyi-zhao** [comment]
Thanks, I'll try to do it.
