### ISSUE TITLE
sudo and brainy theme

### ISSUE THREAD

**Issue by hackhowtofaq** [Bash-it/bash-it#1460]
The check for **sudo** in brainy theme [link](https://github.com/Bash-it/bash-it/blob/876482d616a07b11193b9e13462fdc98cab23ed7/themes/brainy/brainy.theme.bash#L93)

triggers an email with security information, if sudo is set up to send emails on errors.

Also logs are cluttered with a 
```
a password is required ; TTY=pts/1 ; PWD=/home/user/path; COMMAND=/usr/bin/id -u
```
I know that I can disable the check, but is there any other way to do it, without triggering sudo error checks?

Ty

**Comment by nwinkler** [comment]
There have been some previous discussions on this topic in #744, #792 and #902.

The gist is that I have not found a way to reliably have the sudo check functionality without actually using `sudo`. At the moment, disabling it looks like the only option I'm aware of. If you have another way of checking for these permissions without triggering an alert, I'm all ears...

**Comment by nwinkler** [comment]
Maybe this would be an option? https://stackoverflow.com/a/18216122/1228454

The `EUID` environment variable could potentially be used for this check instead of using `sudo` - someone would have to validate this.

**Comment by hackhowtofaq** [comment]
Ok thanks, I will look if I can come up with something....

**Comment by hackhowtofaq** [comment]
Just replacing
```
[ $(sudo -n id -u 2>&1 | grep 0) ]
```
with
```
[ $(id -u) = 0 ]
```
[Ref](https://askubuntu.com/a/30157) is working for me

**Comment by davidpfarrell** [comment]
> Just replacing
> 
> ```
> [ $(sudo -n id -u 2>&1 | grep 0) ]
> ```
> 
> with
> 
> ```
> [ $(id -u) = 0 ]
> ```
> 
> [Ref](https://askubuntu.com/a/30157), is working for me

Hi All,

The purpose of the check is not to confirm `"Am I logged in as root"`, which is what `[ $(id -u) = 0 ]` will tell you.

The purpose of the check is to confirm `"Do I have an active sudo session, whereby if I entered a sudo command it would not ask me for my password"`, which is what the original code is trying to test.

Wondering myself why checking for an active sudo session is so difficult, I did some googling, and the general consensus appears to be:

On a system that considers failed sudo attempts important enough to send emails, checking for active sessions is frowned upon, as it is a form of information leakage, letting a bad actor know that they could safely execute sudo commands.

Which I must say I totally agree with.  If the emails are important, then the check goes against your security concerns.   If the check (and prompt display) are important, then the email goes against your convenience concerns.

Hope that helps

**Comment by nwinkler** [comment]
Completely agree, thanks, @davidpfarrell for the details. At the moment, it looks like the currently used code does what it can do.

If you're not comfortable with the security escalation (emails etc.), please disable the `sudo` check as outlined in the documentation.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
