### ISSUE TITLE
conda.completion.bash is needless, due to conda has diasbled it starting with version 4.4

### ISSUE THREAD

**Issue by hongyi-zhao** [Bash-it/bash-it#1461]
Hi,

See here:

https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/enable-tab-completion.html

`Conda versions up to 4.3 supports tab completion in Bash shells via the argcomplete package. Bash tab completion is deprecated starting with version 4.4.`

The alternative method is using the following package:

https://github.com/tartansandal/conda-bash-completion

Regards

**Comment by nwinkler** [comment]
Please feel free to provide a PR for this.

**Comment by hongyi-zhao** [comment]
I've written a corresponding conda.completion.bash which is based on pyenv, so I'm afraid that it's not meet the general case.

**Comment by hongyi-zhao** [comment]
I've written a conda.completion.bash which is for anaconda managed by pyenv.  I'm afraid that this is not meet the general case.

**Comment by hongyi-zhao** [comment]
The conda bash completion code I mentioned here still has some bugs.  See here for more info:

https://github.com/tartansandal/conda-bash-completion/issues/3

**Comment by NoahGorny** [comment]
@hongyi-zhao can you still work on this?

**Comment by hongyi-zhao** [comment]
@NoahGorny To be frank, recently, no. I haven't kept my eyes on the latest status of the conda package mentioned above for several months.

**Comment by NoahGorny** [comment]
It's okay, thanks for contributing!
