### ISSUE TITLE
Prompt slowness

### ISSUE THREAD

**Issue by LunaticMuch** [Bash-it/bash-it#1463]
Hi there,

I experience frequently slowness of my prompt and I am keen to debug this.  I am now in a situation where even an empty RETURN on my keyboard takes 6-7 seconds to return the prompt.
Here my actual configuration:

- MacOS Mojave
- `Bash 5.0.11(1)-release (x86_64-apple-darwin18.6.0)` (according to `bash --version`)
- Bash-it version `e08014e` (last commit as of now)
- Bash-it theme `bobby`

As far as I can see now, commands:
- `rbenv` take 1.9 seconds
- `svn` takes 1.3 seconds

If I se SCM_CHECK=false, I can reduce the _prompt to prompt_ time to 3.6 seconds, which is still a lot.
Where/what else can I check?

Thanks
LM

**Comment by nwinkler** [comment]
There's more info on this in the following tickets - please take a look:

* #517 
* #914

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
