### ISSUE TITLE
Unable to view Unicode chars

### ISSUE THREAD

**Issue by AmericanY** [Bash-it/bash-it#1466]
I'm using Windows 10 `CMD` or PowerShell to connect to my `Centos7` server.

Today after I've installed [Bash-it](https://github.com/Bash-it/bash-it) on the server, I've noticed the Unicode characters is not displayed correctly.

Screen Shot:

[![enter image description here][1]][1]
  
it's should displaying ⌚ as the [documentation](https://github.com/Bash-it/bash-it/wiki/Theme-Switches-&-Variables)

here's the output of `locale` command:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

  [1]: https://i.stack.imgur.com/6Ib8e.png

**Comment by nwinkler** [comment]
Depending on the theme, you might need to install a Powerline font: https://github.com/powerline/fonts

**Comment by AmericanY** [comment]
@nwinkler I'm using default one which is `Bobby`

**Comment by tbhaxor** [comment]
@AmericanY Please confirm that your terminal application is set to display unicode characters and the follow the fixes as posted here in these answers: https://stackoverflow.com/questions/12649896/why-doesnt-my-terminal-output-unicode-characters-properly

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
