### ISSUE TITLE
New update issue

### ISSUE THREAD

**Issue by AmericanY** [Bash-it/bash-it#1471]
After I've updated to latest version.

I noticed that themes files is not colored anymore and .bashrc file as well.

![Capture](https://user-images.githubusercontent.com/27644047/71619972-c9145900-2bcf-11ea-8dbd-24d9a83428e7.PNG)

**Comment by AmericanY** [comment]
please take a look here @nwinkler

**Comment by nwinkler** [comment]
Not sure what to look at here... Are you saying that the `nano` editor is no longer syntax highlighting the files?

I'm not sure whether that is related to Bash-it...

**Comment by AmericanY** [comment]
@nwinkler thanks for your response. Actually the issue only happens after I’ve updated to latest batch. The issue is only with bash files. All other files the highlight is works fine . I’ve checked /etc/nanorc all files is already included . However if I revert to previous batch it just works fine

**Comment by nwinkler** [comment]
Sorry, not sure what's causing this. I assume that with "batch" you mean Bash-it, right?

I don't think that Bash-it has any support for nano, not sure why that would be impacted...

**Comment by AmericanY** [comment]
@nwinkler yes I meant Bash -it latest modification. After I used bash-it update so bash files highlighting gone

**Comment by nwinkler** [comment]
Sorry, not sure how I can help you with that. I don't use `nano`...

**Comment by AmericanY** [comment]
@nwinkler alright, mind to confirm if bash-it provide shell command highlight ? and if yes so please tell me how to activate it. also if it's support auto-complete for commands. such as fish

**Comment by nwinkler** [comment]
Can you explain what you mean with _shell command highlight_? Do you have an example/screenshot that shows what you're looking for?

**Comment by NoahGorny** [comment]
gentle ping @AmericanY
