### ISSUE TITLE
About the sourcing order of serveral customized scripts.

### ISSUE THREAD

**Issue by hongyi-zhao** [Bash-it/bash-it#1472]
Hi,

If I have several customized scripts, what's the sourcing order of them?

Regards

**Comment by nwinkler** [comment]
They are loaded in alphabetical order, as can be seen here:

https://github.com/Bash-it/bash-it/blob/cfa94e70fa2e1fbd97c67ffd39fa4f5b9175188b/bash_it.sh#L80-L87
