### ISSUE TITLE
What do you think BaseShell framework

### ISSUE THREAD

**Issue by chen-shang** [Bash-it/bash-it#1477]
See
https://github.com/chen-shang/BaseShell

**Comment by nwinkler** [comment]
Sorry, without an English language readme, I'm not able to see what this is about... Is there an English description for BaseShell?

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!

**Comment by cornfeedhobo** [comment]
This is an interesting project. Essentially it's a ton of basic function to make interacting with bash more standard - like a stdlib. I think we could take a few concepts from here...
