### ISSUE TITLE
cat command breaks the powerline theme while outputting text on terminal

### ISSUE THREAD

**Issue by kirk86** [Bash-it/bash-it#1478]
I've found myself over and over having this issue when performing cat command on a text file
![image](https://user-images.githubusercontent.com/2902390/72559569-fd109f00-389c-11ea-8323-929aa9bd0429.png)

Any ideas on what's causing this?

**Comment by davidpfarrell** [comment]
Greetings,

I hate to see the powerline theme causing troubles.

You didn't add very many details about your setup tho.

Q: What version of bash-it are you using?
```
$ bash-it version
```

Q: What is the smallest text file you can create that shows the problem?

i.e. Does this cause the issue to show?
```
$ echo "hello world" > hello.txt

cat hello.txt
```

Q: What is your bash configuration?
```
cat ~/.bash_profile
cat ~/.bashrc
# others?
```

Q: If your bash configuration is complicated, have you tried disabling anything that is NOT bash-it related to see if it helps?

Q: Have you tried simplifying your powerline segments to see if it helps?
```
$ export POWERLINE_PROMPT="cwd"
$ cat hello.txt
```
or clearing it completely:
```
$ export POWERLINE_PROMPT=""
$ cat hello.txt
```

**Comment by kirk86** [comment]
Hey, here's the extra info as requested
 

> Q: What version of bash-it are you using?
```
Current git SHA: e08014e on 2019-12-17T08:21:24+01:00
https://github.com/Bash-it/bash-it/commit/e08014e
Compare to latest: https://github.com/Bash-it/bash-it/compare/e08014e...master

```
> Q: What is the smallest text file you can create that shows the problem?
```
echo "10e4 b850 efa7 f88b dfbd 16b7
b701 0000 0500 0012 4d49 542d
100c 20df 9fb9 e212 13f4 2fe9" > hello.txt

cat hello.txt
```
> Q: What is your bash configuration?
```
# setting up colours
code....

# bash-it
export BASH_IT="/home/kirk/.config/bash-it/.bash-it"
export BASH_IT_THEME='powerline'
source "$BASH_IT"/bash_it.sh
```
> Q: Have you tried simplifying your powerline segments to see if it helps?
```
same thing
```
![image](https://user-images.githubusercontent.com/2902390/72566438-b9716180-38ab-11ea-9e29-9b4af5be626e.png)
> or clearing it completely:
![image](https://user-images.githubusercontent.com/2902390/72566588-05bca180-38ac-11ea-9a18-8c75eafb192b.png)

**Comment by davidpfarrell** [comment]
@kirk86 thank you for replying but I think something is missing.

It seems your `hello.txt` file contains binary data, not text data

HOW did you create your "hello.txt" file?

If you copy / paste this :
```
echo "10e4 b850 efa7 f88b dfbd 16b7
b701 0000 0500 0012 4d49 542d
100c 20df 9fb9 e212 13f4 2fe9" > hello.txt
```

Then do this:
```
cat hello.txt
```

You should see this:
```
10e4 b850 efa7 f88b dfbd 16b7
b701 0000 0500 0012 4d49 542d
100c 20df 9fb9 e212 13f4 2fe9
```

Your `hello.txt` file should just contain letters, numbers and spaces, but it looks like you somehow got binary data into your file?

Q: If you run this on the command line:
```
echo "48 65 6c 6c 6f 20 6b 69 72 6b 38 36" > hello.txt
cat helllo.txt
```
What do you see in your terminal?  You should just see:
```
48 65 6c 6c 6f 20 6b 69 72 6b 38 36
```

But what you're suggesting is that somehow you will see:
```
Hello kirk86
```

Which could only happen if each number was turned into a binary character, but ECHO shouldn't do that, and CAT should do that either.

Please report back what you see when you execute the echo+cat above.

Thank you

**Comment by kirk86** [comment]
> What do you see in your terminal? You should just see:

Yes, maybe my example wasn't the best

Try this text instead, of course there are some escape characters `\` but don't know how exactly to deal with that or if `cat`is meant to read those as newlines or tabs? 
```
("(exit)" "quit" "d" "exit" "2" "make-string" "(string 42)" "(+ (length \"hello world\") 20)" "(+ length \"hello world\" 20)" "(file-string-length (\"hello world\"))" "hellow world" "file-string-length" "(+ file-string-length \"hello world\" 20)")
```

**Comment by davidpfarrell** [comment]
I don't think that will help ... I don't the issue is related to bash-it.

I'm thinking you have unicode characters in your local file and your terminal is not configured to print them.

Q: Have you confirmed that you have unicode support in your terminal?

Try this
```
echo -e '\xe2\x82\xac' 
```
You should see this
```
€
```

Just the same, let's try removing bash-it from the equation:

Q: Can you try temporarily commenting out ALL bash-it related configurations from your bash files?

**Comment by kirk86** [comment]
> Q: Have you confirmed that you have unicode support in your terminal?

Yes, I get the same result as you do

> Q: Can you try temporarily commenting out ALL bash-it related configurations from your bash files?
Same result without bash-it
```
echo -e '\xe2\x82\xac'
€
```

**Comment by davidpfarrell** [comment]
> Same result without bash-it

I assume you mean that you still get a messed up prompt when you cat the file, even if bash-it is not activated?

With that, there's not much else I can help with - It doesn't seem like a bash-it issue, but likely related to characters inside the files you are catting.

You might try doing a hex dump of the file(s) to look for which characters are causing the issue - It will help if you can reduce the file down to the smallest size that still causes the issue.

Good luck

-D

---
PS: I am not the maintainer of bash-it just someone who watches the tickets and tries to help - The actual maintainer may still be available to help you if you can figure out how to confirm that the issue is related to bash-it.

**Comment by kirk86** [comment]
Cheers David,
thanks for the help :smiley:

**Comment by nwinkler** [comment]
Thanks for troubleshooting this, @davidpfarrell - really appreciate it!

@kirk86 As David mentioned, could you try running the `cat` command on your sample file in a shell that is not using Bash-it? What happens when you do that? If that's the case, then the issue is not related to Bash-it...

**Comment by NoahGorny** [comment]
gentle ping @kirk86
