### ISSUE TITLE
"bad array subscript" error on emacs alias completion

### ISSUE THREAD

**Issue by okomestudio** [Bash-it/bash-it#1497]
I have enabled emacs aliases and for some reason only on the alias `en` I consistently get `_xspecs: bad array subscript` error. For example, to open the file named `somefile`, I type `somef` and then hit the tab key, and this results:

```
$ en somefbash: _xspecs: bad array subscript
ile
```

Apparently the auto-complete is being carried out properly, as emacs does launch with the file opened. It just displays the error message. I do not get the error message with the other emacs-related aliases.

Could this be fixed?

**Comment by nwinkler** [comment]
I'm not using Emacs, so probably won't be of much help...

I don't think that the alias is causing this - can you try to type `emacs -nw some<TAB>` (the `en` alias runs `emacs -nw`)? Do you get the same error with that?

It looks like your shell completion is causing this issue, since it seems to happen on the tab key. Can you validate which completion options are enabled for you (both in Bash-it, and outside)?

If you run `complete -p emacs`, it should list any configured shell completions that will run for the `emacs` command. That should give us a hint about the source of the issue.

FWIW, Bash-it does not provide any completion scripts for Emacs, if a completion for the Emacs command has been set up, it might be from the OS.

**Comment by okomestudio** [comment]
With Bash-it activated:

```
$ complete -p emacs
complete -F _filedir_xspec emacs
```

With Bash-it deactivated:

```
$ complete -p emacs
bash: complete: emacs: no completion specification
```

Does this give you any clue?

**Comment by okomestudio** [comment]
Update: It appears that there is something going on with the `alias-completion` plugin. When I disable the plug in (`bash-it disable plugin alias-completion`), then the issue with the `en` alias is gone. But when I enable the plugin, then the alias gets assigned `_alias_completion` which apparently is from the `alias-completion` plugin of Bash-it.

**Comment by nwinkler** [comment]
That's interesting... I have not seen this error with any other aliases before.

The `_alias_completion::en` function is created on the fly, here:

https://github.com/Bash-it/bash-it/blob/8007e782964afa14206d2ad6687dc4eb60e40b7b/plugins/available/alias-completion.plugin.bash#L65-L75

You can its definition by running `type -a _alias_completion::en`, maybe that will give a hint.

**Comment by okomestudio** [comment]
```bash
$ type -a _alias_completion\:\:en
_alias_completion::en is a function
_alias_completion::en () 
{ 
    (( COMP_CWORD += 1 ));
    COMP_WORDS=(emacs -nw ${COMP_WORDS[@]:1});
    (( COMP_POINT -= ${#COMP_LINE} ));
    COMP_LINE=${COMP_LINE/en/emacs -nw};
    (( COMP_POINT += ${#COMP_LINE} ));
    _filedir_xspec
}
```
This looks okay to me, though I admit that I don't have thorough understanding of how all these `COMP_*` variables work with `bash-completion`.

**Comment by nwinkler** [comment]
Well, the error has to be in there somewhere, or in the `_filedir_xspec` function. Where does that come from, BTW?

I don't see any reference to that in Bash-it... It seems to be defined in the Bash shell completion package, found a copy/fork of that here: https://github.com/nanoant/bash-completion-lib/blob/master/include/_filedir_xspec

**Comment by okomestudio** [comment]
I think it is possible the bug is coming from `bash-completion`. I'll try filing an issue ticket there to see if this is something that could be fixed on their end and report back here.

**Comment by nwinkler** [comment]
It would be interesting to see whether you get the same error when you run `emacs -nw foo<TAB>` - that would indicate that the issue is in the `_filedir_xspec` function...

**Comment by okomestudio** [comment]
It looks like the dynamic generation of `_alias_completion::*` function isn't calling `_filedir_xspec` properly, taking into a required argument. I've created a PR (#1503) to address the issue; please look at it.

**Comment by okomestudio** [comment]
Closing this now, since the PR #1503 fixed this particular problem.
