### ISSUE TITLE
"gh" git alias clashes with github-cli

### ISSUE THREAD

**Issue by jmthvt** [Bash-it/bash-it#1498]
GitHub released a new CLI https://cli.github.com/
The command is called `gh`, which clashes with the `gh` alias set by the bash-it git plugin.

**Comment by nwinkler** [comment]
Not sure what we want to do about that... We've had conflicts before (see #825, #867, and #141), similar discussions there. We will not be able to make everyone happy.

If you are using both the Bash-it Git aliases and the GitHub CLI, you can still include a `unalias gh` in a custom Bash-it script or in your Bash init script after Bash-it has been loaded.

Ironically, there has been a similar discussion on GitHub's CLI a while back, from what I remember, back then they switched from a previous version of `gh` to `hub`. They seem to be moving between these two every couple of years. Not sure we want to be part of that dance... See #392 for more details.

**Comment by jeyglk** [comment]
Hmm yes I agree we can't make everyone happy, and unset is a solution for anyone wanting to fix it.
However I was proposing to change the alias here https://github.com/Bash-it/bash-it/pull/1499 since it's "breaking" the `gh` command when you install the CLI and it took me some minutes to realise it was just due to this alias. Just want to avoid other people running into this :)

**Comment by davidpfarrell** [comment]
Greetings,

I've seen the related PR but thought to discuss here instead of there ...

Would it be useful to :
* Add the `ghome` alias (or maybe `ghm`)
* Leave the `gh` alias, but only enable it if the `gh` command is not found in the path?  i think bash-it has a quick check for that?

**Comment by jeyglk** [comment]
@davidpfarrell Sounds good to me, I'll amend the PR.

**Comment by nwinkler** [comment]
Yes, that sounds like a good compromise to me as well. I'll take a look at the PR...

**Comment by jeyglk** [comment]
PR has just been updated.
