### ISSUE TITLE
[Discussion] Packaging and deprecation

### ISSUE THREAD

**Issue by jpmcb** [Bash-it/bash-it#1500]
There has recently been some frustration around the deprecation policy for breaking changes in `bash-it`: https://github.com/Bash-it/bash-it/pull/1483#commitcomment-37406200

Essentially, any breaking change (removal of plugins or functions, behavior changes, etc) that are merged into master are directly consumed by downstream users through the `bash-it update` command. 

I see that releasing and versioning was discussed here https://github.com/Bash-it/bash-it/issues/1038 several years ago.

I believe it's worth discussing again.

In my opinion, taking advantage of github releases and existing packing tools like `brew` and `snap` would allow the maintainers a structured way to deprecate functionality, introduce breaking changes, and communicate with the community. 

Yes, a changelog would likely need to be maintained and a release cycle would need to somehow be established, but this would greatly benefit the users, building trust within the community.

Personally, to handle versioning, I would recommend [semver](https://semver.org/) as it defines how breaking changes should be handled. 

Thoughts?

**Comment by davidpfarrell** [comment]
+1 for semver and for versioned releases (I actually didn't realize there weren't versioned releases on the repo until just now)

One (maybe nice / maybe not so nice) thing about that is that breaking changes would likely be planned for and have multiple breaking changes released in a single release (to avoid thrashing the version number)

Unless the plan was to deprecate `bash-it update`, I don't think packaging tools would fully solve the problem.

You might have something like `bash-it update-info` which could query for available updates and communicate incoming changes.

You could try to be clever and determine if any incoming changes to plugins/aliases/etc marked as having `"breaking changes"` are actually active on the user's bash-it configuration.  If they aren't, the user will likely not be negatively affected by the upgrade.

Or `bash-it update` could fail if the update contained any `"breaking changes"` and require the user's consent via something like `bash-it update please` or require the user provide the version number ie `bash-it update vX.Y.Z`

"Intent to deprecate" is a nice idea, but not if nobody can see the message.   Bash-it's no-output-messaging policy seems like it could make it difficult to ensure that user's are aware of upcoming changes.   The `fail/please` idea might help with that.

Additionally I will use this moment as chance to ask @jpmcb  and @nwinkler  a question:
Q: Why you no hangout on glitter channel?
I posted a Q there related to messaging users ... I should probably just open an issue ...

Not sure if bash-it currently supports reverting an update, but with versioning, a revert feature might be an option.

For plugins that are completely removed, we might make it easy for a user who still cares about that plugin to copy it into their custom bash-it configuration - Maybe by a bash-it function the user could invoke before the upgrade, or copying the plugin into a `gist` or something and referencing it in the changelog.

**Comment by nwinkler** [comment]
Thanks for starting this discussion - many good points here.

@a-b had raised some issues about missing deprecation warnings related to the `fasd` plugin. I apologize for potentially breaking your installation.

Here are some thoughts:

* Bash-it is not _released_ at the moment, whatever is on _master_ is used. This has been the case traditionally, I haven't changed it so far since I did not see a simple solution.
* Releasing on a regular basis, maintaining a change log, pushing releases to package manager all cause administrative overhead. If someone wants to volunteer for handling this, I'm all for it.
* The request for deprecation warnings is perfectly valid, but as mentioned above, there's no easy way to publish these. I thought about starting a blog, or putting them on the Wiki, but again, this comes with additional work, and I don't really have the time to do this properly. If someone has a suggestion on how to do that in an easy manner, let's discuss.
* Publishing to package managers like Homebrew would likely force us to put a license on the repo - it currently does not have one. There have been requests for setting up a license in the past, but I don't see an easy way of just adding the license to the repo. We have a plethora of copy/paste code from dozens of contributors, some of the code probably is licensed -  I don't know whether there's an easy way to just slap the license on the repo. Going through every single file and reviewing what was changed when, by whom, potentially contacting contributors, etc. is an enormous amount of work.

I recommend we take one step at a time - let's talk about how we would handle deprecation messages first, potentially tied with a better branching model.

Lastly about Gitter: I had created that channel a while back, but I found that the "Bash-it" name attracts all kinds of questions about Bash in general. The signal-to-noise ratio was terrible, with the majority of the questions being about "How do I do this in Bash?", and very few on Bash-it. I don't visit the channel any more, since it's very difficult to see the valuable content...

**Comment by jpmcb** [comment]
* I didn't realize the licensing implications. Thanks for the context on that. Licensing issues in my experience have been a huge pain in the neck. So I understand why you'd like to avoid them.

On Gitter: same as Nils, I had joined but noted alot of noise. Maybe this warrants a separate 
conversation around engaging the contributor in a more async manner beyond Github.

**Comment by jpmcb** [comment]
* One simple "git-op" solution would be to refactor the `bash-it update` command to point to a "release" branch. Then, the master branch would essentially be an upstream develop branch. When there are changes to be released, simple pull from master into release. This would at least prevent users from having direct upstream access to every change. We'd likely want to do this regardless in case there was ever an intermittent git issue on master (like a merge conflict or major breaking bug that somehow made it in).
* This could be expanded further to have `bash-it update` parse the git log for any tags in commit messages like `[BREAKING]` or `[DEPRECATED]`. It could then display these logs to the user and ask for the `please` flag. For PRs that have breaking changes, the maintainers could ask the contributors to include commit messages with those tags.
* To expand this even further, we could enable some kind of branch "versioning" where a new git branch is cut and called something like 1.2.3 following sem-ver convention. Then a user could `bash-it update 1.2.3` to a specific branch. The git log would essentially act as the changelog which would cut down on some maintenance time but would require someone to cut releases from time to time. A potential downside to this is that we end up with a fair number of stale branches correlated directly to versions. But I've seen this methodology work well in the past.
* Some of this could be automated in a pipeline. For example, I've seen automation performs git operations and releasing automatically upon starting the job. But I'm unaware of any pipe-lining this project might have. Likely warrants a separate conversation.
* I didn't realize the licensing implications. Thanks for the context on that. Licensing issues in my experience have been a huge pain in the neck. So I understand why you'd like to avoid using a package manager.

On Gitter; same as Nils, I had joined but noted alot of noise. Maybe this warrants another conversation around engaging the contributor community in a more async manner.

**Comment by nwinkler** [comment]
Thanks - good points! If we want to go with a branching model, I'd vote for Git Flow, which I have been using at work for a long time, it works well.

In this case, _master_ would contain the released code, any work (e.g. PRs) would always happen with the _develop_ branch. Upon release, the _develop_ branch is merged into _master_ (via a _release_ branch). There's some administrative overhead, but a lot of it can be automated.

This doesn't solve the following questions, though:

* When do we create a release? On a fixed interval, e.g. monthly, or when we deem enough changes have happened?
* How do we deal with deprecations and potentially breaking changes. Maintaining older release branches (e.g. _1.2.3_, while main development has moved on to _1.3.2_) is going to be tedious and cumbersome.

I like the idea of a change log (could be automated), if someone has an existing process for that, I'm all for it.

**Comment by jpmcb** [comment]
Yes good point: +1 for the git flow method.

* To reduce administrative/maintainer cost, I think doing a bi-weekly or monthly release cycle would be fine. Whatever makes sense and can be easily automated.
* Agree that attempting to maintain older releases would be tedious, difficult, and unmaintainable. One strategy that I've seen work is to keep the release train going forward, advise users to get on the most recent version, and only back fill urgent security fixes to releases that require them. So, essentially, version 1.2.3 would continue to be stale unless something urgent required an update (like a major security flaw). Even then, I'd argue that users should update to consume new features and bug fixes.
* As far as a change log goes, this doesn't have to be only up to the maintainers. People who make PRs should include an update to a `CHANGELOG.md` file as they add features, fix bugs, or break user flows. Otherwise, git commit messages could be compiled into a change log (which would not be pretty or super user friendly) but this could be a start.

**Comment by nwinkler** [comment]
I'd suggest a monthly release cycle with a matching version number, e.g. _20.3.0_ for the March release. This roughly follows semver, but avoids the major/minor discussion - how do we determine whether a monthly release contains major or minor changes?

If possible, I'd like to avoid backporting changes to previous releases. Over the last couple of years, there has been the occasional security-related change, but these have been really sparse.

For the change log, we should look into an automated solution. This requires that PR/commit messages follow a specific format, but on the other hand, the change log is generated automatically.

One downside of a monthly release cycle is that contributions will not show up immediately (unless you use the _develop_ branch, which can be considered less stable than _master_). It's something we would have to communicate - either stay on the stable _master_ branch, which will give you changes less frequently, or use the _develop_ branch, which gives you changes immediately, but can contain minor issues.

Having said that, it should be clear that the amount of testing that is done before merging things into the stable branch will be limited. I don't expect us to have formal QA or anything like that, so even the stable _master_ branch could contain issues...

**Comment by edumco** [comment]
> * Releasing on a regular basis, maintaining a change log, pushing releases to package manager all cause administrative overhead. If someone wants to volunteer for handling this, I'm all for it.

All this tasks could be put on Github CI (Actions) and I can do that.

> The request for deprecation warnings is perfectly valid, but as mentioned above, there's no easy way to publish these.

This could be shown as deprecation warnings like the Python 2.7, but the warning should be added a few releases before the actual deprecation

> Publishing to package managers like Homebrew would likely force us to put a license on the repo

If you only use tags this can be done safely since this way you're not distributing a package, only a point in time of the repo.

>  don't know whether there's an easy way to just slap the license on the repo. 

There is a service that scans licenses and licenses restrictions <https://app.fossa.com/> you can add this integration and start to tackle this issue slowly

**Comment by nwinkler** [comment]
Thanks for adding your view here, @edumco. All of this is good and well, but like I said before, personally, I won't have time for doing all of this (license, tags, releases, ...) - if people really want to see these things happening, start working on it. I don't mean creating a PR right away, but start putting together a plan of what needs to be done - then we can discuss...

**Comment by NoahGorny** [comment]
I think this is very doable by using `git tag` and improving `bash-it update` to update only to new tags unless instructed otherwise. About release schedule, I think we can just push a tag every once in a while, no need to rush anything

**Comment by nwinkler** [comment]
The "every once in a while" is the big topic... Some people expect regular releases (monthly? weekly?) - we need to find a balance to keep the operational overhead as small as possible.

**Comment by NoahGorny** [comment]
I do not think anyone should expect regular releases- this project is already running without any releases whatsoever.
I think we can start releasing versions and bump whenever we see fit (new big feature, bug fix, etc...)
Regular releases require a lot of time and resources that we do not have

**Comment by nwinkler** [comment]
@NoahGorny provided this comment in #1626, leaving it here for discussion:

> We can create v1.0.0 tag, and bump the minor in the monthly release. In case of bug fixes, we can bump the patch version.
We do not have to create a thoughtful discussion every time we want to bump, and creating "news" overview or changelog should not take too much of our time (I can take responsibility if needed)

This is about potentially doing monthly release and which versioning scheme to use for them:
* Something like `1.0.0` is following _semver_ and allows us to distinguish between major/minor/patch. The downside I see with this is that we'll end up with things like `v1.48.0` - don't know whether we'll consider something a major release, depends on the kind of changes we're making.
* Monthly releases like `2020.07` - easier to manage, but not directly following _semver_. Although we could treat it as such with `2020.07.0` as major/minor/patch. Every year would be a new major release.

Thoughts?

**Comment by edumco** [comment]
Semantic versioning allows to add metadata after the 1.2.3 format using an addition sign:

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3—-117B344092BD.

This metadata can be used to ad the release month

> don't know whether we'll consider something a major release

Here some unit tests should solve the problem. 
- If you have to change old tests means you've made a breaking change so you increase to a new MAJOR version (1.2.3 -> 2.0.0)

- if you have to add more tests its a new functionality so we increase MINOR (1.2.3 -> 1.3.0)

- If you don't need to change the tests its a PATCH (upgrade dependencies, changes to CI, new test cases and small changes)

**Comment by nwinkler** [comment]
Thanks for the thoughts, @edumco!

Unit tests will certainly help, but there are a couple of concerns here:
* We don't have unit tests covering all of Bash-it. That means that there might be changes that are not covered by a unit test yet. This makes it hard to figure out what kind of change (major/minor/patch) we're looking at.
* Changing existing tests happens quite often. @NoahGorny added a new parameter to the `bash-it update` command (and its completion), which resulted in having to change an existing test. I don't think that this is a breaking change and shouldn't need a new major version. Unit tests (especially white box tests) focus on the internal implementation, and change frequently when the implementation is changed (or refactored). Major version changes should be based on public APIs and breaking changes in externally facing functionality.

**Comment by NoahGorny** [comment]
I think that a situation of `v1.48.0` is not ideal, but not too bad. Some changes can be considered "major" even without breaking existing API. In any case, a wonky tagging is better than no tagging at all. I think that tagging and updating the version when some changes are introduced will help organize this repository.

I also do not want all of the burden to fall on you @nwinkler, and I would be happy to help. I think I can devote enough time to help maintain the releases (and the repo overall). We can talk about it if you want :smile:

**Comment by NoahGorny** [comment]
Discussed and released already :smile:
