### ISSUE TITLE
History sub search in Bash

### ISSUE THREAD

**Issue by emanuelhfarias** [Bash-it/bash-it#1506]
Does anybody know a **history sub search** plugin for Bash?

In Fish and Zsh there is a plugin called history-substring-search that you can type part of a sentence and press Up Arrow, it will complete the sentence according to history and highlight the matching words.

I miss it in Bash. I already use **Ctrl+R** but it not the same, I don't feel productive.

**Comment by nwinkler** [comment]
I'm not familiar with these features in Fish and Zsh, but there has been a similar discussion here in #894.

There are some great suggestions in that ticket. Personally, I use [fzf](https://github.com/junegunn/fzf) with the Bash-it `fzf` plugin, which overrides the default **Ctrl+R** behavior, that works really well for me.

Please let me know if that helps.

**Comment by emanuelhfarias** [comment]
I've found that GNU Readline has a feature called **history-substring-search-backward** which is what I'm looking for: you can type any part of a previously entered command and press Up Arrow, it will complete it for you.

Since Bash 4+ this feature is available.
You just need to configure it in `~/.inputrc` file:
```
"\e[A": history-substring-search-backward
"\e[B": history-substring-search-forward
```
Then, Ctrl+x Ctrl+r to reload configs from `~/.inputrc`, or just reload bash.

This is faster than using **Ctrl + r** :smile:

The only thing is missing is the highlighting what has been matched. But I can live without that.

Thanks

**Comment by jpmcb** [comment]
Interesting - is there the concept of a configurable `inputrc` for bash-it? The whole mantra of this project seems to be "reduce the number of cluttered *rc files". 

Would it be possible to include this as a plugin / feature so someone could use bash-it instead of manually adding a line to their `inputrc`

**Comment by emanuelhfarias** [comment]
@jpmcb It's also possible to active it in **~/.bashrc** like this:
```sh
bind '"\e[A": history-substring-search-backward'
bind '"\e[B": history-substring-search-forward'
```
So we don't need the **~/.inputrc** anymore.

It's possible to create a plugin to activate this.

**Comment by nwinkler** [comment]
Exactly - these two lines would need to be defined in a plugin, e.g. `bash-history` or something like that.

**Comment by nwinkler** [comment]
OK, looks like we already have that:

https://github.com/Bash-it/bash-it/blob/master/plugins/available/history.plugin.bash

You can enable that with `bash-it enable plugin history`. It uses `history-search-backward`, without the `substring` part, but that could be adjusted, or configured through an environment variable if needed.

**Comment by mcarans** [comment]
@nwinkler How do I make the history plugin use the substring part?

**Comment by cornfeedhobo** [comment]
@mcarans You just need to enable the plugin and reload your shell (or start a new one):

```shell
$ bash-it enable plugin history
$ bash-it reload
```

You may also enjoy our new documentation at https://bash-it.readthedocs.io/en/latest/

**Comment by mcarans** [comment]
@cornfeedhobo The problem is that the current history plugin uses history-search-backward not history-substring-search-backward (https://github.com/Bash-it/bash-it/blob/master/plugins/available/history.plugin.bash). Is there a way to modify the installed history plugin to use history-substring-search-backward?

**Comment by cornfeedhobo** [comment]
@mcarans The original post asked:

> history-substring-search that you can type part of a sentence and press Up Arrow, it will complete the sentence according to history and highlight the matching words.

That is exactly what the history plugin does. When I type `ech` and hit the up arrow, the only commands shown are ones that begin with the `ech` prefix, e.g. `echo "foobar"`.

Are you looking for something different?

**Comment by mcarans** [comment]
@cornfeedhobo That works for me! Out of interest what would the addition of substring do if anything?

**Comment by mcarans** [comment]
@cornfeedhobo I found the answer [here](https://www.gnu.org/software/bash/manual/html_node/Commands-For-History.html)

history-search-backward: The search string must match at the beginning of a history line
history-substring-search-backward: The search string may match anywhere in a history line. 

It seems to me like history-substring-search-backward is more useful. Is there any way I can change the plugin to use history-substring-search-backward?

**Comment by cornfeedhobo** [comment]
@mcarans Sorry got pulled away. Looks like you figured it out - substring means that if you type in `echo` and hit the up arrow, it will show _**any**_ command which contains the string "echo", regardless of position. Thanks for sticking with it!

I definitely think we can work something in to address this option, just need to think of the most elegant way to expose that option to users. I'm not sure if I'd prefer breaking up history into different plugins, or using an environment variable to toggle the functionality.

@tbhaxor @nwinkler @NoahGorny @davidpfarrell  any thoughts?

**Comment by nwinkler** [comment]
@cornfeedhobo I'd go with an environment variable to change which command is being used. Adding a second plugin will lead to further complexity, e.g. when people enable both plugins. Using an environment variable, we can have a defined default behavior and also an easy option for overriding things. A couple of items to address:
* We should aim for consistent naming patterns for plugin configuration options - don't think we have a consistent pattern at the moment.
* How do we document plugin configuration settings? Do we want to support an optional documentation file per plugin?

**Comment by cornfeedhobo** [comment]
Since I was waiting around and ended up coming to my an opposite conclusion, I'm going to continue that discussion in #1764, at least until we decide if we want to go with that route or another one. Thanks everyone!
