### ISSUE TITLE
What is "docker-compose-fresh" ?

### ISSUE THREAD

**Issue by finn-matti** [Bash-it/bash-it#1513]
It's part of the [docker-compose aliases](https://github.com/Bash-it/bash-it/blob/master/aliases/available/docker-compose.aliases.bash).

**Comment by nwinkler** [comment]
Ah, good question.

It points to the `docker-compose-fresh` function that's defined in the `docker-compose` plugin here:

https://github.com/Bash-it/bash-it/blob/c1ec06c9d8e1c6bbc5b15523bc0c5cbfcefb740a/plugins/available/docker-compose.plugin.bash#L4-L20

Probably should have added a comment above the alias definition...

**Comment by finn-matti** [comment]
Ah. That makes sense. Thanks!

P. S.: It might indeed help to put a comment there.

**Comment by nwinkler** [comment]
Thanks - just added a comment!
