### ISSUE TITLE
Getting syntax error while bashit reload

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1514]
I have added some youtube-dl aliases to the bashrc file, but now I have deleted them. Since then i am getting this syntax error. Could you help me identify the cause?

![image](https://user-images.githubusercontent.com/28386721/76228683-0daf1700-6247-11ea-9030-492f1ebba4ad.png)

**Comment by nwinkler** [comment]
Does the same happen when you open a new Terminal window? Or only when you reload?

**Comment by tbhaxor** [comment]
Only on reload and yesterday I tried updating bashit via `bashit update`, the same happened at that time also

**Comment by nwinkler** [comment]
Does the error happen in this scenario?

* Open a new Terminal window
* In this new Terminal window, run `bash-it reload`

**Comment by tbhaxor** [comment]
@nwinkler  yes

**Comment by tbhaxor** [comment]
No, in new terminal it does not happens.

**Comment by tbhaxor** [comment]
could you tell me why it happens in the same terminal?

**Comment by nwinkler** [comment]
It probably happens because your existing Terminal session still contains a definition of the alias in the current session. We don't include automatic unaliasing for things that are no longer there.

Fix: Open a new Terminal window and work there, or run `unalias foo` (replace `foo` with the name of the deleted alias) before running `bash-it reload`.

**Comment by tbhaxor** [comment]
oh cool

**Comment by dschrempf** [comment]
Sorry to bump in here, but I get the same error and did not understand the explanation. I do define custom aliases, and the error involves one of those aliases (not the first one I define, though). Rather, it seems to be the first recursively defined alias. For example:

    alias long-command="bla bla bla"
    alias short="long-command"

Then it complains about `short`.

Detailed error message:

```
bash: /tmp/alias_completion-1175bpCQE5: line 706: syntax error near unexpected token `;'
bash: /tmp/alias_completion-1175bpCQE5: line 706: `                        COMP_WORDS=(sbf; stack install --fast --dump-logs --work-dir .stack-work ${COMP_WORDS[@]:1})'
bash: sbf;: command not found
bash: /tmp/alias_completion-1175bpCQE5: line 711: syntax error near unexpected token `}'
bash: /tmp/alias_completion-1175bpCQE5: line 711: `  
```

**Comment by nwinkler** [comment]
Interesting one. Can you show the actual definitions of your aliases? Would like to see where the `sbf` (and the added semicolon) come from...

**Comment by dschrempf** [comment]
The definitions are:
```
alias sbfast="stack build --fast --dump-logs --work-dir .stack-work"
alias sbf="sbfast"
```
They are in `aliases.bash`, in the `custom` folder.
