### ISSUE TITLE
ls with bash-it configuration does not recognize `.mov` as media file in macOS

### ISSUE THREAD

**Issue by dclong** [Bash-it/bash-it#1517]
Below is the screenshot on macOS. Notice that the color for `trim_3.mov` and `zz.png` are not specially colorized. 
![image](https://user-images.githubusercontent.com/824507/76488569-1c323580-63e3-11ea-815e-66c02a134381.png)
However, 
those files are specially colorized (for easy recognition) in Linux. 
![image](https://user-images.githubusercontent.com/824507/76488711-729f7400-63e3-11ea-9226-8f9f3b4a9b5a.png)

**Comment by nwinkler** [comment]
Good question. This seems to be related to the `dircolors` settings. Please see here for some details:

* https://askubuntu.com/questions/17299/what-do-the-different-colors-mean-in-ls
* https://unix.stackexchange.com/questions/91937/mac-os-x-dircolors-not-found

**Comment by davidpfarrell** [comment]
@dclong  Are you seeing different behavior when bash-it is and is-not installed?  Just wondering if you confirmed that what you are seeing is related to bash-it and not just standard Mac behavior?

In general, the OS-X built-in `ls` command (`/bin/ls`) only comes with basic `"LSCOLORS"` support (`man ls`), and does not come with `dircolors  / LS_COLORS` support.

I found the easiest path to full color support was through installing the `coreutils` package via homebrew:

```
$ brew info coreutils

coreutils: stable 8.32 (bottled), HEAD
GNU File, Shell, and Text utilities
https://www.gnu.org/software/coreutils

Conflicts with:
  aardvark_shell_utils (because both install `realpath` binaries)
  b2sum (because both install `b2sum` binaries)
  ganglia (because both install `gstat` binaries)
  gegl (because both install `gcut` binaries)
  idutils (because both install `gid` and `gid.1`)
  md5sha1sum (because both install `md5sum` and `sha1sum` binaries)
  truncate (because both install `truncate` binaries)
...

==> Caveats
Commands also provided by macOS have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```

Among other things, this will install `gls` and `gdircolors` 

You can use these directly as needed or create aliases that reference them, ie:

_.bash_profile_
```
eval $(gdircolors)
alias ls="gls --color=auto"
```

If you want the coreutils tools to override the built-in mac tools, you can add:

_.bash_profile_
```
PATH="${BREW_PREFIX)/opt/coreutils/libexec/gnubin:$PATH"
eval $(dircolors)
alias ls="ls --color=auto"
```

Hope that helps

-DF

PS: Please do report if you are seeing any further errors specific to Bash-It.  However, please don't ask (me) for further support regarding coreutils, dircolors etc - This was just to (hopefully) get you started - The Internet is your friend - Good Luck !

**Comment by dclong** [comment]
@davidpfarrell Thank you very much for the detailed explanation! I observe the similar patter (media files are not colorized by `ls` in macOS while they are colorized by `ls` in Linux) when bash_it is not installed. I think you are right that it is due macOS standard behavior.
