### ISSUE TITLE
Considder adding git switch aliases

### ISSUE THREAD

**Issue by finn-matti** [Bash-it/bash-it#1525]
I'd love to see some git switch aliases included with the current batch of git aliases. Has this been considered before? Things I'd like:

- `git switch`
- `git switch -c branch`
- `git switch -t branch`

Thanks for your consideration!

**Comment by davidpfarrell** [comment]
TIL about the [Git Switch](https://git-scm.com/docs/git-switch) command.

I created #1526 for these aliases.

I've tested them locally, but feel free to also test/confirm them if you can.

-DF
