### ISSUE TITLE
Git Completions Out of Date (completions @ v2.21 vs latest v2.26)

### ISSUE THREAD

**Issue by davidpfarrell** [Bash-it/bash-it#1527]
In discussing / working on #1525 for the `git switch`, I realized that the current git completions don't support the `switch` command.

Looking into a bit, I see the lats update to the git completions was:

[@trmaphi : Update bash completion for git v2.21.0](https://github.com/Bash-it/bash-it/commit/c8b4ffbac1f9722c39ae544cf1603c3a05ae202b)

The `switch` command was added to git in v2.23, so that explains why it doesn't work.

I'm creating this issue to:

* Track the fact that the git completions are a bit out of date.
* Give a place to ping @trmaphi to see if they might be interested in updating them? :) 

---
cc: @trmaphi

**Comment by trmaphi** [comment]
@davidpfarrell, I haven't take a look at `git switch`  and limited to test in only on macOS. So, feel free to open MR and work on it. Thanks to get me involved 😄
