### ISSUE TITLE
conda support for bash-it?

### ISSUE THREAD

**Issue by charles-typ** [Bash-it/bash-it#1529]
Hi,

I'm a new user and newly installed bash-it but I could not see my conda enviroment anymore, is there some ways to fix this since I've seen a [PR](https://github.com/Bash-it/bash-it/pull/1225) that should have fixed it probably. I have no idea why it's not showing.

Thanks

**Comment by davidpfarrell** [comment]
Greetings @charles-typ,

Are you using one of the bash-it themes?  If so, which one?  And can you share your bash-it startup settings?  (ie. any environment variables you defined as part of installing bash-it)

Also: Before you installed bash-it, how were you *seeing* your conda environment?

**Comment by nwinkler** [comment]
Yes, @davidpfarrell is right - this depends on the theme that you're using. Several themes include support for `conda`, e.g. the _Powerline_ themes.

**Comment by charles-typ** [comment]
Thanks @davidpfarrell @nwinkler  for the quick response and clear solution.

I was using the default theme and before I use bash-it I see the conda environment at the left side of the console. For instance:` (base)~/`

I've changed the theme to powerline and it shows the conda environment now.

It would also be great if there were docs that I could find out which theme supports the feature I want, or to see what kind of features does a theme supports.

Closing this issue and thanks again for your help!

**Comment by nwinkler** [comment]
Thanks for the kind words!

Yes, it would be nice to have that kind of information, but compiling that information would be a lot of work. In general, the Powerline themes are the most advanced ones and provide the most options - my recommendation is to use one of those...
