### ISSUE TITLE
Load progress and success indication

### ISSUE THREAD

**Issue by rico-chet** [Bash-it/bash-it#1531]
I have a couple plugins and aliases enabled and it takes quite some time to load them all, especially when the machine is under high load or throttled for the sake of silence or battery life.

Also, while sharing same default configuration among a couple machines, I found it inconvenient that error messages clutter the console and I cannot see clearly which components failed to load because tools needed are missing.

So, over a year ago, I added a couple commits for my own usage: [branch in the fork](https://github.com/rico-chet/bash-it/commits/progress-status).

It's missing a few things that make it fit for upstreaming, but I find it too useful to keep it for myself. So feel free to bring it up to shape and eventually to mainline this.

Here's how it looks like:
```
☑ 'dotfile/editorconfig' done
☐ 'dotfile/emacs' skipped
☑ 'aliases/fuck' done
☑ 'aliases/git-brief' done
☑ 'aliases/grep-colored' done
☐ 'aliases/local' skipped
☑ 'aliases/ls' done
☑ 'aliases/tig' done
☑ 'dotfile/tmux' done
☑ 'aliases/trash' done
☑ 'dotfile/vim' done
☑ 'plugin/autojump' done
☑ 'plugin/base' done
☑ 'plugin/history-custom' done
☐ 'plugin/keychain-pgp' skipped
☐ doing 'plugin/keychain-ssh'...
 * keychain 2.8.2 ~ http://www.funtoo.org
 * Inheriting ssh-agent (322)
 * Known ssh key: /home/rico/.ssh/id_rsa

☑ 'plugin/keychain-ssh' done
☑ 'plugin/less-raw-chars' done
☑ 'plugin/stow' done
☑ 'plugin/tmux' done
☑ 'plugin/stderred' done
☑ 'completion/bash-it' done
☑ 'completion/system' done
☑ 'plugin/alias-completion' done
 $
```

**Comment by nwinkler** [comment]
Thanks for providing this suggestion - this seems to be in line with #1501. Can you please take a look at that and see if your changes would help with doing something like that?

**Comment by rico-chet** [comment]
Nice, I will take a look. For the time being, here's an [asciinema recording of my current setup](https://asciinema.org/a/ZlcCcF8WnvTIAnNjUjR9YltF6).

**Comment by NoahGorny** [comment]
seems like #1623 is partly taking care of this, closing.
@rico-chet feel free to reopen and submit PRs!
