### ISSUE TITLE
Enable Completion Unable to Process List

### ISSUE THREAD

**Issue by tayjaybabee** [Bash-it/bash-it#1534]
**Expected Behavior**:
Command:
```shell.command
$ bash-it enable completion pipenv pip pip3
```
Returns:
```shell.output
0
```

Check Completions:
```shell.command
$ bash-it help completion
```
Returns:
```shell.output
  ...
  pip3                    [x]     
  pip                      [x]     
  pipenv                [x]
```

----

**Actual Behavior**
  
Command:
```shell.command
$ bash-it enable completion pipenv pip pip3
```

Returns:
```shell.output
0
```

Check Completions:
```shell.command
$ bash-it help completion
```
Returns:
```shell.output
  pip3                    []     
  pip                      []     
  pipenv                [X]
```

Run Command Again:

```shell.command
$ bash-it enable completion pipenv pip pip3
```

Returns:
```shell.return
pipenv is already enabled.
0
```

Check Completions:
```shell.command
$ bash-it help completion
```

Returns:
```shell.output

  pip3                    []     
  pip                      [X]     
  pipenv                [X]
```

**Abstract Description of Issue**:
'enable completion' seems unable to process lists though it accepts them, and will iterate through the list without adding all selections but adding the next option that isn't already enabled

**Comment by nwinkler** [comment]
That's weird, this is working perfectly fine for me:

```bash
❯ bash-it help completion | grep pip
pip                   [ ]     
pip3                  [ ]     
pipenv                [ ]     

❯ bash-it enable completion pipenv pip pip3
pipenv enabled with priority 350.
pip enabled with priority 350.
pip3 enabled with priority 350.

❯ bash-it help completion | grep pip
pip                   [x]     
pip3                  [x]     
pipenv                [x] 
```

Are you sure that you're on the latest version of Bash-it? The enable/disable for multiple parameters was added a while back. Could it be possible that you're on an older version?

**Comment by tayjaybabee** [comment]
So, I just ran it again, after a fresh install of my OS (for unrelated reasons, though it's the same distro) and installing bash-it in this fresh environment via the following process

 ```shell.command
~                                                                   04:51:42  Tay 
❯ bash-it enable completion pipenv pip pip3
```

Listing enabled completions:

```shell.command
 ~                                                                  05:01:04  Tay 
❯ bash-it help completion| grep pip
pip3                  [ ]     
pip                   [ ]     
pipenv                [x]   
```

Just in-case something -is- screwy with my version (though, it doesn't seem like that could be problem) I ran the version command for bash-it:

```shell.command
 ~                                                                   05:03:19  Tay 
❯ bash-it version
Current git SHA: ca843e7 on 2020-03-31T08:51:58+02:00
https://github.com/bash-it/bash-it/commit/ca843e7
Compare to latest: https://github.com/bash-it/bash-it/compare/ca843e7...master

**Comment by nwinkler** [comment]
Thanks for the additional detail. A couple of questions:

* When you ran the `bash-it enable` command, did it print anything? It should have printed something along the lines of what I showed above (`pipenv enabled with priority 350`) - even for a single one, not only for multiple items.
* Can you check whether the enabled completions were created in `~/.bash_it/completions/enabled`, or in `~/.bash_it/enabled`?
* After running the `install.sh` script, did you either call `bash-it reload` or open a new Terminal window/session?

To me it looks like you're shell session still has an older version of Bash-it for some reason. Opening a new Terminal window should force to load the current Git version of Bash-it.

**Comment by tayjaybabee** [comment]
>     * When you ran the `bash-it enable` command, did it print anything? It should have printed something along the lines of what I showed above (`pipenv enabled with priority 350`) - even for a single one, not only for multiple items.

I thought that was odd as well, as I was aware that it should have given output instead of just returning 0. I was thinking I should have made note of the absence of the output in my reply but I figured I was already being too detailed/verbose in my explanation.

Therefore, I ran the same set of commands again today. Note that I have gone through several restarts (full, no sessions being restored) and logouts since I last posted and before issuing the following commands and receiving the resulting outputs (and lack thereof):

----
----

```shell.command

 ~                                   19:28:48  Tay 
❯ bash-it enable completion pipenv pip pip3
```
Which produced this output (and only this output):

```shell.output
pipenv is already enabled.

```
_*Note the lack of additional output_

----
----

The next command I issued the prompt was:

```shell.command

 ~                                   19:30:57  Tay 
❯ bash-it help completion

```
Which produced the following output:
```shell.output
Completion          Enabled?  Description
apm                   [ ]     
awless                [ ]     
awscli                [ ]     
bash-it               [x]     
brew                  [ ]     
bundler               [ ]     
capistrano            [ ]     
composer              [ ]     
conda                 [ ]     
consul                [ ]     
crystal               [ ]     
defaults              [ ]     
dirs                  [ ]     
django                [ ]     
docker                [ ]     
docker-compose        [ ]     
docker-machine        [ ]     
drush                 [ ]     
export                [ ]     
fabric                [ ]     
flutter               [ ]     
gcloud                [ ]     
gem                   [ ]     
gh                    [ ]     
git                   [ ]     
git_flow_avh          [ ]     
git_flow              [ ]     
go                    [ ]     
gradle                [ ]     
grunt                 [ ]     
gulp                  [ ]     
helm                  [ ]     
homesick              [ ]     
hub                   [ ]     
invoke                [ ]     
jboss7                [ ]     
jungle                [ ]     
knife                 [ ]     
kontena               [ ]     
kubectl               [ ]     
laravel               [ ]     
lerna                 [ ]     
makefile              [ ]     
maven                 [ ]     
minikube              [ ]     
ng                    [ ]     
npm                   [ ]     
nvm                   [ ]     
openshift             [ ]     
packer                [ ]     
pew                   [ ]     
pip3                  [ ]     
pip                   [x]     
pipenv                [x]     
projects              [ ]     
rake                  [ ]     
rvm                   [ ]     
salt                  [ ]     
sdkman                [ ]     
sqlmap                [ ]     
ssh                   [ ]     
svn                   [ ]     
system                [x]     
terraform             [ ]     
test_kitchen          [ ]     
tmux                  [ ]     
todo                  [ ]     
travis                [ ]     
vagrant               [ ]     
vault                 [ ]     
virsh                 [ ]     
virtualbox            [ ]     
vuejs                 [ ]     
wpscan                [ ]     

to enable a completion, do:
$ bash-it enable completion  <completion name> [completion name]... -or- $ bash-it enable completion all

to disable a completion, do:
$ bash-it disable completion <completion name> [completion name]... -or- $ bash-it disable completion all
```
_*Note the completion being enabled but not pip3_

----
----
>     * Can you check whether the enabled completions were created in `~/.bash_it/completions/enabled`, or in `~/.bash_it/enabled`?

Neither of these directories seem to be present on my system. I ran the following locate commands and couldn't find anything I feel comfortable matching to the files you described:

```shell.command

 ~                                     19:50:11  Tay 
❯ locate bash_it
```

Which returned:
 
```shell.command
/home/taylor/.src/bash-it/bash_it.sh
/home/taylor/.src/bash-it/test/bash_it
/home/taylor/.src/bash-it/test/bash_it/bash_it.bats
/home/taylor/.src/bash-it/test/fixtures/bash_it
/home/taylor/.src/bash-it/test/fixtures/bash_it/aliases
/home/taylor/.src/bash-it/test/fixtures/bash_it/plugins
/home/taylor/.src/bash-it/test/fixtures/bash_it/aliases/available
/home/taylor/.src/bash-it/test/fixtures/bash_it/aliases/available/a.aliases.bash
/home/taylor/.src/bash-it/test/fixtures/bash_it/aliases/available/b.aliases.bash
/home/taylor/.src/bash-it/test/fixtures/bash_it/plugins/available
/home/taylor/.src/bash-it/test/fixtures/bash_it/plugins/available/c.plugin.bash
```
_*Note that my .src folder is where I cloned (yesterday) this repo and ran install.sh from for installation_

Next I ran locate for .bash_it:

```shell.command

 ~                                       19:53:46  Tay 
❯ locate .bash_it

```
Which simply returned:

```shell.output

0

```

----
----

>     * After running the `install.sh` script, did you either call `bash-it reload` or open a new Terminal window/session?

I did both, in the following order:

1. Run install.sh
2. ```shell $> bash-it reload ```
3. ```shell $> exit ```
4. Open a new term window

This is not to mention the several restarts, relogs, etc in the time since and I am still having the issue.

----
----

> To me it looks like you're shell session still has an older version of Bash-it for some reason. Opening a new Terminal window should force to load the current Git version of Bash-it.

In response to this, I will again run bash-it's version command and provide the output:

```shell.command

 ~                                                 19:54:04  Tay 
❯ bash-it version

```

Which produced the following output:

```shell.output

Current git SHA: ca843e7 on 2020-03-31T08:51:58+02:00
https://github.com/bash-it/bash-it/commit/ca843e7
Compare to latest: https://github.com/bash-it/bash-it/compare/ca843e7...master

```

And it looks like that SHA fragment is accurate:

![screenshot](https://user-images.githubusercontent.com/43686206/78089860-2b772400-738e-11ea-88c3-772b755e12af.png)

**Comment by nwinkler** [comment]
Thanks for the details - that's helpful! One thing I noticed is that your Bash-it installation is in an unusual location: It looks like it's installed in `/home/taylor/.src/bash-it`, whereas the default location should be `~/.bash-it`, i.e. `/home/taylor/.bash_it`.

Can you make sure that your `$BASH_IT` variable is set to `/home/taylor/.src/bash-it`?

```bash
echo $BASH_IT
```

Thanks for hanging in there!

**Comment by tayjaybabee** [comment]
> 
> Can you make sure that your `$BASH_IT` variable is set to `/home/taylor/.src/bash-it`?

Absolutely!

I issued the following command:

```shell.command

 ~                                 08:18:22  Tay 
❯ echo $BASH_IT


```

and received this output:

```shell.command

/home/taylor/.src/bash-it

```

> 
> Thanks for hanging in there!

No problem! I understand that every system configuration can be accounted for, I also understand how in-depth this program has to be and sometimes fringe cases fall through the cracks :3

**Comment by nwinkler** [comment]
One more thing to try: Can you please paste the output of `type -a _enable-thing`?

That's the function that should take care of enabling the plugins...

And also the output of `type -a bash-it`? This is the main Bash-it function that handles cases like enable/disable.

**Comment by tayjaybabee** [comment]
> One more thing to try: Can you please paste the output of `type -a _enable-thing`?

Sure. So here is my command:

```shell.command

 ~                                    16:12:40  Tay 
❯ type -a _enable-thing

```

Which returned this:

```shell.command
\_enable-thing is a function
_enable-thing () 
{ 
    cite _about _param _example;
    _about 'enables a bash_it component';
    _param '1: subdirectory';
    _param '2: file_type';
    _param '3: file_entity';
    _param '4: load priority';
    _example '$ _enable-thing "plugins" "plugin" "ssh" "150"';
    subdirectory="$1";
    file_type="$2";
    file_entity="$3";
    load_priority="$4";
    if [ -z "$file_entity" ]; then
        reference "enable-$file_type";
        return;
    fi;
    if [ "$file_entity" = "all" ]; then
        typeset f $file_type;
        for f in "${BASH_IT}/$subdirectory/available/"*.bash;
        do
            to_enable=$(basename $f .$file_type.bash);
            if [ "$file_type" = "alias" ]; then
                to_enable=$(basename $f ".aliases.bash");
            fi;
            _enable-thing $subdirectory $file_type $to_enable $load_priority;
        done;
    else
        typeset to_enable=$(command ls "${BASH_IT}/$subdirectory/available/"$file_entity.*bash 2>/dev/null | head -1);
        if [ -z "$to_enable" ]; then
            printf '%s\n' "sorry, $file_entity does not appear to be an available $file_type.";
            return;
        fi;
        to_enable=$(basename $to_enable);
        typeset enabled_plugin=$(command ls "${BASH_IT}/$subdirectory/enabled/"{[0-9][0-9][0-9]$BASH_IT_LOAD_PRIORITY_SEPARATOR$to_enable,$to_enable} 2>/dev/null | head -1);
        if [ ! -z "$enabled_plugin" ]; then
            printf '%s\n' "$file_entity is already enabled.";
            return;
        fi;
        typeset enabled_plugin_global=$(command compgen -G "${BASH_IT}/enabled/[0-9][0-9][0-9]$BASH_IT_LOAD_PRIORITY_SEPARATOR$to_enable" 2>/dev/null | head -1);
        if [ ! -z "$enabled_plugin_global" ]; then
            printf '%s\n' "$file_entity is already enabled.";
            return;
        fi;
        mkdir -p "${BASH_IT}/enabled";
        declare local_file_priority use_load_priority;
        local_file_priority=$(grep -E "^# BASH_IT_LOAD_PRIORITY:" "${BASH_IT}/$subdirectory/available/$to_enable" | awk -F': ' '{ print $2 }');
        use_load_priority=${local_file_priority:-$load_priority};
        ln -s ../$subdirectory/available/$to_enable "${BASH_IT}/enabled/${use_load_priority}${BASH_IT_LOAD_PRIORITY_SEPARATOR}${to_enable}";
    fi;
    _bash-it-clean-component-cache "${file_type}";
    if [ -n "$BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE" ]; then
        exec ${0/-/};
    fi;
    printf '%s\n' "$file_entity enabled with priority $use_load_priority."
}

0

``` 

> And also the output of `type -a bash-it`? This is the main Bash-it function that handles cases like enable/disable.

Absolutely! So, issuing the following command:

```shell.command

 ~                                     10:52:31  Tay 
 126 ❯ ❯ type -a bash-it

```

Which returns:

```shell.output

bash-it is a function
bash-it () 
{ 
    about 'Bash-it help and maintenance';
    param '1: verb [one of: help | show | enable | disable | migrate | update | search | version | reload ] ';
    param '2: component type [one of: alias(es) | completion(s) | plugin(s) ] or search term(s)';
    param '3: specific component [optional]';
    example '$ bash-it show plugins';
    example '$ bash-it help aliases';
    example '$ bash-it enable plugin git [tmux]...';
    example '$ bash-it disable alias hg [tmux]...';
    example '$ bash-it migrate';
    example '$ bash-it update';
    example '$ bash-it search [-|@]term1 [-|@]term2 ... [ -e/--enable ] [ -d/--disable ] [ -r/--refresh ] [ -c/--no-color ]';
    example '$ bash-it version';
    example '$ bash-it reload';
    typeset verb=${1:-};
    shift;
    typeset component=${1:-};
    shift;
    typeset func;
    case $verb in 
        show)
            func=_bash-it-$component
        ;;
        enable)
            func=_enable-$component
        ;;
        disable)
            func=_disable-$component
        ;;
        help)
            func=_help-$component
        ;;
        search)
            _bash-it-search $component "$@";
            return
        ;;
        update)
            func=_bash-it_update
        ;;
        migrate)
            func=_bash-it-migrate
        ;;
        version)
            func=_bash-it-version
        ;;
        reload)
            func=_bash-it-reload
        ;;
        *)
            reference bash-it;
            return
        ;;
    esac;
    if ! _is_function $func; then
        if _is_function ${func}s; then
            func=${func}s;
        else
            if _is_function ${func}es; then
                func=${func}es;
            else
                echo "oops! $component is not a valid option!";
                reference bash-it;
                return;
            fi;
        fi;
    fi;
    if [ x"$verb" == x"enable" ] || [ x"$verb" == x"disable" ]; then
        _bash-it-migrate;
        for arg in "$@";
        do
            $func $arg;
        done;
    else
        $func "$@";
    fi
}



```

**Comment by nwinkler** [comment]
These look like the correct versions... I'm out of advice, short of running `set -x ; bash-it enable plugin ... ; set +x`

This will likely print a lot of output, but not sure what else to do...

**Comment by tayjaybabee** [comment]
> These look like the correct versions... I'm out of advice, short of running `set -x ; bash-it enable plugin ... ; set +x`
> This will likely print a lot of output, but not sure what else to do...

That's perfectly fine. The end result is that I can still do what I want to do, just with more effort or I need to make a script. I mainly created this issue because as a developer myself I know I'd like to know about all the little fringe things out there if for no other reason than one person's issue might shed light on another seemingly unrelated issue, or whatever. 

So, no worries. I'm not demanding a fix from ya

**Comment by nwinkler** [comment]
Really sorry that I can't be of more help... Would love to see what's causing this. I'm still pretty sure that you have an older version of Bash-it somewhere, or something like that.

**Comment by tayjaybabee** [comment]
> Really sorry that I can't be of more help...

Well, that's cuz you're a great developer ;P

**Comment by NoahGorny** [comment]
@tayjaybabee can you rerun this and use `bash it doctor`?

**Comment by tayjaybabee** [comment]
Oof. Did you still want this? :<
