### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by cornfeedhobo** [Bash-it/bash-it#1537]
@nwinkler Could we start a communication stream outside of github? Freenode has had the #bash-it channel for over 7 years. I think at the very least this should be noted in the README.

On a personal note, is there a way to reach you without resorting to emailing your place of work? I'd like to discuss the recent issues a little more privately than github issues allow.

**Comment by nwinkler** [comment]
@cornfeedhobo Sure, let's talk. I'm not on Freenode or IRC or anything like that...

You can find my personal email address in the Git log - don't think it's visible here on GitHub, but if you open the log in something like SourceTree, you'll see my email address there.
