### ISSUE TITLE
Consider adding git stash push

### ISSUE THREAD

**Issue by finn-matti** [Bash-it/bash-it#1541]
Since [git stash push](https://git-scm.com/docs/git-stash#Documentation/git-stash.txt-push-p--patch-k--no-keep-index-u--include-untracked-a--all-q--quiet-m--messageltmessagegt--pathspec-from-fileltfilegt--pathspec-file-nul--ltpathspecgt82308203) is the new way to create a stash I find myself writing this command, esspecially with the -m option a lot. Maybe it's worth adding to bash-it?

**Comment by davidpfarrell** [comment]
Greetings,

So there doesn't appear to be a great alias for `push` -- Looking at existing aliases:
```
alias gst="git stash"
alias gstb="git stash branch"
alias gstd="git stash drop"
alias gstl="git stash list"
alias gstp="git stash pop"
```

`gst` has to remain as the *naked* stash command.
`gstp` is ambiguous, but as a long-standing alias for `pop` (I was using it even before installing bash-it), I think it has to stay as an alias for pop.

`gstpu` comes to mind, but I'm not loving it.

`gsts`: Here, the `s` stands for `save`, which I argue is well-known and users will know that its for creating a stash (and I'm wondering why it didn't already exist here as an alias for `git stash save`?) ... We could still implement it with `push`.  Its a little shorter than `gstpu` and easier to type, and users *might* understand that it resolves to `push` - The main difference that someone who actually uses `git stash save` regularly would be tripped up on is that save takes an optional message *without* the `-m` argument, while push requires the `-m` argument.

> ... esspecially with the -m option ...

So maybe something like
```
alias gstpum="git stash push -m"
```

I'm not a huge fan of aliases that resolve to partially-defined argument, but I will say there is precedence in the existing git aliases:
```
alias gcsam="git commit -S -am"
```

With that, I *guess* its okay to create such an alias -- Still bothers me a bit tho.

With all the above, I think the following new aliases might be worth considering:
```
# Push introduced in git v2.13.2
alias gstpu="git stash push"
alias gstpum="git stash push -m"

# Save deprecated since git v2.16.0 - Alias resolves to Push
alias gsts="git stash push"
alias gstsm="git stash push -m"

# Alias *po to pop for symmetry with push
alias gstpo="git stash pop"
```
This would introduce `gsts` (which should have already existed) and `gstsm` but resolves them to push.
This would leave `gstp` for pop, but also add `gstpo` for symmetry with `gstpu` for push.

Thoughts?

-DF

**Comment by nwinkler** [comment]
These are reasonable suggestions, @davidpfarrell!

**Comment by davidpfarrell** [comment]
Thanks for the feedback, I have created PR #1551 for review.

**Comment by nwinkler** [comment]
Great - thanks!
