### ISSUE TITLE
Tests: lack of support for `bats-core` v1.0.2 or newer

### ISSUE THREAD

**Issue by rico-chet** [Bash-it/bash-it#1555]
Currently, we use an old version of `bats-core` which runs all test sequentially and rather slowly (~100 s). Newest version (to be released) of the test framework supports parallel execution: [merged PR](https://github.com/bats-core/bats-core/pull/172). A _dirty_ test where the affecting commit (as explained below) was reverted and `bash-it` test setup adjusted for extra test isolation shows that on a 16-thread machine, the test time goes down from ~100 s to ~16 s.

Since [this PR of bats-core](https://github.com/bats-core/bats-core/pull/105)  was merged, tests with `bats-core` master branch started to fail (as per git bisection). This keeps us from updating the submodule and enabling parallel runs.

Specifically, there seem to be issues with the fixture and I cannot figure out the reason. Refer to [commit](https://github.com/rico-chet/bash-it/commit/e85921ccc894ff01de7dfe157f96103efd7d4ae0) and its [build](https://travis-ci.org/github/rico-chet/bash-it/jobs/673562430).

**Comment by nwinkler** [comment]
Thanks for the analysis - this looks like a great addition! I'll take a look at this when I have a moment!
