### ISSUE TITLE
Provide _completion_enabled function

### ISSUE THREAD

**Issue by nwinkler** [Bash-it/bash-it#1577]
Idea from @tswicegood in #1574: Provide a `_completion_enabled` function that allows checking for an enabled completion quickly. Need the same for aliases and plugins as well.

This needs to be added to the `helpers.bash` file, and should be used throughout that file as well.

Include unit tests when implementing the function.

**Comment by gaelicWizard** [comment]
I think this issue can be closed since we already have `_completion_exists()`, yes?

**Comment by NoahGorny** [comment]
yap
