### ISSUE TITLE
It's not an issue (anymore) but a "fix" related to font for Ubuntu under WSL2 (Windows 10)

### ISSUE THREAD

**Issue by mick-d** [Bash-it/bash-it#1585]
`bash-it` is my go to bash prompt configuration so i immediately went to set it up when configuring for the first time (Windows 10) WSL2 with Ubuntu 20.04.

However the prompt was messed up because of missing powerline symbols. For reference the solution for Ubuntu in Windows 10 Terminal App was to follow [these indications](https://www.hanselman.com/blog/HowToMakeAPrettyPromptInWindowsTerminalWithPowerlineNerdFontsCascadiaCodeWSLAndOhmyposh.aspx) which mainly consisted in downloading and installing [this font](https://github.com/microsoft/cascadia-code).

For the Ubuntu 20.04 App launched directly (i.e. not with the Windows 10 Terminal App), one has to right click on the window and click on properties to change to the above font (`Cascadia Code PL`). Somehow most symbols are rendered correctly except the `>` prompt which is an ugly square instead. No idea why since it works fine for the Terminal App.

In any case i hope this helps anyone having this issue when trying to set up `bash-it` for Ubuntu on Windows 10.

**Comment by nwinkler** [comment]
Thanks for the note! Closing this now.
