### ISSUE TITLE
cannot change locale (UTF-8)

### ISSUE THREAD

**Issue by gregoruar** [Bash-it/bash-it#1590]
Hi!
I installed bash-it on server, and it is wonderful. However a small bug persists. On each log I get this warning:
`-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory`
It seems the problem is somewhere in bash_it.sh, but i do not know there. 
the output of **locale** gives me 
`LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8`

**Comment by nwinkler** [comment]
This is weird - your settings look right. Do you only get this when logging in for the first time, or every time you hit Enter?

Do you set any of these variables in your Bash configuration (`~/.bashrc` or `~/.bash_profile`)? If so, before or after you load Bash-it?

**Comment by gregoruar** [comment]
sorry, it seems the error is not on the side of bash-it
