### ISSUE TITLE
Unable to hide DEFAULT_USER

### ISSUE THREAD

**Issue by bythckr** [Bash-it/bash-it#1597]
I am a newbie, so not sure if the issue is with bash 3.2.57(1)-release or bash-it (latest) + [Powerline](https://github.com/Bash-it/bash-it/wiki/Themes#powerline) or MacOS 10.14.6.

 I have the line to hide:
`export DEFAULT_USER="<user_name>"`

Like in the [screenshot](https://camo.githubusercontent.com/e142ebc7b54816e8335ba66991ec8fe9cbceb6af/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f726576616e732f626173682d69742f696d616765732f73637265656e73686f74732f706f7765726c696e652d626c61636b2e6a7067), its showing the username.

What is the issue? Is the theme not meant to hide the username? Or some issue with my config.

Also, my setting is in `~/.bash_profile` and not `~/.bashrc`. Is that an issue? (I am have still not understand the difference between each.)

**Comment by davidpfarrell** [comment]
Greetings,

Q: Where did you read about `DEFAULT_USER` ?  The bash-it powerline theme does not support that variable (actually the [Agnoster theme](https://github.com/Bash-it/bash-it/blob/eab3f6c469fd8fecb853d2e631a7700176cebff0/themes/agnoster/agnoster.theme.bash#L226) is the only theme that references that variable)

Powerline supports a configurable list of 'segments' ( see the [Readme](https://github.com/Bash-it/bash-it/tree/master/themes/powerline#segment-order) ).

The default configuration is for the following segments:
```
export POWERLINE_PROMPT="user_info scm python_venv ruby node cwd"
```

The `user_info` segment is the one that displays your user information.

If you do not want to display *any* user information, then you can remove that segment:
```
export POWERLINE_PROMPT="scm python_venv ruby node cwd"
```

Also, if you keep the `user_info` segment enabled, you can configure it display a custom username using:
```
export SHORT_USER="me"
```

> my setting is in `~/.bash_profile` and not `~/.bashrc`

Storing the settings in `.bash_profile` is generally correct for bash-it - Mostly you need to set the values *before*  you load the `bash-it.sh` script.

I hope that helps,

-DF

**Comment by bythckr** [comment]
> Q: Where did you read about `DEFAULT_USER` ?

I am not sure. But I just realised that when I started with Bash-it, I was interested in [agnoster theme](https://gist.github.com/agnoster/3712874), not sure how I ended up with Powerline.

I am assuming there is some issue with [agnoster theme for Bash-it](https://github.com/Bash-it/bash-it/blob/eab3f6c469fd8fecb853d2e631a7700176cebff0/themes/agnoster/agnoster.theme.bash) as its not listed now in the [wiki](https://github.com/Bash-it/bash-it/wiki/Themes).

Removing `user_info` did help. I aways kept the `user_info` and added `export SHORT_USER="me"`.

Thank you.

**Comment by nwinkler** [comment]
I guess we can close this then - thanks!
