### ISSUE TITLE
Recording feature

### ISSUE THREAD

**Issue by Mistermind2** [Bash-it/bash-it#1604]
Hello,
I bought the GameService ANE but I need to use ONLY the Recording feature.
I have a couple of question.
1. The very first line of code that I wrote is Core.init() and then the checkAvailability(), but it does not dispatch its event. Why?
Do we need to write the code described in the Initialization paragraph even if we only need to use the recording feature?
2. Do I need to include all the 8 ANEs or I can include just a subset considering that I need only the Recording feature?
3. In IOS I don't want to use the start() function to start the registration, but I want to wait for the STARTED event. How can I make appear the record controls without starting the registration?

Thank you,
Daniele

**Comment by nwinkler** [comment]
Wrong repo? Your description does not look like it's related to Bash-it...

**Comment by Mistermind2** [comment]
I'm sorry but I'm new to the forum, can you tell me where I can post my problem.
Thanks

**Comment by nwinkler** [comment]
Sorry, no idea - since I don't know which project on GitHub you're referring to.

Maybe this one? https://github.com/myflashlab/GameServices-ANE

**Comment by Mistermind2** [comment]
Thanks, I try
