### ISSUE TITLE
How do I move back to my old bash?

### ISSUE THREAD

**Issue by pajju** [Bash-it/bash-it#161]
Just asking, there is no un-installer, so How do I move back?

**Comment by JamesBarnett1993** [comment]
I have the same problem, but a backup file (~/.bash_profile.bak)  was created. How do I remove the bash_it folder and restore the backup?

**Comment by nwinkler** [comment]
Try this, it will simply move your backup file into the old location:

```
mv ~/.bash_profile ~/.bash_profile_bash_it
mv ~/.bash_profile.bak ~/.bash_profile
```

If you want to delete the Bash-it folder afterwards, run this (careful, this will delete the folder!):

```
rm -rf ~/.bash_it
```
