### ISSUE TITLE
Small problem in alias completion plugin.

### ISSUE THREAD

**Issue by charlestang** [Bash-it/bash-it#1625]
https://github.com/Bash-it/bash-it/blob/e0dba9356186954a7393363d753be37939630f85/plugins/available/alias-completion.plugin.bash#L74

I have a alias like this:
```shell
git log --graph --date=short --pretty=format:"%C(auto)%h %Cgreen%an%Creset %Cblue%cd%Creset %C(auto)%d %s"
```
It will show a concise and colorful log list of git.
Quote signs and brackets are used in this alias definition.

It will cause the syntax error in the plugin, like:
```text
-bash: /tmp/alias_completion-4451LTv9qp: line 813: syntax error near unexpected token `('
-bash: /tmp/alias_completion-4451LTv9qp: line 813: `                            prec_word="git log --graph --date=short --pretty=format:"%C(auto)%h %Cgreen%an%Creset %Cblue%cd%Creset %C(auto)%d %s""'
```

**Comment by nwinkler** [comment]
Thanks for raising this issue. It looks like we need to escape quotes before the line in question is executed, right?

**Comment by charlestang** [comment]
yes, maybe escape both of them (quotes and brackets, or sth like that cause syntax error).

**Comment by nwinkler** [comment]
Do you want to take a stab at an implementation of this? Would love to see a PR for this...
