### ISSUE TITLE
Code possibly executed unwantedly in alias completion plugin

### ISSUE THREAD

**Issue by philipp2100** [Bash-it/bash-it#1629]
Consider we have the `alias_completion` function from `plugins/available/alias-completion.plugin.bash` available,
and an alias like ```alias cleantmp='echo Removed `rm -v /tmp/uniquenameasdf* | wc -l` files.'```:

```
$ touch /tmp/uniquenameasdf42
$ alias_completion 
$ rm /tmp/uniquenameasdf42
rm: cannot remove '/tmp/uniquenameasdf42': No such file or directory
$
```

`eval` is dangerous!

**Comment by nwinkler** [comment]
Good point. Any ideas how to work around that? Should we filter out aliases that run a command in a subshell like your example above? Would that fix the issue?

**Comment by philipp2100** [comment]
Doesn't seem so:
```
alias a1="echo ); rm -v /tmp/uniquenameasdf*; somevar=("
alias a2="echo '); rm -v /tmp/uniquenameasdf*; somevar=('"
```

Also, if I understand correctly, filtering out aliases like this was the reason for using `eval` in the first place.
Unfortunately, I cannot really dive into this at the moment. I would consider either limiting the set of supported aliases rigidly or  see if `complete` can be safely used to detect nonsensical completions.

In any case, I would get rid of the `eval`s, since they turn even pretty innocent aliases like `a2` into potential issues.
