### ISSUE TITLE
using `bash-it update` with a `-y` command

### ISSUE THREAD

**Issue by georgettica** [Bash-it/bash-it#1638]
in order to upgrade bash-it constantly, I wanted a `-y` flag to allow running it with no prompt

**Comment by nwinkler** [comment]
Thanks for the note - is #1621 what you're looking for? It's not using `-y`, but `--silent` instead, similar to how the install script works.

I'm looking into merging #1621 now...

**Comment by georgettica** [comment]
Yes it is! Thanks a ton for that :)
