### ISSUE TITLE
Unusual behavioru - potentially clashing functions/aliases?

### ISSUE THREAD

**Issue by tigger04** [Bash-it/bash-it#1652]
Just trying this out for the first time. It's nice, I really like it.

A few gremlins though ..

On launch of my terminal / .bashrc etc (ignore the cheesy messaging / todos), the messages highlighted in red are new:

![image](https://user-images.githubusercontent.com/43514058/90582077-cb5e0e80-e1c4-11ea-9fe6-ea3245bb4130.png)

putting set -x at the top of .bash_profile and I can see ..
```

++++++ complete -F _rg -o bashdefault -o default rg
+++++ for i in "$compat_dir"/*
+++++ [[ task.sh != @(@(#*#|*@(~|.@(bak|orig|rej|swp|dpkg*|rpm@(orig|new|save))))|Makefile*|@(acroread.sh)) ]]
+++++ [[ -f /usr/local/etc/bash_completion.d/task.sh ]]
+++++ [[ -r /usr/local/etc/bash_completion.d/task.sh ]]
+++++ . /usr/local/etc/bash_completion.d/task.sh
++++++ taskcommand='task rc.verbose:nothing rc.confirmation:no rc.hooks:off'
+++++++ task rc.verbose:nothing rc.confirmation:no rc.hooks:off show
+++++++ cut -d. -f2
+++++++ grep --color=auto
+++++++ cut '-d ' -f1
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
++++++ _task_context_alias=
```

this temp file crops up in three places
```

++++ new_completion='complete -F __youtube_dl ytdl'
++++ echo 'complete -F __youtube_dl ytdl'
++++ read line
++++ source /var/folders/5v/r9c88zzj6fz90kvln83nz1hm0000gn/T/alias_completion-18508XXXXXX.4DY4gtpl
+++++ complete -o nospace -F _alias_completion::- -
+++++ complete -o nospace -F _alias_completion::.. ..
+++++ complete -o nospace -F _alias_completion::... ...

---

+++++ mktemp -t alias_completion-18508XXXXXX
++++ tmp_file=/var/folders/5v/r9c88zzj6fz90kvln83nz1hm0000gn/T/alias_completion-18508XXXXXX.4DY4gtpl
++++ local completion_loader

---

+++++ complete -o nospace -F _alias_completion::yt yt
+++++ complete -F __youtube_dl ytdl
++++ rm -v -f /var/folders/5v/r9c88zzj6fz90kvln83nz1hm0000gn/T/alias_completion-18508XXXXXX.4DY4gtpl
/var/folders/5v/r9c88zzj6fz90kvln83nz1hm0000gn/T/alias_completion-18508XXXXXX.4DY4gtpl
+++ '[' '!' -z '' ']'
+++ unset _bash_it_config_file
+++ unset _bash_it_config_type
```
it looks like it's recreating some of my aliases?

**Comment by tigger04** [comment]
Now here's the strangest one ...

I have a function, h () that kind of doubles as an alias. It gets overridden by the bash-it alias for history. So I was looking at the instructions for putting in custom aliases. This should do it right?

<img width="994" alt="image" src="https://user-images.githubusercontent.com/43514058/90583046-255fd380-e1c7-11ea-96c2-8401ac0214c6.png">

Sadly my function still seems to get overridden, but now, when I start a new bash session, or execute any command, vim opens!! (nvim as it happens, aliased to vi)

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/43514058/90583140-55a77200-e1c7-11ea-9ea7-dd16dc22b9d0.png">

In case this might help ..

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/43514058/90583196-8091c600-e1c7-11ea-973a-e28feeba1140.png">

**Comment by tigger04** [comment]
OK so vim opening would be explained by my $MANPAGER variable which is set to `nvim +Man!`
What i don't get it why it's getting invoked on every command (even a blank newline at the terminal), or when you do invoke it with an argument, the argument is not passed to the function

**Comment by nwinkler** [comment]
Hi, sorry for the delay - I was on vacation. Slowly working my way through the backlog now...

You might want to disable the `alias-completion` plugin if you have enabled that. It tries to figure out which completion functions to use for aliases, e.g. when you run `gco <TAB>`, it tries to run the completion for the `git checkout` command. This is really useful, but the implementation contains a call to `eval`, which can lead to strange results with aliases that invoke a function. Give that a try and see if it helps...

**Comment by NoahGorny** [comment]
@tigger04  are you still experiencing errors?

**Comment by tigger04** [comment]
Sorry I never responded, busy period at work so I had to drop the experimentation for a  while. I changed shell to fish for some time but I'm back using bash full-time again and missing the enhanced UX, so i'm going to give bash-it a try again
