### ISSUE TITLE
Show current python venv in barbuk theme

### ISSUE THREAD

**Issue by 8F3E** [Bash-it/bash-it#1660]
I really enjoy using the barbuk theme for bash-it, but feel it would be super helpful if it showed the current activated python virtual environment in the prompt.

Perhaps something can be done similar to the powerline theme? (The following is copied verbatim from `themes/powerline/powerline.base.bash`):
```bash
function __powerline_python_venv_prompt {
  set +u
  local python_venv=""

  if [[ -n "${CONDA_DEFAULT_ENV}" ]]; then
    python_venv="${CONDA_DEFAULT_ENV}"
    PYTHON_VENV_CHAR=${CONDA_PYTHON_VENV_CHAR}
  elif [[ -n "${VIRTUAL_ENV}" ]]; then
    python_venv=$(basename "${VIRTUAL_ENV}")
  fi

  [[ -n "${python_venv}" ]] && echo "${PYTHON_VENV_CHAR}${python_venv}|${PYTHON_VENV_THEME_PROMPT_COLOR}"
}
```

**Comment by nwinkler** [comment]
Closed in #1661
