### ISSUE TITLE
bash memleak

### ISSUE THREAD

**Issue by tiantaohuawei** [Bash-it/bash-it#1662]
when I using the following shell to test.This shell process will abort, using gdb debug to show the following
 
test.sh

#!/bin/bash
for(i=0,i>=0,i++)
do
         echo $i
        bash -x echo.sh
done

echo.sh
#!/bin/bash
echo ''this is test ! !"

root:~$ gdb bash test.sh
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bash...done.
"/root/test.sh" is not a core dump: File format not recognized
(gdb) set args test.sh
(gdb) r
Starting program: /root/bash test.sh
gdb: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted

bash version is 4.4
using the version 5.0 still have this issue.
root@ubuntu:~/mailline/bash/bash$ ./bash --version
GNU bash, version 4.4.0(1)-release (aarch64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by nwinkler** [comment]
I think you're trying to report an issue with the Bash shell itself - this repo is for "Bash-it" a script framework that runs in Bash.

Please open the issue on the actual Bash shell project...
