### ISSUE TITLE
Display aliases being set when toggling an alias

### ISSUE THREAD

**Issue by NoahGorny** [Bash-it/bash-it#1677]
@NoahGorny Yeah these always bug me, but assuming we ensure aliases stay conceptually grouped, the user should know what they're getting themselves into when they enable the alias group. That said, idea for the future: display aliases being set when toggling an alias (I'm sure this can be extended to plugins too).

_Originally posted by @cornfeedhobo in https://github.com/Bash-it/bash-it/pull/1675#discussion_r505139386_

**Comment by tbhaxor** [comment]
@NoahGorny could you explain with current problem?

**Comment by NoahGorny** [comment]
The problem is that when enabling a new alias file, you do not know what aliases you are getting, unless you are looking at the alias file. There should be a command ( `bash it help aliases <alias>` maybe) to help with that

**Comment by cornfeedhobo** [comment]
I love this idea. We could probably solve it with a simple `grep | sed/awk/cut/whatever` on the file being linked.

**Comment by nwinkler** [comment]
What about the existing `bash-it help aliases <component>`? Isn't that what we're looking for?

```bash
$ bash-it help aliases vim
vless=$VLESS'
v='$VIM'
vimh='${VIM} -c ":h | only'
```

Simply call this as part of enabling?

**Comment by davidpfarrell** [comment]
> What about the existing
Well TIL !  Very nice, albeit it feels a *little* like an abuse of the meta extractor :) 
Makes me think we should be having more trailing comments on the alias lines since they can indeed be exposed to the user and aid in documentation.

**Comment by nwinkler** [comment]
Great idea about the trailing comments, that would certainly help!

**Comment by NoahGorny** [comment]
It seems to me like `bash-it help aliases <alias>` is exactly the solution, we just need to improve our docs to mention it (just like we need to add a section about all of the commands)
