### ISSUE TITLE
Framework consists of many obsolete code 

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1682]
I have seen many components are not adhering to latest bash guidelines. 

Of course, I can't pinpoint all such code of my own but some files like this contain that code. Here `function` keyword should not be used.

https://github.com/Bash-it/bash-it/blob/c387517122996e1d2619c9331ae23d4ca57bc1c3/plugins/available/browser.plugin.bash#L6

Since i can't alone fix all the codebase, i am seeking help

Please see this document to know what all syntax is obsolete: https://wiki.bash-hackers.org/scripting/obsolete

**Comment by NoahGorny** [comment]
It is indeed a problem, but we have ways to improve it!
#1434 and currently #1624 are trying to solve this, by enforcing `pre-commit` hooks with `shellcheck` and `shfmt`.
This will help us to prevent insertion of such problems in the future. In the meantime, feel free to open PRs in which you fix a plugin, and step by step, the codebase will improve. We also plan on merging #1624  and enforcing the standard on each "cleaned" file

**Comment by nwinkler** [comment]
Thanks for reporting this, @tbhaxor! Closing this now, since the same ground seems to be covered by #1624 and #1678 (you'll love that one!)
