### ISSUE TITLE
In github-cli completion, use custom load order and check with complete -p

### ISSUE THREAD

**Issue by NoahGorny** [Bash-it/bash-it#1686]
Looks good.

A comment for future follow up:

If this completion could have overlap with system then it should set a custom load order and instead of testing for brew, test for the existence of the completion directly, e.g.

`complete -p ... || ...`

Originally taken from https://github.com/Bash-it/bash-it/pull/1685#pullrequestreview-513373348

**Comment by tbhaxor** [comment]
@NoahGorny is merged with master. please close this issue

![image](https://user-images.githubusercontent.com/28386721/104066130-de7e8300-5226-11eb-962e-d0c33748c2ad.png)

**Comment by NoahGorny** [comment]
I think you are confused here @tbhaxor, as you can see, the completion checks for `brew` existing instead, which is a worse solution. I will be happy if you open up a PR about it though!

**Comment by NoahGorny** [comment]
closed with #1801
