### ISSUE TITLE
terraform completion regression

### ISSUE THREAD

**Issue by pschiffe** [Bash-it/bash-it#1709]
Hello,

I've noticed this some time ago, but was lazy to report sooner. Previously, the terraform completion worked also for parameters, not sure if all of them, but for example completion worked for `-target=` in `terraform apply -target=` and now it doesn't, it works only for `apply`. I suspect that it behaves like this since https://github.com/Bash-it/bash-it/pull/1646

Could it be fixed somehow? What do you think?

cc @cornfeedhobo

**Comment by cornfeedhobo** [comment]
@pschiffe Generally speaking, we want to avoid embedding copy-written works unless absolutely necessary, and this was an easy one to tick off.

I use terraform every day and agree this change hasn't been great. The tab completion takes forever and is missing a bunch of stuff. Unfortunately, I'm still on the side of sticking with this pattern and taking up the issue with [terraform core](https://github.com/hashicorp/terraform). Now that they maintain an official tab completion, it should be given the attention.

**Comment by pschiffe** [comment]
Thanks for reporting it! For reference the issue in tf repo is https://github.com/hashicorp/terraform/issues/26856

**Comment by cornfeedhobo** [comment]
Yeah. I'm going to see if I can make time to figure out a PR. No promises! 😅

**Comment by cornfeedhobo** [comment]
I've unfortunately narrowed down the slowness to a local issue with tfenv, but that doesn't address your question. I think long term the answer is to get this fixed upstream. To that end, I'll open another issue with terraform and take a swing at a PR when I can find time. With the holidays coming up, that may be difficult to prioritize.

**Comment by pschiffe** [comment]
Thank you so much even for that :pray:
