### ISSUE TITLE
create branch with prefix

### ISSUE THREAD

**Issue by georgettica** [Bash-it/bash-it#1712]
see https://stackoverflow.com/a/36517935

I was thinking 
`alias gcobu="git checkout -b ${USER}/"`

the change should happen in: https://github.com/Bash-it/bash-it/blob/e290af4eecd335064451a2cdfb7de3e7413c4c50/aliases/available/git.aliases.bash#L64-L69

**Comment by NoahGorny** [comment]
Sounds like a great idea! would you like to open a PR for this change? I will gladly accept it into the project :smile:
