### ISSUE TITLE
Separator leftover after hiding scm on Atomic theme

### ISSUE THREAD

**Issue by egvimo** [Bash-it/bash-it#1713]
If you hide SCM on the Atomic theme there is a separator left:

![image](https://user-images.githubusercontent.com/5247100/100339429-27ada700-2fda-11eb-8794-4ef4b073ddef.png)

Is there a way to remove that?

**Comment by egvimo** [comment]
@lfelipe1501 the theme is from you, if I'm not mistaken. Can you have a look at this?

**Comment by lfelipe1501** [comment]
i'm on it

I hope to solve this problem soon....

**Comment by lfelipe1501** [comment]
Hello friends 

I resolve this issue and put the pull request to do the change

https://github.com/Bash-it/bash-it/pull/1715

only remains to wait while the admins approve the pull 

![image](https://user-images.githubusercontent.com/7816653/100361197-da283e80-2fc7-11eb-91b5-837618f110f6.png)

**Comment by cornfeedhobo** [comment]
@lfelipe1501 thanks for jumping on this so quickly!

@egvimo I'm going to close this issue since it appears to be fixed. Thanks for reporting this!
