### ISSUE TITLE
Wiki themes page does not include all themes

### ISSUE THREAD

**Issue by egvimo** [Bash-it/bash-it#1714]
In the wiki themes page is the following statement:

> Below is a list of all of the themes (with screenshots) that bash-it ships with.

Maybe it could be reformulated:

> Below is a list of **some** of the themes (with screenshots) that bash-it ships with. All themes can be taken [from here](https://github.com/Bash-it/bash-it/tree/master/themes).

Furthermore there are themes which provides an own readme file ([e.g. Atomic](https://github.com/Bash-it/bash-it/tree/master/themes/atomic)). Maybe this could be also mentioned somewhere.

**Comment by cornfeedhobo** [comment]
@egvimo Thanks for making this issue! @NoahGorny is in the process of cleaning up and improving our documentation, and they'd probably take a look at a pull request if you feel like drafting one.

Note: I think the team wants to get rid of the screenshots long term, or at least until there is a more elegant way to manage them.

**Comment by egvimo** [comment]
I tried to create a pull request before opening the issue. But if I fork the repository the wiki is empty.

I found some solutions on the internet, but they seemed to be specific for the repository mentioned there.

**Comment by NoahGorny** [comment]
Hello @egvimo !  
We are currently moving away from the wiki solution into [readthedocs](https://bash-it.readthedocs.io/en/latest/). We currently try to figure out where to place the screenshots in, I think the best idea would be [github-pages](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#:~:text=To%20publish%20a%20user%20site,github.io%20.) solution.

Happy to hear your opinion on the matter!

**Comment by egvimo** [comment]
I think the documentation and the presentation of the project should be separated and therefore Github Pages is a nice solution.

There you can have a good looking site with the screenshots as examples for the templates.

**Comment by NoahGorny** [comment]
@egvimo take a look at the page now, it now resides [here](https://bash-it.readthedocs.io/en/latest/themes-list/)  
If you have more things to say, feel free to open another issue/PR :smile:
