### ISSUE TITLE
Deprecate Docker-Machine plugin and completion

### ISSUE THREAD

**Issue by NoahGorny** [Bash-it/bash-it#1744]
Docker-Machine is deprecated, the recommendation is to move to native Docker apps on Windows/Mac. This might be a candidate for deprecation...

_Originally posted by @nwinkler in https://github.com/Bash-it/bash-it/pull/1741#discussion_r543158995_

**Comment by nwinkler** [comment]
How do we want to mark deprecated components? Just remove them, or is there some grace period during which we will still include the code but communicate to users that it will be removed soon?

**Comment by NoahGorny** [comment]
> How do we want to mark deprecated components? Just remove them, or is there some grace period during which we will still include the code but communicate to users that it will be removed soon?

I think that removing and adding a log about what happened is enough. We need to improve `bash-it version` to add an option to update to the latest `patch`, `minor` or `major`. This will allow users to have more control about the stability they want
