### ISSUE TITLE
Add a functionality to migrate the versions

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1771]
## Expected Behavior

List the version of the bashite

## Current Behavior
Update only supports migrating to the latest version, which sometime doesn't work on some desktop due to version mismatch (check the bash-it issues)

## Possible Solution

1. Do not use git for end client (rather use the zip and tarballs of release)
2. Use the command like the following
    + `bashit version` current version
    + `bashit version list` list all the versions and setting `*` on the version currently installed
    + `bashit update` should update to the most recent version
    + `bashit update <RELEASE_TAG>` the release tag to update, which is indeed the version release

## Context

Check the popular tools like rvm or nvm

**Comment by NoahGorny** [comment]
This is a fairly complicated issue, as we currently have no such packaging plan/utility. We need to discuss this and how we move forward with this

**Comment by tbhaxor** [comment]
I agree with you but I would let users to choose the specific version. 

The more freedom we give to users, the more it will be used.
