### ISSUE TITLE
github-cli binary is conflicting with aliases

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1774]
## Expected Behavior

I should be able to run `gh` command for github-cli

## Current Behavior

I am not able to run the command

![image](https://user-images.githubusercontent.com/28386721/104065638-16d19180-5226-11eb-8524-dc2622930ec8.png)

## Context
My whole development workflow is disrupted. Need immediate action on this plz

## Steps to Reproduce

_follow the steps shown in screenshot_

## Your Environment

* Bash-it version used:
* List of enabled plugins, themes and aliases (use ``bash-it show (plugins/themes/aliases)``):
* ``bash-it doctor`` output:
* Bash version:
* Operating System and version:

## Your Bash Config File

```bash
  # Your bash config file should be here
```

**Comment by NoahGorny** [comment]
Is this happening when you open up a new shell? We have a check in place if `gh` already exists before adding the alias

**Comment by tbhaxor** [comment]
> Is this happening when you open up a new shell? We have a check in place if `gh` already exists before adding the alias

Yes

**Comment by NoahGorny** [comment]
Which version of Bash-it are you using? Are you sure you did not modify it? This seems strange as we have an exact check for it.

On another thought, maybe the `gh` binary is not on your path?

**Comment by tbhaxor** [comment]
@NoahGorny I

> Which version of Bash-it are you using? Are you sure you did not modify it?

Yes, and yes

I have clone repo to another directory and working from there

**Comment by NoahGorny** [comment]
@tbhaxor please pull from the latest master, set it up and open up a terminal. Lemme know if the problem persists

**Comment by NoahGorny** [comment]
ping @tbhaxor

**Comment by tbhaxor** [comment]
It's fixed. I guess you are using `_is_binary`
