### ISSUE TITLE
capistrano completion should not create files

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1781]
https://github.com/Bash-it/bash-it/blob/c268cd9abc60efd64789d0d0d4227aaeeedeff74/completion/available/capistrano.completion.bash#L13

This completion is creating an arbitrary files might cause bugs while sourcing the enabled completions

**Comment by NoahGorny** [comment]
@tbhaxor how would you want to fix it? you can change the implementation to use a variable instead, seems like an okay choice to me

**Comment by tbhaxor** [comment]
> @tbhaxor how would you want to fix it? you can change the implementation to use a variable instead, seems like an okay choice to me

Well I was thinking the same or better it if we can `eval` it anyhow
