### ISSUE TITLE
Apple Silicon M1 Error

### ISSUE THREAD

**Issue by craldaz** [Bash-it/bash-it#1811]
When I try to install this on the Mac M1 I encounter the following error:

```
codyaldaz@Codys-Mac-mini bash-it % source ~/.bash_profile      
/Users/codyaldaz/bash-it/bash_it.sh:source:48: no such file or directory: /Users/codyaldaz/bash-it/lib/*.bash
/Users/codyaldaz/bash-it/scripts/reloader.bash:23: command not found: compgen
/Users/codyaldaz/bash-it/themes/base.theme.bash:525: command not found: _command_exists
/Users/codyaldaz/bash-it/themes/base.theme.bash:535: command not found: _command_exists
safe_append_prompt_command:3: = not found
```

Is this something that can be fixed relatively easy?

**Comment by cornfeedhobo** [comment]
@NoahGorny Despite the other issues we're going to find in this ticket, first and foremost I think it's safe to say the script should have errored before continuing on with any of the other steps.

**Comment by NoahGorny** [comment]
> When I try to install this on the Mac M1 I encounter the following error:
> 
> ```
> codyaldaz@Codys-Mac-mini bash-it % source ~/.bash_profile 
> /Users/codyaldaz/bash-it/bash_it.sh:source:48: no such file or directory: /Users/codyaldaz/bash-it/lib/*.bash
> /Users/codyaldaz/bash-it/scripts/reloader.bash:23: command not found: compgen
> /Users/codyaldaz/bash-it/themes/base.theme.bash:525: command not found: _command_exists
> /Users/codyaldaz/bash-it/themes/base.theme.bash:535: command not found: _command_exists
> safe_append_prompt_command:3: = not found
> ```
> 
> Is this something that can be fixed relatively easy?

Hey @craldaz, thanks for the report, can you please specify which version of bash is located, and how did you install bash-it?

I suspect that the bash version is weird or misconfigured, it seems like the globbing of `lib/*.bash` is failing, and it also fails to find `compgen` which comes default with bash.

**Comment by cornfeedhobo** [comment]
@craldaz I'm going to bet this is because it's actually running in `zsh`, which is the new default shell for mac.

The solution for that is:

```bash
brew install bash bash-completion
sudo sh -c 'echo "/usr/local/bin/bash" >> /etc/shells
chsh -s /usr/local/bin/bash
```

**Comment by craldaz** [comment]
That worked thanks @NoahGorny @cornfeedhobo
