### ISSUE TITLE
/usr/bin/which: no gprintf error on every bash startup if gprintf is not installed

### ISSUE THREAD

**Issue by NariyasuHeseri** [Bash-it/bash-it#1827]
SSIA
## Expected Behavior
No error message should appear

## Current Behavior
/usr/bin/which: no gprintf error on every bash startup if gprintf is not installed

## Possible Solution
The issue is caused by `[ -x "$(which gprintf)" ] && _printf_cmd=gprintf` in `vendor/github.com/erichs/composure/composure.sh` line 61.
Changing the code to something like

    ```shell
        if [ -x "$(which gprintf)" ]; then
          _printf_cmd=gprintf
        fi 2>/dev/null
    ```

fixes the issue, but I don't whether I should report this to upstream.

**Comment by cornfeedhobo** [comment]
@NariyasuHeseri Thanks for reporting this! I saw this bug yesterday but wasn't able to follow up until this morning. I'm going to reach out to erichs and make a PR upstream today. If it looks like they'll be slow to act, we might discuss reverting in the meantime. 

As for you today, if this gets too annoying, you can switch to the newest release tag until we fix this. Thanks again!

**Comment by cornfeedhobo** [comment]
@NoahGorny Sadly, I'm still seeing this today. Investigating further...
