### ISSUE TITLE
append-to-config option does not run unless --silent flag is passed

### ISSUE THREAD

**Issue by kirkmadera** [Bash-it/bash-it#1829]
Based on the fact that the append-to-config check is in an else statement, the only way to get it to run is to also pass the silent flag. This conditional needs to be reworked. The silent check should probably be separated into another conditional.

https://github.com/Bash-it/bash-it/blob/71116f785f2701a5a2cbf39420131ecd1b786bf1/install.sh#L133

**Comment by NoahGorny** [comment]
Hey @kirkmadera, thanks for the report!
#1830 tries to fix this bug,  try to use it and see if it solves your problem :smile:
