### ISSUE TITLE
Ability to Show the Active K8s Context

### ISSUE THREAD

**Issue by Xtigyro** [Bash-it/bash-it#1839]
## Expected Behavior

Ability to show the active Kubernetes context in your prompt (`$PS1`).

## Possible Solution

I can try to contribute if some general ideas are given on what needs to be modified. A good framework should be: https://github.com/jonmosco/kube-ps1

**Comment by davidpfarrell** [comment]
Greetings,

Have you seen the `k8s_context` available in the Powerline theme:
* [powerline-base.rst # segment-order](https://github.com/Bash-it/bash-it/blob/1ab755360dc1609f91e0045d3a3f9ce272644c77/docs/themes-list/powerline-base.rst#segment-order)
```
k8s_context - Show current kubernetes context
```

It utilizes a common core theme function here:
* [base.theme.bas # k8s_context_prompt](https://github.com/Bash-it/bash-it/blob/2a2741d7614a15cbde8ced0fbeaed956ae0eecec/themes/base.theme.bash#L428)
```
function k8s_context_prompt {
	echo -e "$(kubectl config current-context 2> /dev/null)"
}
```

Any theme that supports segments could probably be modified to include support of the prompt.

Which theme are you using?

BTW: All of this was discovered simply by searching the bash-it repo for `k8s`:
* https://github.com/Bash-it/bash-it/search?q=k8s

**Comment by Xtigyro** [comment]
Hey @davidpfarrell - thank you for the reply!

I haven't changed the theme - so should be using the default one (on latest stable version of `bash_it`).

BTW, I've tried this but couldn't find anything:

```bash 2021-02-15 23:25:07 ⌚  ubuntu in ~
○ → bash_it search k8s

 2021-02-15 23:25:10 ⌚  ubuntu in ~
○ → bash_it search kube
      aliases:  kubectl
  completions:  kubectl minikube

 2021-02-15 23:25:12 ⌚  ubuntu in ~
○ → bash_it search context

```

**Comment by davidpfarrell** [comment]
> BTW, I've tried this but couldn't find anything:
> 
> ```shell
> ○ → bash_it search k8s
> ```

Yeah the built-in search doesn't search themes, just aliases, completions, and plugins.


> I haven't changed the theme - so should be using the default one (on latest stable version of `bash_it`).

I *think* the default theme is `bobby` -- The [bobby](https://github.com/Bash-it/bash-it/blob/7b817f388d9b34f2bd82f92d8516b2a9c0f29bee/themes/bobby/bobby.theme.bash) theme has some configurable colors, but the segments aren't easily configurable, unfortunately. 

As a quick hack, you could try modifying your local version of the bobby theme, ie:

_${BASH_IT}/themes/bobby/bobby.theme.bash_
```
- 	PS1+="${yellow}$(ruby_version_prompt) "
+	PS1+="${yellow}$(k8s_context_prompt) "
```

You could also try switching to one of the powerline themes and test the k8s context without having to modify any bashit code.  ie. something like:

_.bash_profile_
```
- export BASH_IT_THEME='bobby'
+ export BASH_IT_THEME='powerline'

export POWERLINE_PROMPT="user_info scm k8s_context cwd"
```

**Comment by Xtigyro** [comment]
@davidpfarrell Thank you! I think the default `bobby` theme is super nice. And it'll be super nice if we can this tweak leveraged somehow.

```
PS1+="${yellow}$(k8s_context_prompt) "
```

**Comment by NoahGorny** [comment]
hey @Xtigyro 
I am closing this as I think @davidpfarrell gave here an excellent answer :smile: 

About adding this to the theme- feel free to try and open up a PR- we dont usually change the simple themes too much as we want to keep them as simple as possible, but if you want to try and change, feel free to do so :smile:
