### ISSUE TITLE
Newest preexec version disables ignorespace and ignoreboth

### ISSUE THREAD

**Issue by cornfeedhobo** [Bash-it/bash-it#1844]
## Expected Behavior

When `HISTCONTROL` is set to `ignorespace` or `ignoreboth`, I expect commands with a preceding space to not be stored in history. This is a common expectation to work around situations where it's just easiest to enter a secure string as an argument to a command, and you don't want it stored in history.

Edit: before this inspires a bunch of comments about how this is bad practice, how the secrets are leaked in `ps`, etc; none of that is relevant.  This is a behavior that the user expects to be supported and because they are unable to opt-out of our use of preexec, this should be addressed.

## Current Behavior

The updated preexec library edits `HISTCONTROL` with the [__bp_adjust_histcontrol](https://github.com/rcaloras/bash-preexec/blob/10b41c5ed8dc28fe5bb6970cb8e12e618aa5a998/bash-preexec.sh#L73-L84) function.

## Possible Solution

- Remove all references to this function
- Fork and apply a working version of [their PR](https://github.com/rcaloras/bash-preexec/pull/96) for munging history

See rcaloras/bash-preexec#115

## Steps to Reproduce
1. set HISTCONTROL
2. reload
3. type command that starts with a space
4. history 5

**Comment by cornfeedhobo** [comment]
@davidpfarrell @NoahGorny could you take a look at this?

**Comment by davidpfarrell** [comment]
I left a [comment](https://github.com/rcaloras/bash-preexec/issues/115#issuecomment-880902154) on the linked issue.

For now, I think we need to remove references to the function and claim that we don't support `$1` in pre-exec actions

**Comment by cornfeedhobo** [comment]
@davidpfarrell I'll make a PR while waiting for @NoahGorny's input. Thank you very much for reviewing this!

**Comment by cornfeedhobo** [comment]
@gaelicWizard I know you've since taken an interest in this issue. I want to finally close it out. I didn't really understand what you were trying to suggest for a solution. FWIW, I'm not looking to get into a drawn out solution, I just want something that works _now_, and can be improved later.

@NoahGorny This relates to the other issue where I brought up patching vendored libs.

The paths forward that I considered are:
- manually patch when vendoring, with the applied patch file included in our repo just for tracking
- we fork things we want to vendor and apply our patches there

Considering the overhead of multiple repos for a small use case, I'm leaning towards the first option. I look forward to reading everyone's opinions.

cc: @davidpfarrell

**Comment by gaelicWizard** [comment]
My bash-preexec#119 I think is the closest to "best of both worlds" as it allows all relying parties to get what they want in different use cases. I don't have anything to add beyond what I submitted there.
