### ISSUE TITLE
install script modifies the existing ~/.bashrc file despite giving NO response in prompt

### ISSUE THREAD

**Issue by adisakshya** [Bash-it/bash-it#1853]
## Expected Behavior
I followed the installation instruction from [installtion-docs](https://bash-it.readthedocs.io/en/latest/installation/). According to it - on executing the install script it was expected that it would automatically back up my ```~/.bash_profile``` or ```~/.bashrc```, depending on the OS.

## Current Behavior
When I run the install script it does backup the ```~/.bashrc``` file but also copies/appends the template .bashrc to ```~/.bashrc``` despite I gave **No (N)** response in the prompt ```Would you like to keep your .bashrc and append bash-it templates at the end? [y/N]```. 

I realise that there is a ```--no-modify-config``` option which actually worked for me as it didn't modify the existing ```~/.bashrc``` file. But why did the install script modified the ```~/.bashrc``` despite I gave **No (N)** response in the prompt?

## Context
I wanted to install bash-it but I didn't wanted the template .bashrc file. Instead, I have my own ```~/dotfiles/.bashrc``` file with bash-it configurations which I symlink to ```~/.bashrc```. So I was trying to automate the installation of bash-it using ```echo 'N' | ~/.bash_it/install.sh``` in my Makefile before I symlink the .bashrc file, and when the installation was complete the template .bashrc file was appended to ```~/.bashrc```. So I saw bash-it customizations right after the installation process + bash restart instead which should've happened after the symlink + bash restart.

## Steps to Reproduce
1. ```$ git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it```
2. ```$ ~/.bash_it/install.sh```
3. Answer **No (N)** in the prompt ```Would you like to keep your .bashrc and append bash-it templates at the end? [y/N]```. 
4. ```$ cat ~/.bashrc``` - you'll see the template .bashrc appended to the existing ```~/.bashrc``` or would create a new ```~/.bashrc``` with contents of the template if it didn't already exist.

## Screenshot
![Screenshot (985)](https://user-images.githubusercontent.com/45028982/111602574-7dac9180-87f9-11eb-88a1-027cff513574.png)

## Your Environment

* Bash-it version used:
```
Version type: dev
Current git SHA: 6f02b8d on 2021-03-15T23:01:43+02:00
Commit info: https://github.com/Bash-it/bash-it/commit/6f02b8d
Compare to latest: https://github.com/Bash-it/bash-it/compare/6f02b8d...master
```
* ``bash-it doctor`` output:
```
DEBUG: core: main: Loading libraries(except appearance)...
DEBUG: lib: helpers: Loading library file...
DEBUG: lib: log: Loading library file...
DEBUG: lib: preview: Loading library file...
DEBUG: lib: search: Loading library file...
DEBUG: lib: utilities: Loading library file...
DEBUG: vendor: Loading "preexec"...
DEBUG: core: reloader: Loading all enabled components...
DEBUG: aliases: general: Loading component...
DEBUG: plugin: base: Loading component...
DEBUG: completion: bash-it: Loading component...
DEBUG: completion: system: Loading component...
DEBUG: plugin: alias-completion: Loading component...
DEBUG: core: reloader: Loading "bobby" theme...
 WARN: themes: base: Command 'battery_percentage' does not exist!
DEBUG: core: main: Loading custom aliases, completion, plugins...
DEBUG: core: main: Loading general custom files...
DEBUG: custom: example: Loading custom file...
```
* Bash version: ```4.4.20(1)-release```
* Operating System and version: ```Ubuntu 18.04.5 LTS, Codename bionic```

**Comment by NoahGorny** [comment]
Hey @adisakshya, are you sure the installation actually appends to the bashrc? I could not reproduce it..
If I press `N`, the installation script correctly backups the `.bashrc` file and replaces it. When I press `y`, the scripts correctly appends to the existing config.

In any case, we improved the non interactive installation, and added many flags, try running `./install.sh --help`

Good luck :smile:

**Comment by NoahGorny** [comment]
As you noted, the correct solution here is to use to `--no-modify-config` flag, good luck!
