### ISSUE TITLE
When using bash_it, I get double notification from undistract me

### ISSUE THREAD

**Issue by vojtapolasek** [Bash-it/bash-it#1860]
I am using bash_it from Master with Undistract me utility. This utility uses preexec and probably also precmd function to announce finishing of long running command.
https://github.com/jml/undistract-me
Note, I have just noticed you have a new plugin cmd-returned-notify... do you plan to enhance it in future?

## Expected Behavior
The notification from undistract me appears once.

## Current Behavior
After some update (not sure which commit), the notification works, but appears twice. And it also notifies when for example I just run "cd" after longer time.
I guess some problem with preexec function.

## Steps to Reproduce

1. Install bash_it. Enable powerline theme.
2. Enable undistract me
3. Run "sleep 12"
4. You will receive double notification.

## Your Environment

* Bash-it version used: latest from master
* List of enabled plugins, themes and aliases (use ``bash-it show (plugins/themes/aliases)``):
* plugins: thefuck, ssh, powerline, git, explain, base

* ``bash-it doctor`` output:
* DEBUG: core: main: Loading libraries(except appearance)...
DEBUG: lib: helpers: Loading library file...
DEBUG: lib: log: Loading library file...
DEBUG: lib: preview: Loading library file...
DEBUG: lib: search: Loading library file...
DEBUG: lib: utilities: Loading library file...
DEBUG: vendor: Loading "preexec"...
DEBUG: core: reloader: Loading all enabled components...
DEBUG: aliases: general: Loading component...
DEBUG: aliases: git: Loading component...
DEBUG: aliases: systemd: Loading component...
DEBUG: plugin: base: Loading component...
DEBUG: plugin: battery: Loading component...
DEBUG: plugin: browser: Loading component...
DEBUG: plugin: explain: Loading component...
DEBUG: plugin: git: Loading component...
DEBUG: plugin: powerline: Loading component...
DEBUG: plugin: ssh: Loading component...
DEBUG: plugin: thefuck: Loading component...
DEBUG: completion: bash-it: Loading component...
DEBUG: completion: system: Loading component...
DEBUG: plugin: alias-completion: Loading component...
DEBUG: core: reloader: Loading "powerline-multiline" theme...
DEBUG: core: main: Loading custom aliases, completion, plugins...
DEBUG: core: main: Loading general custom files...
DEBUG: custom: example: Loading custom file...

* Bash version:   GNU bash, verze 5.0.17(1)-release (x86_64-redhat-linux-gnu)
* Operating System and version: Fedora 33

## Your Bash Config File

```bash
  # Your bash config file should be here
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
#tmux
if which tmux >/dev/null 2>&1; then
    #if not inside a tmux session, and if no session is started, start a new session
    test -z "$TMUX" && (tmux attach || tmux new-session)
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

source ~/.bash_aliases
export EDITOR=/usr/bin/nano
eval $(keychain --eval --quiet id_rsa)
# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

#undistract me
export IGNORE_WINDOW_CHECK=1
export UDM_PLAY_SOUND=1
export LONG_RUNNING_IGNORE_LIST="ssh nano sftp leafpad firefox"
#[[ -f /usr/share/undistract-me/undistract-me.sh ]] && source /usr/share/undistract-me/undistract-me.sh


# Path to the bash it configuration
export BASH_IT="/home/vojta/.bash_it"

# Lock and Load a custom theme file.
# Leave empty to disable theming.
# location /.bash_it/themes/
export BASH_IT_THEME='powerline-multiline'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
#export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
#export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
#export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
 export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1

# Load Bash It
source "$BASH_IT"/bash_it.sh


# url decoding
urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }



```

**Comment by vojtapolasek** [comment]
Cool, I thought it will be problem with preexec. I will gladly update the plugin, it actually seems to do what I want. How are plugins configured? I would like to modify it so that it could play a sound file instead of bell... Should I use environment variables to get configuration options for bashit plugins? Any documentation on this?

**Comment by NoahGorny** [comment]
Hey @vojtapolasek, thanks for your commitment and willingness to work on this :smile: 
Sadly, there is no standardised way to define environment variables in Bash-it..

You can use them however, and we do this anyway with many themes. I think that we should just put all of the relevant information in the docs, maybe in a new section that will be called `plugin configurations`.

You can see [powerline docs](https://github.com/Bash-it/bash-it/blob/master/docs/themes-list/powerline-base.rst) for reference on how to document env variables and such.

In any case- your idea sounds really great! Let me know if you need any more help :smiley:

**Comment by davidpfarrell** [comment]
HI all !

I peeked at the undistract me code and man the `"notify user"` logic is a mess.

Might I suggest we use a simpler approach, treating the notify action as a configurable command to execute, but defaulting to the BEL sound ... something like:
```bash
precmd_return_notification() {
        # Allow user to override alert action, defaulting to BEL
        local ALERT=(${CMD_RETURNED_NOTIFY_ACTION:-echo -e \\a})
	export LAST_COMMAND_DURATION=$(($(date +%s) - ${LAST_COMMAND_TIME:=$(date +%s)}))
	[[ ${LAST_COMMAND_DURATION} -gt ${NOTIFY_IF_COMMAND_RETURNS_AFTER:-5} ]] && "${ALERT[@]}"
	export LAST_COMMAND_TIME=
}
```

With this, the user can configure *any* action they like, and our plugin is not responsible knowing how to play audio files, or flash the window, etc ...

BTW: This code was tested locally and appears to work as expected.
