### ISSUE TITLE
When installing an error is given

### ISSUE THREAD

**Issue by jchanam** [Bash-it/bash-it#1861]
## Expected Behavior

The installation should happen without any issue

## Current Behavior

When running the installation, an error is given:
`install.sh: line 174: "2" - 1: syntax error: operand expected (error token is ""2" - 1")`

## Steps to Reproduce

1. git clone --depth=1 https://github.com/Bash-it/bash-it.git
2. cd bash-it
3. ./install.sh

## Your Environment

* Bash-it version used: master branch
* Bash version: 4.2.46
* Operating System and version: Amazon Linux 2

## Your Bash Config File

```bash
  # Your bash config file should be here
```

**Comment by NoahGorny** [comment]
Hey @jchanam , I opened a PR that should fix this- let me know if this works as expected :smile:
