### ISSUE TITLE
zork error when in git repo

### ISSUE THREAD

**Issue by daniejstriata** [Bash-it/bash-it#1867]
Xork looks great but when I go into a git repo I get an error after each command being run.

![image](https://user-images.githubusercontent.com/13314239/114701355-ff251000-9d22-11eb-8dc1-0fbb81a35699.png)
```
-bash: 1m]±[e[0m]master: command not found
-bash: 1m]✗[e[0m]: command not found

```
## Expected Behavior
There should be no errors

## Current Behavior
There are errors printed after each command being run while in a git repo.

## Your Environment

* Bash-it version used: 2.1.3
* List of enabled plugins, themes and aliases (use ``bash-it show (plugins/themes/aliases)``):

> plugins

1. alias-completion
2. base
> aliases
1. general

* ``bash-it doctor`` output:
└─▪ bash-it doctor
DEBUG: core: main: Loading libraries(except appearance)...
DEBUG: lib: helpers: Loading library file...
DEBUG: lib: log: Loading library file...
DEBUG: lib: preview: Loading library file...
DEBUG: lib: search: Loading library file...
DEBUG: lib: utilities: Loading library file...
DEBUG: vendor: Loading "preexec"...
DEBUG: core: reloader: Loading all enabled components...
DEBUG: aliases: general: Loading component...
DEBUG: plugin: base: Loading component...
DEBUG: completion: bash-it: Loading component...
DEBUG: completion: system: Loading component...
DEBUG: plugin: alias-completion: Loading component...
DEBUG: core: reloader: Loading "zork" theme...
 WARN: themes: base: Command 'battery_percentage' does not exist!
DEBUG: core: main: Loading custom aliases, completion, plugins...
DEBUG: core: main: Loading general custom files...
DEBUG: custom: example: Loading custom file...
-bash: 1m]±[e[0m]master: command not found
-bash: 1m]✗[e[0m]: command not found

* Bash version:
bash-4.4.19-12.el8.x86_64
* Operating System and version:
Cenots 8

**Comment by NoahGorny** [comment]
I could not reproduce this error, are you sure this is happening, even if you open a new terminal/ use `bash-it restart`?

**Comment by daniejstriata** [comment]
I see. That's what I did wrong. Sorry. Closing...

**Comment by NoahGorny** [comment]
Thats alright @daniejstriata, thanks for reporting and being invested in Bash-it :smile:
