### ISSUE TITLE
nwinkler theme - slight improvement to displayed text

### ISSUE THREAD

**Issue by daniejstriata** [Bash-it/bash-it#1868]
The open bracket is not coloured the same as the closing bracket for the time entry.

![image](https://user-images.githubusercontent.com/13314239/114702358-4364e000-9d24-11eb-95a9-c01c87c4af56.png)

When I logged out and back in the time was not coloured.
![image](https://user-images.githubusercontent.com/13314239/114702878-e9b0e580-9d24-11eb-826f-0d957c4c789e.png)

## Your Environment

* Bash-it version used: 2.1.3
* List of enabled plugins, themes and aliases (use ``bash-it show (plugins/themes/aliases)``):
* ``bash-it doctor`` output:
→ bash-it doctor
DEBUG: core: main: Loading libraries(except appearance)...
DEBUG: lib: helpers: Loading library file...
DEBUG: lib: log: Loading library file...
DEBUG: lib: preview: Loading library file...
DEBUG: lib: search: Loading library file...
DEBUG: lib: utilities: Loading library file...
DEBUG: vendor: Loading "preexec"...
DEBUG: core: reloader: Loading all enabled components...
DEBUG: aliases: general: Loading component...
DEBUG: plugin: base: Loading component...
DEBUG: completion: bash-it: Loading component...
DEBUG: completion: system: Loading component...
DEBUG: plugin: alias-completion: Loading component...
DEBUG: core: reloader: Loading "nwinkler" theme...
 WARN: themes: base: Command 'battery_percentage' does not exist!
DEBUG: core: main: Loading custom aliases, completion, plugins...
DEBUG: core: main: Loading general custom files...
DEBUG: custom: example: Loading custom file...
* Bash version:
bash-4.2.46-34.el7.x86_64
* Operating System and version:
Centos 7

**Comment by daniejstriata** [comment]
It seems the themes got confused as nwinkler does not print the full date as my first example. Looking for the actual theme that was printed first.

**Comment by daniejstriata** [comment]
Peculiar. I cannot find the theme that was printing in the first screenshot. I don't see any that prints the full date like that.

**Comment by daniejstriata** [comment]
I see what is happening. When you bash-it reload to activate a new theme it does seem to mix 'n match. See what happened here moving from tonka to nwinkler :
![image](https://user-images.githubusercontent.com/13314239/114705343-ebc87380-9d27-11eb-8a00-b382ac324553.png)
then I run bash-it restart
![image](https://user-images.githubusercontent.com/13314239/114705405-000c7080-9d28-11eb-8041-f38b12aa8252.png)

**Comment by NoahGorny** [comment]
Howdy @daniejstriata!
Indeed, you cannot use `bash-it reload` to change your theme, and you need to use `bash-it restart`, or open a new terminal. We can try to mitigate this by improving the documentation about it, so it will be more understandable which command is suitable for what.

Thanks for your efforts here!

**Comment by daniejstriata** [comment]
But I'd think that `source .bashrc` would do the same as `bash-it restart`?

**Comment by NoahGorny** [comment]
> But I'd think that `source .bashrc` would do the same as `bash-it restart`? IS this more an issue with bash itself?

If you will closely inspect the source, you can see how we do this: https://github.com/Bash-it/bash-it/blob/58f2240789bdf2819e6466a09ac1285acd4b3f2e/lib/helpers.bash#L424-L439

We actually `exec` bash, so we fully restarts it. Only sourcing the file is what `bash-it reload` is doing:
https://github.com/Bash-it/bash-it/blob/58f2240789bdf2819e6466a09ac1285acd4b3f2e/lib/helpers.bash#L441-L457

Because the themes sometimes set variables that the other themes do not set, only reload (by sourcing the profile) is not enough. The cleanest way to do it is by re-running bash.

I hope this is making sense, but it will also make a nice addition to the docs actually :smile:

**Comment by daniejstriata** [comment]
That's a good tip for future me to remember. Thank you!
