### ISSUE TITLE
What is the correct way to update bash-it without losing my setup?

### ISSUE THREAD

**Issue by mcarans** [Bash-it/bash-it#1889]
When I ran `bash-it update stable`, I got:

```
Would you like to update to v2.1.3(ebe59c9)? [Y/n] Y
Error updating Bash-it, please, check if your Bash-it installation folder (/home/mcarans/.bash_it) is clean.
```

Presumably if I empty the .bash_it folder, all my settings will disappear?

How do I update and keep my settings?

Sorry if it's obvious, but I looked here: https://bash-it.readthedocs.io/en/latest/commands/update/#update and it didn't talk about this.

**Comment by davidpfarrell** [comment]
Hi @mcarans ,

Q: Do you have any local changes in your bash-it functions/plugins/completions/themes etc?

ie. what does this produce?
```
$ cd ~/.bash_it
$ git status
```

The bash-it code hides the git output during the update, so there might be some error(s) going unseen.
Here's the effective git action being done, which you can try manually:
```
$ cd ~/.bash_it
$ git checkout v2.1.3
```
Please let us know what message(s) are generated by these and we can go from there,

Thanks!

**Comment by mcarans** [comment]
Thanks, I had local changes in the bash history plugin for substring history which I reverted (history-substring-search-backward in plugins/available/history.plugin.bash). I notice that the new file has changed significantly.

Update worked fine after that. Thanks a lot @davidpfarrell . I'd suggest putting the debugging steps you mention above in the docs here: https://bash-it.readthedocs.io/en/latest/commands/update/#update.

**Comment by tbhaxor** [comment]
@davidpfarrell We should stash the local changes. 

https://github.com/Bash-it/bash-it/blob/8c47706139ec5928d940732e51725b200db1820b/lib/helpers.bash#L288

This line should be like this

```diff
+ git stash
 _bash-it_pull_and_update_inner $TARGET $version
+ git stash pop
```

**Comment by mcarans** [comment]
@tbhaxor It would be good for some instructions to be printed about what to do in the event of a merge conflict (as would have happened in this case given the file had changed significantly).

**Comment by tbhaxor** [comment]
@mcarans We can print the information about uncommitted files and prompt user whether to stash and update or not.

@NoahGorny Can I do this?

**Comment by NoahGorny** [comment]
> @mcarans We can print the information about uncommitted files and prompt user whether to stash and update or not.
> 
> @NoahGorny Can I do this?

I like the idea of displaying information about uncommited changes. I am not sure that stashing them is the correct solution, as this can cause merge conflicts and I dont want users to have to solve stuff every time they update..

If you could just provide the information, abort the update and tell them to commit and save their changes that would be a great PR in my opinion

**Comment by tbhaxor** [comment]
> this can cause merge conflicts

I have tried it out in a local dev environment. 

Prompt is not working and correctly, git stash pop was declined due to merge conflicts. 

@NoahGorny What we can do is show the files modified and exit with a message "Clean the unstaged changed in  bash_it directory before upgrading to avoid merge conflicts"

To show the files we can use `git diff --name-status`
