### ISSUE TITLE
Git alias takes precedence over GitHub CLI of the same name

### ISSUE THREAD

**Issue by zzhengnan** [Bash-it/bash-it#1893]
## Expected Behavior

When git aliases are enabled, the `gh` alias does _not_ take precedence over the [GitHub CLI](https://cli.github.com/), which is invoked by the same name.

## Current Behavior

`gh` currently invokes the git alias, not the GitHub CLI.
https://github.com/Bash-it/bash-it/blob/e06066c36768ac08a31927646a150a6e66badbfc/aliases/available/git.aliases.bash#L89-L91

## Possible Solution

A few possibilities that might have caused the bug
1. The `_command_exists` function
2. Whether git aliases are enabled _before_ or _after_ the GitHub CLI has been installed. In my case, I enabled the aliases before installing the CLI. Perhaps if I flip the order, the bug will go away

## Context

In my view, when an alias happens to have the exact same name as a command line program, priority should be given to the program. This goes beyond just the GitHub CLI.

## Steps to Reproduce

1. `bash-it enable alias git`
2. `brew install gh`
3. `gh --help`: Instead of seeing the help message for the GitHub CLI, I see nothing

## Your Environment

<details><summary>Bash-it version used</summary>

```
Version type: dev
Current git SHA: 6093ecb on 2021-02-26T10:17:01+02:00
Commit info: https://github.com/Bash-it/bash-it/commit/6093ecb
Compare to latest: https://github.com/Bash-it/bash-it/compare/6093ecb...master
```

</details>

<details><summary>List of enabled plugins, themes and aliases</summary>

- Plugins: `alias-completion`, `base`
- Themes: `bobby-python`
- Aliases: `git`

</details>

<details><summary>bash-it doctor</summary>

```
DEBUG: core: main: Loading libraries(except appearance)...
DEBUG: lib: helpers: Loading library file...
DEBUG: lib: log: Loading library file...
DEBUG: lib: preview: Loading library file...
DEBUG: lib: search: Loading library file...
DEBUG: lib: utilities: Loading library file...
DEBUG: vendor: Loading "preexec"...
DEBUG: core: reloader: Loading all enabled components...
DEBUG: aliases: git: Loading component...
DEBUG: plugin: base: Loading component...
DEBUG: completion: bash-it: Loading component...
DEBUG: completion: system: Loading component...
DEBUG: plugin: alias-completion: Loading component...
DEBUG: core: reloader: Loading "bobby-python" theme...
 WARN: themes: base: Command 'battery_percentage' does not exist!
DEBUG: core: main: Loading custom aliases, completion, plugins...
DEBUG: core: main: Loading general custom files...
DEBUG: custom: example: Loading custom file...
```

</details>

<details><summary>Bash version</summary>

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

</details>

<details><summary>Operating System and version</summary>

macOS Catalina 10.15.7

</details>

## Your Bash Config File

<details><summary>.bash_profile</summary>

```bash
#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

export BASH_IT="/Users/zhengnan/.bash_it"
export BASH_IT_THEME='bobby-python'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1

# Load Bash It
source "$BASH_IT"/bash_it.sh
```

</details>

**Comment by NoahGorny** [comment]
If you restart your shell using `bash-it reload` or `bash-it restart`, does the problem persists?
I usually recommend to reload your shell after installing stuff as a good practice.

**Comment by davidpfarrell** [comment]
Hi all,

in the example above:

```
bash-it enable alias git
brew install gh
gh --help: Instead of seeing the help message for the GitHub CLI, I see nothing
```

This is guaranteed not to work since the alias was created *before* installing the binary, BUT within the same bash session.

Once you reload bashit / your terminal session, you should see the expected behavior.

Can you confirm by starting a fresh terminal session and dong `type gh` ?

**Comment by zzhengnan** [comment]
Thanks both. Unfortunately, I'm unable to try any of your suggestions because strangely I can no longer reproduce the _original issue_ I reported. 

Here's what I did
1. Comment out the following code https://github.com/Bash-it/bash-it/blob/e06066c36768ac08a31927646a150a6e66badbfc/aliases/available/git.aliases.bash#L89-L91
2. Start a new Bash session and run `gh` -> GitHub CLI is invoked, as expected
3. Uncomment the code above
4. Repeat step 2 -> GitHub CLI is _still_ invoked; the `gh` git alias no longer appears to be "masking" the GitHub CLI

Any theories as to why this is happening?

**Comment by zzhengnan** [comment]
I tried the suggested fix on a _different_ laptop where I'm also experiencing this issue -- running `bash-it reload` doesn't fix the problem.

Interestingly though, on this laptop I don't see the behavior described in my last comment. That is,
- If I comment out the code, `gh` invokes the GitHub CLI
- If I then uncomment the code, `gh` invokes the git alias

The setup on this laptop is slightly different. The diff (as compared against those in the original post) is pasted below

<details><summary>Bash-it version</summary>

```diff
-Version type: dev
-Current git SHA: 6093ecb on 2021-02-26T10:17:01+02:00
-Commit info: https://github.com/Bash-it/bash-it/commit/6093ecb
-Compare to latest: https://github.com/Bash-it/bash-it/compare/6093ecb...master
+Current git SHA: 8a8a901 on 2020-10-02T10:40:45+02:00
+https://github.com/Bash-it/bash-it/commit/8a8a901
+Compare to latest: https://github.com/Bash-it/bash-it/compare/8a8a901...master
```

</details>

<details><summary>Enabled aliases</summary>

```diff
git
+general
```

</details>

<details><summary>bash-it doctor</summary>

```diff
 DEBUG: core: main: Loading libraries(except appearance)...
+DEBUG: lib: composure: Loading library file...
 DEBUG: lib: helpers: Loading library file...
+DEBUG: lib: history: Loading library file...
 DEBUG: lib: log: Loading library file...
+DEBUG: lib: preexec: Loading library file...
 DEBUG: lib: preview: Loading library file...
 DEBUG: lib: search: Loading library file...
 DEBUG: lib: utilities: Loading library file...
-DEBUG: vendor: Loading "preexec"...
 DEBUG: core: reloader: Loading all enabled components...
+DEBUG: aliases: general: Loading component...
 DEBUG: aliases: git: Loading component...
 DEBUG: plugin: base: Loading component...
 DEBUG: completion: bash-it: Loading component...
+DEBUG: completion: git: Loading component...
+ WARN: completion: git: completion already loaded - this usually means it is safe to stop using this completion
 DEBUG: completion: system: Loading component...
 DEBUG: plugin: alias-completion: Loading component...
 DEBUG: core: reloader: Loading "bobby-python" theme...
```

</details>

<details><summary>.bash_profile</summary>

```diff
-#!/usr/bin/env bash

-# If not running interactively, don't do anything
-case $- in
-  *i*) ;;
-    *) return;;
-esac
```

</details>
