### ISSUE TITLE
Git Push does nothing

### ISSUE THREAD

**Issue by MariyaBukh** [Bash-it/bash-it#1896]
I had to reset my computer after I got it back up and running git push no longer actually pushes anything, I can get 
## Expected Behavior

I should be able to push my files up to my gitHub
## Current Behavior

After I submit a git push request the system sits and does nothing, I tried forcing it and that does nothing either.
## Context

I am working on a project as an expo for my job and I need to be able to push it 3 days ago and it deleted everything I did in VisualStudio.

I need to get my files pushed 
![git config](https://user-images.githubusercontent.com/85184644/122004309-401cbd80-cd82-11eb-9485-838a1a001cdc.png)
![GItPushAndErrorMessage](https://user-images.githubusercontent.com/85184644/122004313-40b55400-cd82-11eb-9902-358cd6bc7272.png)
![myBranchesGit](https://user-images.githubusercontent.com/85184644/122004314-40b55400-cd82-11eb-9163-9a542c316c78.png)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Bash-it version used:
* List of e
[BashErr.log](https://github.com/Bash-it/bash-it/files/6653369/BashErr.log)
![SSHErrorpng](https://user-images.githubusercontent.com/85184644/122004683-b6b9bb00-cd82-11eb-98a7-f7362f0e24d2.png)

nabled plugins, themes and aliases (use ``bash-it show (plugins/themes/aliases)``):
* ``bash-it doctor`` output:
* Bash version:
* Operating System and version:

## Your Bash Config File

```bash
  # Your bash config file should be here
```

**Comment by NoahGorny** [comment]
Hi @MariyaBukh 
This issue does not seem related to Bash-it. What is your setup? What program do you use in order to execute `git push`?
The supplied screenshot does not make things more clear sadly, so please provide another one if the problem persists :smile:

**Comment by NoahGorny** [comment]
closing due to no response
