### ISSUE TITLE
How to Crash a Terminal with a Print Command

### ISSUE THREAD

**Issue by alephpt** [Bash-it/bash-it#1905]
If you run `export VAR="\x1b[1A  + \x1b[2K"`
And then run `printf $VAR && exec printf $VAR`
It will crash the terminal/connection on any Linux terminal.

Thought I should share this fun fact. I am curious what is happening under the hood that makes this "Up One Line && Delete" crash the whole terminal if anyone can explain it?

Cheers

**Comment by NoahGorny** [comment]
what happens here is that you `exec` inside the shell- which replaces the shell process with the `printf` one- so it closes the shell instantly. the `VAR` variable does not matter, and the first printf does not terminate the shell.

However- this is not the correct place for fun facts like this- you can go to our [chat](https://web.libera.chat/?channel=#bash-it) for this!

**Comment by alephpt** [comment]
didn't realize this was a simple error on my part, and that it wasn't a bash (or more specifically a bash-it) issue. My apologies!

**Comment by NoahGorny** [comment]
No worries, feel free to always ask questions and open issues :smile:
