### ISSUE TITLE
Huge delay between commands

### ISSUE THREAD

**Issue by Erythros** [Bash-it/bash-it#1919]
First timer to bash-it. There's one issue I couldn't find a solution for.
I open the terminal, run a command - any command - like `ls`, I get the results instantly, but then I have to wait ~5 - 10 seconds until the next "entry" line where I type a new command shows up.

At first, I thought there's a delay set on purpose, but I couldn't find anything related to it in the documents.

As soon as I install, my terminal is back to "normal" where within one second of typing `ls` I get my results and the possibility to type the next command.

All settings are default and I'm using Windows-Terminal. 
Everything else is default, as I just got a new laptop and didn't get the chance to install much else.

**Comment by davidpfarrell** [comment]
Hi @Erythros  - Quick question : Do you have a bash-it theme enabled?  If so which one?

**Comment by Erythros** [comment]
> Hi @Erythros - Quick question : Do you have a bash-it theme enabled? If so which one?

Just the default one.
```
○ → echo $BASH_IT_THEME
bobby
```

**Comment by NoahGorny** [comment]
Whats up @Erythros?
Does the slowness usually occur when you are inside a git repository, or just in any folders?
If it is really about git- there are multiple solutions specified in [our docs](https://bash-it.readthedocs.io/en/latest/vcs_user/?highlight=slow#prompt-version-control-information)

If it just happens and not related to git. I would be happy if you could provide me with the output of running the `bash-it doctor` command. Please pay attention into which steps takes the longest and seems to be slowing down the prompt

Hope to hear back from you soon :smile:

**Comment by hackhowtofaq** [comment]
Same problem but with export BASH_IT_THEME='brainy' theme.

When I commented that line, everything back to normal.
