### ISSUE TITLE
set -u in the tests

### ISSUE THREAD

**Issue by NoahGorny** [Bash-it/bash-it#1923]
We should add `set -u` to the tests, and fix all of the problems that arise, especially from vendored ones, that we can fix upstream (see #1903 for reference)

**Comment by gaelicWizard** [comment]
I recently found what's being called "[unofficial strict mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/)" for Bash and I'd like to suggest we work toward testing with that!
