### ISSUE TITLE
Question: how many PRs is too many?

### ISSUE THREAD

**Issue by gaelicWizard** [Bash-it/bash-it#1929]
I have a *pile* of minor improvements to lots of plugins. Should I open a *separate* PR for each and every one? Is it OK if I do one or a few PRs with several commits each?

**Comment by NoahGorny** [comment]
There is no such thing as too many PRs!

I think its completely okay to open up a large number of PRs. We will look at them one by one and merge them :smile: 

Thanks you for contributing so much! you rock!

**Comment by gaelicWizard** [comment]
I think I may alsö add `shellcheck` on these when I submit them. That way it will be less weird to submit such a small PR. My brain makes things difficult for me sometimes 🙃

**Comment by cornfeedhobo** [comment]
@gaelicWizard Yes, please open a separate PR for each change. If you can logically group them some way, either by component changed or by pattern updated, that would be great.

> I think I may alsö add shellcheck on these when I submit them. That way it will be less weird to submit such a small PR.

We actually prefer small PRs. In fact, I'd ask that you please split up functional changes from formatting changes. If you want to mix them into the same PR, please split them up into different commits.

Thanks for your contributions!!

**Comment by gaelicWizard** [comment]
Incoming!
