### ISSUE TITLE
Why does `_command_exists` print a warning?

### ISSUE THREAD

**Issue by gaelicWizard** [Bash-it/bash-it#1937]
It seems like whether a command exists or not is the express purpose of the function, so when a command does not exist then that would not be any kind of error. That's literally the question that the function is being asked to answer, to which the answer may be yes or no. If the answer is no, then...that's the answer. Ń̥o҉̙̻̖̲̮͓̩̀t̵̬̳͔ḩ̡̪͇͈i̼̦̮̙͝n̸̸̲̲͍̟g͏̭͖̠̩̭ is *wrong* that the answer is no (as far as the function is C̳̞͡o̷̪̫n҉̧͇̩̦ͅc͢͏͕͖͓̰͉̭̜̣̤e̬͖̯̮r̶̭̜̯͉n̰͈e̛̹͈̳̖̕d̨̯̲͔̼͙͟, but the caller may then handle the result and issue a warning if appropriate).

Related question: why is there a `command_exists` function in the `base` plugin? It appears functionally identical (but without the warning)?

**Comment by NoahGorny** [comment]
Logging is only used when debugging problems with bash-it, so we prefer that it will be from a centralised location. We maybe should change it into a debug message, but I find it very useful to know what's going on and whats missing.
About the `command_exists` in the `base` plugin- yes, its a mess..
I think that removing it from `base` would be the best solution. I would also accept changing `_command_exists` warning log into debug one (its much easier to change as its a main utility that everyone should use!)
