### ISSUE TITLE
Show anaconda environment in bash it

### ISSUE THREAD

**Issue by willhama** [Bash-it/bash-it#1972]
I would like to see my active anaconda environment, when I activate it. After the installation of "bash-it" it is not visible anymore.

## Expected Behavior
My bash should show something like:
(my-activated-conda-environment) $ _

## Current Behavior
Now it doesn't show anything

## Possible Solution
I thinks there must be a flag set within the .bashrc but not sure how

## Context
It is really annoying when you install things in the wrong environment.

**Comment by NoahGorny** [comment]
Seems like a nice feature to add into bash-it. PRs are welcome on this :smile: 

`base.theme.bash` would be a place where this will fit.

**Comment by NoahGorny** [comment]
you are very correct @davidpfarrell, wow.
I searched for `anaconda` instead.. funny me.

In any case @Man7hano, there are a bunch of themes that support conda from what I am seeing now- so feel free to use any one of them (powerline,modern,gitline are some examples)
