### ISSUE TITLE
possible search bug

### ISSUE THREAD

**Issue by cornfeedhobo** [Bash-it/bash-it#1978]
## Expected Behavior

```bash
$ bash-it search history
      plugins:  history history-search history-substring-search percol
```

## Current Behavior

```bash
$ bash-it search history
      plugins:  history history-search percol
```

## Context

was checking what plugins are enabled using the `search` subcommand, and not all the history plugins were listed. clearly a bug.

## Steps to Reproduce

1. `bash-it search history`
2. cry

**Comment by gaelicWizard** [comment]
The list is generated based on which components have a description, which is grep'd for `'    \['`...but history-substring-search is too long for the first column and pushes the line out in `_bash-it-describe()`.
