### ISSUE TITLE
Provide dotnet/mono completions

### ISSUE THREAD

**Issue by EmilySeville7cfg** [Bash-it/bash-it#1983]
Please assign this issue to me, I want create completions myself. ;)

**Comment by davidpfarrell** [comment]
Hi @EmilySeville7cfg - You are definitely welcome to work on this !

Q: Are you thinking of something along the lines of integrating this:
* https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete#bash

If so, then some research shows that we can actually vendor it from here:
* https://github.com/dotnet/sdk/blob/main/scripts/register-completions.bash

If you had something else mind, let us know and we can discuss a plan

Thanks!

-DF

**Comment by EmilySeville7cfg** [comment]
@davidpfarrell, I think I try first `dotnet complete` and then if I don't like it I rewrite via custom completion. ;)
