### ISSUE TITLE
Is it a good idea to propose any preferred code style to this project?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [Bash-it/bash-it#2045]
I think that code must be readable and easily editable by developers. ;) I am asking because some developers rejects enforcing code styles.

For instance we could describe how better format code, what options (short, old, long) prefer, how make code compatible with previous Bash versions, and any other things

**Comment by EmilySeville7cfg** [comment]
Sorry, I found code style guide. ;)

**Comment by gaelicWizard** [comment]
We use `shfmt` to enforce code style. I've been working to actually apply it to the files here, but it's slow going. For the settings we use, look in `$BASH_IT/.EditorConfig`.
