### ISSUE TITLE
Enable autojump and direnv (and maybe others) plugins will result in wrong PROMPT_COMMAND syntax

### ISSUE THREAD

**Issue by roytseng-tw** [Bash-it/bash-it#2070]
## Expected Behavior

Work without error.

## Current Behavior

```shell
bash: PROMPT_COMMAND: line 3: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 3: `_direnv_hook; ; autojump_add_to_database'
```

## Possible Solution

Change in vendor/github.com/rcaloras/bash-preexec/bash-preexec.sh:__bp_install()
from 
`existing_prompt_command="${PROMPT_COMMAND//$__bp_install_string[;$'\n']}" # Edge case of appending to PROMPT_COMMAND`
to
`existing_prompt_command="${PROMPT_COMMAND//$__bp_install_string+([;$ '\n'])}" # Edge case of appending to PROMPT_COMMAND`

## Context

The value $PROMPT_COMMAND:
```
# before load autojump
__bp_trap_string="$(trap -p DEBUG)" trap - DEBUG __bp_install
# after load autojump
__bp_trap_string="$(trap -p DEBUG)" trap - DEBUG __bp_install ; autojump_add_to_database

# before load direnv
__bp_trap_string="$(trap -p DEBUG)" trap - DEBUG __bp_install ; autojump_add_to_database
# after load direnv
_direnv_hook;__bp_trap_string="$(trap -p DEBUG)" trap - DEBUG __bp_install ; autojump_add_to_database
```

In vendor/github.com/rcaloras/bash-preexec/bash-preexec.sh
```
    local existing_prompt_command
    # Remove setting our trap install string and sanitize the existing prompt command string
    existing_prompt_command="${PROMPT_COMMAND//$__bp_install_string[;$'\n']}" # Edge case of appending to PROMPT_COMMAND
    # _direnv_hook;__bp_trap_string="$(trap -p DEBUG)" trap - DEBUG __bp_install ; autojump_add_to_database
    existing_prompt_command="${existing_prompt_command//$__bp_install_string}"
    # _direnv_hook; ; autojump_add_to_database
```

## Steps to Reproduce

1. `bash-it enable plugin direnv autojump`
2. `bash-it restart`
3. bash will complain:
```shell
bash: PROMPT_COMMAND: line 3: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 3: `_direnv_hook; ; autojump_add_to_database'
```
4. `echo $PROMPT_COMMAND`
```
__bp_precmd_invoke_cmd _direnv_hook; ; autojump_add_to_database __bp_interactive_mode
```

## Your Environment

* Bash-it version used:
* List of enabled plugins, themes and aliases (use ``bash-it show (plugins/themes/aliases)``):
* ``bash-it doctor`` output:
* Bash version: 5.0.17
* Operating System and version: ubuntu20.94

## Your Bash Config File

```bash
  # Your bash config file should be here
```

**Comment by NariyasuHeseri** [comment]
I guess this bug was introduced by commit ae8c9c08a3c3f298409ed9efb755eeffe0d2afb2.
On my system, themes no longer work after this commit.

**Comment by roytseng-tw** [comment]
I think the problem is the way autojump (at least on debian package) append PROMPT_COMMAND.
It uses sth. like `"$PROMPT_COMMAND ; autojump_add_to_database"`
Notice the extra space before `;`. It cause the following line in bash-preexec fails to deal with this edge case
```
existing_prompt_command="${PROMPT_COMMAND//$__bp_install_string[;$'\n']}" # Edge case of appending to PROMPT_COMMAND
```
Fix the matching pattern as the following can solve the issue.
```
${PROMPT_COMMAND//$__bp_install_string+([;$ '\n'])}
```

**Comment by gaelicWizard** [comment]
This ought to be updated to use `safe_append_prompt_command` instead of manipulating `$PROMPT_COMMAND`

**Comment by gaelicWizard** [comment]
This almost looks like `$PROMP_COMMAND` isn't being set at all...

**Comment by gaelicWizard** [comment]
@roytseng-tw, @NariyasuHeseri, does the just-committed change alter this for you both?

**Comment by roytseng-tw** [comment]
@gaelicWizard  I've tried the latest commit 7e79212 on master, and it does not fix the problem.

**Comment by gaelicWizard** [comment]
@NariyasuHeseri, I think the theming should be fixed by the latest commit. I think that problem is unrelated to this bug. Could you confirm?

**Comment by gaelicWizard** [comment]
@roytseng-tw, do you have problems when only one of those two plugins is enabled? It seems like the problem arises only when *both* are enabled, yes?

**Comment by NariyasuHeseri** [comment]
> @NariyasuHeseri, I think the theming should be fixed by the latest commit. I think that problem is unrelated to this bug. Could you confirm?

Yes, the latest commit fixes the theme problem and these two seems unrelated...

**Comment by roytseng-tw** [comment]
> @roytseng-tw, do you have problems when only one of those two plugins is enabled? It seems like the problem arises only when _both_ are enabled, yes?

Yes, the problem only arises when **both** are enabled.
More precisely, only when plugins that prepend the `$PROMPT_COMMAND` are enabled along with the autojump plugin.

**Comment by gaelicWizard** [comment]
I've opened https://github.com/rcaloras/bash-preexec/pull/128 upstream to hopefully address the root of the problem. In the mean time, I'm trying out an idea to deal with this here.

**Comment by gaelicWizard** [comment]
I've added to my #2073 a workaround that avoids letting `$__bp_install_string` get sandwiched between other additions to `$PROMPT_COMMAND`, which should let it happily adjust itself without weird in-betweens.
