### ISSUE TITLE
Completion can't depend on plugins

### ISSUE THREAD

**Issue by ksheedlo** [Bash-it/bash-it#208]
I want to add completion for NPM and I have a script that will do it. However, there's a dependency problem. I'm using the nvm plugin to load Node.js and NPM, and my completion script needs NPM to be loaded before it runs. bash-it currently loads aliases, then completion, then plugins, like so:

```
for file_type in "aliases" "completion" "plugins"
do
  _load_bash_it_files $file_type
done
```

Is there any particular reason this is done? If plugins were loaded first, then aliases and completion scripts could depend on them. As far as I can tell, plugins get no benefit from having aliases and completion loaded first.

**Comment by MunifTanjim** [comment]
fixed in #813
