### ISSUE TITLE
[Question] Would it make sense to show user@hostname in powerline theme?

### ISSUE THREAD

**Issue by kirk86** [Bash-it/bash-it#2090]
I've been using the powerline theme for long time and I always use it with hardcoded info of `user@hostname`. Would this interest anyone to make a pull request? I'd prefer this over the current way of displaying `hostname` since it saves real-estate terminal screen and it de-clutters information displayed.

## Expected Behavior

<img width="453" alt="image" src="https://user-images.githubusercontent.com/2902390/154051286-16124095-c38e-4648-8839-9b3808df4886.png">

## Current Behavior

<img width="453" alt="image" src="https://user-images.githubusercontent.com/2902390/154050730-5bdf32c0-9f8e-4828-9aee-a190dfb050d3.png">

I don't know if there is currently a way to display the `hostname` like in the expected behaviour example?

## Possible Solution

Changing a couple of lines in the ` __powerline_user_info_prompt()` function inside `powerline.base.bash` file.

## Context

From my perspective the info shown in the expected behaviour is more comprehensible and at the same time saves some space on the terminal.

**Comment by davidpfarrell** [comment]
Greetings!

So the logic for the `hostname` prompt doesn't (currently) support any overrides, but the `user_info` prompt has some customizability.

Try this:
* First, remove `hostname` from your POWERLINE_PROMPT value
 I don't know what your current value is, but for me, this would be:
 ```
- export POWERLINE_PROMPT="shlvl user_info hostname scm dirstack cwd"
+ export POWERLINE_PROMPT="shlvl user_info scm dirstack cwd"
 ```
* Ensure the POWERLINE_PROMPT_USER_INFO_MODE mode is NOT `sudo`
 Currently, *any* value other than `sudo` will work, even an empty value (or unsetting the variable entirely).  I'll use `user` in this example.
 ```
 export POWERLINE_PROMPT_USER_INFO_MODE=user
 ```
* Now, you can override the display user value by setting the SHORT_USER variable..
 You can hard-code this to *any* value you like, so you could do:
 ```
 export SHORT_USER="jm@insight026"
 ```
* If you'd like a more dynamic value, you can even use shell built-in codes, ie:
 ```
 export SHORT_USER="\u@\h"
 ```

For me, `\u@\h` yields:
![Screen Shot 2022-02-15 at 5 32 18 PM](https://user-images.githubusercontent.com/45741407/154179207-4c4c63e4-54f2-40d6-94c2-d9c2ee2ec56c.png)

Give it a try and let us know how it goes!

**Comment by kirk86** [comment]
Hi, thanks for the MWE.

so did try it, as you mentioned I exported the following vars in my bash profile
```
export POWERLINE_PROMPT="shlvl user_info scm python_venv ruby dirstack cwd"
export POWERLINE_PROMPT_USER_INFO_MODE=user
export SHORT_USER="\u@\h"

# Path to the bash it configuration
export BASH_IT="/Users/jm/.config/bash-it"
```

But, this is what I get

<img width="348" alt="image" src="https://user-images.githubusercontent.com/2902390/154227377-5fd083cc-7f6f-4f6b-bc6e-c7a664dbf862.png">

For some reason this doesn't work for me even when hard coding `export SHORT_USER="jm@insight026"`.

**Comment by davidpfarrell** [comment]
Hi there.

I think you need to debug your setup some more ...

What is your `POWERLINE_PROMPT` value from a brand new shell? (before making any changes related to this discussion) ?

So, assuming that, starting from a fresh unchanged shell, you still have the prompt that you posted when creating this discussion:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/2902390/154050730-5bdf32c0-9f8e-4828-9aee-a190dfb050d3.png">


Now, **JUST** removing the `hostname` from your POWERLINE_PROMPT value, and doing nothing else, should result in the same line minus the `host` section, yes ?

Assuming yes ...

Then just `export SHORT_USER='\u@\h'` should update the value of the user prompt.

Note: Although I'm not positive it matters, I changed to single quotes.

If that still doesn't work, I would be interested in seeing how your prompt changes as you appy each EXPORT one-at-a-time.

**Comment by gaelicWizard** [comment]
@kirk86, `shlvl` counts the number of shells that have started (but not exited). For example, normally it's `1`. But, if you start a new shell by just running `bash`, for example `BASH_IT_THEME= bash -l`, then it will show `2`. When you exit *that* `bash`, it will return to `1`. If you *restart* the shell, it will stay `1`, for example `BASH_IT_THEME= bash-it restart`. (You can check it with `echo $SHLVL`.)

`dirstack` shows how many (if any) entries are on the directory stack, which you add to with `pushd` and remove from with `popd`. (You can check it with `echo $DIRSTACK`.)

**Comment by kirk86** [comment]
Thanks folks, 

closing this for now.

**Comment by kirk86** [comment]
Yes, thanks.
