### ISSUE TITLE
Delete / disable bash-it ?

### ISSUE THREAD

**Issue by Ewayne** [Bash-it/bash-it#210]
What's the best way to cleanly disable bash-it ?

**Comment by JamesBarnett1993** [comment]
BUMP

**Comment by nwinkler** [comment]
OK, here it is again. If you have a backup of your `.bash_profile`, simply remove the one created by Bash-it and rename your backup file (remove the `.bak` suffix).

If you don't have a backup, edit your `~/.bash_profile` file and remove the following line, which loads Bash-it (https://github.com/Bash-it/bash-it/blob/master/template/bash_profile.template.bash#L30):

```
source $BASH_IT/bash_it.sh
```

Either delete the line or comment it out by prefixing it with `#`. Then close your terminal and open a new one. Once that is done, Bash-it will no longer be loaded. Optionally, you can now delete the `~/.bash_it` folder.

Does that make sense?
