### ISSUE TITLE
Flaky test skips

### ISSUE THREAD

**Issue by NoahGorny** [Bash-it/bash-it#2115]
@NoahGorny I've been seeing this one intermittently of late, but can't reproduce on my own OSX 11.6. It's just skipping some tests!!!!

It's driving me batty. My best guess is that something in `test_helper.bash` is failing and exiting, but because it's not within a function it's not being reported. I'm going to try doing what BATS documentation recommends: load the common setup from within `setup()`, not the other way around. That way at least we'll get the error message...I think...

_Originally posted by @gaelicWizard in https://github.com/Bash-it/bash-it/issues/2107#issuecomment-1060052377_

**Comment by NoahGorny** [comment]
I am not sure whats going on there, @gaelicWizard I can take a closer look if you wish

**Comment by gaelicWizard** [comment]
Don't hold off on my account. I haven't found much time the last few days, but hopefully will be able to sit with it tonight. If you find time before me, have at it! 😃

**Comment by NoahGorny** [comment]
There are also some skipped tests on osx - the `xterm` tests are being skipped silently there, not sure why
