### ISSUE TITLE
Do not use "sudo" with vim for security reasons

### ISSUE THREAD

**Issue by thomasmerz** [Bash-it/bash-it#2151]
Use `sudoedit` for security reasons in https://github.com/Bash-it/bash-it/blob/2ef5d483e38d790cb1c32ea8999dfbc244ff2f91/aliases/available/general.aliases.bash#L74 because `sudo vim` gives users a root shell by executing arbitrary shell commands.

PR will follow…

**Comment by gaelicWizard** [comment]
I would definitely prefer to use the most correct tool for the job, but it doesn't seem like this is a vulnerability anywhere except a specially configured `sudoers` environment. If the user can already `sudo` then what happens after that is not a vulnerability. 

I left a review on the PR asking for some logic to deal with not having a `sudoedit` binary on the system.

**Comment by thomasmerz** [comment]
If a user already can do `sudo` everything, than I fully agree. But if a user is only allowed to `sudo vim` (any file) he/she/it can get a root-shell but normally this is not intended by allowing users editing all files. At home I'm fine that my user can `sudo` everything. But would never allow any non-root-granted person than me `sudo vim`.

**Comment by tbhaxor** [comment]
I agree with @gaelicWizard, this is not a vulnerability but a misconfiguration I would say. We can have shell set to `/bin/false`, but it is mostly required on the servers.

**Comment by cornfeedhobo** [comment]
Instead, I vote we remove any customizations and/or tools that require `sudo`, most especially, not in the `general` aliases.
