### ISSUE TITLE
[Bug]: aliases completion has conflict with tmux completion

### ISSUE THREAD

**Issue by pffang** [Bash-it/bash-it#2169]
### Expected behavior

aliases completion and tmux completion can work together.

### Current behavior

If aliases completion is enabled, tmux completion doesn't work.

### Possible solution

Disable aliases completion by `bashit disable completion aliases` can make tmux completion work again.

### Steps to reproduce

`bashit enable completion aliases tmux` can always reproduce this issue.

### Bash-it version

Stable v3.0.2

### List of enabled plugins, themes and aliases

tmux aliases 

### Bash version

GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

### Operating system and version

Ubuntu 18.04.6 LTS

### bash-it doctor output

DEBUG: core: main: Loading libraries(except appearance)...
DEBUG: lib: colors: Loading library file...
DEBUG: lib: command_duration: Loading library file...
DEBUG: lib: helpers: Loading library file...
DEBUG: lib: history: Loading library file...
DEBUG: lib: log: Loading library file...
DEBUG: lib: preexec: Loading library file...
DEBUG: lib: preview: Loading library file...
DEBUG: lib: search: Loading library file...
DEBUG: lib: utilities: Loading library file...
DEBUG: core: reloader: Loading all enabled components...
DEBUG: aliases: bash-it: Loading component...
DEBUG: aliases: bash-it: Loaded.
DEBUG: aliases: curl: Loading component...
DEBUG: aliases: curl: Loaded.
DEBUG: aliases: general: Loading component...
DEBUG: aliases: general: Command 'gshuf' does not exist
DEBUG: aliases: general: Loaded.
DEBUG: aliases: git: Loading component...
DEBUG: aliases: git: Loaded.
DEBUG: aliases: systemd: Loading component...
DEBUG: aliases: systemd: Loaded.
DEBUG: aliases: tmux: Loading component...
DEBUG: aliases: tmux: Loaded.
DEBUG: plugin: base: Loading component...
DEBUG: plugin: base: Command 'markdown' does not exist
DEBUG: plugin: base: Loaded.
DEBUG: plugin: colors: Loading component...
DEBUG: plugin: colors: Loaded.
DEBUG: plugin: git: Loading component...
DEBUG: plugin: git: Loaded.
DEBUG: plugin: gitstatus: Loading component...
DEBUG: plugin: gitstatus: Loaded.
DEBUG: plugin: history: Loading component...
DEBUG: plugin: history: Loaded.
DEBUG: plugin: history-search: Loading component...
DEBUG: plugin: history-search: Loaded.
DEBUG: plugin: man: Loading component...
DEBUG: plugin: man: Loaded.
DEBUG: plugin: powerline: Loading component...
DEBUG: plugin: powerline: Command 'powerline-daemon' does not exist
DEBUG: plugin: powerline: Loaded.
DEBUG: plugin: projects: Loading component...
DEBUG: plugin: projects: Loaded.
DEBUG: plugin: tmux: Loading component...
DEBUG: plugin: tmux: Loaded.
DEBUG: plugin: xterm: Loading component...
DEBUG: plugin: xterm: Loaded.
DEBUG: completion: system: Loading component...
DEBUG: completion: system: Loaded.
DEBUG: completion: bash-it: Loading component...
DEBUG: completion: bash-it: Loaded.
DEBUG: completion: defaults: Loading component...
DEBUG: completion: defaults: Loaded.
DEBUG: completion: git: Loading component...
 WARN: completion: git: completion already loaded - this usually means it is safe to stop using this completion
DEBUG: completion: git: Loaded.
DEBUG: completion: makefile: Loading component...
DEBUG: completion: makefile: Loaded.
DEBUG: completion: pip3: Loading component...
DEBUG: completion: pip3: Loaded.
DEBUG: completion: pip: Loading component...
DEBUG: completion: pip: Loaded.
DEBUG: completion: pipenv: Loading component...
DEBUG: completion: pipenv: Command 'pipenv' does not exist
DEBUG: completion: pipenv: Loaded.
DEBUG: completion: projects: Loading component...
DEBUG: completion: projects: Loaded.
DEBUG: completion: ssh: Loading component...
DEBUG: completion: ssh: Loaded.
DEBUG: completion: tmux: Loading component...
DEBUG: completion: tmux: Loaded.
DEBUG: core: main: Loading theme 'powerline'.
DEBUG: core: main: Loading custom aliases, completion, plugins...
DEBUG: core: main: Loading general custom files...
DEBUG: custom: example: Loading custom file...
DEBUG: core: main: Command 'gloobus-preview' does not exist

### Your ~/.bashrc

```bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
export HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=1000
export HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
#alias ll='ls -alF'
#alias lt='ls -alFt'
#alias la='ls -A'
#alias l='ls -CF'
#alias m='more'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
#if ! shopt -oq posix; then
#  if [ -f /usr/share/bash-completion/bash_completion ]; then
#    . /usr/share/bash-completion/bash_completion
#  elif [ -f /etc/bash_completion ]; then
#    . /etc/bash_completion
#  fi
#fi

if [ -f ~/.bash_completion ]; then
    . ~/.bash_completion
fi

function set_title()
{
  echo -en "\033]0;$*\a"
}

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# Path to the bash it configuration
export BASH_IT="/home/fpa1szh/.bash_it"
export BASH_IT_GREP='grep'
export BASH_IT_PROJECT_PATHS=${PROJECT_PATHS}
export EDITOR='nano'

# Lock and Load a custom theme file.
# Leave empty to disable theming.
# location /.bash_it/themes/
export BASH_IT_THEME='powerline'
export THEME_SHOW_CLOCK=false
export POWERLINE_PROMPT_USER_INFO_MODE='sudo'

# Some themes can show whether `sudo` has a current token or not.
# Set `$THEME_CHECK_SUDO` to `true` to check every prompt:
export THEME_CHECK_SUDO='false'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# (Advanced): Change this to the name of the main development branch if
# you renamed it or if it was changed for some reason
# export BASH_IT_DEVELOPMENT_BRANCH='master'

# Your place for hosting Git repos. I use this for private repos.
#export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true
# Set to actual location of gitstatus directory if installed
export SCM_GIT_GITSTATUS_DIR="$HOME/.gitstatus"
# per default gitstatus uses 2 times as many threads as CPU cores, you can change this here if you must
export GITSTATUS_NUM_THREADS=4

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
export SHORT_USER=${USER:0:8}

# If your theme use command duration, uncomment this to
# enable display of last command duration.
#export BASH_IT_COMMAND_DURATION=true
# You can choose the minimum time in seconds before
# command duration is displayed.
#export COMMAND_DURATION_MIN_SECONDS=1

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
export BASH_IT_RELOAD_LEGACY=1

# Load Bash It
source "$BASH_IT"/bash_it.sh
```

**Comment by davidpfarrell** [comment]
Greetings!

Can you please confirm:

Are you having issues typing `tmux <tab> <tab>` or are you having issues trying to use one of the bash-it tmux aliases (i.e. `txl <tab> <tab>`) ?

Assuming the former ...

Can you try disabling the bash-it tmux plugin:
```
$ bash-it disable plugin tmux
```
**note:** Don't forget to restart  your shell after disabling the plugin

This plugin creates an alias *named* `tmux`, and I suspect that is interfering with the alias-completion plugin ...

Please give a try and let us know if it helps anything.

Thanks!

**Comment by pffang** [comment]
I have issues when type `tmux <tab> <tab>`. I don't use the aliases of tmux.

Enable/Disable plugin tmux has no any difference to this issue.

**Comment by pffang** [comment]
@davidpfarrell After fully restart bash sessions, your solution works for me.
Thank you!

**Comment by davidpfarrell** [comment]
@pffang thanks for confirming - closing the issue
