### ISSUE TITLE
bash-it help completions not a valid option

### ISSUE THREAD

**Issue by b00y0h** [Bash-it/bash-it#217]
README.md lists the help screens available, but 'bash-it help completions' throws the following error: 

oops! completions is not a valid option!

even tried 'bash-it help completion general' to show completions for the 'general' completion, but throws same error.

**Comment by ivoba** [comment]
same here on Ubuntu 14, bash 4.3.11(1)

**Comment by edubxb** [comment]
The function to show the completion help is not implemented (`_help_completion` not exists in [`lib/helpers.bash`](https://github.com/revans/bash-it/blob/master/lib/helpers.bash)).

**Comment by nwinkler** [comment]
I'm not sure what to show for this anyway. I suggest we simply remove the reference from the help file.

**Comment by nwinkler** [comment]
Fixed in https://github.com/Bash-it/bash-it/commit/d29d6df2f218624cb176fe4a251e00eb0b70adc8
