### ISSUE TITLE
rgb color, how to?

### ISSUE THREAD

**Issue by b00y0h** [Bash-it/bash-it#218]
it's not clear how to use your own rgb color values for the themes/prompt. could someone please point me in the right direction? thanks

**Comment by SergioScabuzzo** [comment]
Sorry to revive this, but I just don't understand how to change the colors using RGB.
zork.theme.bash...

I used this:    
  my_ps_host="$(color rgb 195 232 141)\h${normal}";
But the color is a pinkish orange, not green. 

Looked at colors.theme.bash:

function __color_rgb {
  r=$1 && g=$2 && b=$3
  [[ r == g && g == b ]] && echo $(( $r / 11 + 232 )) && return # gray range above 232
  echo "8;5;$(( ($r * 36  + $b * 6 + $g) / 51 + 16 ))"
}

This makes 0 sense to me :(
I've spent about an hour reading and following links to no avail.  Any help with the syntax?

**Comment by nwinkler** [comment]
Sorry, can't help you with that. A search in the code showed that the `__color_rgb` function is not used anywhere.

Not sure who added that function and what it does, sorry...

**Comment by SergioScabuzzo** [comment]
it was added a while back.
[https://github.com/Bash-it/bash-it/pull/99#issue-3133339](url)

on this file [https://github.com/Bash-it/bash-it/blob/569a7a902e133963bd897eee1a1a8173a5a3f66a/themes/colors.theme.bash#L110](url)

Maybe shooting in the dark... thanks at any rate

**Comment by SergioScabuzzo** [comment]
Perfect! Not what I was thinking but it did the trick. Thanks
