### ISSUE TITLE
SCP transfrer break when enabling bash-it

### ISSUE THREAD

**Issue by vpassapera** [Bash-it/bash-it#220]
If i enable bash it and make my .bashrc a link to .bash_profile whenever I try to do an SCP transfer instead of transferring the file it echos out the last directory used.

**Comment by nwinkler** [comment]
@vpassapera On the off chance that you're reading this - is this still an issue for you? If it is - a couple of questions for you:

* Which OS/Linux distro are you using?
* We've made a couple of changes to the installer to select the correct file based on the OS, i.e. for Linux we're installing into `.bashrc` now - which should avoid the above problem. Have you tried this change, and has it fixed your issue? See #173 for more details...

CC @edubxb

**Comment by namtrah** [comment]
This does not fix the problem. I use Ubuntu 14.04.1 and have pulled the latest bash-it version. then sourced my .bashrc and tried the following command:

scp name@ubuntu:~/.bashrc BASHRC

Which should technically use scp to copy my local .bashrc via SSH back into BASHRC (this is a hypothetical test here). All I get is the directory and no file copied.

**Comment by edubxb** [comment]
@namtrah can you put here the output of the error you get then doing this?

**Comment by vpassapera** [comment]
@nwinkler I completely forgot about this issue.

I actually eventually solved the problem so long ago, I don't even remember what I did.

Thank's for the follow up though!
