### ISSUE TITLE
How to change prompt dynamically every command?

### ISSUE THREAD

**Issue by miketheman** [Bash-it/bash-it#222]
There's a common use case for displaying a colorized character as an indication if the previous command exited cleanly or not.

I can't figure out how to re-invoke prompt change after every command, so that it would change based on previous actions.

**Comment by pmbenjamin** [comment]
@miketheman .. I'm a bit late to the party, but I was running into the same issue.
I was able to resolve it with a bash short-circuit.

Note the conditional statement followed by `&&` and the `$STATUS_THEME_PROMPT_OK` expression. If `$?` is not equal to `0`, then print the `$STATUS_THEME_PROMPT_BAD`.
Finally, store the result of this expression as `ret_status` local variable and print the local variable in the `PS1` prompt.

Example:
```bash
STATUS_THEME_PROMPT_BAD="${red}❯${reset_color} "
STATUS_THEME_PROMPT_OK="${green}❯${reset_color} "

function prompt_command() {
    local ret_status="$( [ $? -eq 0 ] && echo -e "$STATUS_THEME_PROMPT_OK" || echo -e "$STATUS_THEME_PROMPT_BAD")"
    PS1="\n${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${ret_status}"
}
```
