### ISSUE TITLE
rvm and virtualenv plugins fight

### ISSUE THREAD

**Issue by miketheman** [Bash-it/bash-it#223]
If you have rvm enabled, it complains about not being the first thing in $PATH.
When you activate a virtualenv, this places the venv's path first, and rvm begins to complain.

I don't know what "the right thing" would be to do here.

**Comment by thedrow** [comment]
The same happens with the rvm and pyenv plugins... No idea what to do.

**Comment by miketheman** [comment]
Closing. I've resolved by using direnv to handle virtual environments.
