### ISSUE TITLE
[Bug]: .bash_it/lib/history.bash reuses HISTCONTROL for it's own incorrect purposes by default

### ISSUE THREAD

**Issue by kmcfate** [Bash-it/bash-it#2232]
### Expected behavior

mcfly (a bash history replacement) should properly record and recall commands

### Current behavior

mcfly does not properly record or recall commands

### Possible solution

 Setting HISTCONTROL to 'noauto' fixes the problem, but ignore the fact this is an invalid value for HISTCONTROL. Do not enable .bash_it/lib/history.bash contents by default, or specifically do not run `history -a` by default as histappend is enabled by default. There is a whole plugin dedicated to bash history, why does this library even exist?

### Context

It breaks mcfly 

### Steps to reproduce

Install mcfly and try to use it.

### Bash-it version

https://github.com/Bash-it/bash-it/commit/36708d7

### List of enabled plugins, themes and aliases

N/A

### Bash version

5.2.15

### Operating system and version

Ubuntu 22.04

### bash-it doctor output

```
# How to get: bash-it doctor
```

### Your ~/.bashrc

```bash
# How to get: cat ~/.bashrc
```

**Comment by cornfeedhobo** [comment]
I would like to see more reasoning than `mcfly`. We have users that have used this for too many years to leap to this conclusion to accommodate a new tool. I'm still open to reviewing this topic, but I'm sensitive to how central this is to many people's environments and how stable it's been over time.

**Comment by kmcfate** [comment]
I've been using mcfly and bash-it for years before this change was introduced. Pulling a recent version broke me. Please see my comments on the PR.

**Comment by kmcfate** [comment]
Workaround is adding 'noauto' to HISTCONTROL.
