### ISSUE TITLE
Does `bash-it` load `bash-preexec` by default?

### ISSUE THREAD

**Issue by hongyi-zhao** [Bash-it/bash-it#2244]
After I installed bash-it, I noticed that the `$PROMPT_COMMAND` variable changed to the following:

```shell
werner@X10DAi:~$ echo $PROMPT_COMMAND
__bp_precmd_invoke_cmd __hishtory_postcommand; _zlua_precmd;_pyenv_virtualenv_hook __bp_interactive_mode
```
So, it seems that `bash-it` loads [`bash-preexec`](https://github.com/rcaloras/bash-preexec) by default. Is this a mandatory requirement or not? If not, how can I disable it?

Regards,
Zhao

**Comment by hongyi-zhao** [comment]
By inspecting the variable's value of `PROMPT_COMMAND` immediately after [`bash_it.sh`](https://github.com/Bash-it/bash-it/blob/master/bash_it.sh) was sourced, I noticed the following result:

`__hishtory_postcommand; _zlua_precmd;_pyenv_virtualenv_hook __bp_trap_string="$(trap -p DEBUG)" trap - DEBUG __bp_install`

A further checking tells me that the `__hishtory_postcommand` comes from [hishtory](https://github.com/ddworken/hishtory) and `__bp_trap_string="$(trap -p DEBUG)" trap - DEBUG __bp_install` comes from `bash-it`.

**Comment by akinomyoga** [comment]
> I'm still not quite sure.

That's processed in [`bash-preexec.sh`](https://github.com/rcaloras/bash-preexec/blob/8926de0a1f69d17f5b05099cfaaa52d833084c2f/bash-preexec.sh#L340-L347).

`bash-preexec.sh` wants to call `__bp_precmd_invoke_cmd` before any other `PROMPT_COMMAND`, and it also wants to call `__bp_interactive_mode` at the very end of `PROMPT_COMMAND`. This setup can be broken when other frameworks set `PROMPT_COMMAND` for them after `bash-preexec.sh` introduces its setup. For this reason, `bash-preexec.sh` delays its initialization until the first call of `PROMPT_COMMAND`. The string `__bp_trap_string="$(trap -p DEBUG)"\ntrap - DEBUG __bp_install` is the code to call the initialization. The strings `__bp_precmd_invoke_cmd` and `__bp_interactive_mode` are the strings set by the bash-preexec's initialization (in particular by the shell function `__bp_install`).

**Comment by akinomyoga** [comment]
In the codebase of Bash-it, the feature provided by `bash-preexec` seems to be used in the following places:

- [bash-it/lib/history.bash at d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce · Bash-it/bash-it](https://github.com/Bash-it/bash-it/blob/d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce/lib/history.bash#L6)
- [bash-it/lib/command_duration.bash at d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce · Bash-it/bash-it](https://github.com/Bash-it/bash-it/blob/d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce/lib/command_duration.bash#L75)
- [bash-it/plugins/available/xterm.plugin.bash at d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce · Bash-it/bash-it](https://github.com/Bash-it/bash-it/blob/d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce/plugins/available/xterm.plugin.bash#L43)
- [bash-it/plugins/available/goenv.plugin.bash at d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce · Bash-it/bash-it](https://github.com/Bash-it/bash-it/blob/d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce/plugins/available/goenv.plugin.bash#L41)

Also, the following plugin indirectly uses `bash-preexec` through plugin `command_duration`:

- [bash-it/plugins/available/cmd-returned-notify.plugin.bash at d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce · Bash-it/bash-it](https://github.com/Bash-it/bash-it/blob/d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce/plugins/available/cmd-returned-notify.plugin.bash#L14)

As far as you don't use those features, I think you can technically loading `bash-preexec` by commenting out this line:

https://github.com/Bash-it/bash-it/blob/d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce/lib/preexec.bash#L12

**Comment by hongyi-zhao** [comment]
> Also, the following plugin indirectly uses `bash-preexec` through plugin `command_duration`:

According to the discussion [here](https://github.com/akinomyoga/ble.sh/issues/422#issuecomment-1986857840), [`bash-preexec`](https://github.com/rcaloras/bash-preexec) often gives inaccurate, usually overestimated `command_duration`.

> As far as you don't use those features, I think you can technically loading `bash-preexec` by commenting out this line:

It may be more convenient to provide options to enable and disable these features.

**Comment by akinomyoga** [comment]
> > Also, the following plugin indirectly uses `bash-preexec` through plugin `command_duration`:
> 
> According to the discussion [here](https://github.com/akinomyoga/ble.sh/issues/422#issuecomment-1986857840), [`bash-preexec`](https://github.com/rcaloras/bash-preexec) often gives inaccurate, usually overestimated `command_duration`.

Right. That problem is ubiquitous as far as `bash-preexec` or a similar approach using the `DEBUG` hook is used.

> > As far as you don't use those features, I think you can technically loading `bash-preexec` by commenting out this line:
> 
> It may be more convenient to provide options to enable and disable these features.

Probably.

> This will trigger the following problem:
> 
> `__bp_install_after_session_init: command not found`

Then, you can also comment out this line:

https://github.com/Bash-it/bash-it/blob/d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce/lib/preexec.bash#L25

**Comment by hongyi-zhao** [comment]
By this way, the `PROMPT_COMMAND` will finally looks as follows:
```shell
werner@X10DAi:~$ echo $PROMPT_COMMAND
_bash-it-history-auto-load;_command_duration_pre_cmd;__hishtory_postcommand; _zlua_precmd;_pyenv_virtualenv_hook

```

**Comment by cornfeedhobo** [comment]
> So, it seems that `bash-it` loads [`bash-preexec`](https://github.com/rcaloras/bash-preexec) by default. Is this a mandatory requirement or not? If not, how can I disable it?

Indeed, `bash-preexec` is a requirement for bash-it, currently.
