### ISSUE TITLE
Feedback : put a user repository into $XDG_CONFIG_HOME/bash-it

### ISSUE THREAD

**Issue by jmfayard** [Bash-it/bash-it#231]
Hello,

First, let me tell that I find this project awesome, so thank you for that.
Second, this is not a bug, this is feedback, a suggestion, a question.
Such things don't play well at all with bugtrackers that were designed to... well track bugs
But since few developers know very useful tools like https://www.uservoice.com/ , I post my feedback here.

----

A little thing bugs me with bash-it
It follows the bad very old idea to hide config files right under $HOME
This was fine when you had only to configure .bashrc and .emacs, but this got out of control since a long time.

That's why the $XDG_CONFIG_HOME variable was invented in the first place
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

I happen to use macosx, but I have precisely the same problem.
All my pet projects, most forked from github, are stored in $HOME/github
bash-it is an exception here and I found it weird.
But ok I will do an exception. 
So I opened GitHub.app, will do "File -> Add local directory"
Here the standard MacosX's Open Dialog pop up
I browse to $HOME
Same problem : hidden files are not shown (because it doesn't scale well)

So I had to browse the web to find a work-around, a shortkey that displays hidden files, get the job done.

*With the dialog box as the front-most window (you can click once in the dialog box to make sure it’s in front), press the command, shift, and period keys at the same time.*

Ok, but now I'm pretty sure that I will forget it soon, and that most people don't know it either.

**Suggestion:**

improve the documentation so that people put their copy of bash-it in $XDG_CONFIG_HOME, $HOME by default

**Comment by nwinkler** [comment]
Additional locations are supported now.
