### ISSUE TITLE
Retain current working directory when opening new tab/window OSX

### ISSUE THREAD

**Issue by jedateach** [Bash-it/bash-it#240]
After I've started using bash-it, I've noticed that new terminal tabs/windows don't open in the same working directory. Disabling bash-it resolves this.

I don't understand the bash-it internals enough to know where/how to fix this.

**Comment by alfv89** [comment]
I have the same issue in Linux. Some one knows how help me?

**Comment by nwinkler** [comment]
I've added a fix for OS X in #514, @yagudaev and @tswicegood - could you take a look before I merge? It works for me on Yosemite with the standard Terminal app. Pressing Cmd+T opens a new tab using the current directory as the starting directory.

**Comment by nwinkler** [comment]
Closing this as it should be fixed with #514.
