### ISSUE TITLE
Transferring bash-it config between computers

### ISSUE THREAD

**Issue by bsgreenb** [Bash-it/bash-it#283]
Is there a file that stores settings/what's enabled that I could transfer from one comp to the next to transfer over my bash-it config?

**Comment by aaroncaito** [comment]
@bsgreenb I use a ~/etc.git to keep track of my stuff.
mkdir ~/etc && mv ~/.bash_profile ~/etc/bash_profile && ln -s ~/etc/bash_profile ~/.bash_profile
mkdir ~/etc && mv ~/.bash_it ~/etc/bash_it && ln -s ~/etc/bash_it ~/.bash_it
I move most my .dotfiles and other config type stuff in to ~/etc and symlink where it belongs. then I keep my etc backed up. I use boxen to create those repos and symlinks for new systems to help keep everything in sync. there are probably more elegant solutions but this is what i'm doing now.

**Comment by cornfeedhobo** [comment]
@bsgreenb I copy the entire directory to my new computer, or restore from a back up. I'd say that if you want a settings export feature, a PR would be more than welcomed.

@nwinkler my guess is that this can be closed.

**Comment by davidpfarrell** [comment]
I posted this somewhere else around here, but think sharing it here could be useful too:

[bashit-backup.sh (gist)](https://gist.github.com/davidpfarrell/f437a0e5fd905ca58d0148f067bd28d4)
```
# Exports Bash-it components as a series of 'enable' commands.
# The output can be saved to a file and sourced as needed to re-enable components.
# A 'disable all' statement is present for each component, but commented by default.
```

**Comment by nwinkler** [comment]
Thanks for posting your Gist here! I use a similar script that also produces an executable file with all the enable/disable statements. It can be found here: https://github.com/nwinkler/dotfiles/blob/master/home/bin/backup-bash-it

I'm wondering whether we want to either add this to the Wiki section, or add it as a function to Bash-it. Something like `bash-it backup`...

**Comment by finn-matti** [comment]
Why was this closed? It seems backup is not a recognized function of bash-it.

**Comment by davidpfarrell** [comment]
Hey @finn-matti ,

I think this was closed since, at the time, the discussion resulted in some working solutions (for example, see the gist I link to a couple posts above)

However, there is also a current effort to bring some form of official support to bash-it:
* [add profile subcommand](https://github.com/Bash-it/bash-it/pull/1865)

So keep an eye on that PR !

**Comment by finn-matti** [comment]
@davidpfarrell That looks great. Also thanks for the clarification. 👍
