### ISSUE TITLE
vagrant plugin update default path

### ISSUE THREAD

**Issue by tonybolzan** [Bash-it/bash-it#295]
In Vagrant 1.5 the default path for box is `~/.vagrant.d/`
Change line 40 in `plugins/available/vagrant.plugin.bash` resolve the problem.

**Comment by edubxb** [comment]
This plugin don't exists in Bash it, only in the @goldi42 [fork](https://github.com/goldi42/bash-it).

Also, the vagrant completion file (`completion/available/vagrant.plugin.bash` line 130) that comes with Bash it seems that don't have this problem, so I will close this issue.
