### ISSUE TITLE
pyenv+virtualenv == crash

### ISSUE THREAD

**Issue by rfergu** [Bash-it/bash-it#325]
So if you've installed pyenv and you have both the pyenv and virtualenv plugins you'll get an instant crash.  Perhaps make it so if you have a which pyenv you use https://github.com/yyuu/pyenv-virtualenv instead?

**Comment by edubxb** [comment]
@rfergu are you still having this issue or can we close it?

Thanks!

**Comment by rfergu** [comment]
fixed!

**Comment by edubxb** [comment]
Fantastic, thanks, and sorry to take so long...
