### ISSUE TITLE
Tab completion case insensitivity like in oh-my-zsh

### ISSUE THREAD

**Issue by xanview** [Bash-it/bash-it#361]
It would be great if bash-it could (maybe optionally) do tab completion that is case insensitive like oh-my-zsh does :) - This is a feature I sorely miss in bash-it.

**Comment by pahindman** [comment]
I'm not sure what zsh does exactly, but bash [uses readline](https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File.html) to handle completions, and readline supports case-insensitive completion.  You could try putting the following in your ~/.inputrc and see if it works for you:

    $if Bash
    set completion-ignore-case on
    $endif

**Comment by edubxb** [comment]
I close this because the @pahindman is the correct solution.

**Comment by rgm3** [comment]
Setting `set completion-ignore-case on` in the ~/.inputrc file does not work for completing branch names, but it does seem to work for completing directory names.  I'm using GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15).
