### ISSUE TITLE
Add a subcommand to update Bash-It easily

### ISSUE THREAD

**Issue by edubxb** [Bash-it/bash-it#395]
Could be a nice feature the possibility to update Bash-it simply running:

$ bash-it update

**Comment by pickfire** [comment]
It may be better to just auto-update like oh-my-zsh but `zsh/datetime` is not available so need to use other method such as `date`.

**Comment by tswicegood** [comment]
:+1: for an explicit `bash-it update` command.  We could hook it up to an auto running code so it'll update ever N days or some such as an option, but I'd say the first part is something that updates for you.

**Comment by max-mykhailenko** [comment]
Waiting for it!

**Comment by edubxb** [comment]
Done, someone want to try it? :stuck_out_tongue_closed_eyes:
