### ISSUE TITLE
Enable plugins/aliases/completion for installed-only application

### ISSUE THREAD

**Issue by pickfire** [Bash-it/bash-it#405]
I hope that there is a new function in for installed application other than all, some, none in the [install.sh](https://github.com/revans/bash-it/blob/master/install.sh) as the user can easily select those which isn't installed as an option.

**Comment by nwinkler** [comment]
Sorry, I'm not sure I understand what you're after. Could you provide an example?

**Comment by pickfire** [comment]
On 27/01/2015 15:14, Nils Winkler wrote:
> Sorry, I'm not sure I understand what you're after. Could you provide
> an example?

Your original .bashrc has been backed up to .bashrc.bak
Copied the template .bashrc into ~/.bashrc, edit this file to customize 
bash-it
Do you use Jekyll? (If you don't know what Jekyll is, answer 'n') [Y/N] 
n
Would you like to enable all, some, or no aliases? Some of these may 
make bash slower to start up (especially completion). (all/some/none) 
base

Base for the applications that have been installed and some base setup.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
