### ISSUE TITLE
unicode characters cause PS1 command wrapping issues

### ISSUE THREAD

**Issue by deanmalmgren** [Bash-it/bash-it#409]
I'm running the stock bash on OSX Yosemite version 3.2.57(1)-release and this issue is related to #36 to a certain extent. When using any of the themes that have unicode characters like `✗`, `✓`, etc, this causes the PS1 to wrap commands longer than a line incorrectly like this:

![screen shot 2015-02-09 at 11 51 47 am](https://cloud.githubusercontent.com/assets/255672/6111909/12f127be-b052-11e4-9f72-1be4ee871c1f.png)

If I replace the unicode characters with plain ASCII characters, it fixes the problem:

![screen shot 2015-02-09 at 11 49 27 am](https://cloud.githubusercontent.com/assets/255672/6111875/bdbf095a-b051-11e4-8989-cdbcd8f884eb.png)

It would be nice if bash-it automatically detected the bash version when using these unicode things. This threw me for a loop and was rather challenging to track down. I happened to have a 2-hour conference call during which I could debug the issue, but I probably wouldn't have had the patience to figure this out if it weren't for this call. Has backward compatibility been discussed at all?

I'd be happy to throw together a PR to try and be more accommodating with older versions of bash, but if this has already been discussed and decided, feel free to let me know and I'll save the time for something else (like paying attention on my next conference call).

**Comment by deanmalmgren** [comment]
From the conversation in #466, this is related to having `$TERM` set to `term-256color`. Replacing this with `term` fixed the issue for me.

**Comment by hansgans** [comment]
Changing `$TERM` to `xterm` does not make a difference in my case. I also changed bash from 4.1 to 4.4 without any success. I encounter the problem both on macOS and Linux. I tried the themes `powerline` and `bobby`. Could you please reopen the issue?

**Comment by gustavobittencourt** [comment]
I had the same problem that @hansgans.
