### ISSUE TITLE
Install Error with Raspberry Pi

### ISSUE THREAD

**Issue by slambert** [Bash-it/bash-it#410]
Hey,

I've been too spoiled by bash-it on my osx machine, so I decided to try to install it on the Raspberry Pi I use as a file server (perhaps my first mistake?). I got this error. I was able to manually install everything I needed via individual commands (i.e. `bash-it enable plugin history`).

     Linux raspberrypi 3.18.6+ #754 PREEMPT Sun Feb 8 20:22:45 GMT 2015 armv6l

<snip>

     pi@raspberrypi ~ $ sh ~/.bash_it/install.sh
     Your original .bashrc has been backed up to .bashrc.bak
     Copied the template .bashrc into ~/.bashrc, edit this file to customize bash-it
     Do you use Jekyll? (If you don't know what Jekyll is, answer 'n') [Y/N] n
     /home/pi/.bash_it/install.sh: 39: /home/pi/.bash_it/install.sh: Syntax error: "(" unexpected

**Comment by edubxb** [comment]
Can you launch the installation in the debug mode and paste the results?

    $ sh -x ~/.bash_it/install.sh

**Comment by slambert** [comment]
Sure:

	sh -x ~/.bash_it/install.sh
	+ BASH_IT=/home/pi/.bash_it
	+ CONFIG_FILE=.bashrc
	+ test -w /home/pi/.bashrc
	+ cp /home/pi/.bashrc /home/pi/.bashrc.bak
	+ echo Your original .bashrc has been backed up to .bashrc.bak
	Your original .bashrc has been backed up to .bashrc.bak
	+ cp /home/pi/.bash_it/template/bash_profile.template.bash /home/pi/.bashrc
	+ echo Copied the template .bashrc into ~/.bashrc, edit this file to customize bash-it
	Copied the template .bashrc into ~/.bashrc, edit this file to customize bash-it
	+ true
	+ read -p Do you use Jekyll? (If you don't know what Jekyll is, answer 'n') [Y/N]  RESP
	Do you use Jekyll? (If you don't know what Jekyll is, answer 'n') [Y/N] n
	+ break
	/home/pi/.bash_it/install.sh: 39: /home/pi/.bash_it/install.sh: Syntax error: "(" unexpected

**Comment by nwinkler** [comment]
Which version of Bash are you running on the Raspberry Pi?

**Comment by slambert** [comment]
`GNU bash, version 4.2.37(1)-release (arm-unknown-linux-gnueabihf)`

**Comment by Armored-Dragon** [comment]
The problem is because you need to use `bash` to run install.sh, but you're using `sh`. Simply replace `sh` with `bash` in the command.

**Comment by slambert** [comment]
@Armored-Dragon you are right! I forgot I left this issue open. Thanks!
