### ISSUE TITLE
Integration idea - oh-my-git

### ISSUE THREAD

**Issue by seefood** [Bash-it/bash-it#413]
Just bumped into this sexy thing: https://github.com/arialdomartini/oh-my-git

My thought is to add it as an external module under current bash-it and let it provide a nice theme backend. Does that make any sense, Since a big chunk of its code is going to be kinda redundant?

**Comment by nwinkler** [comment]
Looks interesting - but there definitely is some overlap with some of the existing themes, e.g. Powerline.

**Comment by edubxb** [comment]
I have plans to borrow some "bits" from:

Oh my Git → https://github.com/arialdomartini/oh-my-git
Rainbow Bash → https://github.com/slok/rainbow-bash
Git Prompt → https://github.com/git/git/blob/563d4e59bd167fe2eecc5480e3841d878b1c8c2b/contrib/completion/git-prompt.sh
Awesome Terminal Fonts → https://github.com/gabrielelana/awesome-terminal-fonts

to make Bash It look great!

**Comment by tswicegood** [comment]
:+1: to that @edubxb!

I really do like oh-my-git's explanation.  It'd be awesome if someone put together something like that for bash-it with a theme like powerline.

**Comment by seefood** [comment]
:+1: from me too :) I hope to have some free time between jobs in a month to get this done, or join the efforts of whoever starts those first!

**Comment by apaatsio** [comment]
:+1: oh-my-git's prompt looks awesome

**Comment by nwinkler** [comment]
@apaatsio Have you tried the `powerline-multiline` theme? It doesn't have all of the fancy icons, but it's pretty nice otherwise. Maybe we can have a discussion about what features from oh-my-git you would like to see added...

**Comment by apaatsio** [comment]
@nwinkler Oh, I hadn't tried powerline-multiline :flushed:  It's really good. 

I see the remote/upstream branch name is missing in powerline-multiline (compared to oh-my-git). That would be nice to have. In my workflow I often have two remotes (`origin` and `upstream`). Therefore, the information about the remote would be useful.

**Comment by edubxb** [comment]
@apaatsio what information you need to be shown in the prompt? I have some fixes and features pending to be added to `powerline-multiline`, but any feedback is always welcome.

**Comment by apaatsio** [comment]
@edubxb Like I said, I would like to see the remote branch name.

The logic would be:

- if no remote branch -> just show the local branch name `my-branch`
- if remote branch name is the same as local branch -> show branch name and remote name: `my-branch (origin)`
- if remote branch name is different than local branch name -> show local branch name, remote name, and remote branch name `my-branch (origin:my-remote-branch)`

And the same thing as an actual use case:

1. `git checkout -b my-branch` -> shows `my-branch`
2. `git push -u origin my-branch` -> shows `my-branch (origin)`
3. `git push -u origin my-branch:my-remote-branch` -> shows `my-branch (origin:my-remote-branch)`

**Comment by edubxb** [comment]
@apaatsio I just uploaded some "improvements" that you might enjoy, and others too, of course, check it out if you have some spare time.

@nwinkler, @tswicegood, any feedback or review is welcome!

Thanks!

**Comment by nwinkler** [comment]
Wow, busy weekend!

Love your changes - good stuff! :+1:

**Comment by edubxb** [comment]
Thanks @nwinkler!

I hope this changes be useful for everyone!

**Comment by edubxb** [comment]
I will improve a bit the git information and how is displayed in themes, but for now, I think that this issue could be closed.

**Comment by nwinkler** [comment]
OK, great - closing for now.
