### ISSUE TITLE
[nvm] Use nvm from ~/.nvm

### ISSUE THREAD

**Issue by RobLoach** [Bash-it/bash-it#422]
The [packaged version of nvm](https://github.com/revans/bash-it/blob/master/plugins/available/nvm.plugin.bash) seems to re-implement a lot of what nvm does. Couldn't we just use https://github.com/creationix/nvm straight?

**Comment by tswicegood** [comment]
@RobLoach, I'd have to go back through the history to be sure, but I believe the nvm code that ships with bash-it was simply an install of the original at some point in time.  Would you want to take a stab at doing a new manual install into the available plugins directory and open up a PR with the new code?

**Comment by jawshooah** [comment]
@tswicegood Why use the `nvm` source at all? Why not follow [oh-my-zsh's example](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/nvm/nvm.plugin.zsh) and just source the user's own installation?

**Comment by nwinkler** [comment]
I've done exactly that in #612 - I'll merge this now...

**Comment by RobLoach** [comment]
@nwinkler :+1:
