### ISSUE TITLE
Completion only on first command

### ISSUE THREAD

**Issue by uloco** [Bash-it/bash-it#423]
After installing bash-it, the completion for other 'normal' commands only works on the first command. I had to add the following to the .bashrc but it should be made elsewere. I just don't know where...
```
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
```

**Comment by EvgenyOrekhov** [comment]
Same issue here. Type `sudo a`, hit [tab] - no completion at all.

**Comment by edubxb** [comment]
What OS are you using?

**Comment by EvgenyOrekhov** [comment]
@edubxb Ubuntu 15.04

**Comment by edubxb** [comment]
Can you put here the list of Bash it completions you have enabled?

Can be obtained with this command:

`$ bash-it show completions`

**Comment by EvgenyOrekhov** [comment]
@edubxb I enabled everything except conda.

**Comment by edubxb** [comment]
In Linux, packages normally include Bash completions they need, and are enabled globally for all users of the system, so you don't need to activate it in Bash it. Completions included in Bash it are more useful for Mac users, that don't have these completions activated by default when they install something via brew, or something similar.

Moreover, some apps that come in Mac are different from apps that come with Linux, Mac uses BSD command line tools and Linux uses GNU command line tools, and sometimes, the apps have incompatible flags or work in a different manner, so the completion scripts could don't work correctly in Linux, sudo is an example.

So try disabling all completions in Bash it, and only activate those that aren't included in system packages.

I'm in Debian, and I only have activated the pip completion in Bash it, the rest of completions I use come with packages I have installed.

Hope this helps.

**Comment by EvgenyOrekhov** [comment]
@edubxb thanks. Maybe you should put this in the README.md.

**Comment by edubxb** [comment]
@EvgenyOrekhov is you problem solved then? and yours @uloco?

**Comment by EvgenyOrekhov** [comment]
@edubxb nope. Disabled all bash-it completions, the problem remains.

**Comment by Cayan** [comment]
Create a file in customs for completion with the following content:
```
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi
```

**Comment by EvgenyOrekhov** [comment]
@Cayan thanks, it fixes the problem.
