### ISSUE TITLE
Remote SSH Commands - history.plugin.bash: line 3: bind: warning: line editing not enabled

### ISSUE THREAD

**Issue by notbrain** [Bash-it/bash-it#429]
I am new to bash_it and after installing I noticed that the history plugin was outputting warning when I ran commands over ssh:

    $ ssh host 'ls -als'
    /home/ubuntu/.bash_it/plugins/enabled/history.plugin.bash: line 3: bind: warning: line editing not enabled
    /home/ubuntu/.bash_it/plugins/enabled/history.plugin.bash: line 4: bind: warning: line editing not enabled`
    [...ls output as expected...]

Googling for this in other contexts wasn't clear to me so I figured it couldn't hurt to ask here. Is there a way to suppress plugins or output for non-interactive shells? Is there some ssh_config I can use to suppress these warnings?

Thanks!

**Comment by notbrain** [comment]
I am able to (sort of) fix it by calling `echo -e '\0033\0143'` after each bind inside the history plugin, but it also resets the terminal buffer as if I had `ctrl-l`'d, which isn't so bad but want to know if there's a cleaner way to enable the history plugin without this.

File: history.plugin.bash
    # enter a few characters and press UpArrow/DownArrow
    # to search backwards/forwards through the history
    bind '"^[[A":history-search-backward'
    echo -e '\0033\0143'
    bind '"^[[B":history-search-forward'
    echo -e '\0033\0143'

**Comment by nwinkler** [comment]
A short term workaround would be to disable the history plugin:

```
bash-it disable plugin history
```

You can pretty much get the same results using `Ctrl+R` - or do you absolutely rely on the up/down arrow keys for this?

**Comment by ezander** [comment]
Have you tried `set -o emacs` or `set -o vi` into the history plugin?
