### ISSUE TITLE
Origional .bashrc

### ISSUE THREAD

**Issue by MessC** [Bash-it/bash-it#438]
Hi, I accidentally erased something and want to do a reinstall of this.  After I removed everything in the .bashrc that was associated with the install I lost my aliases and other stuff that used to load by default? I'm not the greatest with this stuff any help would be great!  I lost my customized colors and my aliases?

**Comment by MessC** [comment]
never mind I see the .bash_profile.bak file

**Comment by nwinkler** [comment]
Closing since this seems to be resolved.
