### ISSUE TITLE
General debugging How-To?

### ISSUE THREAD

**Issue by miketheman** [Bash-it/bash-it#439]
Hi there!

I've been trying to debug where and when things are happening during a profile load - and couldn't find any methods for debugging bash-it loads, and wondered if I'm just not looking in the right place.

Things I'm trying to ascertain:

- file/load order
- commands executed at each point (like `set -x`)
- timing of plugins/modules

I really enjoy the project and would love to help if this isn't already in the code somewhere, point me where I'd need to look!

**Comment by nwinkler** [comment]
Take a look at the `bash_it.sh` file in the project's root folder, this is the entry point. It first loads the files from the `lib` folder and then proceeds with loading the enabled aliases, plugins and completions. The `lib/helpers.bash` file has most of the functions used for loading the individual files.

I don't think there's any debugging functionality in there at the moment, feel free to add one, ideally enabled through an environment variable or something like that.

Example:

```
BASH_IT_DEBUG=1 reload
```
