### ISSUE TITLE
Installation Instructions not working

### ISSUE THREAD

**Issue by zeebluejay** [Bash-it/bash-it#443]
I'm trying to install Bash-it on OSX. When I try to install Bash-it using the install instructions, I see errors, esp. when it tries to install plugins, aliases and completion. 

The install script expects them to be under "plugins", "aliases" and "completion" directories respectively. But when I look at the directory structure in Github, the files are under "available" directories, instead. I'm thinking this breaks the install script.

I don't want to manually change the install script. Looks like the installation is broken.

Thanks
ZeeKay

**Comment by nwinkler** [comment]
Can you be more specific as to the errors you're seeing? Please provide the following:

* Which directory did you clone Bash-it into?
* Please show the clone command that you used.
* Which options are you selecting in the install script (none/all/some)?
* Please show the error message printed by the install script.

BTW: The install script specifically references the `available` directory, e.g. on line 24: https://github.com/Bash-it/bash-it/blob/master/install.sh#L24, also on lines 39 and 47.

Let me know what you're seeing.

**Comment by gamaralf** [comment]
I had the same "problem". 

Installation instructions say you should use a directory called "`~/.bash_it`" (note the underscore) but instead I used "`~/.bash-it`" (note the dash).

As the name of the git repository is `bash-it` (dash), I believe it is not hard to make the same mistake I (and zeebluejay) did.

**Comment by ipoval** [comment]
@gamaralf, did it happen because you didn't see the whole string
`git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it` on the same line?
if so, maybe readme can use shortcut `git clone --depth=1 https://git.io/bash-it ~/.bash_it`, but I'm not sure

**Comment by gamaralf** [comment]
@ipoval, it happened because I did not copy&paste from the instructions. I was reading them from a tablet and typing them on a computer terminal.

Anyway, I think the installation directory should be  `bash-it` (dash), just like the name of the project. I see no reason to change the "-" to a "_".

**Comment by edvinasme** [comment]
Additionally, we should follow $XDG_CONFIG_HOME variable and have an ability to have it under `~/.config/bash_it` (or `~/.config/bash-it` if the author insists). I have made an issue #519 for this.

**Comment by nwinkler** [comment]
Other install locations are now supported as well.
