### ISSUE TITLE
Provide Update Instructions

### ISSUE THREAD

**Issue by philbritton** [Bash-it/bash-it#445]
Love the project, but I'm always afraid to update and risk losing my settings.  Can you help out by providing instructions or an update script?

**Comment by nwinkler** [comment]
What are you looking for exactly? If you do the update through Git, you shouldn't lose any settings.

If you run `git pull` in the `~/.bash_it` folder, it will simply pull the latest version from GitHub, it shouldn't remove anything.

Your local settings are your `~/.bash_profile` or `~/.bashrc` file (depending on the OS), and in your custom scripts - these are not overwritten by Git. There's no need to run the install script again if you have run it previously - the only update you need is to run `git pull`.

For keeping track of my `.bash_profile`, I'm using [Homesick](https://github.com/technicalpickles/homesick). All of my files are backed up into my [Dotfiles](https://github.com/nwinkler/dotfiles) repo.

Does that make sense?

**Comment by philbritton** [comment]
perfect, makes sense, thanks man
