### ISSUE TITLE
Not an issue but helpful func for who use docker

### ISSUE THREAD

**Issue by jujubha** [Bash-it/bash-it#469]
Assuming there are containers running and has configured sshd and it is running(don't forget pam_loginuid.so optional stuff for docker). 

I think it would be helpful for people who runs multiple containers with distinctive names.
basically 
you just ssh into the container with the below command

ssh ${DOCKER}_preciousstone

and have this put in .profile/.bashrc/.bash_profile

for VAR in $(docker ps | perl docker-ps-list | cut -d '|' -f 7); do
  XVAR=DOCKER_$(echo $VAR| sed 's/-\|_//g')
  export $XVAR=$(docker inspect "$VAR"| grep "IPAddress" | cut -d ':' -f 2 | cut -d '"' -f 2)
done

#below is docker-ps-list 
#!/usr/bin/perl

my $line = <STDIN>;

my $CONTAINER_ID = index($line, 'CONTAINER ID', 0);
my $IMAGE        = index($line, 'IMAGE', 0);
my $COMMAND      = index($line, 'COMMAND', 0);
my $CREATED      = index($line, 'CREATED', 0);
my $STATUS       = index($line, 'STATUS', 0);
my $PORTS        = index($line, 'PORTS', 0);
my $NAMES        = index($line, 'NAMES', 0);

my $CONTAINER_ID_W = $IMAGE        - $CONTAINER_ID;
my $IMAGE_W        = $COMMAND      - $IMAGE       ;
my $COMMAND_W      = $CREATED      - $COMMAND     ;
my $CREATED_W      = $STATUS       - $CREATED     ;
my $STATUS_W       = $PORTS        - $STATUS      ;
my $PORTS_W        = $NAMES        - $PORTS       ;
my $NAMES_W        = length($line) - $NAMES       ;

my $template = 'A'.join('A', $CONTAINER_ID_W, $IMAGE_W, $COMMAND_W, $CREATED_W, $STATUS_W, $PORTS_W).'A*';

while(my $line = <STDIN>) {
  $line =~ s/(\r|\n)$//g;
  my ($CONTAINER_ID_VAL, ,$IMAGE_VAL, ,$COMMAND_VAL, ,$CREATED_VAL, ,$STATUS_VAL, ,$PORTS_VAL, ,$NAMES_VAL) = unpack($template, $line);
  print join('|', $CONTAINER_ID_VAL, ,$IMAGE_VAL, ,$COMMAND_VAL, ,$CREATED_VAL, ,$STATUS_VAL, ,$PORTS_VAL, ,$NAMES_VAL)."\n";

}

**Comment by nwinkler** [comment]
Can you provide an example of how this would be used? If it makes sense, it could go into the docker plugin...

Feel free to provide a pull request with instructions on how to use/test it.

**Comment by jujubha** [comment]
Basically, presumably there are containers running with network configured and sshd is running inside the container.

If you know the name of the container but to find the IP address for the container isn't difficult (you can still do with docker inspect) but it is just simple shorthand hot find the IP and setting up few environment variables with the IP address for each container with their respective IP would definitely ease the burden of running all the commands to find the IP.

Instead running the above script along with the perl script would make the environment variables with settings like

DOCKER_fedora=172.17.42.2
DOCKER_mysql56ubuntu=172.17.42.3

Then the current user can login simply with the below command

ssh $DOCKER_fedora

or to any other container with the environment variable instead of running docker inspect and find the IP and then ssh into it or even do anything else.

Hope this helps.

**Comment by nwinkler** [comment]
Thanks, that makes sense. Feel free to create a PR to add this to the docker plugin.

**Comment by jujubha** [comment]
Will let you know once ready

**Comment by jujubha** [comment]
Create a PR and waiting for your review

**Comment by nwinkler** [comment]
Closing to continue the discussion in #475
