### ISSUE TITLE
compdef

### ISSUE THREAD

**Issue by SolarAquarion** [Bash-it/bash-it#473]
In git.completions bash is fucking up

**Comment by edubxb** [comment]
Can you explain a little more the exact problem you have?

Thanks!

**Comment by SolarAquarion** [comment]
bash: type: compdef: not found

compdef is only found in one package

**Comment by nwinkler** [comment]
Which OS? What happens when you type `compdef` in your terminal?

**Comment by SolarAquarion** [comment]
Arch Linux bash: compdef: command not found

**Comment by nwinkler** [comment]
This code should actually never be called. The `compdef` part is in an if block that should only be executed when using `zsh`:

https://github.com/Bash-it/bash-it/blob/master/completion%2Favailable%2Fgit.completion.bash#L2648

`compdef` is a `zsh` command, it's not available in bash. The question is why your machine executes that piece of the code...

Can you post the output of `echo $ZSH_VERSION`? The presence of that variable seems to trigger that part of the code? When running Bash, you shouldn't have that variable defined.

**Comment by SolarAquarion** [comment]
5.0.7

**Comment by SolarAquarion** [comment]
zsh 5.0.7

**Comment by nwinkler** [comment]
Why is that variable set? Are you sure you're only running Bash? You're not running Bash-it inside of zsh in some way?

**Comment by SolarAquarion** [comment]
I changed to zsh to see what's going on

**Comment by nwinkler** [comment]
Can you open a new Terminal window with Bash and see whether you're still getting the same error? Or is it just because of having opened zsh in the same window previously?
