### ISSUE TITLE
RFC: swap CWD and SCM in powerline themes

### ISSUE THREAD

**Issue by jitakirin** [Bash-it/bash-it#485]
It seems a bit more intuitive to me if CWD info and SCM info were swapped, i.e. to have CWD first and SCM second in the prompt.  That way it reads like "I'm in some working tree and on some branch".

Let me know if you would be open to swapping them around and I can implement that change.

**Comment by edubxb** [comment]
I think that this type of changes are very personal, a great feature could be the possibility to change the order of all (or almost all) sections of the prompt.

Another simple way could be adding a "switch" (variable), to let the user choose the position of the path section, first or last.

**Comment by nwinkler** [comment]
Agreed - we will never be able to make everyone happy if we switch the order for all users. A flag to determine the order would be great - Pull Requests are welcome :smile:

**Comment by jitakirin** [comment]
Fair enough, I'll take a look at making it customisable.
How about we trigger another function, say ``powerline_prompt_command_customise`` if it exists, at the end of ``powerline_prompt_command`` in order to allow it to modify/redefine PS1?

**Comment by nwinkler** [comment]
Where would a user define this function if they want to customize the prompt?

**Comment by jitakirin** [comment]
Most likely in a file in ``$BASH_IT/custom/``, but could also be a plugin if someone wanted.

**Comment by edubxb** [comment]
@ljfranklin, I just make a PR https://github.com/Bash-it/bash-it/pull/605 that allows "reorder" the prompt information, so you now can put the CWD info first.

**NOTE**: for the moment, only done in the powerline multiline theme
