### ISSUE TITLE
Removing bash-it

### ISSUE THREAD

**Issue by sangimed** [Bash-it/bash-it#486]
There is no steps to follow to remove bash-it in the doc.

**Comment by nwinkler** [comment]
I'll take a stab at adding something in the next couple of days...

**Comment by abbshr** [comment]
@sangimed  just `cp .bashrc{.bak,}` or `cp .bash_profile{.bak,}`, isn't it?

**Comment by nwinkler** [comment]
The `uninstall.sh` script takes care of this now.
