### ISSUE TITLE
New feature - Search for missing dependencies on install / load

### ISSUE THREAD

**Issue by TCMiranda** [Bash-it/bash-it#491]
Hello!

In addition to: [New feature - Installation with config file](https://github.com/Bash-it/bash-it/issues/490)

Wouldn't it be nice to use [pacapt](https://github.com/icy/pacapt) to require missing apps at installation or load, if the plugin/alias/completion is enabled (if the user agrees)?

I would be glad to help if so!

Thanks

**Comment by nwinkler** [comment]
This looks interesting!

One thing we need to be careful with is with installing too much. One of the current dangers of the installation script is the `all` option. Many people seem to use this without really needing all of the functionality. When using `pacapt`, we would potentially install lots of dependencies that most people might never use.

I would prefer to take a closer look at the install script first. Maybe we should remove the `all` option and rather use a meaningful set of defaults (like the `base` plugin and the `bash-it` completion)...

@tswicegood @edubxb What do you think?

**Comment by TCMiranda** [comment]
I agree, it could cause problems with the "all" option, it happened to me, by the way.
I am like "Plugins? Yeah, i want them all!"

I don't think that enabling only a few could be bad, by default, and another option would be to use the "some" option.

Maybe, at installation, we can tell that the user may "enable support for some applications, with plugins" or something like that.

About requiring dependencies, the way i see, to not cause much problems, would require only manually defined repositories, containing a header "YUM" or "APT" at the plugin definition. 

That way, this feature would be supported progressively.

But if we make it right, when the user says 

    "bash-it enable plugin tmux"

bash-it would respond 

    "tmux is not installed in your system, do you want to install it now?"

this is also nice with the config file, mentioned above, because someone could define the apps that he works with, and when installing bash-it on a new machine, we can also install stuffs that he uses.

**Comment by edubxb** [comment]
Auto-installing things is a very "intrusive" option, IMHO, any person interested in install and use Bash-it is able to install any necessary dependency. 

Another point to consider is the "prefered" method to install, for example, in Linux, some people could prefer use pip to install a python app rather than the system package manager.

Furthermore, the variety of supported platforms, versions, packages managers, etc. is too wide to support and maintain all (with bash scripting).

**Comment by TCMiranda** [comment]
Yes, you are right.

I think that we would might figure out a good way to make it work, but it would be specific, optional, and very clear that it would install it via the system package manager, if available.

Another point is that i think that we would never support all, and also, not all plugins would require the option. But contributors could help to improve the information about the plugin, with the package headers.

Is now the right time for this, what you think?

I think that a good point that we've made here, is that the installation needs to be more clear. Meanwhile, i agree to remove the "all" option, maybe defining some to be a "default package", with common apps, "none" or the "detailed" which asks the user.

**Comment by NoahGorny** [comment]
I am against auto installing like that, also, `Bash it` currently offers a limited set of configs at installation. We can maybe remove `all` from `enable` in the future
