### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by kekumu** [Bash-it/bash-it#512]
Is there a particular reason? Some of the individual plugins contain licenses, but most of the stuff is unlicensed.

**Comment by thedrow** [comment]
No reason. We'll probably pick something very permissive.

**Comment by jeffeb3** [comment]
+1. Please add something, MIT, BSD, GPL2. There are some great ideas in here, but ambiguously licensed stuff can really be poison. At least to people who care about that kind of thing. Many people work for people who care about that kind of thing...

**Comment by nwinkler** [comment]
Good question. I guess the biggest problem is finding a license that works for all of the content. As mentioned earlier, some of the files contain licensed content, e.g. the Git Completion file has a GPL2 header.

I'm not a lawyer - I simply don't know what it would mean to slap something like an MIT license on the whole repo, if it already contains content licensed under GPL...

**Comment by thedrow** [comment]
You can dual license.
We just need to add a license for bash-it code and an excerpt for each code that isn't our own.

**Comment by ontherunvaro** [comment]
If there's GPL2 plugins we're basically stuck with GPL2. Dual licensing doesn't work with things that are statically linked (in this case, literally included in the project) as far as I know.

**Comment by ontherunvaro** [comment]
By the way, there's this nifty license calculator: http://operaciones.cenatic.es/comunidad-legal/CalculadorLicencias/licencias (it's in spanish, mind that) that will, given the licenses that are contained in the project, output which licenses you can apply to the project as a whole.
Statically linked ("_Estáticas_") in that page are software that is directly distributed with our project, in this case for example the git completion file. Dynamically linked ("_Dinámicas_") are those that are not distributed with it, but are used by it. That would strictly include `bash` in this case, which is GPLv3 and impossible to combine with GPLv2, but we probably are better off ignoring that.

**Comment by kekumu** [comment]
Unfortunately, any contributions that didn't specify a license explicitly
(like some plugins) are still under the contributor's sole copyright.

Most projects that get to this point will decide on a license and then
email all contributor's for permission to put their past contributions
under that license.

**Comment by andschwa** [comment]
I'd really appreciate a license on this repo. I'd like to reuse bits of it in my own repo, but am a bit uncomfortable doing so without proper licensing.

**Comment by nwinkler** [comment]
Thanks for the feedback. I am not a lawyer, and don't have the time to figure out what kind of license would work with all the contributions...

So what about using something like GPL v2 for Bash-it? Any concerns?

CC @revans @tswicegood @edubxb @thedrow

**Comment by thedrow** [comment]
I don't think there's a problem with it.
It's not like someone is going to try to commercialize this framework.
We'd have to get permissions from all authors though.

**Comment by ontherunvaro** [comment]
If I may, I'd go for GPLv3, there's no real reason to pick GPLv2 if the whole project is going to be re-licensed anyway.

**Comment by nwinkler** [comment]
What would a process look like to get permission from all authors? Go back through the commit history and email every single author? That's going to be a lot of work... And I'm pretty sure that plenty of people will not respond - what to do in this case?

**Comment by jeffeb3** [comment]
I bet there's a slick way to query for email addresses of all the commits in master. I'm not at my computer, but I'm sure there's some combination of git blame or git log with awk. Once someone is unreachable, then you have a lot of work. What did they commit? Can we remove it? Is anything else derivative of it?

I also don't think commercialization is that unlikely. No one will sell bash-it at Staples, but it might be included in a commercial distro or as part of a NAS or embedded system. Especially parts of it, like docker stuff or git stuff. It's very easy for companies to include all kinds of software if it has a forgiving license. I don't think that's a bad thing. Most contributors probably just want to share the joy and give something back.

Personally, I think gpl V3 might be much more restrictive than necessary. BSD or MIT is the way to go. A lot less controversy. I haven't contributed anything besides bringing up this issue, so feel free to disagree. That's just my $0.02.

**Comment by nwinkler** [comment]
In general, I agree - I'm much more in favor of MIT or BSD as a license. On the other hand, there is some content in Bash-it that is using GPL (e.g. the Git completion file), so we need to be careful.

Regardless of that, I simply don't have the time to do this. I maintain this project in my free time, and I won't have time to track email responses and chase people up if they don't respond.

Here's a call for contribution: If someone really wants to have a license added to Bash-it, please feel free to initiate the communication with past contributors, review the code for possible conflicts, contributions from other sources that have a license, and so on...

**Comment by thedrow** [comment]
@nwinkler That's exactly what DataStax did when they bought an open source python client.
If anyone is going to do this, just contact an FSF lawyer to help with the process.

**Comment by tswicegood** [comment]
FWIW, I think we'd need to look at a multi-license solution for this (like what jQuery did all those years ago) to cover our bases. I also think given that so many parts of this are brought together from other packages with other licenses it'd be nearly impossible to get it right.

**Comment by adborden** [comment]
Ping, I think it would be good to get a license on this. You don't have to work out all the issues to say that everything going forward is under X license. I would add headers to individual files that are not X license, and go from there. Since there's somewhat of a plugin architecture happening here, you don't necessarily have to have everything on the same license. Asking for compliance help on this is a great idea, but don't let it block you from choosing something going forward.

I'm a GPL fan, so GPLv3 would be my vote. LGPL might also be good because it "plays well" in a mixed-license environment.

**Comment by nwinkler** [comment]
@adborden Thanks for the note. Like I said before, I support this request in general - it would be good to have a license on this project.

On the other hand, I simply don't have the time to do this. If you really really want to have a license on this, then I suggest that you coordinate with some of the other people requesting a license to be added in this thread, and work out the details (contacting contributors, adding headers, etc.).

**Comment by trmaphi** [comment]
Speaking of license, if this project need to put under one specific license. I proposed at start using link to raw file content instead of putting content under this repo.

**Comment by cornfeedhobo** [comment]
Hah. Some of the questions in this thread make my head spin and want to walk away from the internet for a day.

After some nightmares dealing with corporate lawyers, here is my $0.02; We can pick something _extremely permissive_, such as MIT, and like @trmaphi suggests, scrub the repo of embedded content, opting for linking to files installed by the system's package manager instead. Done.

As for getting the work done, it would be nice if one of you that is passionate about this subject would collect all the instances of embedded content and open issues accordingly. Finally, open a PR to add a LICENSE file, once all the issues have been addressed.

**Comment by nwinkler** [comment]
Thanks for commenting on this, @cornfeedhobo! If someone would like to pick this up, let me know!

**Comment by NoahGorny** [comment]
Hey folks, Bash-it now have MIT license, so if this was a problem preventing you from using/contributing- I hope your concerns are resolved now :smile:
