### ISSUE TITLE
git rebase problem

### ISSUE THREAD

**Issue by hanskoff** [Bash-it/bash-it#516]
Hi, since some time I'm using bash-it - it's cool
but today I wanted to rebase on branches and see following error

```✓| → git rebase -i master
/usr/local/Cellar/git/2.4.5/libexec/git-core/git-rebase--interactive: line 245: -w: command not found
Could not execute editor```

can you help?
I've tried without success `git config --global core.editor "vim"`

**Comment by nwinkler** [comment]
Where do you see Bash-it involved in this? Does the same work in a terminal when you're not using Bash-it?

**Comment by nwinkler** [comment]
Question: Do you have the `textmate` plugin enabled? It tries to use `$(which mate) -w` as the Git editor.

Try disabling the textmate plugin:

```
bash-it disable plugin textmate
```

Then please try the rebase again.

**Comment by hanskoff** [comment]
wow that was fast ;)
So problem doesn't occur when I use my previous bash settings.
And thank you for tip for disabling `textmate` - it helped ;)

**Comment by nwinkler** [comment]
Great, good to hear!
