### ISSUE TITLE
Uninitialized constant Gem (NameError)

### ISSUE THREAD

**Issue by Shazer2** [Bash-it/bash-it#518]
Hi!

When I open a new terminal using bash_it, I get the error at the top "Uninitialized constant Gem (NameError)". Just wondering what I should do to resolve this?

Thanks

**Comment by nwinkler** [comment]
Which plugins/completions do you have enabled? Anything related to Ruby or Gem? Do you have `rb` and `gem` on your path? If not, you should probably disable the ruby plugin.

Also, which theme are you using?

**Comment by Shazer2** [comment]
I'm using powerline theme. I just enabled the defaults when I was setting bash-it up! How do I disable the ruby plugin?

**Comment by nwinkler** [comment]
Try this:

```bash
bash-it disable plugin ruby
bash-it disable completion gem
reload
```

**Comment by Shazer2** [comment]
Perfect. Thank you!

**Comment by nwinkler** [comment]
Is the error gone? If so, please feel free to close this ticket.
