### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by iRitwik** [Bash-it/bash-it#520]
How do I uninstall bash-it? Is there a script provided in the repository?

**Comment by nwinkler** [comment]
No script at the moment - sorry.

If you have installed using the `install.sh` script, you should be able to simply restore your `.bashrc` or `.bash_profile` file, which has been backed up by the installer.

Depending on your OS, you should have the following in your home directory:

* Mac OS X: `~/.bash_profile.bak`
* Linux: `~/.bashrc.bak`

Let me know if that helps...

**Comment by nwinkler** [comment]
Bash-it now has an uninstall script, which will restore your previous profile.

**Comment by McKid** [comment]
Thank you rmwinker.  Where could I find the uninstall script?

Also, I tried Mac OS X: ~/.bash_profile.bak received response :Permission denied.

Thank you

**Comment by edubxb** [comment]
The uninstall script is in the Bash-it home:

```
~/.bash_it/uninstall.sh
```
