### ISSUE TITLE
pyenv stopped working

### ISSUE THREAD

**Issue by thedrow** [Bash-it/bash-it#524]
pyenv no longer works on my shell with the pyenv plugin.
I think it started after https://github.com/Bash-it/bash-it/commit/dabf0e8c42027ae83e3ae0eea26ed610062c1932

**Comment by nwinkler** [comment]
Can you compare the $PATH before after this change? The `pathmunge` function should do the same thing as the other literal path manipulation...

**Comment by thedrow** [comment]
I can try to find a version where this works. I'll give it a shot tomorrow.

**Comment by nwinkler** [comment]
Could this be related to #532? @haomingz provided a fix for the Pyenv path...

**Comment by thedrow** [comment]
Yes, that was the problem exactly. Thanks.
