### ISSUE TITLE
installing bash-it on remote server causes sftp to fail

### ISSUE THREAD

**Issue by mcampo84** [Bash-it/bash-it#530]
I installed bash-it on my development server to help give me more insight into my git status/branches/etc. When I try to connect via sftp, I receive an error: "Received message too long"

I suspected bash-it was the cause, so I uninstalled it and tried to sftp again, and had no issues. When I re-installed to confirm my suspicions, I received the same error.

**Comment by nwinkler** [comment]
Which OS? And which file was created by the installer? `~/.bashrc` or `~/.bash_profile`?

**Comment by mcampo84** [comment]
OS is Red Hat Enterprise Linux Server release 5.11 (Tikanga)

installation creates ~/.bashrc

**Comment by nwinkler** [comment]
I'll give this a try on Monday on one of my servers...

**Comment by nwinkler** [comment]
I don't have this problem, it works fine for me. With a quick search, I found the following:

http://serverfault.com/questions/485487/use-bashrc-without-breaking-sftp

This indicates that if there is any output generated by the `.bashrc` file, it will confuse sftp. Can you do the following:

* Log in to the server through SSH
* Check whether there are any messages printed when you log on, e.g. from one of Bash-it's plugins, if a command is not found or anything like this.
* Disable all Bash-it plugins, aliases and completions:

```
bash-it disable aliases all
bash-it disable completions all
bash-it disable plugins all
bash-it enable completion bash-it
```

* Try logging in again to check whether any error messages are gone now.
* Once the login works without any messages, try SFTP again.
* Start enabling aliases, completions and plugins one by one, only the ones you really need.

Let me know if that works...

**Comment by mcampo84** [comment]
I wasn't seeing any output from .bashrc, but your advice worked. Thanks!

**Comment by nwinkler** [comment]
Good to hear! Which part worked? Disabling the plugins?

**Comment by mcampo84** [comment]
Yeah, disabling everything, basically. I'm going back in one-by-one and adding everything to see what the root cause was. I'll report back once I identify the culprit. At least on my end.

**Comment by nwinkler** [comment]
OK, cool. It's probably a plugin where you are missing the underlying executable and it's causing an error during startup.

Please report back, so we can fix the plugin - it should really test whether the executable is there.

**Comment by mcampo84** [comment]
OK, so I ran through all the plugins, and here are my results:

chruby_auto => gives bashrc output, sftp OK
chruby => output, sftp OK
fasd => NO output, sftp error
less-pretty-cat => output, sftp error
postgres => output, sftp OK
pyenv => output, sftp OK
rbenv => output, sftp OK
virtualenv => output, sftp OK

**Comment by nwinkler** [comment]
Which output are you seeing from `less-pretty-cat`?

**Comment by mcampo84** [comment]
I get the following:

/usr/bin/which: no pygmentize in (/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin)
Pygments is required to use this plugin
Install it by doing 'pip install Pygments' as the superuser

**Comment by nwinkler** [comment]
Thanks - I'll take a look at this!

**Comment by nwinkler** [comment]
I've made a change to the `less-pretty-cat` plugin in #533 - can you try whether this fixes the issue for you? The plugin shouldn't show an error or a message anymore...

**Comment by mcampo84** [comment]
Yeah, that worked.

**Comment by nwinkler** [comment]
Fantastic! I'll take a look at the `fasd` plugin as well... I'm not using that personally, but I'll give it a try to see what's wrong...

**Comment by edubxb** [comment]
The [upstream fasd](https://github.com/clvv/fasd/) differs from the version that comes with Bash-it, I suggest upgrading it to match the upstream before trying to fix this issue, what do you think about @nwinkler?

**Comment by nwinkler** [comment]
Yes, agreed, @edubxb

**Comment by edubxb** [comment]
I just started to use fasd, I will try to upgrade it, and do a PR with the new version.
