### ISSUE TITLE
protocol error: unexpected <newline>

### ISSUE THREAD

**Issue by norbertosoriano** [Bash-it/bash-it#535]
When trying to copy (using scp) a file from A (has bash-it installed) to B, I get an error:

protocol error: unexpected <newline>

Tracing back the error, there seems to be problems with some plugins that print out (echo) information which ssh protocol considers as not valid.

E.g. NVM plugin prints out "echo NA".

**Comment by nwinkler** [comment]
Seems to be similar to #530 - can you check the solution described there (disable all plugins, then enable only the ones you really need or have installed)?

I've had a look at the `nvm` plugin - it seems to do stuff even when nvm is not installed locally. I'll add a huge `if` statement around that...

**Comment by nwinkler** [comment]
Looking at the `nvm` plugin - it seems like it's a really old version of https://github.com/creationix/nvm. I'm not sure why we're keeping a copy of this in the repo...

@tswicegood @edubxb - what's your opinion on this? Same as for the `fasd` plugin - do we want to keep copies of this tools in Bash-it? It sounds like a maintenance nightmare to me - we will never be able to keep up with updates...

**Comment by nwinkler** [comment]
On OS X, I can install `nvm` using `brew install nvm` - I prefer this to having an outdated version here... It then tells me to do the following, which might be difficult to capture in a Bash-it plugin:

```
source $(brew --prefix nvm)/nvm.sh
```

**Comment by norbertosoriano** [comment]
@nwinkler thank you for your comments. So, I've disabled all plugins and enabled only those ones needed, and by this I've managed to have a stable environment, but I don't think this should be the approach taken in order to have a stable bash-it environment.

**Comment by nwinkler** [comment]
Sure, I completely agree. I guess you selected the `all` option during the installation, right? This will enable everything, and we have seen that this is causing many issues for some people.

I'm in the process of updating the install script to use a sane default of plugins to minimize the risk of causing issues. This will hopefully streamline things...

**Comment by edubxb** [comment]
@nwinkler I agree with you, probably is a bad idea trying to maintain plugins that really are tools maintained with other people and "inlcuded as is" in Bash it.

Removing these "plugins" could be the best option.

**Comment by tswicegood** [comment]
Just catching up on an old thread (via #611). If we start removing things like this, let's change it to include output when its sourced explaining that it's been removed and how to disable the warning.

**Comment by nwinkler** [comment]
:+1: 

To be really useful, the `nvm` plugin should only do the following, which is to load the local `nvm` installation:

```bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

I agree, to keep things compatible, maybe we should check for the presence of the `nvm` command in this case, and if it can't be found, we create a simple function which just prints a message saying that you should install it using the documented `nvm` install instructions. This way, people would be aware of the change.

I'll take a stab at implementing this for the `nvm` plugin...

**Comment by nwinkler** [comment]
I've given this a try in #612 - please feel free to take a look, @tswicegood @edubxb 

Not sure if the wording is the best, but the general idea should be clear.
