### ISSUE TITLE
RVM and Bash-it => "Warning! PATH is not properly set up..."

### ISSUE THREAD

**Issue by fusillicode** [Bash-it/bash-it#544]
Hi guys, I'm trying to solve a problem I'm getting with RVM and Bash-it. 

Here it is:
```
Warning! PATH is not properly set up, '/home/user/.rvm/gems/ruby-2.2.1/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.1'.
```

I found another open issue (from last year...) stating that the problem was related to the node plugin. Unfortunately even if I disable the node plugin I still get the over presented warning.

I know that it could be silenced but before I want to know if there is something wrong with my configuration or if it is still a known and unsolved issue.

Cheers.

**Comment by nwinkler** [comment]
Can you share the contents of your `$PATH` variable?

**Comment by fusillicode** [comment]
Here I am, sorry for the lateness of my response.

Sure here it is:

`
/home/me/bin:/home/me/.rvm/gems/ruby-1.8.7-p302/bin:/home/me/.rvm/gems/ruby-1.8.7-p302@global/bin:/home/me/.rvm/rubies/ruby-1.8.7-p302/bin:/home/me/.rvm/bin:/home/me/.rbenv/bin:/home/me/.pyenv/bin:./node_modules/.bin:/home/me/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/opt/nginx/sbin:/home/me/.gem/ruby/2.1.0/bin:/home/me/.bash_it/plugins/available/todo
`

Btw just for now I've put `rvm_silence_path_mismatch_check_flag=1` inside the `.rvmc` in my home.

**Comment by nwinkler** [comment]
I don't know (or use) `rvm`, but I find it strange that you have several versions of `/home/user/.rvm/gems/ruby-x.x.x/bin` on your PATH - that looks wrong. Also, the `ruby-2.2.1` version that you show in the original error doesn't show up in your PATH at all...

What does your $PATH look like when you are not using Bash-it?

**Comment by fusillicode** [comment]
The `ruby-2.2.1` doesn't show up because right now I switched to 1.8.7-p302.

Anyway when I'm using a vanilla config the PATH is:

`/home/user/.rvm/gems/ruby-1.8.7-p302/bin:/home/user/.rvm/gems/ruby-1.8.7-p302@global/bin:/home/user/.rvm/rubies/ruby-1.8.7-p302/bin:/home/user/.rvm/bin:/home/user/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin`

**Comment by nwinkler** [comment]
OK, so it's just the `/home/usr/bin` at the beginning of your PATH that's causing the trouble...

**Comment by fusillicode** [comment]
Yes so it seems but sincerely I don't know where it get set up by Bash-it :(

To tell the truth I didn't check every single plugin...my bad :(

**Comment by nwinkler** [comment]
Can you check the following files to see if that's being added to your $PATH at one point? Check for patterns like

* `export PATH=...`
* `pathmunge ~/bin`

Check the following files:

* `~/bash_profile` or `~/.bashrc`
* `~/profile`
* `$BASH_IT/custom/*` - these scripts are executed after all of the plugins have been loaded. It's likely that `~/bin` is prepended to the PATH in a file in this folder.

**Comment by fusillicode** [comment]
Thank you very much for your support I'll check as soon as I can and let you know.

Thank you again :)

**Comment by nwinkler** [comment]
You're welcome - let me know if you find anything...

**Comment by fusillicode** [comment]
Ok I've found `export PATH=` in:

`~/.bash_it/lib/helpers.bash # line 375 and 377`
`~/.bash_it/plugins/available/nvm.plugin.bash: # line 195`

`pathmunge ~/bin` isn't found anywhere.

But you know what, inside of `.profile` I've found this nice snippet of code: 

```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```

I briefly tried to remove it and open a new terminal and it seems to work ;)

Thank you really a lot and sorry for the bother.

**Comment by nwinkler** [comment]
Good to hear that you've found it. To be on the safe side, you might want to change the setting of the path to

```
PATH="$PATH:$HOME/bin"
```

This will ensure that `~/bin` is on your path, just not at the front.

**Comment by fusillicode** [comment]
Sure I got that ;)
