### ISSUE TITLE
Weird Digits showing up in prompt

### ISSUE THREAD

**Issue by lacykerel** [Bash-it/bash-it#552]
<img width="333" alt="new" src="https://cloud.githubusercontent.com/assets/3173546/9412556/ed897764-47f1-11e5-926c-dddb5bb84ab6.png">

Not sure why I'm getting those characters, can anyone shed some light on this?

**Comment by edubxb** [comment]
Are you asking for `U:5` and `?:1`?

The first one are the files you have *unstaged*  in your git repo, the second one, are the number of *untracked* files in your git repo.

This information is obtained with `git status`, let me show you an example:

    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

	     modified:   file1
  	     modified:   file2
  	     modified:   file3
  	     modified:   file4
  	     modified:   file5

    Untracked files:
      (use "git add <file>..." to include in what will be committed)

	    file6

    no changes added to commit (use "git add" and/or "git commit -a")

A little explanation of this behavior can be found in the [README](https://github.com/Bash-it/bash-it#git-repository-info-in-the-prompt).
