### ISSUE TITLE
How do I completely remove bash-it ?

### ISSUE THREAD

**Issue by anweshknayak** [Bash-it/bash-it#554]
Upon Terminal Startup I get this issue.
bash: /home/iiita/.bash_it/bash_it.sh: No such file or directory

$sudo -i
Please install argcomplete to use conda completion
-bash: /usr/local/share/chruby/chruby.sh: No such file or directory
-bash: /usr/local/share/chruby/auto.sh: No such file or directory
-bash: /usr/local/share/chruby/chruby.sh: No such file or directory

I can't even change to root permission.

I did uninstall bash-it ? How to restore back. I had no backup.

**Comment by edubxb** [comment]
Can you put here the content of your .bashrc and/or .bash_profile?

**Comment by nwinkler** [comment]
Simply rename your `~/.bash_profile` (on Mac OS X) or your `~/.bashrc` (on Linux), and you should be good.

It looks like you removed the `~/.bash_it` folder, but your user profile's dotfiles still refer to it.

BTW: The current version of the `uninstall.sh` script should have taken care of that. It will revert/remove the files in question in a safe manner.

**Comment by anweshknayak** [comment]
https://gist.github.com/marioBonales/1637696 Here is the default code I tried to put back in ~/.bashrc. Still of no help.

**Comment by nwinkler** [comment]
Can you provide the following information:

* Which operating system are you using?
* What's the content of `~/.bash_profile`?
* The output of `grep "bash_it.sh" -s ~/.*`

These should help us to find the culprit.

**Comment by anweshknayak** [comment]
1.OS: Ubuntu 12.04 LTS
2. Seems like it is empty. I use Linux so ~/.bashrc --> https://gist.github.com/marioBonales/1637696
I tried to put in the default code and replaced the bash_it profile which still existed after removal.


3. Binary file /home/iiita/.bashrc.swp matches

**Comment by anweshknayak** [comment]
I would be glad if I can use my "sudo" back.

**Comment by nwinkler** [comment]
Closing this now...
