### ISSUE TITLE
Significant slow down inside Git repositories

### ISSUE THREAD

**Issue by otrenav** [Bash-it/bash-it#572]
When visiting a directory with a Git repository, the terminal slows down quite a bit when executing commands, i.e. when executing `time ls` is fast but I get the prompt back after almost 5 seconds. The output of `time ls` is:
```
...
real   0m0.001s
user  0m0.001s
sys    0m0.001s
```
This is too much time for bash-it to be useful. I have made sure to disable all plugins when trying this. I pulled the latest changes, and they have the same problem.

Any hints on how to solve this? Is this something only on my side? Is there a way to trace what is being execute to pinpoint the problem?

Thanks.

**Comment by otrenav** [comment]
I've figure out why it's taking so long to return the prompt... the larger the Git repository, the more it takes to load. Specifically, when there are many changes in the repo (i.e. `git status` reports lots of changes), then it significantly slows down. 

Is there any way to prevent this?

**Comment by nwinkler** [comment]
This can happen with large Git repos. The Bash-it themes show a lot of information, and collecting that information takes a lot of time. There are some flags that can be set to disable some of the info.

Check out the _Misc_ section of the readme: https://github.com/Bash-it/bash-it

Some variables you could try are:

* `export SCM_CHECK=false` - this will disable all SCM information in the prompt
* `export SCM_GIT_SHOW_DETAILS=false` - this will disable showing untracked, unstaged and staged file counts in the prompt
* `export SCM_GIT_IGNORE_UNTRACKED=true` - don't show info on untracked files

Please give these a try and then report back.

**Comment by edubxb** [comment]
There are another option, not currently documented in README, sorry, to disable checking the repo status in Bash it:

    $ git config --add bash-it.hide-status 1

You can use set this flag globally for all repos (same effect as `SCM_CHECK=false` setting) or locally, you choose.

Hope this helps!

**Comment by edubxb** [comment]
Now fixed, I added a [short explanation of that feature](https://github.com/Bash-it/bash-it#ignore-repo-status) to the README.

**Comment by otrenav** [comment]
Thank you. The information both of you provided was useful. Best.
