### ISSUE TITLE
On Mac: ./uninstall.sh: Permission denied

### ISSUE THREAD

**Issue by marvindanig** [Bash-it/bash-it#575]
Tried uninstalling `bash_it` using the uninstall script but I get a permission error:

>  ./uninstall.sh
> -bash: ./uninstall.sh: Permission denied

What's missing?

**Comment by nwinkler** [comment]
It doesn't want you to uninstall Bash-it :smile: 

No, seriously, I forgot to set the _executable_ flag on the file. I'll do that in a second, but if you want to run it now, simply do:

```bash
chmod +x uninstall.sh
```
