### ISSUE TITLE
bash-it help completions

### ISSUE THREAD

**Issue by david-frederick** [Bash-it/bash-it#582]
I wanted help using completions since I'm not exactly sure which are available or how to use them. I tried `bash-it help completions` (which I expected to work since `bash-it help aliases` gives me the expected list of available aliases) but instead of getting help using completions I get a list of completions I could choose to enable; the same results as `bash-it show completions`.

Am I missing something obvious, or is this a legitimate issue?
Thanks

**Comment by nwinkler** [comment]
That's not an issue, that's the intended behavior. The difficulty with completions is that there is no easy way of showing what can be completed.

In general, the name of the completion (that you see when running `bash-it show completions`) should give a hint about the command. The `git` completion for example will provide completion capabilities for the `git` command. When it is enabled, you can type `git <TAB><TAB>` to show the available Git sub-commands (about 138) and their possible arguments if you keep pressing `<TAB>`.

Is there anything else you're looking for?

**Comment by david-frederick** [comment]
Nope I that's all I needed to understand. Thanks.
