### ISSUE TITLE
LS_COLORS

### ISSUE THREAD

**Issue by samuelecarpene** [Bash-it/bash-it#584]
Themes do not include changing LS_COLORS?

**Comment by nwinkler** [comment]
It doesn't look like they include that at the moment. Are you interested in seeing that as part of a theme?

**Comment by samuelecarpene** [comment]
Yes. I think it can be useful to have LS_COLOR styles as the theme. Isn't it?

**Comment by nwinkler** [comment]
I don't know, I never thought about that myself...

Care to provide a PR to show a matching set of LS_COLOR styles for one of the themes?

**Comment by samuelecarpene** [comment]
You can configure an example in a quick way heare. http://geoff.greer.fm/lscolors/.

**Comment by edubxb** [comment]
Not sure if this is a good idea, colors can be changed via the terminal emulator easily, and most themes only use a few colors, so trying to "match" the colors between prompt and LS_COLORS have no sense, I think.

**Comment by nwinkler** [comment]
True, let's close this for now.
