### ISSUE TITLE
R function on dirs.plugin.bash interferes with R binary

### ISSUE THREAD

**Issue by mimoralea** [Bash-it/bash-it#586]
https://cran.r-project.org/

Maybe we want to rename the R function for something else.

**Comment by mimoralea** [comment]
○ → R
R function requires 1 argument

**Comment by mimoralea** [comment]
○ → R

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

>

**Comment by Marwe** [comment]
Yes, please do!
Please try not to interfere with existing programs. I found quite some of the aliases introduce similar problems:
https://github.com/Bash-it/bash-it/issues/825

The commandline there might help to check for shadowed binaries in packages (at least with apt-file/debian based systems, rpm-based system have other programs, likerpm -q --filesbypkg <packages>).

**Comment by nwinkler** [comment]
I'm going to close this now - let's move the discussion to #825. I know this issue was created for a function, not for an alias, but maybe we can use a common approach for both...
