### ISSUE TITLE
Customising PS1 prompt

### ISSUE THREAD

**Issue by ghazlewood** [Bash-it/bash-it#587]
I'd like to remove the ruby version from my PS1 as it's not relevant to me but can't see how this is possible.  I've tried changing the theme (from bobby to powerline) but it seems to have no effect.

**Comment by ghazlewood** [comment]
Think I might have worked this out myself (typical!), made a custom.prompt file in ~/.bash_it/custom/ and copied the while `function prompt_command()` and `PROMPT_COMMAND=prompt_command;` from a theme (bobby in my case) and then modified it to my needs.  Then added a `source ~/.bash_it/custom/custom.prompt` back into my ~/.bash_profile

**Comment by nwinkler** [comment]
Yes, that's one way to do it - glad you figured it out.

The other way to do this would be to create your own theme. Simply copy the whole `bobby` theme folder and rename it and the files to something like `bobby-no-ruby`, then make the changes there. In your `~/.bash_profile`, you can then simply refer to that theme.

**Comment by botty** [comment]
This is a good guide
http://apple.stackexchange.com/questions/224149/show-username-on-mac-terminal-prompt
