### ISSUE TITLE
when I start my terminal window here is the message I get 

### ISSUE THREAD

**Issue by demhaq** [Bash-it/bash-it#597]
-bash: {{BASH_IT}}/bash_it.sh: No such file or directory, here is what my .bash_profile looks like

```
!/usr/bin/env bash

# Path to the bash it configuration
export BASH_IT="{{BASH_IT}}"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='zork'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh
```

**Comment by taylorjason** [comment]
I am having this same issue.
When I run any command i get `bash-it: command not found`.
**Additional point to note:**
1. My `.bash_profile` was not edited to the bash-it template.
2. Also, the plugins, completions, and aliases folders are being created in my home directory instead of inside the .bash-it folder.

**Comment by demhaq** [comment]
mine is also created in home directory but it is inside .bash-it folder when i type cd bash_it then ls_alt it shows templates,themes,aliases,bash_it.sh and many others

**Comment by nwinkler** [comment]
Seems to be related to the changes in #589 

@justin8 - can you take a look at the above? It looks like the installer did not replace the placeholder in the `.bash_profile` file.

@demhaq - do you have the output of the `install.sh` script? What did it report?

**Comment by demhaq** [comment]
yeah it is inside bash_it directory

**Comment by nwinkler** [comment]
@demhaq - Can you try to replace the following line in your `~/.bash_profile`?

Old:

```
export BASH_IT="{{BASH_IT}}"
```

New:

```
export BASH_IT="$HOME/.bash_it`
```

**Comment by nwinkler** [comment]
@demhaq - I didn't mean to ask where the install script is. Did you run the install script after cloning the repo? What did the install script print out when you ran it?

**Comment by demhaq** [comment]
thanks problem solve I don't remember my install script print but I think it is loading and it shows no error :+1:

**Comment by taylorjason** [comment]
@nwinkler Here is the output of my install script.
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
cp: ./template/bash_profile.template.bash: No such file or directory
sed: 1: "/Users/jtmoney/.bas ...": invalid command code j
Copied the template .bash_profile into ~/.bash_profile, edit this file to customize bash-it

Enabling sane defaults

Installation finished successfully! Enjoy bash-it!
To start using it, open a new tab or 'source /Users/jasontaylor/.bash_profile'.

To show the available aliases/completions/plugins, type one of the following:
  bash-it show aliases
  bash-it show completions
  bash-it show plugins

To avoid issues and to keep your shell lean, please enable only features you really want to use.
Enabling everything can lead to issues.
```
and now I have the `aliases`, `plugins`, and `completions` folders in my home folder

**Comment by nwinkler** [comment]
@taylorjason - which OS are you using? Looks like some of the command options are not supported on your OS.

**Comment by taylorjason** [comment]
@nwinkler Mac OSX 10.11
That is what I am gathering as well.  Is the initial readlink issue causing the BASH_IT variable to go haywire and messing the rest of the install?

**Comment by nwinkler** [comment]
Yes, that looks like what's happening here. It looks like the `readlink -f` is not a supported option on OS X.

@justin8 - Looks like your change to the installer `readlink -f` does not work on OS X...

**Comment by taylorjason** [comment]
@nwinkler @justin8 That seems to make sense but the manual pages provide the -f switch as a viable switch for the display format.
```
    -f format
             Display information using the specified format.  See the FORMATS
             section for a description of valid formats.
```

**Comment by nwinkler** [comment]
Looks like this is the way this should be done in a cross-platform way:

```
"$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```

(Source: http://stackoverflow.com/a/246128/1228454)

**Comment by justin8** [comment]
We can remove the readlink part then and just use basename; forgot about OS X having BSD readlink. On linux -f ensures the file exists and follows all links:

```
       -f, --canonicalize
              canonicalize by following every symlink in every component of the given name recursively; all but the last component must exist
```

You would also hit an issue with sed -i; apple sed is almost a decade old last I checked and doesn't support inline changes. I'll make a PR that should support OS X. but I don't really have a machine to test it on, my macbook only runs Linux.

**Comment by nwinkler** [comment]
Cool - let me know when you have this ready and create a PR - I'll test it on OS X.

**Comment by justin8** [comment]
@nwinkler https://github.com/Bash-it/bash-it/pull/598

**Comment by nwinkler** [comment]
Thanks - I'll give this a try now.

**Comment by nwinkler** [comment]
Tested the change from #598 - works fine!

@taylorjason - can you pull from the Bash-it repo and try to install again? It should work now.
