### ISSUE TITLE
command_exists: command not found when loading bash-it for the first time

### ISSUE THREAD

**Issue by thedrow** [Bash-it/bash-it#609]
I have no idea why this is not implemented.
This is a clean installation of Ubuntu 15.10.
Could that be the issue?

**Comment by thedrow** [comment]
It seems like the base plugin was not enabled by default when performing a clean install without --interactive.

**Comment by nwinkler** [comment]
Good point. Looks like we should add the base plugin here: https://github.com/Bash-it/bash-it/blob/master/install.sh#L91
