### ISSUE TITLE
protocol error: unexpected <newline> -scp-Anoconda

### ISSUE THREAD

**Issue by artonmarton** [Bash-it/bash-it#611]
Hello,

I am getting this error "protocol error: unexpected <newline> " when trying to copy a file from a server to my macbook using scp ssh. It was working perfectly until  installed Anoconda on my macbook. There was a path added to the bashrc file by Anoconda which I removed but nothing changed. I most of the posts about this problem and I didn't manage to fix this. I don't have a bashrc file or bash_profile. I did create one but I am still getting the error. Can someone please help me to solve this issue?

**Comment by nwinkler** [comment]
How is this related to Bash-it? If you don't have a `~/.bashrc` or `~/.bash_profile` file, how is Bash-it loaded in this case?

Which operating system are you using?

**Comment by artonmarton** [comment]
I might have posted in the wrong page. I am new in github. OSx

**Comment by nwinkler** [comment]
No problem at all. Let us know if we can help in any way...

Closing this for now.

**Comment by artonmarton** [comment]
Thanks. I know that in this page there was the same issue as mine, that is the main reason I posted here. (https://github.com/Bash-it/bash-it/issues/535).
