### ISSUE TITLE
When loading bash-it I repeatedly get plugins: plugins: is a directory 

### ISSUE THREAD

**Issue by thedrow** [Bash-it/bash-it#613]
I have no idea which plugin causes it and I'm going to find out.
Disabling all plugins make bash-it work again.

**Comment by edubxb** [comment]
Have you finally solved this issue? If not, can provide more info about it?

**Comment by thedrow** [comment]
I disabled all the plugins and re-enabled what I really needed. I can't single out the cause for this issue and I don't have access to the machine anymore.
Let's close this for now.
