### ISSUE TITLE
completion on aliases not working

### ISSUE THREAD

**Issue by scherler** [Bash-it/bash-it#617]
Hi,

I am just playing around with bash-it and migrating my current home cooked solution. 

Now first I created my current bash-aliases in the custom folder and  they get picked up fine. Now I have 
`alias b='bash-it'` in that file but with that the completion is not working for bash-it (only for the not aliased command).

Now when do 
± |master ?:1 ✗| → ln -s bash-it.completion.bash b.completion.bash

Then the completion is working as expected. 

I think bash-it should dynamically lookup the command of an alias, it is not really intuitive the hoops I had to overcome further now 

± |master ?:1 ✗| → g s
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	b.completion.bash

nothing added to commit but untracked files present (use "git add" to track)

**Comment by nwinkler** [comment]
Did you enable the `alias-completion` plugin (https://github.com/Bash-it/bash-it/blob/master/plugins/available/alias-completion.plugin.bash).

This should do what you're asking...

This works for me:

```bash
# Enable the plugin
bash-it enable plugin alias-completion

# Define the alias
alias b='bash-it'

# Reload Bash-it
reload

# Try the completion
b <TAB><TAB>
disable enable help show
```

Let me know if that works for you...

**Comment by scherler** [comment]
Yeah, thanks that was missing.
