### ISSUE TITLE
Feature request .gitconfig

### ISSUE THREAD

**Issue by scherler** [Bash-it/bash-it#618]
Hi, 

since I am migrating my home grown solution now to bash-it I am missing one feature for getting aliases for git.

I use lots of sub aliases in git such as:

[alias]
	r = checkout --
	rs = reset HEAD
	rv = revert
	rb = rebase
	rbc = rebase --continue
	rba = rebase --abort
	rbs = rebase --skip
	s = status
	a = add
	d = diff
	ds = diff --staged
	c = commit
	ca = commit -a
	u = pull --rebase
	uv = pull
	p = push
....

You get the picture, would be awesome, when I could save the config as well via bash-it

**Comment by nwinkler** [comment]
Not sure what you're looking for. Could you provide an example of what you're trying to do?

Are you looking for a way to store/versionize the `~/.gitconfig` file as part of Bash-it?

**Comment by scherler** [comment]
Yeah, thanks for your answer, something like that but actually I switched to oh-my-zsh so I close this issue.
