### ISSUE TITLE
Add bash-it stuff to the end of .bashrc during install.

### ISSUE THREAD

**Issue by naught101** [Bash-it/bash-it#621]
I think it's probably pretty common for users to already have a bit of `.bashrc` customisation in place before they try .bashrc. It would be good not to destroy that information. For the most part, you can just add the bash-it content to the end of the existing .bashrc and it will work fine. That would probably be a better default, as then users won't lose their custom PATHs, etc.

On a side-note, the backup process fails if .bashrc is a link to elsewhere. In that case, you copy the link, then edit .bashrc, which edits the same file, so the .bashrc.bak also gets changed. You could get around that by using `cp -aL ...` at line 36 of the installation script, or you could just move it, and create a new `.bashrc` instead. I think the former is better.

**Comment by nwinkler** [comment]
Good thoughts! Feel free to provide a PR for both of these:

* Fixing the backup process with `cp -aL`
* Appending to the existing file instead of copying the template.

**Comment by spectrumIG** [comment]
Hi, it seems there's no PR so far for these requests so, if it's ok for @naught101 I could do this in a couple of days. Anyway, I just discovered this project (which is quite great, by the way :) ) and I may be wrong. Thx

**Comment by naught101** [comment]
Don't wait for me - both of these I already had to fix manually, and now no longer need, and I haven't had time to make pull requests.

**Comment by nwinkler** [comment]
@spectrumIG Great - please feel free to provide a PR for this!

**Comment by nwinkler** [comment]
Thanks to @spectrumIG for fixing this in #641 - closing this now.
