### ISSUE TITLE
vim aliases enable produce gvim autocompletion error

### ISSUE THREAD

**Issue by hpsaturn** [Bash-it/bash-it#630]
in current bash-it master:

when:
bash-it enable alias vim

then autocomplete gvim:
gvim [tab][tab]

produce:
gvim -bash: _xspecs: bad array subscript

fix:
bash-it disable alias vim

System:
bash 4.3-11+b1
bash-completion 1:2.1-4
vim-gtk 2:7.4.488-7
Debian GNU/Linux 8.2 (jessie)

thanks!

**Comment by sveneh** [comment]
This should be fixed with https://github.com/Bash-it/bash-it/pull/757

**Comment by nwinkler** [comment]
Thanks - closing for now!
