### ISSUE TITLE
Illegal option issue after installation

### ISSUE THREAD

**Issue by atomic** [Bash-it/bash-it#643]
After installing bash-it on freeBSD SunOS remotely from ssh, any commands will get me 'illegal usage' error in grep or ls. No changes were made on .bashrc or .bash_profile. 
Here's the screen. http://pasteboard.co/D6vPDFE.png

**Comment by nwinkler** [comment]
![image](https://cloud.githubusercontent.com/assets/907063/12192435/c7525e70-b5de-11e5-9345-1edf3fb453db.png)

Adding the image here for reference...

**Comment by nwinkler** [comment]
It looks like SunOS does not support some of the options for `ls` or `grep`. Example: The `grep` man page does not contain the `color` option: http://www.manpages.info/sunos/grep.1.html, while FreeBSD seems to support it: http://www.freebsd.org/cgi/man.cgi?query=grep&sektion=&n=1

**Comment by nwinkler** [comment]
The aliases are defined at the following locations:

* `ls`: https://github.com/Bash-it/bash-it/blob/master/aliases/available/general.aliases.bash#L6
* `grep`: https://github.com/Bash-it/bash-it/blob/master/lib%2Fappearance.bash#L4

Fixing this would require someone to wrap these locations in an `if` statement, defining the alias unless the OS is SunOS. Feel free to create a PR for this...

This seems to work fine on all other operating systems so far.

**Comment by nwinkler** [comment]
Similar to #819

**Comment by nwinkler** [comment]
This should be fixed now, see #885
