### ISSUE TITLE
New logo for Bash it

### ISSUE THREAD

**Issue by edubxb** [Bash-it/bash-it#650]
Bash debuts a new and awesome logo, we can ask the current Bash maintainer and/or the logo contributor/designer if we can create a logo for Bash it based on it.

More info about the new Bash logo election:

https://lists.gnu.org/archive/html/bug-bash/2015-12/msg00116.html
https://hacklog.mu/maxcdn-sponsors-gnu-bash-logo-redesign/
https://tiswww.case.edu/php/chet/bash/bashtop.html

Opinions?

**Comment by nwinkler** [comment]
Sure, go for it! :+1:

**Comment by nucliweb** [comment]
#### Logo proposal

![bash-it](https://cloud.githubusercontent.com/assets/1307927/12588522/4e176ec2-c459-11e5-9d12-155f3c44bf3c.png)

**Comment by edubxb** [comment]
Love it! I personally prefer the A3.

What are your preferences @nwinkler @tswicegood?

Thanks @nucliweb!

**Comment by nwinkler** [comment]
A3 for me as well!

I also agree with the use of the dash (_Bash-it_ instead of _Bash it_), it makes it look like a brand, and is less awkward when used in a sentence.

**Comment by nucliweb** [comment]
#### Concept Stickers ;)

![stickers](https://cloud.githubusercontent.com/assets/1307927/12669547/c750e502-c661-11e5-82d0-5ed2b05f753e.jpg)

**Comment by nwinkler** [comment]
:+1: Awesome!

**Comment by nucliweb** [comment]
If you create a repository for mark, I'll add the logo and icon in various formats

**Comment by edubxb** [comment]
:clap:

**Comment by edubxb** [comment]
@tswicegood I want to know your opinion about this :smiley:

Also, @nwinkler and I are discussing about use **Bash-it** (with the slash) as the officlal name, as her points out.

**Comment by tswicegood** [comment]
Doh! I thought I'd weighed in on this. I've been watching it. I love them all. I think A3 is probably the best, but only slightly. :-)

**Comment by tswicegood** [comment]
Speaking specifically to capitalization, I think it should be `Bash-it` since [Bash][1] uses that capitalization.

[1]: https://www.gnu.org/software/bash/

**Comment by nucliweb** [comment]
![capitalization](https://cloud.githubusercontent.com/assets/1307927/12856928/968b6e6a-cc47-11e5-8617-4d677ff07a40.jpg)

**Comment by nwinkler** [comment]
OK, so it looks like we agree on using `Bash-it`:

* Uppercase B
* Dash for separating the two words
* Lowercase i

Great - let's use that going forward!

**Comment by edubxb** [comment]
Great!

How about to create a repo called "media" (or something that make sense), to upload the logo files?

**Comment by nucliweb** [comment]
The last update, the dot of `i`

![logo](https://cloud.githubusercontent.com/assets/1307927/12901755/9c15f648-cebd-11e5-9d61-e3974e383fac.jpg)

The original font, has a circle the dot of the `i`, proposal *A*.
The *B* proposal, the dot it's a square, It's the same as !

**Comment by edubxb** [comment]
Little details matters... love B too!

**Comment by edubxb** [comment]
Just created a repo called [media](https://github.com/Bash-it/media), please @nucliweb feel free to make a PR.

Thanks!

**Comment by thedrow** [comment]
B Looks great!

**Comment by sveneh** [comment]
For me the **A** proposal looks much nicer. The logo has so many round shapes, a round _i-dot_ seems preferable.

**Comment by tswicegood** [comment]
Thanks for weighing in @sveneh. Looks like we've already got this settled over in https://github.com/Bash-it/media and this was never closed though.
