### ISSUE TITLE
Landing page for Bash it

### ISSUE THREAD

**Issue by edubxb** [Bash-it/bash-it#651]
I think that could be a great idea to have a simple but awesome landing page for Bash it, it will improve the SEO of the project being more easy to find it, with the benefit that we can gain more users and contributors.

We can use the GitHub pages to do it.

**Comment by nwinkler** [comment]
Great idea! :+1:

**Comment by NoahGorny** [comment]
I think that `readthedocs` is an acceptable solution, if someone wants to create a good looking website im all for it, but I do not think its needed currently
