### ISSUE TITLE
Stop supporting Bash 3

### ISSUE THREAD

**Issue by edubxb** [Bash-it/bash-it#652]
Bash 3 is +15 years old, the last version from the 3 series, 3.2, 10 years old, (I'm not sure, but I think that my guess is very approximate) and Bash 4 (currently 4.3) is the current stable version, that have some interesting and useful features, not found in Bash 3.

Mac OS X comes with Bash 3.2 by default, but with brew, the install of Bash 4 is very easy, so I suggest to stop supporting it.

Anybody that wants to install Bash it, can install Bash 4 with brew, so IMHO, there's no reason to not do it.

We can add a "check" during the installation and cancel it if the supported version cannot be found, and suggesting the user to upgrade.

**Comment by nucliweb** [comment]
:+1:

**Comment by nwinkler** [comment]
I'm on the fence about this one. While I agree that it's probably easy to upgrade Bash on the Mac (haven't actually tried it), we will lose a good chunk of the potential user base if we force people to upgrade.

In case someone hasn't installed Homebrew yet, and wants to use Bash-it, we will tell them that they first need to go through the Homebrew install (including recursively changing permissions on `/usr/local`), install Bash v4, and then they can start using Bash-it. For someone that just wants to check whether Bash-it might be a good idea, and they're not sure whether they want to use it, this seems like a big hurdle.

Wouldn't it make more sense to have the functionality that actually depends on Bash v4 make a check and then provide a message to the user? I haven't checked, but are there really that many features in Bash-it that require Bash v4? I'm using it with the stock Bash v3, and it works perfectly fine...

**Comment by edubxb** [comment]
The new features included in Bash v4 are listed here:

http://www.tldp.org/LDP/abs/html/bashver4.html

another good read about the new features in Bash v4:

http://lcorg.blogspot.com.es/2010/04/new-features-in-bash-version-4x-part-1.html

some features can help to simplify the code, and remove the need from use external commands, others are options to change the default Bash behavior.

Really there's nothing that make a big difference to force the update...

**Comment by thedrow** [comment]
We could support both by using $BASH_VERSION if it's needed.

**Comment by seefood** [comment]
indeed. as a Stallmanist I have no deep sentiments for OSX users, but I'm all for backwards compatibility if it's not a big effort. I think we can keep supporting it for a while...

as for the homebrew solution - it installs in /usr/local, it's not a ready option in chsh if you are not a power user (or an admin on your own Mac/Unix machine), so I think it will be a worthy effort to stay bash3 compatible.

**Comment by thedrow** [comment]
We'll stay bash 3 compatitable for now. I'm closing this issue. When the time comes. Let's reopen.

**Comment by nwinkler** [comment]
Thanks - good discussion!
