### ISSUE TITLE
add `source ~/.bashrc` to .bash_profile

### ISSUE THREAD

**Issue by ahillio** [Bash-it/bash-it#663]
I almost didn't use this because I thought "it doesn't work.  there's no theme. heck."  Then I remembered that every time I've customized .bashrc I've had to source it in .bash_profile.  Doing that solves the issue of prompt looking the same as before I installed bash-it.  I wonder why bash-it doesn't add that line itself?  Anyhow, thanks for the cool shell config :)

**Comment by nwinkler** [comment]
Which OS are you using? Bash-it updates the following files during installation, depending on the OS:

* `~/.bash_profile`: Mac OS X
* `~/.bashrc`: Linux, Unix

This usually works perfectly fine, since these are the files used by the OS when opening a new shell.

**Comment by ahillio** [comment]
Ubuntu 12.04 server.

I installed, didn't see it do anything, so logged out and then back in a
couple times.  This didn't work so I uninstalled.  I reinstalled and it
still seemed to have no effect.  That's when I remembered about sourcing
.bashrc in .bash_profile.

**Comment by nwinkler** [comment]
What does the install script print when you run it? There's a check for the OS, and based on the result, it's either using `.bash_profile` or `.bashrc`: https://github.com/Bash-it/bash-it/blob/master/install.sh#L4

Unless your system is a Mac (`darwin`), it should always use `.bashrc`...

The install script prints a message after backing up your current config file - please let us know what is shown there.

I'm assuming that you are running the latest version of Bash-it - the install script was always using `.bash_profile` in the past, but that was changed some time ago. The latest version should be smart enough to use the correct file...

**Comment by edubxb** [comment]
If you are logged via SSH or virtual tty, not using a terminal emulator, in GNU/Linux, the `.bashrc` file is not read, the `.bash_profiles` in used instead, a solution for this was commented [here](https://github.com/Bash-it/bash-it/issues/173#issuecomment-35332159).

**Comment by ahillio** [comment]
Oh, that explains it.  I was installing on a remote server and connected to
it via SSH.  I imagine the install script wouldn't be able to detect that
automatically, but perhaps there could be a check/prompt for that in
`--interactive` mode?  Or at least mention of
https://github.com/Bash-it/bash-it/issues/173#issuecomment-35332159 in the
README.

On Thu, Feb 11, 2016 at 9:34 AM, Eduardo Bellido Bellido <
notifications@github.com> wrote:

> If you are logged via SSH or virtual tty, not using a terminal emulator,
> in GNU/Linux, the .bashrc file is not read, the .bash_profiles in used
> instead, a solution for this was commented here
> <https://github.com/Bash-it/bash-it/issues/173#issuecomment-35332159>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bash-it/bash-it/issues/663#issuecomment-182889986>.
>



-- 
Alec Hill
(802) 279-8800
http://firestick.me

**Comment by edubxb** [comment]
Trying to guess how the machine is accessed and then choose what file use, is not a "good" solution, IMHO, imagine a situation where you install Bash-it via SSH, and you also need to access the same machine via xterm o another terminal emulator, Bash-it will not work, just like other settings included in the *wrong* file, so the most simple solution to share settings in login and interactive terminals (as the official Bash documentation suggests) is sourcing `.bashrc` in `.bash_profile`.

About the installer, feel free to submit a PR improving it asking what file use to write the config. 

To avoid future "issues" like this, I will update the README.

If you agree, I will close this issue.

**Comment by ahillio** [comment]
Sounds good on closing this issue.  I would like to someday be capable of
contributing :)  Thanks for your work on Bash-it!
