### ISSUE TITLE
Teaching mode

### ISSUE THREAD

**Issue by greenrd** [Bash-it/bash-it#674]
The reality is, I am never going to remember most of this stuff, and I'm sure many people are similar. It would be useful to have a teaching mode that responds to commands like

```
$ cd -
```

with

```
bash-it: Use "-" instead
```

and then executes the command.

**Comment by nwinkler** [comment]
Nice idea. Not sure how this could be implemented, though...

**Comment by jusdepatate** [comment]
@nwinkler if you are still ok with this, I think if I open a pr it would be a new file that people need to add in .bashrc (source teachingmode.bash), which will contains a lot of function (like a teaching mode for cd, ls, cat, ...)
