### ISSUE TITLE
Background Installation without prompt

### ISSUE THREAD

**Issue by stanzgy** [Bash-it/bash-it#676]
Hi, thanks a lot for creating this convenient tool.
Now I get trouble in batch installing bash-it on many servers by running a script using ansible:

 >#!/bin/bash
git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
bash ~/.bash_it/install.sh 

It will get stuck at install.sh and I shall only handle it manually. 
Could you consider add an install option like "--without-prompt" / "--quiet" for scripted install?

**Comment by nwinkler** [comment]
Good point. I'd go for a `--silent` install option.

BTW: I just noticed that the install used to be silent, it didn't ask any questions as long as there was no existing backup file. This has changed, there now is a question whether the config should be appended to the original bash profile. This was added recently and it looks like that has broken the silent install.

So I guess we need to look into defaults for all the questions asked during the installation:

* If the backup file exists, overwrite or terminate the install? I'd go for overwrite.
* Append to bash profile, or backup/new? I'd go for backup/new.
* Enabling just the sane default plugins etc. - that's already in place. The `--interactive` switch needs to be ignored in the case of a silent install.

Sounds like a good addition. Interested in implementing this in a Pull Request?

**Comment by stanzgy** [comment]
Okay. I will give it a try later.

**Comment by kigster** [comment]
I was struggling with this too (installing without interaction), but was able to workaround it this way:

`echo 'n' | ./bash_it/install.sh`

Not ideal. but works.

**Comment by ravenhall** [comment]
Can I get a review on my PR for this issue?

**Comment by nwinkler** [comment]
Sorry, I was pretty busy the last couple of days. I've added a couple of comments to the PR...

**Comment by ravenhall** [comment]
No problem. I suffer from a general lack of time as well. I've updated the branch to incorporate your suggestions.

**Comment by nwinkler** [comment]
Closed in #725 - thanks to @ravenhall for the fix!
