### ISSUE TITLE
battery plugin - incorrect values

### ISSUE THREAD

**Issue by jfmcarreira** [Bash-it/bash-it#683]
Is any reason for the battery plugin use code line this "local PERC_OUTPUT=$(echo $ACPI_OUTPUT | head -c 23 | tail -c 2)" with head and tail to extract battery percentages?

Would not be possible to use commands like "awk" for example? in my case it is not retrieving the value correctly when discharging and 100% battery yet.

**Comment by nwinkler** [comment]
Do you have an example for this? I guess you're using Linux, right? I can't test the above since I'm running OS X, and that's using a different logic branch (and a different command).

If you find a better and more reliant way of finding the correct value, feel free to provide a PR - we're always looking for contributors.

**Comment by jfmcarreira** [comment]
So in OS X awk command is not available? or it is not even possible to run acpi commands?

**Comment by tswicegood** [comment]
@jfmcarreira `awk

**Comment by nwinkler** [comment]
`awk` is available, but `acpi` is not. Here (https://github.com/Bash-it/bash-it/blob/master/plugins%2Favailable%2Fbattery.plugin.bash#L64) you can see that on OS X, it will use `ioreg` instead.

**Comment by tswicegood** [comment]
@nwinkler beat me to it :-)

**Comment by nwinkler** [comment]
@tswicegood Sorry about that, must have typed my reply at the same time :smile:

**Comment by jfmcarreira** [comment]
so if in the acpi case we could use awk i guess :) 
 Either way head tail is wrong at this point. awk has the advantage of  avoiding trailing spaces.  i will make the pull request as soon as i manage to add it to my bash to test it :)

**Comment by nwinkler** [comment]
Yes, of course you can use `awk`! Looking forward to your PR!

**Comment by jfmcarreira** [comment]
Sent the PR.

I guess it will work like this. I will do further test i also have another idea for a function. themes could change colour depending if the battery is charging or discharging.

**Comment by tswicegood** [comment]
This was fixed in #690.
