### ISSUE TITLE
sudo completion does not complete commands

### ISSUE THREAD

**Issue by tomashavlas** [Bash-it/bash-it#695]
I often have to run commands as root using sudo, however when using sudo autocompletion does not seems to work correctly, I can only successfully autocomplete files or directories. Is there any chance for having working autocompletion when using sudo?

**Comment by nwinkler** [comment]
Do you have an example for this? I just tried it and it is working for me:

```bash
sudo mvn <TAB><TAB>
```

This shows the available options defined in the `maven.completion.bash` file for me.

**Comment by tomashavlas** [comment]
I've just tried `sudo mvn <TAB><TAB>` and I got list of files in current directory, if I do just `mvn <TAB><TAB>` I got correct options like you just wrote. Maybe some local problem with my configuration, I'll try to do some more research and post my results.
