### ISSUE TITLE
How to get history according to input?

### ISSUE THREAD

**Issue by fuzihaofzh** [Bash-it/bash-it#723]
I want to get history command after I typed some thing. for exampe I typed `gi` and press up key, is should give recent command start with 'gi' rathan just the recent command. Can Bash-it do that?

**Comment by nwinkler** [comment]
Yes, you can enable the [history plugin](https://github.com/Bash-it/bash-it/blob/master/plugins/available/history.plugin.bash) for that purpose:

```bash
bash-it enable plugin history

reload
```

Then the up/down arrow keys should do what you're looking for.

**Comment by edubxb** [comment]
@maplewizard the solution proposed by @nwinkler is working for you? can we close this issue then?

Thanks!

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
