### ISSUE TITLE
README instruction incorrect

### ISSUE THREAD

**Issue by jadekler** [Bash-it/bash-it#738]
> Update
> To update Bash-it, simply run:
> bash-it update
> that's all.

When we do this:

```
○ → bash-it update
bash-it             bash-it help and maintenance
parameters:
                    1: verb [one of: help | show | enable | disable ]
                    2: component type [one of: alias(es) | completion(s) | plugin(s) ]
                    3: specific component [optional]
examples:
                    $ bash-it show plugins
                    $ bash-it help aliases
                    $ bash-it enable plugin git
                    $ bash-it disable alias hg
```

**Comment by nwinkler** [comment]
Now here's a nice chicken/egg problem. It looks like you have an older version of Bash-it locally that does not have the _update_ functionality yet. But you can't update using `bash-it update` either...

Can you check whether you have the latest version, e.g. your `lib/helpers.bash` file should have this line: https://github.com/Bash-it/bash-it/blob/master/lib/helpers.bash#L35

In theory, you should be able to do this:

```bash
cd $BASH_IT
git pull origin master
```

This will only work if you have cloned Bash-it from the original remote (the official `Bash-it/bash-it`). If you have your own fork and are using that, you will have merge the changes from the official repo into your fork first.

Once you have done all of that, you should be able to open a new Terminal session and run `bash-it update` there.

**Comment by jadekler** [comment]
@nwinkler Sorry for the slow response! Unfortunately the VM I was on got blown away. I'll try to reproduce this error and post here if it returns. Apologies!

**Comment by nwinkler** [comment]
Sure, feel free to open a new issue in that case.
