### ISSUE TITLE
bash: complete: --: invalid option

### ISSUE THREAD

**Issue by kprikshit** [Bash-it/bash-it#740]
bash: complete: --: invalid option

This error  appears every time you open a new terminal. This only happens when you have enabled/added bash-it to your bashrc file. 

I have checked this multiple times and every time result is same.

Please look into this.

![image](https://cloud.githubusercontent.com/assets/10362570/15921447/2d06757a-2e3f-11e6-88b4-cea72bbd52ad.png)

**Comment by nwinkler** [comment]
Can you post the following information?

* Which OS you're using
* The output of `bash-it show completions`

That should help with identifying what's wrong.

**Comment by kprikshit** [comment]
**OS**:
Linux Normandy 4.2.0-36-generic #42~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**output**:
Completion          Enabled?  Description
awscli                [ ]     
bash-it               [x]     
brew                  [ ]     
bundler               [ ]     
capistrano            [ ]     
conda                 [ ]     
defaults              [ ]     
dirs                  [ ]     
django                [ ]     
docker                [ ]     
drush                 [ ]     
fabric-completion     [ ]     
gem                   [ ]     
gh                    [ ]     
git                   [ ]     
git_flow_avh          [ ]     
git_flow              [ ]     
gradle                [ ]     
grunt                 [ ]     
gulp                  [ ]     
homesick              [ ]     
hub                   [ ]     
jboss7                [ ]     
maven                 [ ]     
npm                   [ ]     
packer                [ ]     
pip                   [ ]     
projects              [ ]     
rake                  [ ]     
salt                  [ ]     
sdkman                [ ]     
ssh                   [ ]     
svn                   [ ]     
system                [x]     
terraform             [ ]     
test_kitchen          [ ]     
tmux                  [ ]     
todo                  [ ]     
vagrant               [ ]     
virtualbox            [ ]

**Comment by nwinkler** [comment]
Does it still happen if you disable the `system` completion?

```bash
bash-it disable completion system
```

**Comment by kprikshit** [comment]
Yes it still happen.
I also tried disable all completion and it still happened.

**Comment by kprikshit** [comment]
Hi, 
this has been resolved. One day I installed the ubuntu updates and this was not longer there. 
I guess something must be broken from Ubuntu's side.

**Comment by nwinkler** [comment]
Thanks for verifying and closing this issue here - much appreciated!

**Comment by kprikshit** [comment]
No problem!
Will let you know if something happens in future. 


Bash-it is an amazing library. Kudos to the team for doing such an amazing work (y)
