### ISSUE TITLE
Sudo indicator for powerline themes generates secure log entries

### ISSUE THREAD

**Issue by Neraste** [Bash-it/bash-it#744]
Hello the Bash-it team, thank you for your hard work

The sudo indicator for the powerline themes (#452, #484) works by trying to call sudo at each new prompt. This is done by default even if the feature is disabled. This causes a sudo failed attempt which is recorded in the security logs of the system.

As I work in a corporate environment (where sudoing my machine is out of question), I have received several emails from the IT staff complaining about it.

One solution implies to move the sudo check, so as it is done only if the feature is enabled. In `.bash_it/themes/powerline-multiline/powerline-multiline.theme.bash`, replace:

``` sh
if sudo -n uptime 2>&1 | grep -q "load"; then                            
  color=${USER_INFO_THEME_PROMPT_COLOR_SUDO}
fi
case "${POWERLINE_PROMPT_USER_INFO_MODE}" in
  "sudo")
    if [[ "${color}" == "${USER_INFO_THEME_PROMPT_COLOR_SUDO}" ]]; then
      user_info="!"
    fi
    ;;
  ...
```

by:

``` sh
case "${POWERLINE_PROMPT_USER_INFO_MODE}" in
  "sudo")
    if sudo -n uptime 2>&1 | grep -q "load"; then    
      color=${USER_INFO_THEME_PROMPT_COLOR_SUDO}
      user_info="!"
    fi
    ;;
  ...
```

And in `.bash_it/themes/powerline/powerline.theme.bash`, replace:

``` sh
    if sudo -n uptime 2>&1 | grep -q "load"; then
        SHELL_PROMPT_COLOR=${SHELL_THEME_PROMPT_COLOR_SUDO}
    fi
```

by:

``` sh
    case "${POWERLINE_PROMPT_USER_INFO_MODE}" in
        "sudo")
            if sudo -n uptime 2>&1 | grep -q "load"; then
                SHELL_PROMPT_COLOR=${SHELL_THEME_PROMPT_COLOR_SUDO}
            fi
            ;;
    esac
```

It seems to do the job.

**Comment by nwinkler** [comment]
Looks like a sensible addition. If you could please create a Pull Request for this, and I'll merge after reviewing.

**Comment by Neraste** [comment]
Ok, I do the pull request asap.
