### ISSUE TITLE
bash-it slows down mac terminal

### ISSUE THREAD

**Issue by imtdeepak** [Bash-it/bash-it#747]
Open a new or tab in  terminal/iterm2 and compare the time to show the prompt with bash-it and without bash-it.

With bash-it it is taking way longer.

Issue #2: This is slow when we execute any command, like `ls` or any other command. The prompt takes time to come back to terminal.

**Comment by nwinkler** [comment]
Well, that's a trade-off when using a tool like this. When you open a new shell, all of your enabled plugins, aliases and completions are evaluated and loaded into the shell - this obviously takes time.

If you want to make things faster, I suggest that you only enable the things that you really need, and disable everything else.

Please also see #517 for some stats on the individual plugins' load times.

Other than that, what do you suggest to solve this?

**Comment by imtdeepak** [comment]
Thanks for the response, I think we can live with terminal loading for first time.

I have updated it with issue #2 where prompt takes longer to come back after executing any command. Looks like it is running some python script after each execution or reloading the bash.

**Comment by nwinkler** [comment]
This is probably caused by the theme that you're using. The themes gather a good deal of info, e.g. about the Git repo you're in, about the Ruby/Python/etc. version that you're using, and then displaying that.

Which theme are you using? Some of the themes provide options to exclude some of the info. Or it might make sense to customize or patch the theme so it doesn't gather that info.

**Comment by imtdeepak** [comment]
@nwinkler It might be correct. I was using the default theme "bobby". Now I tested bunch of the themes and found nwinkler_random_colors and powerline-multiline really good in terms of looks and speed. 

I added one extra line in nwinkler_random_colors, just for my taste and style so that It looks clean and easy on eyes to make out between commands.

**Comment by nwinkler** [comment]
Glad to hear that you found something that works for you!
