### ISSUE TITLE
With latest update, themes don't appear to work

### ISSUE THREAD

**Issue by MakotoTheKnight** [Bash-it/bash-it#756]
Reference: <a href="https://asciinema.org/a/ebmt1osc5nfubcdcmhy56t6mw" target="_blank"><img src="https://asciinema.org/a/ebmt1osc5nfubcdcmhy56t6mw.png" /></a>

Note that I did do a bit of preliminary toying around with a few other commits off-camera, but it does seem like #754 has something to do with this particular issue.

It may be the case that this fix is valid, but it represents a regression in my usability of bash-it.  If it is the case that this is expected behavior, what should I do to mitigate this?

**Comment by nwinkler** [comment]
Can you please try the following?

* Open a new terminal window to see if the theme works there? The commit changed the way the `PROMPT_COMMAND` variable is handled, and it might break things when updating within the same window.
* Paste the output of the `$PROMPT_COMMAND` variable both with the last working commit and with the latest HEAD.

Please paste directly in your reply, not as a movie :-) While the movie is nice to illustrate things, it takes longer to watch.

**Comment by MakotoTheKnight** [comment]
Sure thing - I had used the movie to demonstrate the visual difference between the two, but I'm happy to paste things here.

I've opened a new terminal (xfce-terminal-emulator) and have the output with both the last working and the more recent.

Last working:

``` echo $PROMPT_COMMAND 
powerline_prompt_command
```

Latest HEAD:

```echo $PROMPT_COMMAND 
powerline_prompt_command;__git_ps1 "\u@\h:\w" "\\$ " " [%s]"
```

**Comment by ierenstein** [comment]
Have you enabled the xterm plugin?
`bash-it show plugins`
If yes then:
`bash-it disable plugin xterm`
That's what fixed it for me when the same thing happen to me.

**Comment by MakotoTheKnight** [comment]
Thanks for the suggestion @ierenstein but I don't have that plugin enabled in my setup.

For completeness, here are the plugins I have enabled:

 - alias-completion
 - base
 - virtualenv

**Comment by nwinkler** [comment]
Not sure where the `__git_ps1 "\u@\h:\w" "\\$ " " [%s]"` part comes from - I did not find that in the Bash-it codebase. Is that something you have locally for some reason?

**Comment by antisilent** [comment]
Are you using a custom theme?

'__git_ps1' is used with git-prompt.sh... maybe try using 'scm_prompt_info' instead?

**Comment by MakotoTheKnight** [comment]
@nwinkler:  It was something that I had locally - both on my laptop and on my tower.  Not sure how it got there, but once it was removed, the themes started working with the latest version.

My belief was that the theme specified by `$PROMPT_COMMAND` overrode what was there previously; now it's using it in addition to what is there.  This is probably why I never noticed a problem.

Anyway, my belief is that this can be safely closed out.

**Comment by nwinkler** [comment]
Yes, that sounds right, this is exactly the changed behavior - the themes now add to the variable instead of overriding.

Thanks for confirming that it's working now.
