### ISSUE TITLE
Advise to rename to oh-my-bash to compare with on-my-zsh.

### ISSUE THREAD

**Issue by crazy-canux** [Bash-it/bash-it#759]
Advise this action to make this project more usefull.

**Comment by seefood** [comment]
So many people know it by this name (and it's not meant to be a direct rip-off AFAIK), that it would create more confusion IMHO.

**Comment by nwinkler** [comment]
Same here, don't agree with this request. I fail to see the connection between the name and the usefulness...

Bash-it is the first Google hit when searching for "bash oh-my-zsh", no need to change anything...
