### ISSUE TITLE
Automatically reload shell after enabling and disabling things

### ISSUE THREAD

**Issue by antisilent** [Bash-it/bash-it#763]
Currently, when a user enables or disables a plugin/alias/completion, the change doesn't take effect until the shell is reloaded...

While this isn't awful, it's not ideal. Moreover, in order for changes to take effect upon disabling anything a user has to restart their shell, since sourcing `~/.bashrc` doesn't actually remove defined aliases and functions from the environment.

**Comment by nwinkler** [comment]
Closing this - let's continue the discussion in #764
