### ISSUE TITLE
bash-it search fails

### ISSUE THREAD

**Issue by rdgreen** [Bash-it/bash-it#765]
```
→ bash-it search emacs
bash: alias: /usr/bin/egrep: not found
bash: alias: -i: not found
bash: alias: --: not found
bash: alias: emacs: not found
bash: alias: /usr/bin/egrep: not found
bash: alias: -i: not found
bash: alias: --: not found
bash: alias: emacs: not found
bash: alias: /usr/bin/egrep: not found
bash: alias: -i: not found
bash: alias: --: not found
bash: alias: emacs: not found
```

Using GNU bash, version 4.3.42(1)-release (x86_64-redhat-linux-gnu)

**Comment by rdgreen** [comment]
No plugins installed

**Comment by jammer3d** [comment]
'unalias egrep' solves the issue but yea, there is a bug here

**Comment by nwinkler** [comment]
Can you guys help figuring out what's wrong? I don't have that OS to try out...

**Comment by edubxb** [comment]
Seems that the `which` command in RedHat/CentOS return aliases and not only the command path.

When executing:

`which egrep`

the output in Debian is:

```
/bin/egrep
```

and the output in Centos 7 is:

```
alias egrep='egrep --color=auto'
	/usr/bin/egrep
```

and for this reason the [function that performs the search](https://github.com/Bash-it/bash-it/blob/master/lib/search.bash#L89) fails.
