### ISSUE TITLE
battery plugin

### ISSUE THREAD

**Issue by kirk86** [Bash-it/bash-it#766]
Hello,
Thanks for this great "bash-it" enhancement of the shell.
I would like to ask a question regarding the battery plugin.
I'm using iterm2 but also tested on terminal app on macos, when i enable the plugin ti doesn't show the battery percentage animated to the right of the terminal. Shouldn't it be doing that?

Or is just a command line tool where you type battery_percentage and you get a number indicating the percentage?

Thanks!

**Comment by nwinkler** [comment]
This depends on the theme that you're using. From a quick search, the following themes include the battery charge:

* bobby
* brunton
* demula
* modern
* rana

These all use the `battery_charge` function.

In addition to these, the `powerline-multiline` theme also shows the battery percentage on the right.

Please let me know if this works for you when using one of these themes (and with the `battery` plugin enabled).

**Comment by kirk86** [comment]
@nwinkler thanks. I did try and and  I go something like the terminal output below.

`user@hostname in ~ >>>>>`

My question is are these right arrows the indication for the battery. If so why are they not displayed in the right far side of my terminal screen?

I'm a bit confused.

**Comment by nwinkler** [comment]
Which theme are you using?

I'm using "powerline-multiline" and the battery status is indicated on the right hand side:

![image](https://cloud.githubusercontent.com/assets/907063/17298112/e9b38c4c-5808-11e6-8a08-59529620b6f5.png)

**Comment by kirk86** [comment]
@nwinkler thanks a lot now I see it. I was using the simple powerline theme. Now I understand that the battery plugin doesn't work with every theme, so I am closing this issue.

**Comment by nwinkler** [comment]
If you want to continue using the Powerline theme, you can add the battery status in there if you want...

Thanks for closing the issue once it was resolved for you - good housekeeping.
