### ISSUE TITLE
[discussion] Allowing themes to be configurable

### ISSUE THREAD

**Issue by NigelGreenway** [Bash-it/bash-it#768]
I have reverted back to Bash from ZSH as Bash is the core shell in the Linux environments I am using and would like to learn it more.

The themes are very nice, but some presuppose that you want line breaks in certain places.

I have made some [changes](https://github.com/Bash-it/bash-it/compare/master...NigelGreenway:add-theme-configuration?expand=1) that I would like to propose for themes being submitted whereby a line break will be configurable within the `.bashrc`.

`export BASH_IT_THEME_ENABLE_PREPENDED_LINE_BREAK`
`export BASH_IT_THEME_ENABLE_APPENDED_LINE_BREAK`

To not break BC, they are left as they are already in the theme example I have worked on so far.

This will allow the following to be included in every theme file allowing the defaults to be set per theme.

``` bash
RVM_THEME_PROMPT_PRE_FIXED_LINE_BREAK="\n"
function disable_prefixed_line_break() {
    RVM_THEME_PROMPT_PRE_FIXED_LINE_BREAK=""
}

RVM_THEME_PROMPT_APPENDED_LINE_BREAK=" "
function enable_appended_line_break() {
    RVM_THEME_PROMPT_APPENDED_LINE_BREAK="\n"
}
```

Thoughts?

**Comment by nwinkler** [comment]
From what I understand, this looks like a reasonable request, and will add more flexibility. Do you have a screenshot that shows the difference in behavior (once with the feature enabled, once disabled)?

We also have to think about documentation so people know how to use this feature.

**Comment by NigelGreenway** [comment]
I can get a screen shot sorted.

In regards to the documentation, would it be looking at other theme variables? Like enable git info, username,  path info and so? 

Would make it more powerful than oh-my-zsh from a theme point of view, especially with switches and theme defaults?

**Comment by nwinkler** [comment]
We have quite a few switches for the themes, some of them are documented in the main README file (mainly the ones relating to Git) under the _Misc_ heading.

Since this feature will have to be added to each theme on a case-by-case basis, it might make sense to add it to the individual theme's documentation (some of them already have their own `README.md` file).

Which theme do you want to use this with?

**Comment by NigelGreenway** [comment]
Currently using bakke, but if I worked on this more then I would back port it to all themes if you were okay with it?

I have had a brief look through the `README.md`, maybe I could flesh out the wiki for themes and add a reference in the generated `.bashrc` file?

**Comment by nwinkler** [comment]
Sure, sounds good to me.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
