### ISSUE TITLE
Non-desired additional characters in branch on Debian Jessie

### ISSUE THREAD

**Issue by ErickChacon** [Bash-it/bash-it#770]
I have tried some themes (bobby, envy, powerline) and, in most of all, I have extra characters to the side of branch like "?:3","U:1":
|master ?:3 ✗| 
|master U:1 ✗| 
|master U:2 ✗|
Is there a setting to not show them?

**Comment by seefood** [comment]
run "git status", you will find untracked files or maybe other issues. consider adding this into your .gitignore. this is a feature, not a bug :)

**Comment by nwinkler** [comment]
In short, the themes are detecting that you are in a Git project folder, and it's showing you the current status.

* "master" is the name of the Git branch that you're on
* "?" shows the number of _untracked_ files
* "U" shows the number of _unstaged_ files
* The "X" shows that your workspace is _dirty_, i.e. that it has uncommitted changes.

I suggest you learn how to use this feature, as it's extremely useful.

If you still want to disable this feature, you can do so by defining the following in your `~/.bashrc` or `~/.bash_profile` (depending on your OS):

```bash
export SCM_GIT_SHOW_DETAILS=false
```

**Comment by ErickChacon** [comment]
Thank you so much @nwinkler . I like this feature, but not the symbols used for that (?, U). Is there a way to change this symbols for something more informative like (UK, UG)? Anyway, I am closing the issue. Thank you.

**Comment by nwinkler** [comment]
You can change these as part of the theme. Check out the theme definitions - the default values are defined in the base theme here: https://github.com/Bash-it/bash-it/blob/master/themes/base.theme.bash#L33

You can override these values in your own theme to something that you like better.

**Comment by ErickChacon** [comment]
Yeah!!, You are right @nwinkler. Thank you so much.
