### ISSUE TITLE
PROMPT_COMMAND environment variable is set incorrectly

### ISSUE THREAD

**Issue by Samze** [Bash-it/bash-it#772]
The prompt_command environment variable can be incorrectly set to contain two consecutive semi-colons. This causes the following error:
```
-bash: PROMPT_COMMAND: line 0: syntax error near unexpected token `;;'
-bash: PROMPT_COMMAND: line 0: `direnv_hook;prompt_command;;preexec_invoke_cmd`
```

It seems related to #767 

This occurs on OSX El Capitan.

**Comment by AcidSlide** [comment]
Hi Samze..

I've sent a issue ticket about this and already made a temporary workaround..

See here: https://github.com/Bash-it/bash-it/issues/767
