### ISSUE TITLE
Battery Plugin

### ISSUE THREAD

**Issue by brenoos** [Bash-it/bash-it#774]
When use powerline-multiline theme, battery porcentage dont appear.

whenre use comands: battery_char, battery_charge, battery_percentage, it's returned the following:
![bash](https://cloud.githubusercontent.com/assets/16320379/17371436/3db07328-5976-11e6-8492-48a814a0daa1.png)

can someone help me?

**Comment by nwinkler** [comment]
Which OS are you on? 

The battery plugin uses the following tools to get the battery charge information:
* Linux: `acpi`
* Mac OS X: `ioreg`

The `battery_percentage` function returns the word "no" when neither of these tools is found on the system.

**Comment by brenoos** [comment]
i'm using Ubuntu 16.04.

installed the acpi and now its workking, thanks man

**Comment by nwinkler** [comment]
Glad to hear that it's working now!
