### ISSUE TITLE
Add --global flag to install.sh to make Bash-it available to every user on the system.

### ISSUE THREAD

**Issue by rahiparikh** [Bash-it/bash-it#779]
It would be nice feature to have a `--global` flag for `install.sh`, which would make bash-it available to every user on the system. If that's not possible/a lot of work, would a Wiki page with instructions be an option?

**Comment by nwinkler** [comment]
Where would you recommend to install Bash-it in this case? It is currently installed in the user's home directory and then loaded from the user's `~/.bashrc` or `~/.bash_profile`script.

Installing it globally would mean to
* Install it in a global location like `/usr/local` (not sure where this would be on Windows)
* Run the installer with root access, e.g. `sudo`.
* Load Bash-it from a global startup script like `/etc/bashrc`

This sounds pretty invasive to me - do you see the need to have Bash-it enabled for every single user on the system?

**Comment by rahiparikh** [comment]
I was thinking of this as a feature for those who would like to do so and it could be helpful during templating, where an administrator might want to give the users powerful bash shell. 

How about a Wiki page or something that helps one achieve the similar without the need of `--global`l like option, if creating `--global` like flag looks too invasive?

**Comment by nwinkler** [comment]
Just to be clear - I don't think that the `--global` flag would be too invasive, that's not what I've meant.

I haven't encountered a use case where all users of a machine want to use Bash-it... If you have such a use case, feel free to draft a Wiki page that outlines the process. It should be along the lines of what I wrote above.

**Comment by edubxb** [comment]
I you would like to make Bash-it available to all users, why not use "skel", then, nd useradd/adduser will copy the Bash-it files to the user home?

The steps to make this work could be:

```
$ sudo git clone --depth=1 https://github.com/Bash-it/bash-it.git /etc/skel/.bash_it
```

then, change the `.bashrc` that you may have in the skel folder and add the minimal options needed in Bash-it to be activated:

```
## enable Bash-It ##
export BASH_IT=$HOME/.bash_it
. "${BASH_IT}/bash_it.sh"
```

After this, all users can manage Bash-it by their own.

What do you think about my proposal?

We can update the README.md to describe this procedure.

**Comment by rahiparikh** [comment]
I think this is really good suggestion.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
