### ISSUE TITLE
rvm-prompt command not found

### ISSUE THREAD

**Issue by twellspring** [Bash-it/bash-it#782]
I just installed bash-it on Mac OS 10.11.5  and am getting an rvm-prompt error every time I run a command.

```
 2016-08-17 12:09:22 ☆  xxxxxx-MacBook-Air in ~
± |master ✓| →
-bash: rvm-prompt: command not found
```

I have rvm instaleld via `port`
`rvm                            @1.07           sysutils/rvm`

which does not install the executable [rvm-prompt](url)

```
○ → port contents rvm
Port rvm contains:
  /opt/local/bin/rvm
  /opt/local/share/man/man1/rvm.1.gz
  /opt/local/var/log/rvm/.turd_rvm
```

Possible solution would be to add a `2>/dev/null`

```
function rvm_version_prompt {
  if which rvm &> /dev/null; then
    rvm=$(rvm-prompt 2>/dev/null) || return
    if [ -n "$rvm" ]; then
      echo -e "$RVM_THEME_PROMPT_PREFIX$rvm$RVM_THEME_PROMPT_SUFFIX"
    fi
  fi
}
```

**Comment by nwinkler** [comment]
That looks like a sensible addition. Please feel free to add a Pull Request for this change, and I'll merge...

**Comment by edubxb** [comment]
As you pointed to, `rvm` can be installed, but `rvm-prompt` not, but not the opposite, could be?, if yes, I think that the function can check directly for the `rvm-prompt` command:

```
function rvm_version_prompt {
  if which rvm-prompt &> /dev/null; then
    rvm=$(rvm-prompt 2> /dev/null) || return
    if [ -n "$rvm" ]; then
      echo -e "$RVM_THEME_PROMPT_PREFIX$rvm$RVM_THEME_PROMPT_SUFFIX"
    fi
  fi
}
```

I'm not a Ruby user/developer, so not sure if my guesses are right...

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
