### ISSUE TITLE
Wrong characters on xfce4-terminal with powerline theme

### ISSUE THREAD

**Issue by apaatsio** [Bash-it/bash-it#784]
xfce4-terminal (0.6.3) is showing wrong characters. For example it shows T where I believe should be an arrow. Wrong encoding somewhere? The xfce4-terminal has encoding set at UTF-8.

I don't know if this is a problem in bash-it or xfce4-terminal.

![terminal - wrong characters](https://cloud.githubusercontent.com/assets/195210/18125740/75bcaac8-6f80-11e6-8a59-43bffa854a81.png)

**Comment by nwinkler** [comment]
You need to install a font that has the Powerline symbols, e.g. from here: https://github.com/powerline/fonts

I'm using "Source Code Pro" from the above repo, and it's working fine.

**Comment by seefood** [comment]
or the "Input Font", if it meets your fancy....
http://input.fontbureau.com/

**Comment by apaatsio** [comment]
Thanks for the responses!

I installed Source Code Pro. I'm using Arch Linux so I installed the package https://www.archlinux.org/packages/extra/any/adobe-source-code-pro-fonts/

It's working perfectly now.

**Comment by nwinkler** [comment]
Great - thanks for closing!

**Comment by apaatsio** [comment]
Bumped into this issue again. This time on Linux Mint (Ubuntu). In case someone else is having the same issue, here's the solution. Just run

`sudo apt-get install fonts-powerline`

and restart the terminal.
