### ISSUE TITLE
Installing bash-it with hardcoded dependencies

### ISSUE THREAD

**Issue by cbaines** [Bash-it/bash-it#786]
Firstly, thanks for making this, I'm very much enjoying making my bash neat and usable, without putting in much effort :)

I'm using bash-it, along with GNU Guix, and one of the great things about Guix is the environments, so, for example, you can do `guix environment --pure --ad-hoc guile` and you have a shell with none of the environment leaking in. After starting to use bash-it, I noticed that I was getting lots of errors when doing this: 

```
bash: dircolors: command not found
bash: uname: command not found
bash: [: =: unary operator expected
bash: ls: command not found
bash: sed: command not found
bash: git: command not found
bash: awk: command not found
bash: tr: command not found
bash: wc: command not found
```

When packaging things for Guix, its quite normal to get the package to reference its dependencies using absolute paths to other files in the store, so if you want to use `gawk`, you run `/gnu/store/dwdp486f8yb41k8h1bigl98s5fbpga1q-gawk-4.1.3/bin/gawk`. So, as I want to package bash-it for Guix, I thought I would see if there was anything that could be done that would help with this?

I'm not sure just replacing the occurrences of awk, sed, ... with the absolute paths will work, as there will be false positives in the replacement. The only thing that came to my mind was possibly using variables like $SED such that just the assignment can be replaced?

**Comment by nwinkler** [comment]
Ouch, that sounds like a pretty invasive change...

So how do people use the Guix stuff that you mentioned. Are you seriously typing the full path, including that long random id for every single command?

Maybe I misunderstand the concept, but wouldn't that impact all scripting attempts? How do people write shell scripts for such environments? Maybe I'm missing something...

**Comment by cbaines** [comment]
> Ouch, that sounds like a pretty invasive change...
> 
> So how do people use the Guix stuff that you mentioned. Are you seriously typing the full path, including that long random id for every single command?

Not normally, when either installing a package within your profile, or using `guix environment` to create a profile, the programs you use are just on the $PATH.

> Maybe I misunderstand the concept, but wouldn't that impact all scripting attempts? How do people write shell scripts for such environments? Maybe I'm missing something...

I'm not aware that there is one perfect approach. Some Guix packages use "wrappers", scripts that wrap around another script or program that change the environment, e.g. adding directories to the $PATH. Also, I believe if you are packaging a script, another reasonable approach is to effectively "compile" it by hardcoding the paths to its dependencies.

bash-it is slightly different to a standard shell script, in that it can't be wrapped (as far as I am aware), which is why I opened this issue about possibly making it easier to insert absolute paths for dependencies when the package is built.

**Comment by nwinkler** [comment]
> Not normally, when either installing a package within your profile, or using guix environment to create a profile, the programs you use are just on the $PATH.

So is there a way to ensure that everything is on the $PATH? If they are, Bash-it should pick them up from the path.

**Comment by cbaines** [comment]
> So is there a way to ensure that everything is on the $PATH? If they are, Bash-it should pick them up from the path.

One motivation I have for opening this issue is that I want to be able to create environments (with Guix), and have bash-it work regardless of what is on the $PATH, and what is not.

As far as I am aware, there is not a way of just specifying a different value for $PATH that is limited to bash-it?

**Comment by cbaines** [comment]
> So is there a way to ensure that everything is on the $PATH? If they are, Bash-it should pick them up from the path.

So to directly answer your question, yes, but it would mean when I want to create environments which don't inherit the path from the existing environment, I'd need to remember to add all of bash-it's dependencies to that environment.

**Comment by nwinkler** [comment]
> So to directly answer your question, yes, but it would mean when I want to create environments which don't inherit the path from the existing environment, I'd need to remember to add all of bash-it's dependencies to that environment.

Would it be possible to automate this, and put it into a Bash-it plugin? Then it becomes a matter of making sure that it's executed first so that Bash-it runs it before loading the other functionality.

**Comment by cbaines** [comment]
I don't think a bash-it plugin would work, as the environment is somewhat fixed by the time bash-it runs, but just packaging bash-it for Guix, and having that package "propagate" (as in, if you tell Guix to install bash-it, it will also install...) all of the dependencies would mean that they are all available.

However, this would mean that just adding bash-it to an environment would be sufficient, but the bash-it dependencies would leak in to that environment, which is not desirable, and avoiding this was the reason that I opened this issue.

I realise that this global state is probably considered quite normal in the context of bash, but I thought I would enquire to see if you had any ideas about avoiding this.

**Comment by nwinkler** [comment]
Sorry, not sure what to do in that case. I don't want to introduce a huge change where we replace all occurrences of commands with variables - this would be pretty invasive...

**Comment by tswicegood** [comment]
@cbaines if you're interested in tackling the changes necessary we'd definitely take a look at the PR. I'm with @nwinkler – having a hard time visualizing this and what I am thinking of looks like a really big change.

One possible route would be to add `preload` scripts. Right now, when we get to [this line][1] we're already past the point of no return which renders things like a plugin useless to help this. If we add something above that loading anything found in `$BASH_IT/preload/enabled` we might be able to setup the environment there. Then we could use those for extreme circumstances like this.

[1]: https://github.com/Bash-it/bash-it/blob/master/bash_it.sh#L32

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
