### ISSUE TITLE
Slow scm info unless used by theme directly

### ISSUE THREAD

**Issue by Rush** [Bash-it/bash-it#790]
I tried numerous theme and theme `simple` is the only one that works really fast for me.

**Comment by nwinkler** [comment]
Can you provide some more info on this?

* Which SCM system are you using when you see this, e.g. Git or SVN?
* How big is the local repo?
* Can you describe or quantify the slowness?
* What do you mean by "unless used by theme directly"?

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
