### ISSUE TITLE
How to optionally configure custom prompts?

### ISSUE THREAD

**Issue by manojlds** [Bash-it/bash-it#801]
I see that prompts are mixed with themes. How do I add a new prompt that is optional. Like how plugins can be enabled? Am I missing something?

**Comment by nwinkler** [comment]
Not sure I understand what you're looking for...

Themes really are prompts - if you want a custom prompt, just copy one of the existing ones and make the changes you want.

**Comment by manojlds** [comment]
@nwinkler - I understand that from personal use point of view. What if I wanted to contribute it here?

Actual use case - I am trying to add Kubernetes kubectl context to my prompt. I would also like to contribute that back to bash-it. But not everyone would want it to be enabled right? How can I let people who want it, to enable it?

**Comment by nwinkler** [comment]
Got it, thanks, that makes sense.

We don't have a standard approach for that, but here are a couple of ideas:

* If you want to make your functionality available for all themes, add the function that retrieves the data to the `base.theme`. This way, it can be used in any theme.
* Some of the themes have configurable parts, e.g. the `powerline-multiline` theme. See the theme's readme (https://github.com/Bash-it/bash-it/tree/master/themes/powerline-multiline) for more info. I think this is a good pattern - add the functionality, document how to add it and then let the user decide which information to include in their theme.

Once you've made the changes that implement this new feature, feel free to create a Pull Request and we'll review that together.

**Comment by giggio** [comment]
One way to see the Kubernetes prompt is to use https://github.com/jlesquembre/kubeprompt/ with Bathit. But I could not get it to work.

**Comment by davidpfarrell** [comment]
Greetings All ! 

##### Regarding Optionally Configuring

As @nwinkler  mentioned, the Powerline themes are an excellent example of a theme that lets you optionally include different pieces of information into your prompt.

In Powerline, each different piece of information is called a `segment`.

Each segment has a code name and you use the code names to chose which segments you want, AND in which order they should be displayed.

_Example with scm context_
```
export POWERLINE_PROMPT="user_info scm cwd"
```
<img width="604" alt="user_scm_cwd" src="https://user-images.githubusercontent.com/45741407/72458224-086ca900-377d-11ea-9857-67c93ebc26d4.png">

_Example without scm context and different segment order_
```
export POWERLINE_PROMPT="cwd user_info"
```
<img width="604" alt="cwd_user" src="https://user-images.githubusercontent.com/45741407/72458237-0efb2080-377d-11ea-8233-b565a2d95913.png">

##### Regarding K8s Context:

Have a look at recently-added PR #1476  and the discussion I started there.

It introduces logic to for the k8s_context with my recommendation being to centralize that logic so all themes can take advantage of it.

I imagine that the k8s segment would be incorporated into bash-it similar to how the scm segment is incorporated, so you might want to look at that for inspiration.

@manojlds, you and @Diogo-Costa might be able to collaborate on this effort.

-D

**Comment by tuomassa** [comment]
> Greetings All !
> 
> ##### Regarding Optionally Configuring
> As @nwinkler mentioned, the Powerline themes are an excellent example of a theme that lets you optionally include different pieces of information into your prompt.
> 
> In Powerline, each different piece of information is called a `segment`.
> 
> Each segment has a code name and you use the code names to chose which segments you want, AND in which order they should be displayed.
> 
> _Example with scm context_
> 
> ```
> export POWERLINE_PROMPT="user_info scm cwd"
> ```
> 
> <img alt="user_scm_cwd" width="604" src="https://user-images.githubusercontent.com/45741407/72458224-086ca900-377d-11ea-9857-67c93ebc26d4.png">
> 
> _Example without scm context and different segment order_
> 
> ```
> export POWERLINE_PROMPT="cwd user_info"
> ```
> 
> <img alt="cwd_user" width="604" src="https://user-images.githubusercontent.com/45741407/72458237-0efb2080-377d-11ea-8233-b565a2d95913.png">
> 
> ##### Regarding K8s Context:
> Have a look at recently-added PR #1476 and the discussion I started there.
> 
> It introduces logic to for the k8s_context with my recommendation being to centralize that logic so all themes can take advantage of it.
> 
> I imagine that the k8s segment would be incorporated into bash-it similar to how the scm segment is incorporated, so you might want to look at that for inspiration.
> 
> @manojlds, you and @Diogo-Costa might be able to collaborate on this effort.
> 
> -D

Hi, thanks for this input. I'm still stuck with this, though. I want to add a simple segment to my powerline. If $MY_ENV_VAR exists, print its value, with the colors I want. I have been trying to find for example where "user_info" segment is defined so I could copy it, but I just cannot find any references to it, or any of the segment names. Where are they defined? Thanks!

**Comment by nwinkler** [comment]
Hey @tuomassa - thanks for the question.

The `user_info` segment function is defined here: 

https://github.com/Bash-it/bash-it/blob/9e92ef342f9673559e78220b14cd535aa631f4c7/themes/powerline/powerline.base.bash#L16

The naming convention for the Powerline segments is `__powerline_`_segment_`_prompt`, all of the functions can be found in the `powerline.base.bash` file. So for the `node` segment, the function is called `__powerline_node_prompt`, for example.

Does that help?

**Comment by tuomassa** [comment]
@nwinkler Yes, thanks alot! I was actually trying to modify powerline-multiline and didn't notice it actually sources the normal powerline theme so I was not looking in the right place!

**Comment by nwinkler** [comment]
You're welcome!
