### ISSUE TITLE
case insensitive auto complete 

### ISSUE THREAD

**Issue by sulhome** [Bash-it/bash-it#807]
is there a plugin to auto complete directory and file names regardless of their case?
fro example Downloads should be completed by typing *do + tab* or *Do + tab*

**Comment by edubxb** [comment]
This can be achieved setting:

`set completion-ignore-case on`

in your .inputrc file.

More info:

https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html

**Comment by sulhome** [comment]
thank you @edubxb 
it did the trick

**Comment by edubxb** [comment]
:+1:
