### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by mrmartineau** [Bash-it/bash-it#817]
I am trying to setup my work machine to use bash-it (i installed it on my personal machine without any problems).. 

As per the instructions: I have cloned the repo but I cannot run the install script. 
* When I run `~/.bash_it/install.sh` i get this error: `env: bash\r: No such file or directory`
* I have tried changing the permissions on it to make it executable `chmod +x install.sh`, but that returns this error: `-bash: install.sh: command not found`
* I have also tried `./install.sh` while in the `.bash_it`directory only to see this error: `env: bash\r: No such file or directory`

I am running this version of bash: `4.4.0(1)-release (x86_64-apple-darwin15.6.0)`.

Do you have any ideas what might be the issue?

**Comment by edubxb** [comment]
Seems an error in the _shebang_ not finding bash... weird...

Can you launch the installer in debug mode:

```bash -x ~/.bash_it/install.sh```

and paste the output here?

If you execute this in a terminal:

```env bash```

what is the result?

And this?

```which bash```

Thanks!

**Comment by mrmartineau** [comment]
Hi @edubxb, thanks for your response. 

Running `env bash` does nothing - it does seem to take a long time though..

Running `which bash` reveals `/usr/local/bin/bash`

Running `bash -x ~/.bash_it/install.sh` returns a few errors:

```sh
+ 	09:34:34	/Users/zmartineau/.bash_it/install.sh:3 	 main(): $'\r'
/Users/zmartineau/.bash_it/install.sh: line 3: $'\r': command not found
/Users/zmartineau/.bash_it/install.sh: line 5: syntax error near unexpected token `$'{\r''
'Users/zmartineau/.bash_it/install.sh: line 5: `function show_usage() {
```

I'm going to remove bash-it and start again to see if that fixes it..

**Comment by mrmartineau** [comment]
@edubxb does bash-it rely on a specific version of bash? when I run `bash --version` I get this:

```sh
GNU bash, version 4.4.0(1)-release (x86_64-apple-darwin15.6.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

However, when I run `echo $BASH_VERSION` I get this: `3.2.57(1)-release`.  

It is a bit weird to be honest. I have installed bash with brew, perhaps this is the issue..

**Comment by nwinkler** [comment]
It looks like you somehow ended up with DOS line endings in the file (`\r\n`) instead of the `\n` that Bash expects.

You can either try cloning it again, or use something like `dos2unix` to convert the files. Did you clone the project on this machine, or did you copy it over from a Windows machine?

Some further reference: http://stackoverflow.com/questions/5230798/r-character-in-shell-script

**Comment by mrmartineau** [comment]
Hi @nwinkler, I cloned on this machine. Very strange that line endings should be affected. Running `dos2unix` actually fixes the issue, thank you for that. I now have another problem which is preventing me from using bash-it now: lots of `: command not found`, full output below:

```
: command not found
: command not found
: command not found
: command not found
: command not found
': not a valid identifier
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
/bash_it.sh: No such file or directory
```

I ran `dos2unix` on the `bash_it.sh` to now avail - this is quite frustrating now.

**Comment by nwinkler** [comment]
When/where are you seeing these? After you've run the installer, or when opening a new terminal window/shell?

Can you post your `~/.bash_profile` or `~/.bashrc`?

The installer should have created a backup of these files as well - please post that backup, too.

**Comment by nwinkler** [comment]
Also, can you please check the setting of `core.autocrlf` in Git?

```
git config --global core.autocrlf
```

(Reference: https://help.github.com/articles/dealing-with-line-endings/)

**Comment by nwinkler** [comment]
Also, for updating Bash: https://johndjameson.com/blog/updating-your-shell-with-homebrew/
