### ISSUE TITLE
Use ls instead of $(uname) to set ls alias...

### ISSUE THREAD

**Issue by antisilent** [Bash-it/bash-it#818]
When using GNU utilities with MacOS, Bash_it incorrectly sets the `ls` alias in `aliases/available/general.aliases.bash` as `ls -G`.

Proposing the `ls` version check rely on the installed `ls` utility, not `$(uname)` as is currently implemented.

**Comment by haydenk** [comment]
You might be interested in Pull Request #869 

It's not perfect, it assumes if you have coreutils installed that you're using the `ls` that comes with it. If Homebrew isn't installed it doesn't do anything.

**Comment by nwinkler** [comment]
Should be fixed with #885
