### ISSUE TITLE
Issue with alias-completion

### ISSUE THREAD

**Issue by joeparis** [Bash-it/bash-it#820]
I'm running a fresh install of Ubuntu 16.10, have just installed bash-it, and have run into a problem which I've narrowed down to having the `alias-completion` plugin enabled. I have the following aliases, completions, and plugins enabled:

Aliases: `apt, atom, clipboard, general, npm, todo`

Completions: `apm, bash-it, dirs, grunt, gulp, npm, nvm, system, todo`

Plugins: `alias-completion, dirs, explain, extract, history, javascript, latex, less-pretty-cat, nginx, node, nvm, todo, virtualenv, visual-studio-code`

Whenever `alias-completion` is enabled (even if it is the *only* thing enabled) and I open a terminal window I see the following output:

```
bash: complete: /usr/bin/git: no completion specification
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect     Use binary search to find the commit that introduced a bug
   grep       Print lines matching a pattern
   log        Show commit logs
   show       Show various types of objects
   status     Show the working tree status

grow, mark and tweak your common history
   branch     List, create, or delete branches
   checkout   Switch branches or restore working tree files
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   merge      Join two or more development histories together
   rebase     Reapply commits on top of another base tip
   tag        Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch      Download objects and refs from another repository
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.

 2016-10-31 16:40:58 ⌚  ada in ~
○ → 
```

It seems that `git` is being called somewhere but I don't know where. I tracked it down this far but can't seem to get any further. Any help would be appreciated.

**Comment by edubxb** [comment]
Can you put the contents of your `.bashrc` and `.bash_profile`?

Thanks!

**Comment by joeparis** [comment]
I was able to track down the problem. I was loading supplementary scripts using the technique [here](https://sanctum.geek.nz/arabesque/shell-config-subfiles/) including this line: 

`alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'`

which was causing the problem. Moving the line into `~/.bash_it/aliases/custom.aliases.bash` has resolved the problem. Please mark this issue closed and thank you for your help!

**Comment by nwinkler** [comment]
Thanks - closing this now.
