### ISSUE TITLE
which font should I install to fixed the wrong letter?

### ISSUE THREAD

**Issue by ocian** [Bash-it/bash-it#844]
![like this](https://ooo.0o0.ooo/2016/11/25/5837d96dcdee0.png
)
like this

**Comment by nwinkler** [comment]
Which theme is this? If it's one using the Powerline symbols, you need to look here: https://github.com/powerline/fonts

I use the Source Code Pro font from this repo...

**Comment by ocian** [comment]
thanks for your help, the theme is the default theme named   'bobby' . 
> export BASH_IT_THEME='bobby'

**Comment by nwinkler** [comment]
These should be standard unicode characters, like the checkmark you can on this line: https://github.com/Bash-it/bash-it/blob/master/themes/bobby/bobby.theme.bash#L4

Not sure why they aren't shown in your case.

**Comment by ocian** [comment]
I can not find the reason of this in my font, and I do not know why. -_-!!!
My system is the Slackware Linux 14.2 and my  Desktop Environments is kde4.14.21. 
And I have installed the adobe-source-code-pro-font (1.030) font.

**Comment by ocian** [comment]
I have changed  my locale form  en_US to en_US.UTF-8, and the letter is becoming true.
Thanks for your help!

**Comment by nwinkler** [comment]
Great - good to hear that it's working now!
