### ISSUE TITLE
bash-it calls program HyperWorks V14.0 

### ISSUE THREAD

**Issue by craldaz** [Bash-it/bash-it#847]
When I source my bash-it bashrc it keeps opening HyperWorks a program installed on my CP. If I close it, it just opens again.

**Comment by nwinkler** [comment]
Can you please provide the following information?

* Your `~/.bashrc`
* The list of aliases, plugins and completions that you have enabled for Bash-it. You can run `bash-it show aliases` to get that output (replace `aliases` with `completions` or `plugins` to get the other info.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
