### ISSUE TITLE
Fedora - need /etc/bashrc source

### ISSUE THREAD

**Issue by metal3d** [Bash-it/bash-it#849]
Hi, 
I installed bash-it on Fedora 25 and it works like a charm, excpeting that my ~/.bashrc was initialized and didn't import /etc/bashrc whish is needed to have bash-completion functions.

So, maybe the .bashrc created by bash-it installation program should do this on top:

```bash
# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
```

**Comment by nwinkler** [comment]
Can you check whether enabling the `system` completion works for you in this case? It should load the system's own Bash completion scripts through the `/etc/bash_completion` script if present:

https://github.com/Bash-it/bash-it/blob/master/completion/available/system.completion.bash

**Comment by metal3d** [comment]
Bash system completion seems to be enabled:

```bash
bash-it show completion | grep system
system                [x]    
```

**Comment by metal3d** [comment]
To be sure, I removed the given snipet from my .bashrc and opened a new session.

I checked `bash-it show completion | grep system` and see that it's enabled. But completion with TAB shows me error:

example (I enabled git and kubectl completion for example)
```
kubectl bash: __ltrim_colon_completions: command not found
```

**Comment by metal3d** [comment]
OK, I see...

I don't habe `/etc/bash_completion` but `/etc/bash_completion.d` directory. That directory is listed and sourced by `/etc/bashrc`

**Comment by apaatsio** [comment]
I also got the `bash: __ltrim_colon_completions: command not found` error but in a slightly different way. 

I tried to run `docker run <Tab><Tab>` and got `❯ docker run bash: __ltrim_colon_completions: command not found`

It turned out I didn't have bash-completion installed. After installing that, the error disappeared.
