### ISSUE TITLE
${reset_color} does not reset "bold"ness

### ISSUE THREAD

**Issue by pmbenjamin** [Bash-it/bash-it#851]
If bold colors are used in theme, followed by ${reset_color}, the color is successfully reset back to the default color (in my case, white), but the bold font remains.

Examples:
```bash
# my theme
STATUS_THEME_PROMPT_BAD="${bold_red}❯${reset_color} "
STATUS_THEME_PROMPT_OK="${bold_green}❯${reset_color} "
```
Output (note the `cd dotfiles/`):
<img width="435" alt="screen shot 2016-12-06 at 10 38 30 pm" src="https://cloud.githubusercontent.com/assets/6811830/20957491/074b1c2e-bc05-11e6-86d1-a8c93ab9bf1e.png">
As compared to non-bold font:
<img width="418" alt="screen shot 2016-12-06 at 10 38 11 pm" src="https://cloud.githubusercontent.com/assets/6811830/20957496/0c4c7236-bc05-11e6-95d3-384b50f20419.png">

**Comment by pmbenjamin** [comment]
I just saw another theme make use of `${normal}`, so I guess this is a non-issue, but it would be nice if `${reset_color}` did this by default.

**Comment by nwinkler** [comment]
Well, strictly speaking, `bold` is not a color, hence I wouldn't expect `reset_color` to clear the bold formatting.

On the other hand I agree, this should probably be documented in a better way...

**Comment by nwinkler** [comment]
Closing this for now...
