### ISSUE TITLE
[Bug] $EDITOR + git diff alias

### ISSUE THREAD

**Issue by pmbenjamin** [Bash-it/bash-it#853]
First of all, I appreciate `bash-it` project. It has won me over from `oh-my-zsh`. Thank you, owner & maintainers, for such a cool bash framework.

### Issue
I ran into the following issues when trying to `git diff`:
1. I didn't have `$EDITOR` set, so `bash-it` assumed that I have `mate`, which led to errors when attempting to `gd` because `mate` does not exist on my system.

2. I decided to set my `$EDITOR` to `vim`, but that didn't work either. It led to the following error:
    ```
    Vim: Warning: Input is not from a terminal
    Vim: Error reading input, exiting...
    Vim: Finished.
    ```

### Proposal
The logic in `git.aliases.bash` for handling and assigning `gd` alias to `git diff | $EDITOR` can be improved.
Given the current setup:
```
if [ -z "$EDITOR" ]; then
    case $OSTYPE in
      linux*)
        alias gd='git diff | vim -R -'
        ;;
      darwin*)
        alias gd='git diff | mate'
        ;;
      *)
        alias gd='git diff'
        ;;
    esac
else
    alias gd="git diff | $EDITOR"
fi
```
#### Proposal 1: Least amount of effort
```
if [ -z "$EDITOR" ]; then
    case $OSTYPE in
      linux*)
        alias gd='git diff | vim -R -'
        ;;
      darwin*)
        command -v mate && alias gd='git diff | mate' || alias gd='git diff'
        ;;
      *)
        alias gd='git diff'
        ;;
    esac
else
    alias gd="git diff | $EDITOR"
fi
```

#### Proposal 2: 
Since `git` itself has a configuration for `editor` (e.g. `git config --global core.editor`), which can be set to the editor of your choice, piping the results of `git diff` to `$EDITOR` feels a bit awkward.
So, we can just let git use the editor that the user has specified:
```
if [ -z "$EDITOR" ]
then
    alias gd='git diff'
else
    alias gd="git diff | $EDITOR"
fi
```
But this approach could still cause problems for `gd` alias if other software expect the user to set `$EDITOR`, because the logic will fall through to the `else` statement if `$EDITOR` exists.

#### Proposal 3:
Regardless of whether `$EDITOR` is set or not, if a user prefers to use a non-default editor with `git`, they can do `git config --global core.editor "mate"`, which would eliminate the need to pipe output to `$EDITOR` altogether.
```
alias gd='git diff'
```

**Comment by pmbenjamin** [comment]
Also, here is how `oh-my-zsh` address a similar issue:
`gdv() { git diff -w "$@" | view - }` (where `view` is just `vi` in read-only mode, which is much safer than vim or mate since those may not be installed by the user).

**Comment by nwinkler** [comment]
Good suggestions! I don't use the `gd` alias for the reasons you have cited. Using `vim` as my `$EDITOR`, I get the same error as you.

The aliases contain a `gdv` alias that is similar to what you have suggested: https://github.com/Bash-it/bash-it/blob/master/aliases/available/git.aliases.bash#L35

```bash
alias gdv='git diff -w "$@" | vim -R -'
```

The `-R` starts vi in read-only mode, just like using `view`.

I primarily use `gdv`, since it works just fine...

**Comment by nwinkler** [comment]
@pmbenjamin Let me know how you want to proceed here. As stated above, Bash-it has an alias called `gdv`, which does the same thing as the function from oh-my-zsh.

**Comment by pmbenjamin** [comment]
@nwinkler , that's fine. We can close this issue. Thank you for the `gdv` tip.
