### ISSUE TITLE
bash-it dockerized

### ISSUE THREAD

**Issue by ellerbrock** [Bash-it/bash-it#862]
hi there,

i create a docker image pre configured with bash as default shell with bash-it with default configuration. i think this is very useful to get a quick look and play with it in a very easy way.

you can have a look here: <https://hub.docker.com/r/frapsoft/bash-it/>

we could add this to the documentation that new user can have a quick look before installing it on there system. and for docker user its a nice container when configured correct makes working inside containers more fun.

you can have a look and let me know what you think about it.
in case its interesting for the project you could make a new repo "bash-it-docker" or something where i could maintain it.

cheers maik

![](http://i.giphy.com/l3E6qj3wFoUiXbxuw.gif)

**Comment by nwinkler** [comment]
Oh, this is very cool!

I have a Vagrant box that I use for a similar purpose (testing the installer without wrecking my own settings, etc.).

We could create repos for those under the official Bash-it account: https://github.com/Bash-it, then add documentation and people could use this for giving it a try.

What do others think about this?

**Comment by ellerbrock** [comment]
hi @nwinkler,

nice to hear that you like it.
a official repository would be the best solution, further we should create an account on docker hub and quay as well. if docker user search for a special functionality / images this is the first place to have a look, also they don't have to run the compilation from all the dependencies locally and can download just the missing image layer from the registry.
best practices would be to create builds automatically from the source on new releases.
automatically build images are much more trustworthy because you can follow via dockerfile exactly what was happening and nobody can sneak some malicious stuff inside.

after we got all setup and working we could try to get us registered as official account.
again more trust in the images and normally the first choice form the users.

i can help set things up and maintain it, since i depend on secure stable images for my devop work in the company ...

**Comment by ellerbrock** [comment]
hey pal,

just wanted to her what about the docker idear?
best would  maybe first that we collect some infos what people would love to see and based on that build something cool. i ordered for myself on xmas a server with 32 ram so at home and at work will be everything inside a container :)

**Comment by nwinkler** [comment]
Sorry for the delay, I tried to spend as little time in front of the computer as possible over the holidays...

I've created a repo here: https://github.com/Bash-it/Bash-it-Docker

I've also added you to the new Bash-it "Docker" team, you should have received an invite.

It's probably best if you mark the new repo as WIP until we have a stable version.

**Comment by ellerbrock** [comment]
no worries,

same for me, few days relaxing and clearing the head over xmas ...
i just checked but could not find any team invitation yet.
i create a first clean version for bash-it dockerized meanwhile ...

**Comment by nwinkler** [comment]
OK - enabled Travis for the new repo: https://travis-ci.org/Bash-it/bash-it-docker

With the WIP comment I meant that we should probably place a note like "Work in Progress" in the project's README until we have a stable version - nothing more.

**Comment by ellerbrock** [comment]
ok cool,

thanks for activating travis!
i prepared yesterday most of the docker stuff and will try to add some tests and documentation today and then release a first version.

**Comment by nwinkler** [comment]
Awesome - looking forward to that!

**Comment by ellerbrock** [comment]
:whale2: where are up and running  :tada: :sparkles: :dizzy:

**Comment by nwinkler** [comment]
Awesome!

**Comment by nwinkler** [comment]
Closing this now...
