### ISSUE TITLE
bash: command substitution: line 1: syntax error near unexpected token `)'

### ISSUE THREAD

**Issue by eromoe** [Bash-it/bash-it#864]
On git-bash(mintty on windows)
I enable alias and restart shell , then everytime I run a command lost color(ls alias not contain `--color` why?)
 and show this error(though that command works well):
```
alias tree='find . -print | sed -e '\''s;[^/]*/;|____;g;s;____|; |;g'\'''
bash: command substitution: line 1: syntax error near unexpected token `)'
bash: command substitution: line 1: `[[ -n $(git branch 2> /dev/null) ]] && echo " on ")'
bash: command substitution: line 1: syntax error near unexpected token `)'
bash: command substitution: line 1: `parse_git_branch)'
```

**Comment by nwinkler** [comment]
Can you try the following:

* Check the setting of Git's `core.autocrlf` - see #817 for more info.
* Check out a fresh clone of Bash-it in case the above required a change.
* Try a different theme - the code you posted seems to be from the `sexy` theme. Just try a different one to see whether this is a specific issue with the `sexy` theme.
* Post your version of Bash
* Try to disable the plugins and aliases that you have enabled.

Let me know if any of the above fix the issue.

**Comment by JokerQB** [comment]
On git-bash(mintty on windows)
I want to install gulp, and i write ' npm install gulp ', but the git-bash see the following erro:
/d/node/npm: line 1: syntax error near unexpected token `newline'
/d/node/npm: line 1: `> '

**Comment by taavs** [comment]
Same thing happened to me on my Windows machine while using the SEXY theme. 

Changed it to a different one and now is working.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
