### ISSUE TITLE
Theme prompt_command function not executed when including system bashrc

### ISSUE THREAD

**Issue by font** [Bash-it/bash-it#883]
If a user wants to keep including their system `/etc/bashrc` in order to for example utilize the system installed bash completions, then they are not able to overwrite the system `PROMPT_COMMAND` function using the standard `prompt_command` function name in the themes. This is because the great majority of the bash-it themes use exactly `prompt_command` as the name of their prompt command function whereas the `/etc/bashrc` (in the case of Fedora) sets a similar `__vte_prompt_command` function name. This causes [this case statement](https://github.com/Bash-it/bash-it/blob/2b4298c00ea882026134c1d8f5da93d52fbaf6ae/themes/base.theme.bash#L468) to always satisfy the [`*$1*`](https://github.com/Bash-it/bash-it/blob/2b4298c00ea882026134c1d8f5da93d52fbaf6ae/themes/base.theme.bash#L469) case and never execute the custom theme's `prompt_command` function because the wildcards match `prompt_command` as a substring of the system's `__vte_prompt_command` function.

A few possible ways to fix this come to mind immediately:
1. Every theme would need to use a different name other than `prompt_command` as their function name to make sure the wildcard does not match their function name as a substring. Seems too late for this.
2. Somehow change the case statement to check that the caller's argument `$1` is matched ***exactly*** and not a wildcard match for the substring existing in the `PROMPT_COMMAND` variable.
3. Perhaps unset the `PROMPT_COMMAND` variable the first time `safe_append_prompt_command` is called.

**Comment by nwinkler** [comment]
Interesting catch! To fix this, I suggest rewriting the `case` statement that you linked to (https://github.com/Bash-it/bash-it/blob/2b4298c00ea882026134c1d8f5da93d52fbaf6ae/themes/base.theme.bash#L468) to use an `if` statement with a real regular expression, checking that there's a full match on the name (e.g. `\bprompt_command\b`) to avoid the situation you describe.

I guess we'd need one if that checks for the empty case, one for a full match, and else for prepending the parameter to the `PROMPT_COMMAND` variable.

That's closest to what your second suggestion looks like.

Please feel free to provide a PR for this.

**Comment by nwinkler** [comment]
Closing as this is now working (see #888).
