### ISSUE TITLE
How to not have git info in the theme?

### ISSUE THREAD

**Issue by didibus** [Bash-it/bash-it#890]
How do I remove the lookup of git repo status in themes? I don't have the GIT plugin enabled, yet this functionality is there.

Thanks.

**Comment by nwinkler** [comment]
Please set the following in your Bash config file (either `~/.bash_profile` or `~/.bashrc`, depending on which OS you're on):

```bash
export SCM_CHECK=false
```

This will disable the display of SCM information (including Git) in the themes.

You can find this in the `Misc` section of Bash-it's README file...

Please close this issue if this is what you're looking for.

**Comment by didibus** [comment]
That worked, thanks.
