### ISSUE TITLE
Feature request: Fish-like autocompletion and autosuggestion

### ISSUE THREAD

**Issue by seagle0128** [Bash-it/bash-it#894]
Hi, I like this project and use recently. I used Fish and ZSh. I'd like request some new features I missed very much: Fish-like autocompletion and autosuggestion. Some guys implemented in Zsh already. is it possible to implement in Bash? Thanks!

**Comment by nwinkler** [comment]
Can you please described what these features do? Without that, it will be hard to impossible to implement them.

**Comment by arimourao** [comment]
I think he is referring to [fish shell](https://github.com/fish-shell/fish-shell)

**Comment by seagle0128** [comment]
@arimourao yes. Could refer to fish shell.
And here is the implementation in zsh/oh-my-zsh.
https://github.com/zsh-users/zsh-autosuggestions
https://github.com/zsh-users/zsh-syntax-highlighting

**Comment by nwinkler** [comment]
Sorry guys, but I'm way too busy to read through these links and figure out what you're looking for.

If you're interested in having a feature added, please provide a concise description of what you're looking for. Or even better provide a Pull Request that implements the feature. Suggestions are great, but someone will have to implement it in the end.

No offence, but I don't have time for doing this guesswork.

**Comment by seagle0128** [comment]
Okay. Let explain the details. What's I want exactly is Fish-like auto-suggestions as below.
The command suggestions come out automatically according to the history. It's very useful while typing the long commands. And you can see the syntax highlight color of the commands in the screenshot.

**Comment by arimourao** [comment]
@seagle0128 it's interesting but I think this is an entire new project in its own. You or someone else interested in these features should port these to Bash. Only then bash-it could add these as plugins to be installed.

**Comment by nwinkler** [comment]
Agreed. This looks like a useful feature, but if you take a look at the project, it looks like a huge undertaking. Not sure whether Bash supports the features required for making something like this happen.

**Comment by lfelipe1501** [comment]
Hi @seagle0128 I would like to have in bash the zsh autocomplete but so far what I have found is this.

[https://github.com/dvorka/hstr](url)

I hope it works for you and that @nwinkler revises it to implement it in the framework.

Greetings. :bowtie:

**Comment by nwinkler** [comment]
This looks similar to `fzf`, which we already have a plugin for - allowing to search through your history for previous commands...

From what I've seen, the autocomplete functionality you're looking for is not easily possible in Bash...

BTW: I'm not sure why you think that I have to implement this. Feel free to provide a Pull Request if you have something you would like to see added.

**Comment by ShalokShalom** [comment]
I completely support the suggestion of @seagle0128

**Comment by ShalokShalom** [comment]
I completely support the suggestion of @seagle0128 

This is something very similar: https://github.com/scop/bash-completion

**Comment by nwinkler** [comment]
Isn't the Bash completion you linked to exactly what we already have in Bash-it's completion functionality?

**Comment by ShalokShalom** [comment]
Idk, i dont know bash-it - i thought its bash and hit this page here by google xD :P

**Comment by ShalokShalom** [comment]
This is what i mean: https://asciinema.org/a/37390?t=16

**Comment by ericbaranowski** [comment]
I agree with you guys, I can't believe something like that doesn't already exist for bash. Like @nwinkler said, bash probably doesn't support the features necessary to achieve the functionality, otherwise it would exist already. However, based on all these comments I'm gonna look further into the port idea.

**Comment by ShalokShalom** [comment]
I am on zsh now and very happy. Oh-my-zsh made it very easy to setup and https://github.com/zsh-users/zsh-autosuggestions add the functionality. One plus pro is that zsh is fully compatible with bash.
Solved for me...

**Comment by TimothyBramlett** [comment]
@ShalokShalom Nice, yeah I may need to the zsh route also.  I love fish for its autocompletion but I hate that its not compatible with bash, which is used heavily for scripting that you are forced to use it.

**Comment by seagle0128** [comment]
I agree. I switch to `zsh` a few months ago and am happy as well.

**Comment by nwinkler** [comment]
Closing this now...

**Comment by bluz71** [comment]
Personally I believe Bash/Readline's existing `history-search-backward` and `history-search-forward` options are just as useful and less distracting (at least to my eye).

Add the following to `~/.inputrc`:

```
"\e[A": history-search-backward
"\e[B": history-search-forward
```

Type a partial command (one that you have already executed previously) then use the UP-arrow to navigate through all the commands that match the prefix. Whilst it doesn't look as sexy as Fish/Zsh auto-suggestion it is just as functional.

**Comment by nwinkler** [comment]
Personally, I use `fzf` for that. If you install `fzf` and enable the `fzf` plugin, your `Ctrl+R` prompt turns into a fuzzy filter for command history, it will autocomplete previous commands as you type. I find this to be highly productive...

**Comment by benjamin-thomas** [comment]
Coming from a google search...

After seeing some advantages from fishshell over bash but still preferring a lot of bash idioms (`!!`, `$!`, `$!:h`, command completion with `<ESC>*`, etc.)

Oh...my...god!!!

@nwinkler, you just made my day!!

What an awesome tool fzf is!!

Combined with vim integration, I'm blown away..

**Comment by nwinkler** [comment]
Thanks for the kind words, @benjamin-thomas - happy to help.

[fzf](https://github.com/junegunn/fzf) is indeed absolutely fantastic, one of the best shell tools I know.

In addition to the built-in functionality (`Ctrl+R`), the [fzf plugin](https://github.com/Bash-it/bash-it/blob/8217b7beb06f7277c21d773aea80ecb33d6cfb8b/plugins/available/fzf.plugin.bash) contains some common functions that I have adapted from the fzf Wiki, too.

I also use it ad-hoc for things like `ls | fzf`, together with the preview functions this is incredibly useful. Try this with the configuration from my dotfiles:

https://github.com/nwinkler/dotfiles/blob/0d5688368b6a15e701768305625a469e43170c47/home/.bash_profile#L18-L27

**Comment by benjamin-thomas** [comment]
These are very, very nice ideas.

Very well done, and thanks for the share!

**Comment by iamnoskcaj** [comment]
I too, love the fish shell for its unobtrusive command suggestions, inline, as I'm typing.  I got so used to it.  It's nice zsh has something similar (as mentioned by @ShalokShalom).  I am far more comfortable in a bash similar shell, and fish is a little out there for me.

**Comment by cojack** [comment]
Impossible to achieve?

**Comment by akinomyoga** [comment]
As far as I know, it's impossible unless `readline` is modified or replaced by some other line editor. I actually implemented syntax-highlighting and autosuggestions in my bash configuration ([akinomyoga/ble.sh](https://github.com/akinomyoga/ble.sh)), but it replaces `readline` with a line editor written in bash scripts so that some behaviors might be different from those in `readline`. Nevertheless, maybe you like `ble.sh` (if you don't want to implement a new line editor and autosuggestions for yourself).

**Comment by gilescope** [comment]
FYI pwsh is implementing auto-suggest in their PSReadLine project. (See fish branch)

I have a dream, that one day, bash too will have auto-suggest.
