### ISSUE TITLE
bash-it: command not found

### ISSUE THREAD

**Issue by arimourao** [Bash-it/bash-it#896]
I install using the "install.sh" script using the '--interactive' flag. I select all completions and plugins that I want to use. Upon finishing the installation, I try to see the list of available aliases typing: "bash-it show aliases" and then it says that bash-it is not a command. What should I do?

**Comment by nwinkler** [comment]
When the installer finished, it should have printed a message with the suggestion to either open a new terminal window, or to `source` your Bash config file.

Once you've done that, the `bash-it` command should be available.

Can you please try this and report back here?

**Comment by arimourao** [comment]
Hey @nwinkler tnx for your support. Don't know what was I doing wrong, but today I tried again and it is working just fine. You can close this now. Tnx.

**Comment by nwinkler** [comment]
Thanks for confirming!

**Comment by dmwelch** [comment]
Having the same issue after having my work account moved from local admin to Active Directory.  Did a fresh download and install.  After install, I source the `.bash_profile` and get this:

> -sh: `bash-it': not a valid identifier
-sh: `_bash-it-aliases': not a valid identifier
-sh: `_bash-it-completions': not a valid identifier
-sh: `_bash-it-plugins': not a valid identifier
-sh: `_bash-it_update': not a valid identifier
-sh: `_bash-it-migrate': not a valid identifier
-sh: `_bash-it-version': not a valid identifier
-sh: `_bash-it-reload': not a valid identifier
-sh: `_bash-it-describe': not a valid identifier
-sh: `_disable-plugin': not a valid identifier
-sh: `_disable-alias': not a valid identifier
-sh: `_disable-completion': not a valid identifier
-sh: `_disable-thing': not a valid identifier
-sh: `_enable-plugin': not a valid identifier
-sh: `_enable-alias': not a valid identifier
-sh: `_enable-completion': not a valid identifier
-sh: `_enable-thing': not a valid identifier
-sh: `_help-completions': not a valid identifier
-sh: `_help-aliases': not a valid identifier
-sh: `_help-list-aliases': not a valid identifier
-sh: `_help-plugins': not a valid identifier
-sh: `_help-update': not a valid identifier
-sh: `_help-migrate': not a valid identifier
-sh: `_bash-it-search': not a valid identifier
-sh: `_bash-it-array-contains-element': not a valid identifier
-sh: `_bash-it-search-component': not a valid identifier
-sh: `_bash-it-search-result': not a valid identifier
-sh: `about-alias': not a valid identifier
-sh: about-alias: command not found
-sh: `about-alias': not a valid identifier
-sh: about-alias: command not found
-sh: `about-alias': not a valid identifier
-sh: about-alias: command not found
-sh: `about-alias': not a valid identifier
-sh: about-alias: command not found
-sh: `about-alias': not a valid identifier
-sh: about-alias: command not found
-sh: `about-alias': not a valid identifier
-sh: about-alias: command not found
-sh: `about-alias': not a valid identifier
-sh: about-alias: command not found
-sh: `about-alias': not a valid identifier
-sh: about-alias: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `banish-cookies': not a valid identifier
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `local-ignore': not a valid identifier
-sh: `gitignore-reload': not a valid identifier
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `dock-switch': not a valid identifier
-sh: `refresh-launchpad': not a valid identifier
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: `_bash-it-comp-enable-disable': not a valid identifier
-sh: `_bash-it-comp-list-available-not-enabled': not a valid identifier
-sh: `_bash-it-comp-list-enabled': not a valid identifier
-sh: `_bash-it-comp-list-available': not a valid identifier
-sh: `_bash-it-comp': not a valid identifier
-sh: `_dirs-complete': not a valid identifier
-sh: `about-plugin': not a valid identifier
-sh: about-plugin: command not found
-sh: /Users/dwelc/src/bash-it/enabled/365---alias-completion.plugin.bash: line 84: syntax error near unexpected token `<'
-sh: /Users/dwelc/src/bash-it/enabled/365---alias-completion.plugin.bash: line 84: `    done < <(alias -p | sed -Ene "s/$alias_regex/\2 '\3' '\4'/p")'
-sh: `_git-symbolic-ref': not a valid identifier
-sh: `_git-branch': not a valid identifier
-sh: `_git-tag': not a valid identifier
-sh: `_git-commit-description': not a valid identifier
-sh: `_git-short-sha': not a valid identifier
-sh: `_git-friendly-ref': not a valid identifier
-sh: `_git-num-remotes': not a valid identifier
-sh: `_git-upstream': not a valid identifier
-sh: `_git-upstream-remote': not a valid identifier
-sh: `_git-upstream-branch': not a valid identifier
-sh: `_git-upstream-behind-ahead': not a valid identifier
-sh: `_git-upstream-branch-gone': not a valid identifier
-sh: `_git-hide-status': not a valid identifier
-sh: `_git-status': not a valid identifier
-sh: `_git-status-counts': not a valid identifier
-sh: `_git-remote-info': not a valid identifier
-sh: `_p4-opened': not a valid identifier
-sh: `_p4-opened-counts': not a valid identifier
-sh: printf: -e: invalid option
printf: usage: printf [-v var] format [arguments]
-sh: printf: -e: invalid option
printf: usage: printf [-v var] format [arguments]
-sh: _git-hide-status: command not found
-sh: _git-upstream-behind-ahead: command not found
-sh: _git-hide-status: command not found
-sh: _git-status-counts: command not found
-sh: _git-friendly-ref: command not found

(I suspect there are some underlying permissions errors too, as I've found more than one directory (`/usr/local/Homebrew`, `~/Documents`) with the wrong permissions or with the wrong GID.  Any help on what to look for would be appreciated!)

**Comment by nwinkler** [comment]
Are you sure your default shell is set to Bash? It looks like it's possible that you're running this in `sh` instead? Or that `bash` is symlinked to `sh`...

**Comment by 0x4a6f7368** [comment]
That was my problem with only 1 error message ("xyz" not a valid identifier.  I used `sh install.sh` instead of `bash install.sh`.  I uninstalled with `sh uninstall.sh` and reinstalled with `bash install.sh` now no error messages.
