### ISSUE TITLE
Prompt breaks one extra line when computer is charging

### ISSUE THREAD

**Issue by ersiko** [Bash-it/bash-it#899]
Hi

I don't know if it's only me, but with battery plugin, when my laptop is charging, my prompt breaks one extra line:
![image](https://cloud.githubusercontent.com/assets/3366936/22719029/c399de86-eda3-11e6-8fce-616778377a8d.png)

In that screenshot you can see it charging and not charging. Looks like the extra "ray" to indicate charging is pushing the prompt one more character, breaking to next line.

If I resize the window, it will still do the same with the new size, so it doesn't look like a window size problem.

I'm using ubuntu, terminix, bash-it theme 'powerline-multiline' and battery plugin.

Thanks!

**Comment by nwinkler** [comment]
Interesting - I can't reproduce this on the Mac. I also use the `battery` plugin and the `powerline-multiline` theme and it works fine for me...

**Comment by arimourao** [comment]
I also couldn't confirm this error in Debian 8 Jessie. Could it be the terminix emulator that you are using.

**Comment by ersiko** [comment]
Further testing makes me thing is a gtk thing.

These terminals are OK: konsole, xterm
These terminals are not OK: terminix, terminator, unity terminal




2017-02-09 14:31 GMT+01:00 Ari Mourao <notifications@github.com>:

**Comment by boldandbusted** [comment]
Just adding sakura to the affected terminals list. http://www.pleyades.net/david/projects/sakura/ Sakura is based on GTK and VTE.

**Comment by tillepille** [comment]
I have the same issue with MacOS 14.4  

Started with a empty .bash_profile , choose the theme and: 
```bash
$ echo $POWERLINE_RIGHT_PROMPT
> clock battery user_info
```
<img width="1082" alt="Bildschirmfoto 2019-04-13 um 18 43 04" src="https://user-images.githubusercontent.com/16536696/56082686-06577180-5e1c-11e9-815b-db8459d3bb3c.png">

**Comment by pablitok** [comment]
Same problem with Konsole in Kubuntu 19.04 just upgraded from 18.10 but the issue is present with and without charger connected

Didn't see this issue and created a new one. Sorry. https://github.com/Bash-it/bash-it/issues/1377
