### ISSUE TITLE
Why the installer doesn't add git completions in .bashrc by default?

### ISSUE THREAD

**Issue by arimourao** [Bash-it/bash-it#900]
As you can see in the documentation of 'git.completion.bash' it is the expected behavior to wait for the user to add some parameters to his .bashrc to have this completion working. Why not let the installer handle this?

**Comment by nwinkler** [comment]
Sorry, not sure which code you're referring to - what needs to be added to `.bashrc`?

I'm using the Git completion, and I'm pretty sure that I did not need to add anything to make it work. I simply enabled it using `bash-it enable completion git` and that's it...

**Comment by arimourao** [comment]
According to the own documentation inside git.completion.bash:

# To use these routines:
#
#    1) Copy this file to somewhere (e.g. ~/.git-completion.bash).
**#    2) Add the following line to your .bashrc/.zshrc:
#        source ~/.git-completion.bash**
#    3) Consider changing your PS1 to also show the current branch,
#       see git-prompt.sh for details.

and indeed it just worked for me if I added to my .bashrc

**Comment by nwinkler** [comment]
You shouldn't have to do that. The comments in there are from the Git distribution where this script originated from, please ignore them.

The whole purpose of the Git completion script in Bash-it is to be able to use without having to source it explicitly.

What should work instead is the following:

 1) Run `bash-it enable completion git`
 1) Reload the Bash-it configuration: `reload`

After that, Git completion should work - you shouldn't have to source the file from your `.bashrc` at all.

**Comment by arimourao** [comment]
Ok, missed the reload thing. It seems to work indeed as you say. Why is the reload commented by default in .bashrc? Just curiosity. You can close this issue. :+1:
