### ISSUE TITLE
A suggestion for emacs alias

### ISSUE THREAD

**Issue by memoryleakno1** [Bash-it/bash-it#911]
Hello guys, I just installed bash-it and ment do enbalse some alias groups. Since I am have Emacs user I took a peak at emacs group and found that I already have on my own habit almost everything same difined, but for one alias. You have defined ed='emacs --daemon' while I have ed='emacs --debug-init'.

In my opinion one (almost) never runs emacs --deamon from command line. Purpose of emacs --deamon is to start it with your system so one does not have to wait for it to load it. Personally I have systemd service in Linux and start it via shortcut in autostart folder on windows. However, thinkering with your emacs installation, installing packages, adding stuff to you init, customization etc are much more frequent, and when something breaks, emacs --debug-init is really helpfull. So I have discovered after many years of emacs use that I use it much more so I have my alias reflecting that use.

Of course, it's all my personal taste and use-case, so feel free to ignore, it's just a suggestion. 

Thanks for providing bash-it.

**Comment by nwinkler** [comment]
Thanks for the feedback! As I'm not using Emacs at all, I don't really have an opinion on this...

If you're using Bash-it and want to change the alias, you can always do so in your own fork.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
