### ISSUE TITLE
Git diff alias fails when $EDITOR set

### ISSUE THREAD

**Issue by nickjer** [Bash-it/bash-it#921]
This is related to https://github.com/Bash-it/bash-it/issues/853, but since he had two issues in there, I thought I'd break it out into the single issue I am having.

When `$EDITOR` is set ([here](https://github.com/Bash-it/bash-it/blob/5858fcdbdd39eab909425a16ede1c90572ac513c/aliases/available/git.aliases.bash#L97)) on a Linux machine, the alias `gd` will fail in most cases, e.g.:

```sh
$ git diff | vim
Vim: Warning: Input is not from a terminal

Vim: Error reading input, exiting...
Vim: preserving files...
Vim: Finished.
```

```sh
$ git diff | nano
Received SIGHUP or SIGTERM

Buffer written to nano.save
```

```sh
$ git diff | gedit
# Opens to blank screen
```

In all three cases, appending a dash at the end will cause them to work. Although, I am leaning towards removing the `if [ -z "$EDITOR" ]; then` statement completely:

```sh
case $OSTYPE in
  linux*)
    alias gd='git diff | vim -R -'
    ;;
  darwin*)
    alias gd='git diff | mate'
    ;;
  *)
    alias gd='git diff'
    ;;
esac
```

As an aside, since you offer `gdv`, maybe for linux just have `gd='git diff'` instead of `gd='git diff | vim -R -'`. As of right now there is no way to get the default `git diff` behavior on Linux with these great aliases. So something along the lines of:

```sh
case $OSTYPE in
  darwin*)
    alias gd='git diff | mate'
    ;;
  *)
    alias gd='git diff'
    ;;
esac
```

**Comment by nwinkler** [comment]
Good suggestions. I'd even go one step further and get rid of the `darwin` case. I use macOS, but don't have Textmate installed, so for me the `git diff | mate` doesn't work anyway...

Feel free to provide a PR for changing the whole `gd` alias to just `git diff`.
