### ISSUE TITLE
Windows WSL/Bash support?

### ISSUE THREAD

**Issue by thenitai** [Bash-it/bash-it#923]
Hi there,

Not sure if WSL is supported but I gave it a go (should work as it is plain Ubuntu). Cloned the repro and run install. All good. However, upon sourcing the file, I got a lot of ":command not found".

Here is how it looks (don't shot me for installing it into the root home dir) :)

![image](https://cloud.githubusercontent.com/assets/372121/24129095/d8bca146-0da5-11e7-9b4c-25ea3b6ddb33.png)

**Comment by nwinkler** [comment]
This looks similar to #817 - I'm pretty sure it is caused by a Git setting that changes the line endings when cloning.

Can you please try the suggestions in #817 and then report back? It's possible that you have to change the global Git setting for `core.autocrlf` and then clone the project again...

**Comment by thenitai** [comment]
I've tried everything and checked my line endings and all but still doesn't work (I used Linux daily).
Running install shows:
```
./install.sh: line 3: $'\r': command not found
./install.sh: line 5: syntax error near unexpected token `$'{\r''
'/install.sh: line 5: `function show_usage() {
```

**Comment by nwinkler** [comment]
I've committed a change in #927 that should fix this. You probably need to clone the project again on Windows, to a fresh directory (sorry about that). I've added a `.gitattributes` file that should enforce LF line endings for all `.bash` and `.sh` files on all platforms, regardless of the global Git settings.

Please give this a try an reopen the ticket if this still does not work.

**Comment by thenitai** [comment]
Awesome, this did the trick. Thank you. Much appreciated.

**Comment by nwinkler** [comment]
Glad to hear that it's working!
