### ISSUE TITLE
Is there a hadoop completion in bash-it?

### ISSUE THREAD

**Issue by hanfeisun** [Bash-it/bash-it#933]
I didn't find one in bash-it..

**Comment by nwinkler** [comment]
That is correct - Bash-it does not include this at the moment.

**Comment by LanikSJ** [comment]
@hanfeisun see https://github.com/guozheng/hadoop-completion

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
