### ISSUE TITLE
Applying bash-it breaks VTE title detection

### ISSUE THREAD

**Issue by ontherunvaro** [Bash-it/bash-it#939]
Both in Guake and Tilda, pretty common terminal apps, the "detect tab title from VTE" function is broken by `bash-it`. If `bash-it` lines are commented from `.bashrc` it works as expected (shows current `PS1` value).

This has been replicated in various themes (`bobby`, `powerline`, `powerline-plain`), and in two Linux distributions (Ubuntu 16.04, Linux Mint 18).

`bash` version is `4.3.46(1)-release` in the Mint pc, not sure about the other one.

**Comment by nwinkler** [comment]
Can you post a screenshot of the expected result (without using Bash-it) and then with Bash-it? This will give us a hint as to what might be causing this.

**Comment by ontherunvaro** [comment]
Sure, here is one example with the default Ubuntu terminal (I just checked it happens there as well) and another with Guake. Both are using the `powerline-plain` theme. Both are expected behaviour top, bash-it bottom.

- Guake:

![guake](https://cloud.githubusercontent.com/assets/8677743/25170686/bdf44cbc-24eb-11e7-9217-0579db40daa0.png)

- Ubuntu terminal:

![term](https://cloud.githubusercontent.com/assets/8677743/25170687/bdf61a42-24eb-11e7-9ad2-a0260f4e3ac4.png)

**Comment by nwinkler** [comment]
I don't have a Linux box here to try this out - but it looks like this could be caused by the `preexec` functionality, which is trying to set the window title: https://github.com/Bash-it/bash-it/blob/master/lib/preexec.bash#L139

Can you try playing around with that to see whether this is causing the issue?

**Comment by ontherunvaro** [comment]
Ugh, it seems I didn't investigate enough. After taking a lookat that file I've found that the `xterm` plugin implements this functionality, and enabling it solves my issues. You may close this issue.

**Comment by nwinkler** [comment]
Great - thanks for reporting back here!
