### ISSUE TITLE
Tab completion lists way too many options.

### ISSUE THREAD

**Issue by destenson** [Bash-it/bash-it#947]
I have no idea where it gets the list of words to use for tab completion. Using tab completion for the cd command is especially annoying. For example:

     2017-04-24 21:07:42 ⌚  dennis-Z68MA-D2H-B3 in ~/studio-master-dev
    ○ → ll
    total 12
    drwxrwxr-x  4 dennis dennis 4096 Feb  1 21:21 prebuilts/
    drwxrwxr-x 25 dennis dennis 4096 Feb  1 21:21 sdk/
    drwxrwxr-x 13 dennis dennis 4096 Feb  1 21:23 tools/

     2017-04-24 21:07:43 ⌚  dennis-Z68MA-D2H-B3 in ~/studio-master-dev
    ○ → cd p<tab>
    path                      prebuilts/                preexec_interactive_mode  preposition               purple                    

There's only one directory in ./ even starting with p, but it offers 5 options. Only the correct one is even a directory at all, and none of them except the correct one can be used to cd into.

**Comment by nwinkler** [comment]
Can you post the output of `complete | grep cd`? This should give us a hint which completion is being used for the `cd` command.

**Comment by destenson** [comment]
```
 2017-04-30 18:06:57 ⌚  dennis-Z68MA-D2H-B3 in ~
○ → complete | grep cd
complete -F _service /etc/init.d/lsyncd
complete -o nospace -F virtualenvwrapper_load cdproject
complete -F _service /etc/init.d/dhcpcd
complete -o nospace -F virtualenvwrapper_load cdvirtualenv
complete -F _service /etc/init.d/pcscd
complete -o nospace -v -F _cd cd
complete -F _filedir_xspec cdiff
complete -o nospace -F virtualenvwrapper_load cdsitepackages
```

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
