### ISSUE TITLE
bash-completion is polluted by colors.theme.bash

### ISSUE THREAD

**Issue by thomasbarton** [Bash-it/bash-it#950]
bash-it and bash-completion do not play nice.

Currently when i type in my bash terminal (iTerm 2) `cd ` and then hit tab for tab completion i get 100's of suggestions.  Even if there are only a few files / directories in my current directory.  Most of them are bash variables such as `echo_background_black`, `echo_blue`.  These variables come from the bash-it/themes/colors.theme.bash

bash-completion version 1.3_2
Mac OS 10.12.4
bash-it master branch commit e275c627674fc0386b13662cf7b45f31c4d3e14c

This problem was hard to track down because `bash-it completion brew` and `bash-it completion plugin system` both enable the `brew install bash-completion` bash script.

If i disable bash-it and manually source the bash-completion script i dont have the variable pollution problem on cd.

If i disable `bash-it completion brew` and `bash-it completion system` and leave bash-it on.  I do not have the variable pollution problem.  However, i dont have bash-completion sourced so i lose all of that functionality.

I did not have this problem on previous versions of Mac OS 10.11.X

**Comment by thomasbarton** [comment]
It seems like it could be related to this issue -> https://github.com/Bash-it/bash-it/issues/947

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
