### ISSUE TITLE
install.sh is not path-with-spaces-proof

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Bash-it/bash-it#952]
## Current Behavior
```
Installing bash-it
Would you like to keep your .bashrc and append bash-it templates at the end? [y/N] y
Your original .bashrc has been backed up to .bashrc.bak
Bash-it template has been added to your .bashrc
Enabling aliases
ls: 無法存取 '/home/Lin-Buo-Ren/軟體/Bash-it': 沒有此一檔案或目錄
ls: 無法存取 '-': 沒有此一檔案或目錄
ls: 無法存取 'A': 沒有此一檔案或目錄
ls: 無法存取 'community': 沒有此一檔案或目錄
ls: 無法存取 'Bash': 沒有此一檔案或目錄
ls: 無法存取 'framework/aliases/available/[^_]*': 沒有此一檔案或目錄
Enabling plugins
ls: 無法存取 '/home/Lin-Buo-Ren/軟體/Bash-it': 沒有此一檔案或目錄
ls: 無法存取 '-': 沒有此一檔案或目錄
ls: 無法存取 'A': 沒有此一檔案或目錄
ls: 無法存取 'community': 沒有此一檔案或目錄
ls: 無法存取 'Bash': 沒有此一檔案或目錄
ls: 無法存取 'framework/plugins/available/[^_]*': 沒有此一檔案或目錄
Enabling completion
ls: 無法存取 '/home/Lin-Buo-Ren/軟體/Bash-it': 沒有此一檔案或目錄
ls: 無法存取 '-': 沒有此一檔案或目錄
ls: 無法存取 'A': 沒有此一檔案或目錄
ls: 無法存取 'community': 沒有此一檔案或目錄
ls: 無法存取 'Bash': 沒有此一檔案或目錄
ls: 無法存取 'framework/completion/available/[^_]*': 沒有此一檔案或目錄

Installation finished successfully! Enjoy bash-it!
To start using it, open a new tab or 'source /home/Lin-Buo-Ren/.bashrc'.
```

"ls: 無法存取 'blablabla': 沒有此一檔案或目錄" is approximately equal to "ls: Can't access 'blablabla': No such file or directory"

It appears that the installer is not path-with-spaces-proof, and also not error-aware.  
The install prefix of Bash-it is `/home/林博仁/軟體/Bash-it - A community Bash framework`

### Operating System
KDE Neon(based on Ubuntu 16.04 AMD64)

### GNU Bash
4.3-14ubuntu1.1 from Ubuntu 16.04 software archive

**Comment by knorth55** [comment]
I think this PR https://github.com/Bash-it/bash-it/pull/953 fixes this issue.

**Comment by Lin-Buo-Ren** [comment]
I was originally want to fix it myself, but it appears that this kind of issue scattered in the entire project and it frustrates me to do so.

Anyway here's #954 , a slightly different and simplified fix that I expect do the same job

**Comment by nwinkler** [comment]
Thanks for the work on this - it's a starting point. If you find more locations where `$BASH_IT` is not quoted properly, please feel free to fix them - it's appreciated!
