### ISSUE TITLE
Lots of stuff is broken if installation prefix contains spaces

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Bash-it/bash-it#955]
This is a continuation of #952, Bash-it still not runnable after installer fixed.

Traces from running `bash -o xtrace`:  
https://pastebin.com/QhFFYdzJ

**Comment by nwinkler** [comment]
Thanks for the work on this again! Do you want to keep this open - or do you think that #956 fixes all of the issues for now?

**Comment by Lin-Buo-Ren** [comment]
@nwinkler Yes I'd like to keep this open, #956 merely fixes #954

**Comment by nwinkler** [comment]
OK, cool - thanks again for the work you're putting into this!

**Comment by nwinkler** [comment]
I've tried to fix some of these in #974, BTW. Please check if this works for you...

**Comment by nwinkler** [comment]
Closing this for now - hopefully most of the issues should be fixed with #974.
