### ISSUE TITLE
Incorporate ShellCheck as quality assurance?

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Bash-it/bash-it#957]
[ShellCheck – shell script analysis tool](http://www.shellcheck.net/)

Current `find -name "*.bash" -exec shellcheck {} \;` says:  
https://pastebin.com/rQKfKxTe

**Comment by nwinkler** [comment]
Where/how would you add this?

**Comment by Lin-Buo-Ren** [comment]
In the pre-commit hook, and Travis CI script, example [here](https://github.com/Lin-Buo-Ren/GNU-Bash-Shell-Script-Template/blob/master/Git%20Hooks/Client-Side%20Hooks/pre-commit.bash#L509) and [here](https://github.com/Lin-Buo-Ren/GNU-Bash-Shell-Script-Template/blob/master/.travis.yml#L38).

**Comment by NoahGorny** [comment]
Actually resolved by #1624
