### ISSUE TITLE
Virtualenv not setting terminal prompt

### ISSUE THREAD

**Issue by boppyer** [Bash-it/bash-it#962]
The current build stops my terminal from displaying the current virtualenv being displayed in the terminal prompt. Is this to do with the Git display feature?

**Comment by lfelipe1501** [comment]
Maybe, you can attach captures.
Or you can try disabling git from the configuration file.

![alt text](https://image.ibb.co/b3kdRQ/Untitled.png)

You can change the **true** for **false**

**Comment by boppyer** [comment]
Hi ifelipe, thanks for that. I tried disabling SCM_CHECK but it didn't seem to work. Will have a play around

**Comment by lfelipe1501** [comment]
What operating system do you use?
What kind of terminal do you use?

I need more information to help you.

**Comment by boppyer** [comment]
Thanks Luis,

My setup is:
OSX 10.11.6 and I'm using iTerm2 and the standard Terminal that comes with
OSX

Thanks

Benjamin

**Comment by lfelipe1501** [comment]
@boppyer you need follow this steps for your OS.

https://github.com/Bash-it/bash-it#install

> NOTE: Keep in mind how Bash load its configuration files, .bash_profile for login shells (and in Mac OS X in terminal emulators like Terminal.app or iTerm2) and .bashrc for interactive shells (default mode in most of the GNU/Linux terminal emulators), to ensure that Bash-it is loaded correctly. A good "practice" is sourcing .bashrc into .bash_profile to keep things working in all the scenarios, to achieve this, you can add this snippet in your .bash_profile:
> 
> if [ -f ~/.bashrc ]; then
>   . ~/.bashrc
> fi
> Refer to the official Bash documention to get more info.

**Comment by nwinkler** [comment]
@boppyer Which theme are you using and can you please share some screenshots of what your prompt looks like?

The fix recommended by @lfelipe1501 should not be necessary on macOS. If you use the Bash-it installer, on macOS the `~/.bash_profile` will be used for loading Bash-it.

**Comment by boppyer** [comment]
@nwinkler I'm using the theme Bobby and have enclosed a screenshot. And yes I installed it using the installer which was really easy to use.

![screen shot 2017-05-18 at 13 59 03](https://cloud.githubusercontent.com/assets/676976/26203226/5e28a71c-3bd2-11e7-943f-f1ecc121f431.png)

**Comment by deterralba** [comment]
I have the same issue on ubuntu 16.04, with default settings (I used the `--silent` option during install).
NB I'm running bash-it on a ubuntu VM (itself running on ubuntu 16.04), my terminal is terminator.

![screenshot_2017-07-02_14-18-04](https://user-images.githubusercontent.com/10196648/27769763-8b06bdaa-5f31-11e7-8712-be3e3fc783a1.png)

If I can be of any help... Keep up the good work !

**Comment by deterralba** [comment]
Switch to `powerline-multiline` theme "solve the issue" (I see the virtual env on the power line), so maybe it's a "feature" of theme bobby?

**Comment by mbhall88** [comment]
Adding `THEME_SHOW_PYTHON=true` as per @deterralba comment worked for me.

**Comment by robmoggach** [comment]
it's not immediately clear that the order in which the theme is set in the `.bash_profile` is critical for this to work... moving to vanilla install and changing `bobby` to `bobby-python` solved this for me - previously I had commented the `export BASH_IT_THEME="bobby"` line and set the variable later in the file

**Comment by nwinkler** [comment]
@robmoggach Can you be more specific about the order? From what I understand, the `BASH_IT_THEME` variable needs to be set before the main `bash_it.sh` script is sourced. Is this what you're saying, or is there something else that I've missed?

**Comment by robmoggach** [comment]
yes precisely. I was setting the `BASH_IT_THEME` afterwards not realizing it was tightly coupled to the `bash_it.sh` script

**Comment by nwinkler** [comment]
Thanks for confirming. Do you think we need to update the documentation to show the required order? On the other hand, the installer/template sets it up in the right order, not sure how many people go the manual route...

Closing this for now.
