### ISSUE TITLE
Brainy theme changed completely!

### ISSUE THREAD

**Issue by MunifTanjim** [Bash-it/bash-it#964]
After a long time, I updated Bash-it on my system. And I noticed that the theme I used for all this time, is completely gone! I used the **brainy** theme for a very long time and is quite used to it. But the current brainy is a totally different thing. Here's a screenshot (the theme below was the original one.):

![new-old-brainy](https://cloud.githubusercontent.com/assets/8050659/26287749/324b4e32-3ea3-11e7-855d-2020c21391f3.png)

As you can see, it's completely different. Is there any possibility for it to go back being what it was before?

**Comment by lfelipe1501** [comment]
hi @MunifTanjim Thank you very much for your great theme, I worked to increase the improvements in the THEME in order not to copy this if not to make improvements, I have edited your theme if you want we can work to leave a classic theme and an edited theme that can be Choose when to install.

I pay attention to your comments so that we go into detail and do even better.

**Comment by nwinkler** [comment]
I suggest we add the original `brainy` theme back as a separate theme called `brainy-classic`, or we add `brainy` back in its original form and then add a new one called `brainy-improved` with the changes from @lfelipe1501.

Ideally, the two themes would use the same base functionality that's shared in some common files, similar to what the `powerline-*` themes do.

**Comment by MunifTanjim** [comment]
@lfelipe1501 It's okay. But the thing is that, the users of every theme is used to a specific look. So, while under the hood and incremental (and probably optional - like an extra info section) improvements are great; A completely different look, not so much. :grinning: 

@nwinkler i think `brainy-classic` is a good idea.

**Comment by lfelipe1501** [comment]
@MunifTanjim I'm thinking of renombrar the subject for a new one, of course this is putting the respective gratitude for the excellent work that you have done. With this leaving your theme as it was and creating one from scratch using your base.

Let me know what you think.

**Comment by MunifTanjim** [comment]
@lfelipe1501 That sounds good too! :+1:

**Comment by lfelipe1501** [comment]
@MunifTanjim and @nwinkler This issue is resolved with the following pull request #967 

I remain attentive to your comments. 😅

**Comment by nwinkler** [comment]
Thanks for the combined effort to get this done! Since we don't really have code ownership in this project, the situation that we've seen here can come up - I'm glad that we found a good way to deal with it.
