### ISSUE TITLE
`bash: $grouplist: ambiguous redirect`

### ISSUE THREAD

**Issue by shivams** [Bash-it/bash-it#965]
I am trying out bash-it using its Docker container, on my Ubuntu 16.04. All works fine, except when I ask for help on plugins using `bash-it help plugins`, it starts throwing this error:

    bash: $grouplist: ambiguous redirect

This error is printed continuously on the screen for a while, and then finally I press <kbd>Ctrl-C</kbd> after which it shows:

```
[3]+  Stopped                 for gfile in $(cat $grouplist | sort | uniq);
do
    printf '%s\n' "${gfile##*.}:"; cat $gfile; printf '\n'; rm $gfile 2> /dev/null;
done | less

```

**Comment by nwinkler** [comment]
Can you please open this as an issue on the `bash-it-docker` project? https://github.com/Bash-it/bash-it-docker/issues

**Comment by shivams** [comment]
Sorry, I opened the issue in the wrong place. I have opened an issue in the `bash-it-docker` project here: https://github.com/Bash-it/bash-it-docker/issues/1
