### ISSUE TITLE
Invalid characters in bash prompt

### ISSUE THREAD

**Issue by alenbasic** [Bash-it/bash-it#971]
This is on macOS 10.12.5 using both iTerm and iTerm2. This is what it looks like:

![image](https://cloud.githubusercontent.com/assets/2830042/26520598/68d0bb70-4319-11e7-8499-44a277210180.png)

I noticed on the README that it mentions there could be some UTF-8 issues, so I checked my locale and everything is set to en_AU.UTF-8 (changing it to en_US.UTF-8 doesn't change anything). I first noticed this on the powerline theme, but it's affecting others.

Looking at the screenshots, I'm pretty sure it's not "?"s that should be showing up. I'm not sure if this is potentially an issue here, or could it be another setting I am missing?

**Comment by nwinkler** [comment]
Please take a look at the README of the powerline theme, there's a link to the fonts that you need to install: https://github.com/Bash-it/bash-it/tree/master/themes/powerline

I do this on the Mac (using Homebrew):

```bash
brew tap caskroom/fonts
brew cask install font-source-code-pro-for-powerline
```

Then select this font in iTerm and you should be good to go.

Please feel free to close this issue if this is working for you.

**Comment by alenbasic** [comment]
Thanks, that was exactly it! Feel a bit foolish now :|

Also, in case someone else has an issue; iTerm2 has an option that states "use a different font for non-ASCII text", this will need to be unticked when you change the font (otherwise use this to set the powerline font for those characters). I was confused for a moment till I noticed that setting.

Thanks again, and closing.

**Comment by CaesarJeries** [comment]
I did as explained in the link but I still have undefined symbols
