### ISSUE TITLE
Slow implementation of `git_status_summary` in base.theme.bash

### ISSUE THREAD

**Issue by MunifTanjim** [Bash-it/bash-it#977]
Why are we using `awk` implementation of `git_status_summary` instead of `grep` implementation?

`grep` implementation should be significantly faster than than `awk` (I've tested it on Ubuntu).

Is there any compatibility/performance issue with `grep` across different operating systems?

**Comment by lfelipe1501** [comment]
Hi @MunifTanjim How are you implementing it?

I would like to test your implementation since in git-bash windows is too slow.

If you can give me the code to review it would be great. :smiley:

**Comment by MunifTanjim** [comment]
Create a file with the following content and source it:

```bash
#!/usr/bin/env bash

function _bi_git_status_summary {
  awk '
  BEGIN {
    untracked=0;
    unstaged=0;
    staged=0;
  }
  {
    if (!after_first && $0 ~ /^##.+/) {
      print $0
      seen_header = 1
    } else if ($0 ~ /^\?\? .+/) {
      untracked += 1
    } else {
      if ($0 ~ /^.[^ ] .+/) {
        unstaged += 1
      }
      if ($0 ~ /^[^ ]. .+/) {
        staged += 1
      }
    }
    after_first = 1
  }
  END {
    if (!seen_header) {
      print
    }
    print untracked "\t" unstaged "\t" staged
  }'
}

function _bi_git_status_awk {
  local details=""
  local status_lines=$(git status --porcelain 2>/dev/null | _bi_git_status_summary)
  local status=$(awk 'NR==1' <<< "$status_lines")
  local counts=$(awk 'NR==2' <<< "$status_lines")
  IFS=$'\t' read untracked_count unstaged_count staged_count <<< "$counts"
  [[ "${staged_count}" -gt 0 ]] && details+=" S:${staged_count}"
  [[ "${unstaged_count}" -gt 0 ]] && details+=" U:${unstaged_count}"
  [[ "${untracked_count}" -gt 0 ]] && details+=" ?:${untracked_count}"
  echo $details
}

function _bi_git_status_grep {
  local details=""
  local status_lines="$(LC_ALL=C \git status --porcelain 2>/dev/null)"
  local staged="$(echo "${status_lines}" | \grep '^[^? ]. .*' | wc -l)"
  local unstaged="$(echo "${status_lines}" | \grep '^.[^? ] .*' | wc -l)"
  local untracked="$(echo "${status_lines}" | \grep '^?? .*' | wc -l)"
  [[ "$staged" -gt 0 ]] && details+=" S:$staged"
  [[ "$unstaged" -gt 0 ]] && details+=" U:$unstaged"
  [[ "$untracked" -gt 0 ]] && details+=" ?:$untracked"
  echo $details
}
```
That is the stripped down version of `awk` and `grep` implementation for testing purpose.

Now run this command while in a git directory for testing the performance of them:

**first AWK then GREP**

`time for i in {1..1000}; do _bi_git_status_awk >/dev/null; done && time for i in {1..1000}; do _bi_git_status_grep >/dev/null; done`

My output: (git status is `U:3 ?:1`)

```
real	0m22.473s
user	0m3.112s
sys	0m2.220s

real	0m18.524s
user	0m0.588s
sys	0m0.836s
```

**first GREP then AWK***

`time for i in {1..1000}; do _bi_git_status_grep >/dev/null; done && time for i in {1..1000}; do _bi_git_status_awk >/dev/null; done`

My output: (git status is `U:3 ?:1`)

```
real	0m18.491s
user	0m0.484s
sys	0m0.996s

real	0m22.551s
user	0m3.036s
sys	0m2.284s
```

As you can see, the `grep` implementation is 4 seconds faster for 1000 runs. Not a huge difference, I know, but it is faster. :joy:

**Comment by lfelipe1501** [comment]
jejejeje ok thx.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
