### ISSUE TITLE
cp: illegal option -- a

### ISSUE THREAD

**Issue by phoe** [Bash-it/bash-it#978]
Installing bash-it on Solaris 10 sparc64 gives me the following log:

```
bash-4.3# ~/.bash_it/install.sh
Installing bash-it
Would you like to keep your .bashrc and append bash-it templates at the end? [y/N] n
cp: illegal option -- a
Usage: cp [-f] [-i] [-p] [-@] f1 f2
       cp [-f] [-i] [-p] [-@] f1 ... fn d1
       cp -r|-R [-H|-L|-P] [-f] [-i] [-p] [-@] d1 ... dn-1 dn
Copied the template .bashrc into ~/.bashrc, edit this file to customize bash-it

Enabling sane defaults
File /root/.bash_it/completion/enabled/bash-it.completion.bash exists, skipping
File /root/.bash_it/completion/enabled/system.completion.bash exists, skipping
File /root/.bash_it/plugins/enabled/base.plugin.bash exists, skipping
File /root/.bash_it/plugins/enabled/alias-completion.plugin.bash exists, skipping
File /root/.bash_it/aliases/enabled/general.aliases.bash exists, skipping

Installation finished successfully! Enjoy bash-it!
To start using it, open a new tab or 'source /root/.bashrc'.

To show the available aliases/completions/plugins, type one of the following:
  bash-it show aliases
  bash-it show completions
  bash-it show plugins

To avoid issues and to keep your shell lean, please enable only features you really want to use.
Enabling everything can lead to issues.
```

Installation obviously does not work.

(I bet that you didn't expect me trying to install it on such a weird OS on such a weird architecture, did you.)

**Comment by phoe** [comment]
What my `cp` is capable of:

```
bash-4.3# cp 
cp: Insufficient arguments (0)
Usage: cp [-f] [-i] [-p] [-@] f1 f2
       cp [-f] [-i] [-p] [-@] f1 ... fn d1
       cp -r|-R [-H|-L|-P] [-f] [-i] [-p] [-@] d1 ... dn-1 dn
```

**Comment by phoe** [comment]
Actually, it seems to have worked, but now I get this whenever I launch bash:

```
sed: illegal option -- E
bash: rbenv: command not found
bash: rvm-prompt: command not found
```

**Comment by nwinkler** [comment]
`cp -a` seems to be the same as `cp -pPR` - might be worth a Pull Request to change this.

(This is what the macOS `man` page for `cp` says at least)

**Comment by nwinkler** [comment]
The `sed -E` case is a bit more complex... Does Solaris `grep` have an option similar to `-E` (support regular expressions)?

**Comment by phoe** [comment]
I have worked around this issue by installing the GNU coreutils from CSW and subsequently replacing every problematic binary from `/usr/bin/` and `/usr/sbin/` with its GNU equivalent.

```
mv /usr/bin/grep /usr/bin/grep_solaris
ln -s /opt/csw/bin/ggrep /usr/bin/grep
```

The GNU utilities have a `g` in front of their names. Perhaps on Solaris 10 you could depend on them being installed from OpenCSW and available in the path, and inside your scripts run `ggrep` instead of `grep`, `gsed` instead of `sed`, etc.?

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!

**Comment by barracuda156** [comment]
@nwinkler Yes, `cp -pPR` should be used instead of `cp -a`.
