### ISSUE TITLE
Title updates

### ISSUE THREAD

**Issue by dimitrov-adrian** [Bash-it/bash-it#990]
When installing bash_it, titles of new tabs and windows on gnome-termina, and titlda are not updated according host or current directory.

**Comment by nwinkler** [comment]
Have you enabled the `xterm` plugin?

```bash
bash-it enable plugin xterm

reload
```

**Comment by ser** [comment]
Interesting thing with xterm plugin is that it interfes with fzf, crtl-r gives:

```
`__fzf_history__`bash: $'\E]0;bash-it': command not found
 ser  08:20:41  ~  ^[]0;bash-it {~} (me@comp)^G^[]0;bash-it {~} (me@comp)^G^[]0;bash-it {~} (me@comp)^G^[]0;bash-it {~} (ser@vapo)^G^[]0;bash-it {~} (me@comp)^G
```
after issuing ```bash-it disable plugin xterm``` fzf is working again.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
