### ISSUE TITLE
bash-it emits bashdb error without bashdb installed

### ISSUE THREAD

**Issue by ravenhall** [Bash-it/bash-it#992]
Just pulled from master and now I'm seeing this error when launching bash:

    bash: /usr/share/bashdb/bashdb-main.inc: No such file or directory
    bash: warning: cannot start debugger; debugging mode disabled

I'm on Red Hat Enterprise Linux Server release 7.3 (Maipo).
[bashrc.txt](https://github.com/Bash-it/bash-it/files/1113340/bashrc.txt)
[bash_profile.txt](https://github.com/Bash-it/bash-it/files/1113339/bash_profile.txt)
[bash-itplugins.txt](https://github.com/Bash-it/bash-it/files/1113341/bash-itplugins.txt)

**Comment by nwinkler** [comment]
It looks like this is related to this line: https://github.com/Bash-it/bash-it/blob/master/lib/preexec.bash#L122

```bash
shopt -s extdebug > /dev/null 2>&1
```

References:

* https://gitlab.com/gnachman/iterm2/issues/4160
* https://github.com/rcaloras/bash-preexec/issues/6
* https://serverfault.com/questions/745837/bash-to-start-missing-debugger-after-update-to-4-2

Skimming through these, it looks like this error is caused by the above line on specific versions of Bash. The issues describe it in the context of iTerm2, which uses a similar preexec integration script.

Not sure how to fix it - the above links contain a couple of potential workarounds, but I don't have a system to test this...

**Comment by ravenhall** [comment]
I can test if a solution can be sussed out from those threads. The only clear workaround I see is checking if bashdb is installed in the preexec_install() function before setting the DEBUG trap on L130. 

Installing a VM with CentOS 7.2 and then bash-it exhibits the same behavior.

**Comment by ravenhall** [comment]
It looks as though another potential could be that a failed check for bashdb could run `shopt -u extdebug` to disable the external debugger.

**Comment by ravenhall** [comment]
Please see [Season of Code](https://seasonofcode.com/posts/debug-trap-and-prompt_command-in-bash.html) for a description of how the DEBUG trap and PROMPT_COMMAND are being employed in this code to emulate zsh's preexec hook. The page notes that a PS0 variable patch that simplified this was accepted into Bash 4.4. 

How should bash-it handle this? 
1. Check for Bash 4.4 and use a PS0 implementation only
2. Check for Bash 4.4 and use PS0 implementation with fallback to DEBUG/PROMPT_COMMAND
3. DEBUG/PROMPT_COMMAND only (current solution)

**Comment by ravenhall** [comment]
Additionally, I am not sure that the current implementation is working as expected. It looks as though the preexec_invoke_exec hook is being executed three times after the command is invoked.

[preexec_invoke_exec.txt](https://github.com/Bash-it/bash-it/files/1143164/preexec_invoke_exec.txt)

**Comment by nshiell** [comment]
I have this issue on KDE Neon
Linux saturn 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

What's the best way to remove this?

**Comment by nshiell** [comment]
I have this issue on KDE Neon
``Linux saturn 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux``

What's the best way to remove this?

**Comment by NoahGorny** [comment]
hey @nshiell 
are you still experiencing this bug?

**Comment by hv15** [comment]
Hi, I get this on CentOS 7 using Bash 4.2.46(2)-release using the latest version of bash-it.

**Comment by palladius** [comment]
Same here, on Mac:

./blah.sh: /opt/homebrew/Cellar/bash/5.2.15/share/bashdb/bashdb-main.inc: No such file or directory

I believe the issue was:

# #!/bin/bash

# set -euo pipefail

I changed it to

#!/bin/bash

and the shebang worked.
